creation_rules:
  - path_regex: cluster.*\.secret.ya?ml
    encrypted_regex: "((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))"
    age: age1exmdf3ygc06nv8mfw8afsdw5ygvcsvyhfrcv8yz570c4uvhhmg9sqxnadu
  - path_regex: .*\.secret
    encrypted_regex: "((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))"
    age: age1exmdf3ygc06nv8mfw8afsdw5ygvcsvyhfrcv8yz570c4uvhhmg9sqxnadu
  - path_regex: talenv.yaml
    age: age1exmdf3ygc06nv8mfw8afsdw5ygvcsvyhfrcv8yz570c4uvhhmg9sqxnadu
  - path_regex: talsecret.yaml
    encrypted_regex: "((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))"
    age: age1exmdf3ygc06nv8mfw8afsdw5ygvcsvyhfrcv8yz570c4uvhhmg9sqxnadu