creation_rules:
  - path_regex: cluster.*\.secret.ya?ml
    encrypted_regex: "((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))"
    age: age1kuk9gqeywvzmlfdzuwvkzue4s9qs78px73hvz45lk7q996zdqcfsdeh998
  - path_regex: .*\.secret
    encrypted_regex: "((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))"
    age: age1kuk9gqeywvzmlfdzuwvkzue4s9qs78px73hvz45lk7q996zdqcfsdeh998
  - path_regex: talenv.yaml
    age: age1kuk9gqeywvzmlfdzuwvkzue4s9qs78px73hvz45lk7q996zdqcfsdeh998
  - path_regex: talsecret.yaml
    encrypted_regex: "((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))"
    age: age1kuk9gqeywvzmlfdzuwvkzue4s9qs78px73hvz45lk7q996zdqcfsdeh998