---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ispy-agent-dvr
  namespace: ispy-agent-dvr
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: ispy-agent-dvr
            patch: |
              - op: add
                path: /spec/template/spec/containers/1/resources/limits/squat.ai~1tun
                value: 1
  interval: 15m
  chart:
    spec:
      chart: ispy-agent-dvr
      version: 22.1.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        ports:
          main:
            type: LoadBalancer
            port: 10184
            targetPort: 8090
    # ingress:
      # main:
        # enabled: true
        # integrations:
          # traefik:
            # enabled: true
        # tls:
          # - hosts:
              # - ispy.${BASE_DOMAIN}
            # clusterIssuer: cluster-cert
        # hosts:
          # - host: ispy.${BASE_DOMAIN}
            # paths:
              # - path: /
                # pathType: Prefix
