apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:w6lGPIhk81tvBBBfTOikcrwjR+zVKPKcI1077CjDRfRyEU0IjxHWXGmsEh1UI0zv7BvvzskPBERnSfwQnwUj5Y8=,iv:iZ6Zku/0rkkClyewQS5bNAnGwOAK6TDxdYepdAxoSo4=,tag:JJu8cBJqTEJcWIvCnhpHUg==,type:comment]
    #ENC[AES256_GCM,data:Xd6Skaq+ktm4GyGV/V7avlwfHDmsV0etR9vOsoot107hQ+aoJaoK9Erg3x0=,iv:9hRJtlD5ZaIZi/kTbNU4o3p41sXXyqfZghnT6Ox891U=,tag:9xUyCmZzuoAXuqiabg4kEA==,type:comment]
    VIP: ENC[AES256_GCM,data:xmQdaj710VgF+7c=,iv:L0KSyKVphfQXRH+2xsWc+WLhbS+bNj33j8ooe8XfHiE=,tag:lElqBx4zyFKFeYOnake0+Q==,type:str]
    #ENC[AES256_GCM,data:Q/ZpsFKbWREJntHG9db33d0CrSzEnVu5yws=,iv:N5K5A3Y1kOxqnl556DjCh0Lz8vFYr4QprohRQ8zRwAw=,tag:ue1nMffj+9cfXPgMKcrs0Q==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:uET46TLQnNJEYYE=,iv:GIgl3xl4g5laP2jP+/1Oix6V4dKbWncjvi4+rWydhHs=,tag:c9pFFHICxKfsKKiVcNWMEw==,type:str]
    #ENC[AES256_GCM,data:Sxszy3vMvPm8TZ6bwk7PrSta+ESU98GKo8pcPi4MOOCk0Q==,iv:pH+5WO4Alox/yw4oOJ6FWPn7hJqQv+L3c4nGzGV6UZM=,tag:PrH367v7VJL8T8nqOXa0uQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:AkWPvb4X/3+wHsg=,iv:3/jTpiltITdeAeCGkGchS6uroJpQOqEFMin6KEQgU2E=,tag:nbwumT6E3imUgeTMR4WDuw==,type:str]
    #ENC[AES256_GCM,data:HUMn4KtV0KeKhieosPy/lRcuIcEHkahv/lcHmgXFYsE0zM7BvCfQdSGjgMs2zWQ=,iv:ewTsnRERWGMU56CMO79ImvuVpWbVlG7OoTynpYKOkOM=,tag:S+UOiF/oMU+lSvTEqmp0iA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:ba6zPr/6b3IGZVJmPR+L5oBziXWBLurnxw==,iv:EquNDMorlrKLSk8WwuWdpwg+awJ+OaKbEPerPjh6eAk=,tag:n0tI3nT4xvktV8+FiICKhg==,type:str]
    #ENC[AES256_GCM,data:u27ypz5XfptBB1aaWBzjf6TCSV0x/ayFM3arj4Ew3nP+Nae6zG2uAGRShzztPnsfKemNOpkri6zpFTwfPpkYcnfsdBybXPZ+Ug1rmnry5ng=,iv:PU1Fdj6noQfcRzlVbeasA0PIUVDkInbHT46A7s1ICn0=,tag:t/yD1jrohMGRolJiO1H4EQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:bBTwZP2KVReJQ2Ju,iv:ot3bnyW9F5w5bTtIwF4R4dhU5MbM9w+fghDGcDGEigw=,tag:DtHTnxK84y36cxTcUUG4QQ==,type:str]
    #ENC[AES256_GCM,data:oWCor/UuLLyEBwgpS+dLPzeKfid4Y46BZHTHVIHo2RT0HXyzdfvJb01bJPU9rdAG3PlE/k8jycY=,iv:LNeqnmFPuJtJk+UNv3kSdBLKgTu+YZUnOYkvSbipKEw=,tag:qnYf4S93qPA91snmIfAspA==,type:comment]
    #ENC[AES256_GCM,data:KQtluOQyGxXV5nNr3HLVWvKY35IdfntsQQ==,iv:7+BofR+gWTbFXkc3shLbMJbHnU5DOsg0MJMGas4fkA0=,tag:hm0oF6u+6BK+gSjSpifI1A==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:OlGKDIM4xe88Uw84uYVj18+CQMnft2H8IY9OeIkphuKcGcXYIAPTg1x8mg==,iv:ZTgZmhSU8RKB/rVeW79tE066LyHoiKYvVrS2T5IZ8gQ=,tag:XtgmOrs6oQDpONLXi75MEQ==,type:str]
    #ENC[AES256_GCM,data:Xc17qvQIep0ZhukRM8j3+WXrRa2NurGeL+syqkv5DrjCOMu5RiSOUxlnW8taIKaXQbK3v2Q9KHvujsoZFILu2s3m9B7+nsk=,iv:M8dmAJ/YN9uAb4fHWp/V+D1/vxblnsuc5FK1XeFmGSg=,tag:agmojnqQXGdjs56dhYSHpw==,type:comment]
    #ENC[AES256_GCM,data:/eQXksrj7acNMwriGNI4dzNI3+gmUSSdx6GyEmQKEeYxKYUbi/MH9LepLPcF5n6QSVmG3Q3J,iv:4XSbDkaibdky2T12WNNCnhskGTc+tO9ad8J7izMa3ec=,tag:sBsW+SvOvU9VvWGQ8LvVdA==,type:comment]
    #ENC[AES256_GCM,data:iSAezlAzjlbqlTGcQ8XpT3aI9U2Emi89SWFqhbKrje6gISk=,iv:fSK2SK3rOiPxpKcfwwP2wg2BBxmblJt1aafkjuwZZaU=,tag:hYhV7bTn+okLy+zHJ7PK2A==,type:comment]
    #ENC[AES256_GCM,data:ZdHi3vuzSFj4OnlaMnxjvENB2H19TuL7LFoNlwWAMEUkUTlC5MUB,iv:OHg7gLvCqQ8LVS9Dw6QA6tLru23MNcvjh+zKtskE9Uo=,tag:3Q9Q7hfd3Loc4deCEotAWQ==,type:comment]
    #ENC[AES256_GCM,data:t3w737dQmearhGyKCb8=,iv:CdKQiqHyIwS3A1+cr0JRN8ixkt/iTP9/U0FeX1hi9C0=,tag:7XOsYt3jLrGNiQ0qsjbDpQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:+L1Zo2ocjVkTcpiaxg==,iv:O+r6AF5ZFJLMiCXK2W3KrpxWs1G+DtdLtALs3yhTIqo=,tag:GoJDzrV/GUIKOAgWlVq5Ow==,type:str]
    SVCNET: ENC[AES256_GCM,data:NvfOAluurrmLvfhuAw==,iv:cqIX4HMAWCaC/p7cWx1Z4UL4Pln3KJr+XZn3qzUaxrM=,tag:7TLN2YTSN+1cE5YuN3/ixg==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:doiY34vDBqeyJ6Xx,iv:Ip8qq0oMJ7yWXzSFZO8w37/36IANGZs/6QDY9FP2H3A=,tag:2s5uc3NTZ7+n99wSNX7GZg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:QFn/9ADEf/s5J5vl,iv:jZ/efqGHj+W0pR9Uua3reH0Fq453+cdXliBOEDcHUlk=,tag:ybkhIQEIqa+Y9zhX6qi6TQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:5U3BmtxIyGQV2Snbv/o=,iv:F/oSYqhjea7VnlsmhOzFhsXK3UYu6jDF1dpPD9z2Qbo=,tag:qyH0iK/Fyk8krehPP9cuXw==,type:str]
    ADMIN: ENC[AES256_GCM,data:ohv0yzo=,iv:bxc/k6GSNlH/tTQwReKvpr9f9sTSWZxkzQzeErccn8U=,tag:gB7SlsNhrkphH41fzTYzeA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:wkZavT8BmCM=,iv:pn4qYj0qg3mCy3g+XHQhAlfNToGr+wQLABahlvJoIa4=,tag:4g7BhXOKuB/MJ0FgxOX1CQ==,type:str]
    EMAIL: ENC[AES256_GCM,data:9+hl1O5ZuKPjYumbOOxV6i9APFU=,iv:BxwnQZ0CeKtoYl0Whb/euOc5mzUEprhWfa+G5WM8aW0=,tag:+H1cfyw2AnMwuknc6rX86g==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:Rb2CI9AKi75+6fAmdJAm4BJjjdtbbD2rPhBVboWjPaGovDcE4B19bA==,iv:IAcn8EMSJFeZo7cSE/h3635YnoUTMGPipPFEZGzTx0g=,tag:Utlw3WmYyqfvcQnjhYU9aw==,type:str]
    VPN_USER: ENC[AES256_GCM,data:wPRt395t6/w=,iv:my43AFK6ctsuBq6pp6JUn+z5ZagBHovFXSYudnV3bR0=,tag:wO0g/KoXvQ3aHl2AWPeS6w==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:o5VxwNLaUbyg4A==,iv:NQ5NZNdsyAGaaKkiVc/LOwvgjSYKwLuI2MgIkNGBBQI=,tag:5l5xLUzfx7qt5P4OxETFAw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:fkGEFA==,iv:juZ6GUPkwsOyDgs+TMuImrHbb514LDzeWpRI9GDiJGY=,tag:gsO3RfsU6yl2VjnAMxa7+w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caandqrgue5nl44eylp4nvake7znrvxretz3uy3r0ccfa2av4aysejcgfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubnNZWXhIV1dmcVBES2l5
            MXhKeXFOeEc0RGlkQ0UwbmlqZDdmMWV0d2w0CllFOEpqYldXWjR5YzA3RHByeE9l
            cTl6SWsvalR6SWNIUU1GUk9QNHlpYWsKLS0tIFVTdEI3SmxVTHIxZGVKOGlYNEJa
            V2xCcUdsZWorelI5ZHJEeTI2ek5JZTQKB5SWXjZOcZstg/YWXuWR27xN736G6xTs
            t+dyRu5+rPIPHBtBgk3rXb5EFCbgB3DYamVTLbHPWgTRMdrysfWG5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T00:33:19Z"
    mac: ENC[AES256_GCM,data:uCi5NGxo79nggfnykfCbRDsa37FqHsv34WGrMbEG99rtROyam+Yp4WJAesgOr+m0QQN4SHfk3w/KZa20HchBCarThVIOy8rIr96mm/DMFWzx2YPZEsLM+YcCpOkokOS3B0Yk4NK60giuhFMLIGjNETKOWY9XdYM3LFXNsA35SCs=,iv:K3ATb1Fd1psVgGua8npQ0WIxVhBZlpZhwbEFUOJcJOk=,tag:bywqB14h4B7wJwstqLt05g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
