apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:Gu5SiDyv5RhJwHSQcYDEUNS58nNbMq5jUpZrz6WhwDJ3CYDB+Nzf6rk8oLEWF2Quf5yht2TR/J4eiVPY9mAuLC4=,iv:zP4zQOtES8nyQ/ueLyx304yPS1FN/FFMvZLlF3RHJF0=,tag:/QuoxO25WJqDCyICd9T+Zw==,type:comment]
    #ENC[AES256_GCM,data:+TPoZH+Bv8ZECDgLrIEcoa+CfIRimyDNZ7BXyzE4XoXHVKon29pY9aTHAJc=,iv:yfCMlN/6dmneNH23KyO2pCk3l2S7A5U0M4eSjbl3MhY=,tag:HzpcYOu+1n3+ELWHnmGPaA==,type:comment]
    VIP: ENC[AES256_GCM,data:s0NvV3FD8PdfZF0=,iv:NaPSwLPc4LcpVLOzPH7svIApBJDGgp3F3I/tdo/iD1Q=,tag:xdCJRQk92pGzIrQi+tExrQ==,type:str]
    #ENC[AES256_GCM,data:TXd6KTsNMVHGgGn3M9fqLXJqLbnzAOt4kUI=,iv:nBvnnDHqOYZozxls4/xqoMpPQewom4i69gb+BAq/e04=,tag:FT8Gk1vs/9AO/KUnmkUnBg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:ehJiyUTD9Y49te0=,iv:0UJOux1hFB7RIIleysvvCKjyXbfFyUFHaoeJ5HvvC0Q=,tag:15N4jJvKmGFi+ZbTVycA3g==,type:str]
    #ENC[AES256_GCM,data:1nDDy526Ub/Kf3CSLn+FOXO2eTRqdu2oy1/jNo15DXiVWA==,iv:tJR/P+PYxgeQYmQ4yUJggwU5zq5YyfGUvlGdBkR/pn4=,tag:DRDYmBBqw2NkbjXE1uAR1A==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:gbYg0616Xcawn64=,iv:SzD4aMzsQuypqz+uJ3sa1jKTazK2rqVjMxjBE6SJgXE=,tag:+YVpIZP0k8N3eQDB1q66QA==,type:str]
    #ENC[AES256_GCM,data:s4Fc6B4rmy5XrQbuwpAPzPhBZerFZZhZNXWTJyJ9ypdLGmnS6Ky9A7WbIW9ZDQM=,iv:ecNJjvd7XAfd3znCDeKDEZ+R/SU6LqQ41nlTWbpkNPk=,tag:HBcah6NZjSXPBOcDdSqxPg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:lKwneHJdbUQr1OYwAY9JDc8MIWs73MdFZg==,iv:nc2zMlKeft5fYPn2oXTtVNhAKYEKg5OqpZhjyR7cINU=,tag:JqishYe3xnC9vUqLmahcGg==,type:str]
    #ENC[AES256_GCM,data:ry8mtYEXpqkZxQ4B7AxowT4BOX2//tNgYJ8yZlNdXi9QWyogoNHWdfIHCHmzEZ+3WNhfhSynKCAqsVN4wo6Fqo7hU1/klq4IZkp09kvhgio=,iv:a5aDW/evF9Ivneu+N3AzDW934lGAC4idrz/8mWkDL1o=,tag:U954GueOVwlETLZ1rk33Jg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:dOrdLwoqvNPSlWTi,iv:y2Y+Z7QCXbW//C8ItmC6Sr2xWILC6ysT7KBzQld4l5k=,tag:BsnsoZdL0HkYdZiQKx+9qA==,type:str]
    #ENC[AES256_GCM,data:hyrYt5wGXS0cyO/IP5b9xsM6TSFboOLHSco1NhT8kI5RKf0hRIlx+J+8IHgz/oR9Fd4cIPCjXck=,iv:ijFTlPZCMUPvGnKsRHx/IVNmu9unDa5DHmHSCUCz5t0=,tag:p5zP0SfQXO7eU7qjmdB7EA==,type:comment]
    #ENC[AES256_GCM,data:xNDw2HTRc5qHQ/ecxyPtN2CsMDjqJS3rlQ==,iv:EotAwsqhUiWOw3+IuUQOMeV9mIiy5u2SUndjwxQbA7A=,tag:F7Cpl9j7ih/cT9BFp93LXw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:StnPmmNaGexpPMySHz/uYVawiDDqNbmk67r+K6kermcuy/LoIrDQqTpjpg==,iv:/8Sa3foPNbjPjhZVmEnzVh/Xb4ro6yTcATj5oBaSX6U=,tag:C+ssAqvRU3+4iWkMSBZS3w==,type:str]
    #ENC[AES256_GCM,data:SMplTGji41nTUFZ74w==,iv:AIiL+nSX4kysHiLJzCFuz547CuBFUk0o7mamIWGagaY=,tag:yIXo8sU4G3ot/ogG/wg2Gg==,type:comment]
    PODNET: ENC[AES256_GCM,data:9yN+bsEkrUiHwzuBgw==,iv:32K6gG+z5o8XdLha54pexlVf+BQxpBcWC/NzF9me6Z8=,tag:3AYs0xd7YP5yn394LG3miQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:Xwi+N4FRA2ndl84urg==,iv:53bm7XvabrsrwOe98Wa55qNTA2/37sXGpi2H4X9eDgE=,tag:el6oGshEjiXQT1oBJ8zb/Q==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:aj/7BGGOVjhVlAnQfdU=,iv:rNb9ART0aqUvI7sl1LYfUAjmiCZvxJlYoqhz3Rce2+Q=,tag:pvayJAxUnxjKi07hPCR/8w==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:6P/FS+7YpA9pDUJs,iv:ONyoUQODyVfCcyyam2AlZKA7+jlFaahgP3mkpqRfrxM=,tag:dBHm/QMdMUoG1x3VCsV3WQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:GiT1+VHPCaHss2x4,iv:nlH/NCNXgVEAsYi1kAZDi+3KdHYfrew9qitado9OukU=,tag:Tx6URage9wucUOTuBwVRGA==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:5/Zl5/s8urkeLfD0,iv:dVgb1qLXd+4p6vNIZlkkzIcC1KcPsUw5CrJEy4O+sew=,tag:xuxmTWnC4yGH39U5K094lw==,type:str]
    EMAIL: ENC[AES256_GCM,data:oB1JmhfuVldZIGtztdOkVvVPafM=,iv:HKW2HoWtM5Q06AHT9vuqax42se1PPO0GblGTPwzJ+EQ=,tag:mt2XS7se6EM6eLf1rVoI7Q==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:Y5eVNpUay1QoXSnNjcmGqOnhUN6YGmX1LalhkPLvLvn7DCTXqmcwEA==,iv:ZY9TGDtNMc/2Jma8p/WGQ1Xw+dsuFY1Izo+t03IGGkk=,tag:Ln75CgxrzTr7ingrtwQPVw==,type:str]
    ADMIN: ENC[AES256_GCM,data:36YL9ZU=,iv:h8hy1WUy/xyrIBdOLQN+gs+LHSGKv08hSl3igvF4IBE=,tag:133hqR9Aw+zZXhX+q2YgBw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:xmwRSrSZd7Y=,iv:yWpm0sczT5P/xVmM+7aHKKtXAEjmmlY3M1yLXzBMHzw=,tag:4nSCUznDwiTlrp04mfghLw==,type:str]
    VPN_USER: ENC[AES256_GCM,data:i5T2BRZl24o=,iv:vLtWPM6ltK4AA0m/rMy8zGe6cNOyOQg19pyxfz+l6gE=,tag:bYNybPFSCyI+QiA7dyRR2g==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:tIYg95wmnvo38Q==,iv:I52+52z/EDIeKLui9q7u2SbwTBN8gCcQ3PMxeQMkkDc=,tag:O9GkywQKCXejivkqIl7Rmw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:vIP4Rg==,iv:TVxz7RPhbjdG6VGRb13grPFPuxm4YrKryuTXShfAnJ0=,tag:BmNMr35Zabt36J09aBycwA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZmVZY2VTNlFwUXhmWEVj
            ZXoxa0dQejRNaTIyaXcxMnFEejhrOTFVZmk4ClE4SFNIYXBLclp6cjJUQmVtb2xR
            VE5nNklXa3ZZeEV1UnVXM3EvejQrdzgKLS0tIHlXTGlrREVLeTJINlNHRzZBL1M5
            VitlSk9vTFpYSWsxUVhkSTZnR3V6SDgK+0koIBCw0WbLcTnUHxBTlRHOTer9IHJH
            Hk/gqO+w3W3UBfqJGuKuh+Br9E+RxVcC7TmlAQex9xiy9MSIgMXgBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T16:40:13Z"
    mac: ENC[AES256_GCM,data:rxgbv0s1yD7xCWGYZ+LuD9nwdlIrxYBjaIB15SFWpaWwpVtnDtLcnpDjshJoNpIXD6v3AEpu8MvAfCka+1o3djciet5ZpLT8U1ptbWfg/JCb0JCEUEROBFYiSoJ93U1r0oQsMD6IdLxFQcELYtpLlaJ29hf56xjWM1zx8GNvlgE=,iv:MfBdWvog/Ylb58o2dxAXiyMd8lwS29Nwj7CfLVvsfKw=,tag:KukhsCSQtG84RAwt6YzXOA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
