apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:gIciDeg6FJ2/IdE2up/n+3ZuU1M6+twGS+9WgNq8FynsUtap7XmORxzwofY4d9SkTjfWxDYh9jbbc6XCimx5eWs=,iv:2wUeuYH9Jgcit3HxX53g/Omiw7qCqsj6mTh0Hi0hDNk=,tag:hnQJuEdFmFffLN6remDTGg==,type:comment]
    #ENC[AES256_GCM,data:/9c5yOgOvDQ6cn2oOXzp+5IBc7v5RIRL9q+B0uV2I9dHW9ZZpsay05Z2pbc=,iv:m1JTgjY+2cAXhxbXFXx9Wx8XHXRD8h7V7RG/CL8k+fc=,tag:zAGC7U9zcEoS90hrtdDHDw==,type:comment]
    VIP: ENC[AES256_GCM,data:2v+2qW2lHY0cF5U=,iv:9OFqDggUFglcq3kxgOy22qNjD1YaMZ30+DlZvNhSsGg=,tag:a6xpa2RA0lYW3810vjDvnA==,type:str]
    #ENC[AES256_GCM,data:y23G2hoNC+AgVc3oyR0c9lESnTZz0nKrj5g=,iv:8LA5mCSO+JFKM1KOBmn9LxU7rf0gvc+C5U1m6tPLuK0=,tag:OIoNzIxtbLd+FBLUoenGBg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:VAQEhtbYeaZI57s=,iv:IOPLyXD5QER1X20gl6bHG5P0JpZubLkX/9zx+I8ljDI=,tag:ln9/MiD34aFO14fNSR1mmA==,type:str]
    #ENC[AES256_GCM,data:bon5qRCM7DTulC4AvcRYTKZFLEMeWyvkiJoIRt2oEvMmTg==,iv:ZGWcCNElAhxf9LID07eac2Mt02DJao81fxXjgy3hOOY=,tag:YFfzViQkcVThUPZwR3kw0g==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:3Rfz1jLQt0MijKQ=,iv:klrOWRxttoFchDhbnZGj+ggVwtPs582hrMDSCUFBHQ0=,tag:03wf21kxbE18/Hp6XPDznQ==,type:str]
    #ENC[AES256_GCM,data:VDXsJ+g0vqPmgCAGJgdcAx/ziELuZ7IZ2BdY3C+gGw9IeFXzhKV1gibVZ8g5ltw=,iv:U0QMEekq1PkVEH4NqDzUJ6SCVQR9aWL7GwTHEVnR3Ao=,tag:7SHWQAEKyWzrrpCdN87tHA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:EssWk8dexw5QtCr8DV70LWW79LbMioSHhg==,iv:UjxA5SyrnnuRxDB+wtLUb0Zz9510U6yZM/ZPEd2tswY=,tag:A/m91sLjSOh8benyEBn7FA==,type:str]
    #ENC[AES256_GCM,data:IRCnpv1flHjU2Zfmnf8rZB/iB+aOWhK9lj9JMnIycp2oG75F23MqjklmeNpE6qmVRhPpL+dITxrQ0+kFQrVXcf7tjI1w+s2g3piUMZdb0FY=,iv:iigsqyQRjXu/53Xg+v316Tc9gbsC8Rm1fO9uBdTNtWY=,tag:iG0F+4C2kxcr+eKi4Orc2g==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:FBoXSaR9DhVI4KaX,iv:kqdMegr7N0dAwwiQPnETD6pmpJkcGuv4BrT6o8eETRY=,tag:lUIYoqNJ744RsZkGiZqvzg==,type:str]
    #ENC[AES256_GCM,data:qYQZRk+P/PcmJuvTTnPgmzGaDLaQ+RjtHNl0vhnj/IHAxdPSEblLuZmavA/yTqF9q0cTW3cxKw0=,iv:G+pcMIyMEe95Fu8ErhvMn1zqOvQtYKLRHMNh0g3Tf7A=,tag:d6tcwiJcB1evoXlkv/cmBw==,type:comment]
    #ENC[AES256_GCM,data:dYe+ybF+/4g/23l88aVEdWhLbNzjjYT0bA==,iv:AklxcYKLffKVOCZBiyiINV7tJo4uo4eOnqS4eUg97xA=,tag:rmmCmo+0NLJwSg4y7a2H6g==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:8RTssfxACv7xY9QjHITu/1rDpsQpjPNKv9n5s0H+Oiqbr3BcJoWufcQ4OA==,iv:nxitfpER6KiyNLFGRTa57VIE76sA6xp3D9EWVp5LpD0=,tag:/FbdAAK9akFbZpHcYzg+Ow==,type:str]
    #ENC[AES256_GCM,data:O0xTtM8PAkogtqsddA==,iv:daH1GZ9HeITZW+ud5zz8rTplWkxMkvN+JXIgJMjQbKw=,tag:3fKPF+8Y3oZaHbOYLc5Jhg==,type:comment]
    PODNET: ENC[AES256_GCM,data:4QlYqMZUXVCNecfEow==,iv:dZOFNUZK2w4j6O5d6IvtyT8zHeE/JeFsivk7rUKax2E=,tag:7D07qkCiMMdYhRPPgW2AzA==,type:str]
    SVCNET: ENC[AES256_GCM,data:Fbtkkvj2M+Ihhe9uZQ==,iv:nvCrlJOR1QFQ39pOGe1OAMqiRABk5oHM03V06prsYQM=,tag:u22ghBNjVBSYCmL+PtEwGw==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:yzmQfXWjCiTZJRyqbJc=,iv:lFrgVG5D47GE9mMzw38j7FAZx6IBXUeie7TeozXbiRo=,tag:r/8PVkNaHHdf9VDs0/t8gA==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:JwrB6XQQgtD3FhEJ,iv:yj6hPV4U+1ZaUwcjMuwc+/ufwvmWiO4om5uT901s8fk=,tag:4A1z7/r2XyJIEMgLH1KX4A==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:yGj7XBa0FKogXgvx,iv:FZEfboFgadxixR5bJTKWC7LbdJ3T9YptthacRxc2Dt0=,tag:qhlAP4XZ+gQUSEFtRomgVw==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:JqcLVKBqoI1Sodns,iv:qcZV7fKWj+y8MZgvW4BBHYa7mZEh0a1dVKhiEc8pmYI=,tag:kG6i81fyyH2I1C/FmgOiCg==,type:str]
    EMAIL: ENC[AES256_GCM,data:JGe5gqWCoPyKS19v3EtBn+X+9WQ=,iv:hxOxwDStaAPekSTKrPFskExnyvLgzlsQ0KdIpfHrCx8=,tag:YzxG4Bq61+cE3SjGFgXrGg==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:dpXqCWTkcr+qwaxaXJD80/Bp153Dzv1K+P51SfMs/dLs5/egBhNGAA==,iv:Lyx79JXAETwTf2nbbhJzRzckp36HYDL8cUc/SLwxdt0=,tag:ZudYkXIYDpMzhxC+xuJITA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:AvIamw==,iv:63n9Cm6/QWsYrA1bD1q439HzWEucrt8ols0v7+JffdM=,tag:jSZ98aZjyLeOxZCXqJCqTQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzV3ZHU2hpeThkeUdNWkNJ
            a3dYVE5HSU1rc1I1a2RzVWpOR1RaWklGSjJJCnd2MDNEa1JRNk4rNE5YUDN1dUx6
            VHVpZUEwZjdVM1BidWdKN3lxR0lFdzAKLS0tIG1GZUlQQ1orVUZkQzdLWU93YmZh
            VHRPcXlZVlNSb3UvSTFIWDhDK1dFb0kK1YumB2vQut+YG55Y14Gy9Pl60lREekLk
            gXeYJ8FXh5sfoDltx9lOVMhjGjGZmdG7qXHOEAR+iRHYs3vJ3bzBnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T21:03:45Z"
    mac: ENC[AES256_GCM,data:AykUac0kqEe6NE/xS4Xx0TscFesfOXTCevQ9swqQ4yqx2rkP3Lq7f01ffvixBnl1mhem86KGYTlIuwT7NXUVL/8zDZBCMQUYwibxafwuhKhgynd2EQLrCXSCgjf26kqGFiEhpPpDSyuSnoaqAh5xEa6lbHgKr1H6ZiVeswpA5hM=,iv:k1tFxycUjtkwHiJBM5cxbT1YNmIs34VM75rbOxCmkpE=,tag:Gq9JBsDCufsK2F5Kd1ec2w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
