apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:DFat6PCuHC9VljTlqbLIZT6AzGxxIFG9hROwDpu7VvNj7p7nbjeUMlKSwdcoki9/3sO37mtrb4BYO9VN3eKwC3g=,iv:vHnnd9LNtQIcQfrJMe1AM9QhIUmuOgCl1Sice25AA+4=,tag:w3Ox21ctv0+gX6CzBFYjFg==,type:comment]
    #ENC[AES256_GCM,data:FXPqXrbtGEA2QJxQxqX6HwlKm+/xTlSBD1Nykk0/el2m05FiuQLdYEtrrhI=,iv:vLf0vsbRUt6pgXPqJObmJJeWAsGIBvNiXPa1FbigGUE=,tag:qSo0jubxz/lXI5Vqz/4G0Q==,type:comment]
    VIP: ENC[AES256_GCM,data:JRD6P/HeDnIFdFQ=,iv:b3aTihCKGQGWLYVOWG2rBPqrA7tRY6TNrsEbHC5dRGw=,tag:Sr6bGKxJunFa9CMGYZ0JKw==,type:str]
    #ENC[AES256_GCM,data:NloOkZGXvefTY54gTCSqNpEBmPD5x7vOuRM=,iv:Je3Cn7TzJx+1BCXpjnPszPx7G4w75shei8yrou2rrb0=,tag:eI4sxTr5VEKF4NVjY8qL8A==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:hj2Q7l9QtJpV7Pc=,iv:HWgOOv0ljRZ89u2WpwXZVyTMI20t4vKz655WEjvQC4I=,tag:MR7LRtZY/1utGsuQMg6mBg==,type:str]
    #ENC[AES256_GCM,data:Zj3ccvhdRsXR2PaUMhMqF7aDbkITSaSFqRK5AkHNStiJ8w==,iv:+AwxiTb+jDqeyGRemLKQDs9z+06vSruP9kr883HJVYk=,tag:pvMelb+wKhamiBV2smkbQw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:3Fh8vP0ui2fiNQQ=,iv:nVidiskv/3nN1vUG9QQGBjuXKWu20hHoq6NJrydAAN0=,tag:+DXJQYQN8I7HkDuKmfssZw==,type:str]
    #ENC[AES256_GCM,data:aBM8k7dLqdxIc/rg6lGNtjxyM2sxJlE1LjvySrDv9mug3WdhAvugf04C9xfUQ2Q=,iv:M1AsivxKiSWDVlVJMH3DyzYYvueB7pZGdL+XcrV0310=,tag:Pd+wpupfvD3YrMlXExjHeA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:MixPuIRpM+tSQyw0jFxM/wSnyhPx+uPIyQ==,iv:/JulRUDawU7lbaFkOJ/dh0jiHnxRyTz13bTO8p+UNi0=,tag:Vtr+I4WMxOmSZYHrSKlbjA==,type:str]
    #ENC[AES256_GCM,data:+RfPi6K5Z+3GhpBMfNWpTACCHxSCpviodB+PsmH3qnn5ctLyAdPmf8zbAvXOxKptBXzO3zIi87ADu8RVUyVPBLi23H7CKVJs8QkwCrixkdo=,iv:ySiHrchBDR3qm1NCgo+5n+JeH3P6sF0x30tE2kixRVA=,tag:RW36xKS761RgOrKy/iHJ8w==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:7BuQkU5eV+qKxyS/,iv:1RyQvWD+4IUiMfZdCSF8/dfqe2Kz58Ztyty58+wknq8=,tag:idM4QF0ZPajDZgNEdAA/gw==,type:str]
    #ENC[AES256_GCM,data:7w3a7C+JcgFWczMVIdoUlZp7IR26rt018++ZLvlgrhiQinuZVybVkPyjgcto5TXWNEZZT0jS87o=,iv:C4cgZ6qsXiWNQPI7I34+6DGpIa+hUOIwglKraxlM4h8=,tag:c8WBUelDmSlgKEpY2FmaZw==,type:comment]
    #ENC[AES256_GCM,data:Dqr73DQ1cmOq5G0kORhIp3svocWZVznRzw==,iv:E/4km7ucmZ7S3D0u6yZfL3s1LfPVbzNuaEQO1l0ocYI=,tag:zzrTi+QmWLMQXVeR0XCNUA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:Si8v8XcZjfdOqKUCggU7lKI8osz3KOEb1jUSFM3zvk1vQ2Yl8uNyYUkgTA==,iv:pstPA9NHj87Mjl7EQRy9SyRzThd8+/xgbv9XHVNvq24=,tag:tOhpXr3XE2Bj/Oq+BLi9ZA==,type:str]
    #ENC[AES256_GCM,data:La3z1HFXEEpJVP9uZg==,iv:tq4rpFF8jiiE97PUlUBkT09QplBLz2x+cF7WpaD9QQQ=,tag:Q5qA6IOq/m8t2ddrlC+s4w==,type:comment]
    PODNET: ENC[AES256_GCM,data:3pyE42dQstfXha0yLA==,iv:+JCMp+325KosA3z+/Ial4soEH6CToQXOVAhuTve/cAo=,tag:AQHf9PyxFKOKH2cYxkBtsw==,type:str]
    SVCNET: ENC[AES256_GCM,data:9LirXPwGBuuzeBYKfA==,iv:nO2JNKlLnK4WogZB/y70NLAwyitRGCljpNdWC90CIgc=,tag:uQf0T5OqyUIVZLOcwsIH+Q==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:o2idjsAkf1+auMp2Bnw=,iv:9PlUe6akb5/R1RVufy+0cKgOXxPEvP4jBuwT/BgOHo0=,tag:/obw3vJSrqcFqkQNtxLoiw==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:Z7EiG1gYTltTKK97,iv:RFr9qsgYHgldU260bNAgmxBLti48XiPYRAcsCwiwN8c=,tag:GQSr+0Urpfb4bGMrN+/fEg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:Ca0r2lHtLdDX2x8n,iv:yA9TtN988lrgHbRdzB/HTEtbvkpDcTOq1c2f4O54jtE=,tag:1ZB+y00uOnDjWnctu8hI0A==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:Uyu/uIDbY0T3Fi8k,iv:IsWMN8vFPhO/yzTpV2ffXD1BnMCZnh3IEA7YJ5beHrQ=,tag:QKPNyDpgoTR/C5oi7/QGTw==,type:str]
    EMAIL: ENC[AES256_GCM,data:Apl7o52L6euVQ15yxkyvItL21xA=,iv:1huI36hLYbt3C0LMJIjsCzlALZzmBBfTVa0RzuTYUK0=,tag:QJMiz01mU6m96rlnub37hg==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:ldvPBHndTWbMHfokJYqT71qv9/sn/nvPOW8TBAiaG+sjWTgMX/5ubA==,iv:2rB/dAzDcJmmmN+8ch9xHM+zpPYZLKQ2DeGKkqKfXZI=,tag:hZyA5XWB3t2ByUdnbWpoeQ==,type:str]
    ADMIN: ENC[AES256_GCM,data:AUBt/XM=,iv:CgQzPvgrj4+bignIakruL3ghQcXhT6GHdnCr6qJnItE=,tag:T3RuzPzyVA28Vwm+MW74Cg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:8i9hjPuoOFw=,iv:tZYLdTGVJDFmuxiNSBap+D7kpM2+joo7h7wXU1k1aoU=,tag:Crzmu+evptHHZN5dHYrAAA==,type:str]
    VPN_USER: ENC[AES256_GCM,data:HDO+Hk0K+f4=,iv:6r2eMzMrmW9MfV9F4doddA8SDgIEyZdyHFYlhPF+q9c=,tag:cVQUZzN0Xkzw1Kw+g3+Y7w==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:WUJDgYOLNTO2ag==,iv:kx+UhxWdKT8+625d61XO9LBCDYbYgMk2Y2Cv+Y4BprE=,tag:hBekQbBQ9oM7KCnL9ZdbRA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:WhrmKQ==,iv:CtY2uTdzXhzE7NeFVtDzJ5n27Ub5hGa8qVGFmI0yVFU=,tag:/uMku1kesQ9RWW3esrV9vw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN3BZcU13QkJYendtWGlz
            SWVNMWNnSVEzckxvUHh3VVhZcWh5VndLc2pJCmlCWTFIMXkxME5CcENTbGlMSVk2
            R1g1YkVDcmdEQzN2aUNqUGMvNUxTaHcKLS0tIFdwY0Jab0QzSVRiVUNsY2hlS2d2
            ZGI2QzRraGdwalBqcGx0Qi9lcExJSkUKE0joJxHV7IenqExzNHnTw+N3NSOwA/Xk
            P42EYxNUW9ms58slZqVxFDzYwt6BjYjMPWl5P3pdBOSxrOF/IpDokQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T13:48:42Z"
    mac: ENC[AES256_GCM,data:mMZ9vsybZqVpGGrGxLCD7oW6CaA2ze+7HIH5ap5P1Yk04z3te8xQbMDIVUP+7CbGhYDrekOxihNo6oJoJkqABp176jeBKhE4UihZdmgZnOAYJSlWXZfSxjpKU/SeMKlU/kVMWI447OuJzjCiZ+t/e2PvwQsEs+sAJBizZqJBIVc=,iv:HnaHUrfOlcEncrEqpNMNofROQOjwTsiexqkg8D+s3Os=,tag:sF/e4NJbeAdyRDK2q6krBQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
