apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:fFA6Hop06T1SKLT6VyY0pwGcEavOUNoKC/Bup+Etirz+MNSpz1fD7rBUFgCqSrThJeIjzG0XUJrjsqr8su0QzDs=,iv:XbSV40SyJ/KZPsCHPm+BSY5H8ww+BAhp1Uf4p37YzCc=,tag:HvvCwpdaRmAbEkXwsYk1pQ==,type:comment]
    #ENC[AES256_GCM,data:vUHgud2lRbTOIigH3QsunBMRylx25sRMUucW/kP2s7vXOYU4MhtAvqHZivE=,iv:E8M0VtzhBucuzd0r7WIQ/An3aqeh+Grh2qJHbD7tPlQ=,tag:fMqIEnvKm1fP53ACx6TPGw==,type:comment]
    VIP: ENC[AES256_GCM,data:pfh1NsIGJaRJRf8=,iv:KgclLaFZWTrB6V1+bXz1wWmGTF8b8ZQILBBgrBPqZWw=,tag:nKcQBmQzJSqjqjeHz87boQ==,type:str]
    #ENC[AES256_GCM,data:bk0ONWTnado+l+XkMQQ3SFTvGFPpYW4L5lr7,iv:GzkGmMfLfZFz6SOYqJA/27Er696JBiU9cnmoBf3ttqY=,tag:YmkxfGe9OJQz+QRN+OxQFQ==,type:comment]
    #ENC[AES256_GCM,data:bKxjAu9gQOyb4u0edPGi5QiV4ch/rgHwNeWbkv8nd1fEZphRkX6C/SdlOP95Fguu6AHtr7bTC4NP7y/I7lhCNZdV7U51+AzEpG4kPmAwM0OF2UjxcNL3qs8=,iv:vZnOxJlCT8Xzk2txCFQ1z6d4/C0l1XQwFPi01uyvbyk=,tag:eOrsW8AX2duFsEJB5yMwVQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:i4bwhOFjcZQ4384=,iv:L/nA9Io/0pepnS3GuJcJp6worSCWRj65JBe1VEpHEHw=,tag:KPQvCvYEY7bG2nx9UiQc2A==,type:str]
    #ENC[AES256_GCM,data:eiYeTCJbNp8yLnbCCYGE9fW3Tca7gLQHLZskBQhc5f4gPw==,iv:UPxP6o0IXHoiCIqz9226xz4LKFckWLNQfnsvqJKiCOU=,tag:VWJY/K7wEgTBRb9KdiQz1w==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:pZYLr0fPxjLWnbA=,iv:hWyPYM3l/hJGbod7Hw8yWA6WB1nH9ln+R+Lof5ok9MY=,tag:e2Z0ox/kqwnl1mUe9yYi/Q==,type:str]
    #ENC[AES256_GCM,data:wgAnuG2MYLnZs2eZJw+pktwd+CNVDWYoPXUIuWmipmZgD/YQFaZXo4CJ7ImT5M0=,iv:4zrQdcThT+Aeo9bPhV8a18EKw77gbdRawLB4HK5bbMM=,tag:LfcGY/2Vj1dYxZuItUYvug==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:Et3q2QC159RByhVoWy5xEYxM+ge6A8C6jQ==,iv:wp+m8Xz7wpd7/FC1Biyb7HSzGJFnoiTITtbljxj5bSQ=,tag:1ZkrDGeOFr6bsuMa6a7T2Q==,type:str]
    #ENC[AES256_GCM,data:xMUA7Tvty/7XMG++gJ939t5ZDAYsP7HYMFlmorzrqzokcxinwCjmcn7E9+1BApegBvk8o5F7/gm+bYZjJDY73ksv622vxZsWwR/TjhF/zUFuQw==,iv:/r56Q2dNYm0dBin1Q7Z0NF/AkYWVx5OWjB7G9DTJVJ8=,tag:rVxfkb7uEBEHMZMwZMjA+Q==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:2eKdFAdELxD/PYEc,iv:U602j4BdwwW2LwUI5/VdRPOhcd0vHeycJ5MITuZ4zpM=,tag:dOLtSsl+IhRBjSnDHqqCvg==,type:str]
    #ENC[AES256_GCM,data:XnP3H8JBF9A7wMzUHf962oFANjlb0xsVLXMjqC7pUm2C,iv:EZTcqoHCX9l2witOgEOndKn5NhJaFvw73zoKoPBfRJY=,tag:9FdCd9cw5gFJX2ZbDDTm6A==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:cd4J7QAJ87//q3jY,iv:XiNndoIXGGyE+iSmcQzNh7jpkwNi8cB9V6bUPmKOzaE=,tag:qI3kSqapViHnKF1VsEdgNg==,type:str]
    #ENC[AES256_GCM,data:Lc15dFzyMqGNeHREkjpkWSPnRJNkQWRCM1oCt7FdP5Te5R5MTsAeWAFWyQfF39dwZNLkiWhBBFbjeR0Xp4doRJcQWPOu27eyAZFHsxp7CX8=,iv:UgFdsrMI3cdH/Va+A4E9i9bL4iEQ7oV2CQStkHPxSws=,tag:t+ugwiFmmOc/c9PQHLA45Q==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:GRpHXIOhK3cUTsLW,iv:sarcsLFVuQElwCQ8AlgsTWb6YuKjtCr485rECbnHJ/w=,tag:gWeSRTa/QTEL0UyQDUeGpw==,type:str]
    #ENC[AES256_GCM,data:SAc+Qj1mEv440pvJD2wvwxt7KsqhjpZnhtOHb46koC9xDfb+Y6HAS+ummFPR+ARme75nRoZm/w9QPYn0UMj9eFzwSlx1J4FQQ1ty7+Mj7drUec4EcyJN,iv:9PxELiqJu3i23AR4DjtTVGQcJ3FuJqMX/G+v4Isz/QI=,tag:8jKiKNBCwZsfNVvZdyZg3Q==,type:comment]
    #ENC[AES256_GCM,data:m4T0JumH7ac9xjw9VLd7RW11DmeoFrtKMMtQ66jqXiyvV3qAN5n1m5bg4YxcMv0q++hQkoOarSMCqJ5dPcZM2P/0nA0n/6CHV+s2aBDtI8XrMGITKgcy+tPPGRkNHihrirN+5L+W+Q/DBqHTvUFdHZ0aQam9oAF4s8jTTg==,iv:0NlrvGbIk2juRTHkliuGkehqHNQrg1vScwGQFMVHqck=,tag:2fbZ0JU6+AwyTV1CxM6tsQ==,type:comment]
    #ENC[AES256_GCM,data:7JBvqPat6/w5jRB/y6vzwqSIRi20mIadlOwQu9llXrM0Qzn20VH1BMEkX6cQwWCZiaVGXJQpL5TBYl1lortf6usAwnkl+Dpg7dql2122Wns=,iv:ZD5zyk0T1znlIQ7+0yve0BnKg4yVD0plnt0XuoJi3kQ=,tag:8w47DjBQrfLRqbZNQwGrTw==,type:comment]
    #ENC[AES256_GCM,data:xjZGGq8P4Ut2OZuEyR/+UOLJnRp6Pmg1t7uj1k75djKhcjpYNiRfGSoy7Y6iT8ZofmdfSvxc,iv:HnGDolb77FCuzBdhEMKXu3c8iFfq2BTW/9auLJhGdsU=,tag:mH3VOyc/DSpWkGoTimp8vQ==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:6s00aN0fipfkIGgYVtM=,iv:Uwvis3mckMX7sWOL/37ZvTBp38G277yX+sO0uta48+w=,tag:tlb0X+V5pvftq8ad+t1ATA==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:KOcHPLwaqN32U04F6obdy5M9qBA=,iv:a6+IawmmjMxm1IMX85DQOVQpOXiE4Q+zUzHlW5j35mA=,tag:CCTc04onwL1ULy2OKpPBeQ==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:PlAvaheViZBMwcjtkr/CKvK2cUU7lH7XzwEqAq4odgU7CeCO+9zfAQ==,iv:YUr0O/cYB2oeKHCYxoc2KirNbf4VIgt3Epj+7iXJGaw=,tag:HABSGf95ctjO8aF+8UQAIA==,type:str]
    #ENC[AES256_GCM,data:b+mmomd2k6rhxU3UySYXqXHbSnKJ8iUUHd6H2qTW6/5w2ovnlU7lkPCw+Pi7eVCSZlLySqfxwmM=,iv:BbnX149YH0VqJcAQ+tDHHFdSedzOhBLAjmEmzwDsxQI=,tag:2jMNYP01FPq0s3Q/w5O/Ag==,type:comment]
    #ENC[AES256_GCM,data:OSuiFL9MQWLEoBVaHPWqr+z9bolvW2VNeA==,iv:0ZNYEFz6cwSVrlmitoXzhffsHMN/cXH6D18yldf4tro=,tag:3mvwtshTrjGyTz/WKWA6jw==,type:comment]
    #ENC[AES256_GCM,data:8hfvj+HeL3FymQyVPM3MXsFweDVfKH6xRVDHB3ptXLpfRC4CekfyHkRnMu6yy9bBqNVfgpWk1+aVBX8YfXu1TNzjavyhFfDFOJlyNdk=,iv:h2UHMkOlAur6hyJeMOTnxN+QPxpKbu8VkFq31Tnhhww=,tag:Yqry6tmuJ7bwT6/BApK44Q==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:BgXIRpNydMBgB8Q0fNmp7UygTsbb+K4B3tG2j1/vqEDwGyz5+qYPHFlVlw==,iv:AiM9Cr6WSVSsFLcBw8Y4PZ091A+DQPiqScv8fL4bUcM=,tag:B4sZS41rCeWgbDqDmo9hYw==,type:str]
    #ENC[AES256_GCM,data:etBmklduy3IRA12x8ubpcWkqdM+3x9opaTg/QXS1DqQaDpMADEAgwn0c1WJfputfQSni8UTNxcsfahc+mPYdFRCRjerb09U=,iv:iPC+OQbnvIC+9KQKAUa0XadIcNPsrKTpz5BxURd4Ktk=,tag:nx4+1x4LexdLF1dCYfKLYw==,type:comment]
    #ENC[AES256_GCM,data:u/GIL489l7q2AuqtW+mRMco/48KBKLbNWXGw06iNDjiPXXSibBSP0nwxPfQcXHmwb7+59sZB,iv:x1l9m9YjawqcfiSLuj0Hi1ggn9mmWdg+nwOq7Y9ArPM=,tag:o2TCieO+nJ4ahgDvbYgLTg==,type:comment]
    #ENC[AES256_GCM,data:wJ/E7Q71HxSbjl/UVotHraA3yNwJnekDzkBpkqkHdvezda4=,iv:0R0aljgU8EgE3yb/hF9FwHRsAhRBmraOXhP7ec2bN48=,tag:YL1YuRMgOLuY8Ouitzcn7w==,type:comment]
    #ENC[AES256_GCM,data:l7RyTN5NPR1McsVyOLE95solUPw59JGr/OBoXZUOC+tsnBD2caKM,iv:nExUTCxiv/cGU7sUCfH99/FzyRyr5gNzepHYtApCwYk=,tag:86/XYjcrmJYdD1ORepZYtQ==,type:comment]
    #ENC[AES256_GCM,data:0XqaNQkOrhUj7bCHqm8=,iv:BHFL5lLD8nJwl1cnOpdJkeq79t0K3m7xzSZ7T8T8S/I=,tag:woYbFtf3mXnp/xkByrh/KQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:vXJaROa9lf9MEOPCfg==,iv:m0w07uu/jYTbKs7OWMerW4aqP8HQshn5Avd0SVJ4l1M=,tag:TnH76nqNeA39/OSPj5wwZg==,type:str]
    SVCNET: ENC[AES256_GCM,data:Pmqjf3SDLdtMXvb+Dw==,iv:ZWgquWhVRgc0TV4mDvdnABDG+QMFwCIfoDbPp3d2KtU=,tag:wO7GdGEat3BK984UOycDzg==,type:str]
    ADMIN: ENC[AES256_GCM,data:YhQMezo=,iv:bfCYulcgUFtzgGl7IM3SrARthXSoufxoxJ7qs3cjDcs=,tag:zFiCfMDoEYBD3FvIY6TmcQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:aRmHfcSYYlQ=,iv:RGC3/Hd6HysrAr3EPvQnBMFYjfWHZLXnJHFjw9yxfno=,tag:q5//b5umk+61ujw5Hzh16w==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:/Kd4Bw==,iv:U7YCEjQdUfkZ6iSMU+j+SFUBNdNDkMcl5rFVWDtBjEA=,tag:UilJAPXw1jQ4AmAjxLZP/w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kt6a6y84qj0y5ndxtn6n77ru00musyv88q5tu7vm80095wv9s3pqzxcxxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZm5aTGx6U081c1YzS2lX
            ZHVicnFCS0puYUdzbGtoQkVVTCs3RnExT0JJCjJleEpmQzVnaVVyOUxlUGZPOVN0
            dkZQU2ZLU2h0ekFhRm01V21udnR3aTgKLS0tIFZONjgycm4rN1R4N2hOejZISXBq
            L2pyUjM3NThQZlFRQVBodXdoV2JnWkkKudMjTJSiCFJFAWsppxA1Ypidq/sm7Q/I
            RE7kS9LWChTS/agTMqXF04CycVUV/1PVGGbi+IKYlIZHX4sQuOYgpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-13T19:16:28Z"
    mac: ENC[AES256_GCM,data:zhaUBK6Rh5oxFOTb7zEczcasFH/dkqHjDFDbuXrf0yb/yYVOsxipfbgawApupy2Spcdl8AhTAt+yxVrQLAslEtz6lmvRpPebIoHskj+kfPnXvNPdv1PazIieNwFkXKgKugzICi7aN20aa1dRsFBWKhUHsQWRwL3tkdyAkutzUTw=,iv:9/lqW1tIczQDotbXJQVws5UbMq+T3/HQfFDSn59NS/0=,tag:75q4JCK7sOOahi5wKLq95Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
