apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:xQyV+4mxf4Wuedq2D68Cx/2Jw0JnWPEEcC2p/cBXtJzhhI2yDpPBvtkS9Q1B9Tn2wnabnhlpI9JCYNwtrQOlRXY=,iv:9z+JTZrYI/I2XMugebLFfmNZf4Uu1t7rEEe4uq99nRM=,tag:M14k2e5OIhd9LpfuyIZigQ==,type:comment]
    #ENC[AES256_GCM,data:qNoT5JU89NNpvdow26G7ZYoI83fZEvB5pxqXLsUtfjfxVaJtBIcjU4wfcTs=,iv:/nliBqCKhoDBkPvEJZO/V8EX8EejwBpDCwFgI1Ypc5c=,tag:gCT4U7siBdaZ6CBvQYRahQ==,type:comment]
    VIP: ENC[AES256_GCM,data:NKZ6Gwt/jKVCThk=,iv:1xLEXVhxeEbcNcqqBhkL6rSj1M28vVk0D5MkgOAi+ZE=,tag:B6gTjTE8vmtlQe+6beb+Sw==,type:str]
    #ENC[AES256_GCM,data:OY1QTTg8xvLV/+Ntxo0TaLAGusRbM3sfu8Q=,iv:+KVoiE8X/fd9VNsk0aNvo0pZf1weVaRQCoRCHZa3UKA=,tag:JxTeI5sGo9LetvlDW7C8pQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:J9YeSEIGUzGV4Ko=,iv:bh+DcZntQId2ZXI/aBaEb62W9cAIc7Vhix5v4s7By14=,tag:JCLqQpBDYtCjz/vQjLBf6g==,type:str]
    #ENC[AES256_GCM,data:/GJr8AmWKDp5M/h9nvNUrd+swH9xP/nkUtxFMHuxjcQ5Jg==,iv:enhp85MU4DPUpkyZBgAZla1+6xKNjK6ulueyxJllwtk=,tag:9N2IVaf6CmDyDRJJt4AXZA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:q2eECehFP8DPXp8=,iv:ty+gSGU9CsRf+5ZKAAvwqAI1ILmyf/WN6XkrEIuCa/Q=,tag:PZwmHqBaX9jcBjr50bTu8w==,type:str]
    #ENC[AES256_GCM,data:ExmjgK5fz9ZGCz4dAL1lcTkHaGZDbFLmUApNN65vckzK3puO1d7PaqQjZqyKW54=,iv:GirfFHeoIDAnpplkTs99oOfHW+SE3mfph/aaCTYnSOc=,tag:7vXFsyEZMMnwEW2oALebrA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:etO62kRE57IVyk+923AisQMFaCa3KSAhzw==,iv:aHzfBbKSrscQmaoSEGJUWY1pzHkA+s3tEBYXOHMMVcE=,tag:qFoPKSX7PkwQMrb1Ly1l2A==,type:str]
    #ENC[AES256_GCM,data:JvgtB5knvf3hVxvgOSssCKp+JiCo4k6G+d1iADcgz36X0vcSvmIzoUvyOFJffI6FK6zHEJBQMx2gi7Kwjdar8kErcolXOzqxEPQQVUMAXeI=,iv:8Hf4Hba+LPwI/88W0e+tI34IZgHDn0yOJKSJMtyb2l8=,tag:+t8O+S54axqczYmfI7o+gg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:H1uFcBaYlEMJwmmx,iv:LpgDtyHw2BjH000PZFneqmhX5YY4Cr/5FXKLcuZ8FKs=,tag:vUwwwlfQ5yzBMnaaSO63+w==,type:str]
    #ENC[AES256_GCM,data:ZRlNfUdU4nApziL5MObJ1wyfqH/TiyOGDxqyrEUKlbFzVB2nXRoxAl62TbbGda6P88T9F3jIdys=,iv:HqmUEYZRdDG6G0gWQkpUiVoJfIt1dHvC8WNKI0BotoI=,tag:XLl6PgrtdlOyOvEoBFtYAA==,type:comment]
    #ENC[AES256_GCM,data:gW07bXP4eMw5eg5Go+MOiVp8ODj+cHcJJw==,iv:XWcFGnu74ulFz89vET6ZkWH3en1s4nYy7uOzUxrk+FA=,tag:iZ1qxx9x0tjv7Ux0eq3EBQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:mAUl1/zCPl28ikvRExPo4r/Sw/3eKAlZ38X+V+Xxj8CJyhvFrmI3FXKjhQ==,iv:qgxGuBMP1zaQb20OR0OcWsjonlY3KiKp3lGjM+w9tKk=,tag:mAraacI78nsgO7XRENAjlA==,type:str]
    #ENC[AES256_GCM,data:tq+54/HMveyWAy0MCjrmlC5qk6PqCEQJTpiiIERh8808LN+CChs/U+1Ue+T7Bnzbfvg2svkV8uodot/wawQevYVENeX7XPk=,iv:qGGfdXoo+WUo7ufP9i+Luk39KhiaUIkbG3DphypLQMY=,tag:YfX32kiMnap3Q199B7yCUA==,type:comment]
    #ENC[AES256_GCM,data:CNDBsgHDXMMGeB6bvhNvpWB8gCCh7V7PI3YdEV3iyn5sDN6ffddNQxa4wrABFesO+U4B/Ire,iv:1c51CvwWAuCBrnasWxM447zO344i9iaNfSJDX2JheOM=,tag:+nihPBICf6tA0U/TqEt+oA==,type:comment]
    #ENC[AES256_GCM,data:6jHPIN7KI8JQdmGTtoFpTQ88KtLF13s2HBPPkWBJgxa62sI=,iv:4g2GPswZB084WGuQVmnd+BxLiW3LGZXh2fbitvc48Dk=,tag:ouQ6TSXw+R3L3/KAQGNpsQ==,type:comment]
    #ENC[AES256_GCM,data:q4mJ2FAYj9HYQYc1HMGbeWbs5OhFwDW0NDzeu31foxkdo/7Ixf4J,iv:wQSujW1OjaeZdxPxzZSTJE+OEwuj3P2yUOI/OleI3Po=,tag:VBrJhBMEronTVeELnPRCdg==,type:comment]
    #ENC[AES256_GCM,data:cYFDgg/dqkV2PAL7bLk=,iv:J41A8QeOlf9skh6W1BRqk1FG+Y289ZnGNOo+NVoEdjE=,tag:Wg8b8t2Iq7u5C0HAljSTVQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:XHSyScqI5mrOUeOB3Q==,iv:BPNq2LFpyG+HC0Qz2sGbV/AiwwEzpH3zCmp9OKx1A0M=,tag:LEJtNs/uqB83EqdJ/gbFtA==,type:str]
    SVCNET: ENC[AES256_GCM,data:X6Ewf3F3lyHIO1bdCA==,iv:Pr8q4ByVaqEOyXzMIMQ3I4l2/LJUAA9ZZJ/YI9cVzQk=,tag:sZR49gl09F2zc1TAHM5N9A==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:RgpSHtbFWEILAckT,iv:/CxtQnUvqanD+RIxGmIwh+UbEAw9QI2R/BNjXvd0Urg=,tag:9CFp/ZgsJtUCZJXdQ3tjAw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:0R3SeW0UAsaImI+C,iv:6XUw2Ai6fcdfyp1Ih0h5LWWfkzziMt6n/GdvOws8E0o=,tag:c3HTvl9m+GJLs5TrqC22cA==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:f0S67IVmGuUbu6KB4wM=,iv:uzE2BTYzRKzVFzcyAJHuKHgHnNFW9tMHWA1fNw1jZ6I=,tag:v9tbsy4WkGX20szsF3FXOw==,type:str]
    ADMIN: ENC[AES256_GCM,data:+W/ith8=,iv:tHQDTAh8zhZOz4NFb7xB9Q6erCCapjj8yJHxNkfmQJk=,tag:VYlIiEEyEpHLGBGO/2lO6Q==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:RwE+F07ua48=,iv:zU5jlvSZiECWjU9fPuitI6qlaFdH3Mb6L8ydvWjOYKA=,tag:Do6ayMf726XX6uHXfJxPgg==,type:str]
    EMAIL: ENC[AES256_GCM,data:St9R0m+kbWCDq1dUONFS4msRi0s=,iv:ccYZgYE9N7SejcnJ+CQFe/col4xYL7ImMbZ44U9uWt0=,tag:GNjJpHG+uU+chAx5RxfSfw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:9I6NV5Ng91+ihXeaISpNzISYB3/AsHdqHEmcgXGT5wdzGOy2z+Clhg==,iv:G4YCzYAFdTGU50VYPP8MpL670YEBEk3flkBnJsCwoVA=,tag:t2vGVAg2EozGGqPk2DX07A==,type:str]
    VPN_USER: ENC[AES256_GCM,data:PIdLRCXZVeM=,iv:Iqc8tCF8MeX08wtQ+v7xwtiyCX9cojc6HwdZ7l1fNcc=,tag:se+lxxovttOrAx8ikSWHrA==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:/6S6ZFrfgbTa8w==,iv:BYiQBAjFCdlrhUAOjSqB2a5B5Txnw9OgvbpV+cvsq4o=,tag:Z8PoNplA+koV0gCzl94DSA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:sMNuVw==,iv:skK9AX7o8tu8Yhd2jlZ8/f8VJ85+V/0BbkkIAyvQzIQ=,tag:HLcrTto5cn3SVO3IBbkYgQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caandqrgue5nl44eylp4nvake7znrvxretz3uy3r0ccfa2av4aysejcgfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRFFFbUx1czRMYUJHRm1K
            dUdaK3pZTVhhbUFlL2ZmVlVVZWVVQlJrSHlrCklzRE5NZkU0c21ORTV1UXh1WVNM
            NmgvUUg5NExZa0RZM29pL25uVERvZlUKLS0tIDg0eEdlYXJlaXVSdm05OTRrU291
            cEJPNitIUXRhM2lLbzAwdk9hWUJNY1UKLECootlHAPEItjuNyfEyBqrPK0G/wqmS
            5X8OabmUUVY3yl29QeGNK09mwGWvwgGJjATcPFTwCsDvJ1LNF0oqcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T00:35:29Z"
    mac: ENC[AES256_GCM,data:sOD/+iC/bB1pPtYPn7cLiMSdI4Gb9oPo0d0oMniybqDB4TGQ1r0mn6NIPvYRds4wSRDb4pxzjCkD0KGx2DxGg9pgOlxVEx4lVTlZXmfyLIHtDxXz5rU5UkZm0mNWd2AdnBiupXbFmZdH+w1cOPp1MHjNmFF/QN/QZQTh3KFddJ0=,iv:n8lXLgIg7PYPbjn2ieFOvrF4gnYf5MqNTqjFparC+uE=,tag:z2TAiO99Qg8shBn7E+oOlQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
