apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:JL/I3EqfxmHtQ5E/scgg2WqszLYivaG6ZaCRzZl5TznioGWrwIthMhWLTbIohDLLhCMYwIkoGdMTU8BBsdC6mQI=,iv:RcZ9DeBesKmYpCapv63AwqF2HCi53ANS3xFAfjGTHKc=,tag:xsQQA37SJJd2/4kpmPQozw==,type:comment]
    #ENC[AES256_GCM,data:cbhN28jBzr9rCz0AqfCenpx1DkGrP20RpnV6qblnMTuC5TKdrLyB3Ml6cJE=,iv:0s6jc7z5kSiWp2nBUH0clhgaTDl6lKDcmXCWjwB5i6g=,tag:08sIdANhZVoNPo5X4JvZMQ==,type:comment]
    VIP: ENC[AES256_GCM,data:MLFOfq3WDwfBfzM=,iv:Nc5ZaWK3fD4MwWPpuMIsd4L4EV0k3MyaMhfi7s1dYyw=,tag:3/1FWOpB4btbXWoukPFFvQ==,type:str]
    #ENC[AES256_GCM,data:LWLzso5a1ed8sSyQPy7ZXf99TI18zJ0qGw4=,iv:Tc+jE7mKbt/nPDxHZJYJNuP6W+Zuh3+++IFRaiYiqKA=,tag:4gumIAWXjlDQT+vDV7ekBQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:duwH5ZlS03KTdYs=,iv:AD75Q9SMSuwH6OL1bSheBCYz11OfAUzfdDDuAJfDkuY=,tag:GqOspeh/6iKi0Ghx2HF2kg==,type:str]
    #ENC[AES256_GCM,data:oW932irT2P1CnCnUiKNqC1NKl4qBCllFtN2nEfTJUFUG6w==,iv:ZiNrGiBB/36US6eu1K4/C/jcBlOGJpr0Tql3Awe5k9k=,tag:wLdwzmnw6kAKpeG18nbY8w==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:fR9Ttfw8JqTLv2k=,iv:2QOy4ktG5uQx4ub4+qjyiCQc0/bad5CuxmebkGu+PxI=,tag:FxNNs3IBCnWKc1hmv+6Kxw==,type:str]
    #ENC[AES256_GCM,data:RpfqEl8B+dEbd/DnUogsXsAhmDukeEC7dfjf9UQnjA4lVwyaY55PTn7f5jccmxs=,iv:S/g5/DmR4v01dEq7cPMLEIcbbX2SDk5+VvGxEQHRtDM=,tag:JdX63W3SVSi7BwWepovoZQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:/Ty/AtkX91sgcCFB7FnC4byigEybMm4UTQ==,iv:07Y5WeKZWpRNhaUgDCS5xXzbFmDIZJDFOhmjeYUdECU=,tag:dgSaeiRDt78y0Dp/fv8FYw==,type:str]
    #ENC[AES256_GCM,data:kSrhKFTbPaUimwq3mLgMZBoo662nfmO3v2lhA4FCuS02jTqjGfrrdze2EBzEkbf5z5JlsKyjzpdDz21m5WvyZmyNPlzb2o+B760BfuunKzI=,iv:zuIV9s9dJAcwPFCP2mFw7Hg4TPiQv/GBrZAYJYvnx94=,tag:Ftnh2xyxStAJ5NjysXeQMg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:+NwAAVlfiRKZ+scT,iv:YPG9ecUIHTekbnpkYt7QIXfhwGV6s4mAt/X8hU8PtAc=,tag:x4wy90l66mszOHB/j2BC4Q==,type:str]
    #ENC[AES256_GCM,data:pbDdjRrqS3AP0ToFjIKbo6zm67028ksVyW3x/X1+V0CnqPXli2hGEdISFCycTRZB29t+lm6nxCc=,iv:wmjtAfuxiuqU7mtRq9xgtARMK04PTZJrJe4GOOdMBpw=,tag:MWvNuWlZ+oDPO9fKximzxQ==,type:comment]
    #ENC[AES256_GCM,data:wosLBXv+j9feeMGlGXWQ41vim3WdiBsmeA==,iv:TqM5+Ypm3M7ODyUuuCMdv0e4eU4PDQmFCFlj+IUQa1I=,tag:VATIyTF1bMr2jzcUECJzxw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:rNjWMRPoxQpjoJVktpSqEFetmmOb1APmX7oGnFH8i+CUTWgx8H7DTDBP0g==,iv:k18uc2gQHHAuNwWkYe3umMi9jhlGvJDseCQdsBe7sv4=,tag:GnySZHHA9jW2/k0oGMZFoQ==,type:str]
    #ENC[AES256_GCM,data:7FeD548Fp6Cgq5m/3Q==,iv:FclKZtVRWJ62xbK5S9P0UaMJHqVTL8a1Cls3lscTQkI=,tag:Hennx1nNlHHPHSwp1nf6QA==,type:comment]
    PODNET: ENC[AES256_GCM,data:EvE0OnNa4qMrutUfew==,iv:smTPImEKEc9H3FuiyNDapRv8jSYZBolP4nAskOJqoX4=,tag:VyP1FBD8EHYkCs0ENISrQQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:6Y+lQD8KK38WzCi7TQ==,iv:IBG6/dv/QGo1p3lzsObpeb/mykoSVCJWL5W0/Gl4H9g=,tag:HqtlaAotRvoB9DKxtA69OQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:UNdgB//W3eucG5hvA6Q=,iv:wjYUDWdIvxFbGkt7wGhsXB75jy6LG4k9HiIxagWJpeo=,tag:AiAzsgmia3mhtN7nCuOYhQ==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:M91W4WH/aOWEz6cR,iv:bwcF0Aqy+Mz/PWMNonxHfWKuGquIwgctW5wxbS+nKrA=,tag:w1pQ5F5YKUmoJ5WV5B/qlw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:g3Bfqt7HrEJB5w5b,iv:MD30Ii/tDO+0ddobQll3gXW2olye5glcwtKIQmqmV8g=,tag:zBVJp+QiFUvWSvl9BcKxaQ==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:bBxjN76f7JSjd0y7,iv:RfIt3rghKSN6PWqZNcUX38+XdAYUXjZYLS/1Nx705/U=,tag:JQ+CrcutnRGolnDAEtWLXw==,type:str]
    EMAIL: ENC[AES256_GCM,data:dCprT4hQ8d0kOj/R1CpOL9rgCik=,iv:syi8RvYSfAvut+PEkHdzYGcwXvo1IILUcm2Xc0HQyIc=,tag:+a9clCHtP0Tc3LS63+SxEw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:WqwCQGVXczuNt5F5ULhXwNJ4d2mpw9P2HQfBvARWnEx4v0e9G8XWqw==,iv:Xb7INeQzkTUXOJsV5kvtQZTGxVGdJeEN8rp+LvDJFZQ=,tag:VZjOBng1TQyT8ZMrOGMQ4Q==,type:str]
    ADMIN: ENC[AES256_GCM,data:wrfg4Tc=,iv:JhXLx8+YgNYIuRGOShTsbEmfwYy+8JOUjP1hazb1ZeY=,tag:+eFSrrQdT4Ng6M/PEE/znA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:whgh4qAiAjo=,iv:p9JBTTElxoaglMaJaC3OFON0/EfZkW+I0tv/kCpuF48=,tag:9XHnvY6ciaLouvhPnc5FAQ==,type:str]
    VPN_USER: ENC[AES256_GCM,data:KJFClmbsq5E=,iv:FZ9wcBEoLZ55FJeAfbzzLk/FcVTxTC+qM9Ehz/jB1g0=,tag:kLFAWHcVTelXsJopsVqCcw==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:OmAZwXBpFfqJ3w==,iv:cU/oy6WeRocHY0EIDme/QuAnDA9SdYjg+QLz/OJzk/c=,tag:K8ebvdP6/D2EhMfcEzeJsQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:mjZ+qg==,iv:pz3QFbd/2gXERhd468wqaBffOPZuJxZVCcagOymOnMM=,tag:Iji+v4bpEJ+z7M9GNTrRJA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNmhuYUlYaGg2dERZS0Yw
            eHJFbnQwNS9EbFdNa1dwVmtzTmJqbEsyR2tvCjcvbHpGUGdZRmlZbzZjMEVkYnp4
            TnlaU2E2Q0ltcU16ZGt5ZysyVTJRQWMKLS0tIGF3YnpxOTRseFNEL0hhUldFa2c1
            YjRwQ1B4WlU4dGhPN2JPMms1VTFTTFEKM1LciMziOQfrPZCpVeaLKCOnQkIls4DG
            8JNPwFn9nAGDhc9aSHUwXB3GzwBdsYvUOT0WJMqbdUHk8WEtil8Gnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T20:32:40Z"
    mac: ENC[AES256_GCM,data:xi+sHFiJXEyRg3XDH7z977xTRoUllsukbTidGdVtQr+M0qJkxTW/29w0OZJW+inx4OYSzuslZby2cMSolIeK2Jbo8i2xkZDVydRjhQHREwtepXqvErO/Eqg4ASrjs1mzXJmg0mpztnbwYsfViYo5girZpZmwHHI1E61K7PnJ6WU=,iv:YPS5vLK9VMZctRuYucXkeUluItfk7hFbwdjkdsoaWco=,tag:znNrcNAbDgo+O4q3drZzRA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
