apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:S28aMCXTA7IeeLEyHpKZODY7e9Rar6Nx1k7QNjc+fjQf9xf4s/WOrUpRbJD81cCeKxFE00SthA8yzWft7VdJY0Q=,iv:rJrGg9fzOPrOyT7yz3T8nWqBUw3zN1tIW+HTF9/bxo8=,tag:iAzJl71mCf8IBi1uchFyvg==,type:comment]
    #ENC[AES256_GCM,data:9a17LYVGW+Cst0VtFsA4xP9I8zcrS9rTcYphVwErgSINDN+bFDaTwdybT5U=,iv:mVfOmMQfiZEFrdv6l/hrGdHK9T9FtXhY4jfBZVuEQ3A=,tag:NxUTfQE9UUFCQPCDEMutdQ==,type:comment]
    VIP: ENC[AES256_GCM,data:OxYkMtDoIQWq550=,iv:OGUs8EDNMQNKH65FS7txKVgVa3aF6lLNvia6ZK37VxQ=,tag:g+HMWFZLOOKyg2L2JAuFlg==,type:str]
    #ENC[AES256_GCM,data:pJQXkWfmuHeoFyUpdGzNObZg19sqF7o3LVI=,iv:dn+dtxLWUmMajj7JiPiEDPjiwzBmoBS45uG7AOmVEns=,tag:eY0ddejFbQPgE4Y9rIkKAg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:5tZZeffmIpK7Tz0=,iv:uo7Oc9k4YfFqrIwxYUlwRc0A/tu/28SWVPwTYytlJAY=,tag:xiVo4Bugad/f/0bGf/M8+g==,type:str]
    #ENC[AES256_GCM,data:2ojUkDRfbexfMRAjnjOtho2aKJs0z303tqn2VoJBf7sJ5A==,iv:09EUnYWdwq01Gnh/M8EpXuYedVD+4innDgkALXsBvSU=,tag:BL4dfmN13HwYkZINhnuw1A==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:IF8eSrm+58VrE2g=,iv:MsXSI8Kr8+hTobKJlhUFRFTSQVyvYVgdsQ+1XyXAcqY=,tag:kUnSrJyR8TzHql0qtg0gtA==,type:str]
    #ENC[AES256_GCM,data:ljAEAtQGY+ZpO3h6uJ15g/Vej7qB+vkeF79xVbIIyjcMGxe5dM5kkQljBi7Gw6Y=,iv:ZQpcep+2HAU0rCs805+5H8jG7aap9NW5euraELlqi1M=,tag:9AdNx+Xn5lT5IJLIhSSS6Q==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:KK52Qx0+kAacte4ZrtFF5QF3Zdr8DFaaDA==,iv:LK3BaUfQSrrkL6y97krvSZk23bBiVrPNhrkMSD8WiqQ=,tag:+XVGB3nBF6izAcR4DFFlPA==,type:str]
    #ENC[AES256_GCM,data:UHxOS3NMMUkltYnHIweKyDupt6LmyFa//PhgV1aI+/Vhb5hpW+LRh4cP6AxdXw2MTiUUrw0+MJFo9t9YhsaGeV36hZjXmDxmzUUZsQogzOI=,iv:wYfE4jiOw7Qmw7F68P+4Q/xRVcPOM8XcFSKm2Jo7HW8=,tag:WxU3uYywHuaLWhcDqSO3HQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:6FABSEMbvV97W3RI,iv:61LGw4XwKqsa78O8Ydmj2d9AXM7vs92KUzahsG6S2uI=,tag:CyRNMb3eGlYeC7jEcZ6ioQ==,type:str]
    #ENC[AES256_GCM,data:vzXlj6jvzbvkC6tfW7jdGdzH//6mPno3WqlRX9zodNbdHbug4QTz50iQXq/dh/R9rGuDTh17CmA=,iv:7Cs7+S9mmrPFS3RKm54NHiUHj+KCar6O+bwXQ93g+Sg=,tag:9DG3P1OTOrMgrp7XlFWsGQ==,type:comment]
    #ENC[AES256_GCM,data:K/aCzTkLena5GXvocq5luSDuPNlmD9IY2A==,iv:VcLfvFP/Xes1s8FtUKnKynuEHaKIVlyMOFhpNYCEySY=,tag:prEsGl9KjRpnCCn6/H/+PA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:ddKEqMzO10kdwqu0cLLoKZEGnVX8KvJaWMwDYokC5RP+W8j60kU3bsf4qQ==,iv:p0sZflVaJuTnVOl4TDbwSksape+K2OsOezOAQzw8upk=,tag:cqjzwcfDp1ttf5ABbNefAA==,type:str]
    #ENC[AES256_GCM,data:CkJtOtP8lUu+BiZZ9pSZj1Dmt7hloXbdGSLHrkuyOzHnBNKSqEVeKdn4aoKDOxYLebSQqDwHc/67qXxcGk36tOkdWyhYFU0=,iv:ADPvsdAYj9Sl9Wkd8hlZp3p+5nPsP/kPrM5Jgv50HQU=,tag:k4RFS7+7gtbzCWRmfu2tOA==,type:comment]
    #ENC[AES256_GCM,data:dUiTFmIjPuWvvkUtaEzkLvAYDsrW4w4GT/b8/vBIpaCVMfQ6qb+CshnpvZdSD/L16UFiTgUw,iv:Tf3okuPMtHp2SLHR5A59SNb2bv3G/qWPSlHsZJI+yFI=,tag:+bVZyS9NBuimK+avWjQmDg==,type:comment]
    #ENC[AES256_GCM,data:WJqUj6zh7C5yDN5A8WrwTrSqB/AOINvPElcP5FOMm579RBg=,iv:eV/caQB/X3ZN8xLQQUnx7ZUKOXE+lNENGYDGGnkcj5U=,tag:KrA6RPs2lkhny7xyKJJjKg==,type:comment]
    #ENC[AES256_GCM,data:sNG1MdTGXvkTRZxlLZyLe82izzQILDswix0vV1S6cShoMQNkfunk,iv:iCSrK9i7KnYfDGDuJd0Eod3Y7wzCdfx5hnjsW0aeX/s=,tag:I4nkg1WveEG/KZfCwho6Dw==,type:comment]
    #ENC[AES256_GCM,data:i7VTrPUQylZN+bV9QvQ=,iv:6Z/U92rkcV2v47eefop+5If9Xbb4pzAwBDyIvZojRAA=,tag:3/woylvs63J4FO6rPp8I4g==,type:comment]
    PODNET: ENC[AES256_GCM,data:HU9VpZ90/ZGkuoBhUQ==,iv:8Scf9PduzvW30xsYSzt7/3n3PhtsyFPHTNcHDj6hQmg=,tag:JMs7KxacF6j28lywqP352A==,type:str]
    SVCNET: ENC[AES256_GCM,data:3n8Z+7hrEkk81To5yA==,iv:L1txM2dTh5RNAPZdy2DEHAa5v86noeK67E/q6QtgLrE=,tag:jHQ7dqR8ZsAeEOvtju3NHg==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:mLZVRtfaM4sorOLA,iv:fhBD/9gG7jvxzETGfYedayqQbOEPBQsL9d/p7gOiVso=,tag:A4jGtpCqYzxB2ri+rDpk7Q==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:mj8xfP2vpC0E+src,iv:sLFt3esdz4UZFRTIUHc7mxu3s5e8Z2ZjtotyHDOoAB0=,tag:D/i59dzroSCvpXYft+ouUg==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:yuto5EOfxNjAoW5q7Pw=,iv:FEff/QMKzoZV9C116GObqyh0I/UyNdStFVuNcbpzhwA=,tag:WxtZ/P9fLRHEaf0TPBH0mQ==,type:str]
    ADMIN: ENC[AES256_GCM,data:ZJE8ByA=,iv:i+pcFYgy1Vd8G8Ia6Fsc6xFrcNkAlqcHzetmGPQc4Js=,tag:26M0RCzPfrdGlLFAdY2mNw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:k0C/5tVGwLg=,iv:m7drlRDN+0SEgcH1FdUoVb/tCwW/dU3FoFu+vk1pCiI=,tag:nFQhWiZIpc9uRGiysWVmcA==,type:str]
    EMAIL: ENC[AES256_GCM,data:Jc3BEGcsw1XLmf3/XZIo/onGhTk=,iv:M5uuJW5LKuyw0EMxcKaIl6yxbRImJygbzukINpu5ZJY=,tag:nbeTQP8wiXQCAR7J9ERJtg==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:sK+N6Lys/C5Jmhpf5s5xnENhqftEouWj6kNDOhcjAKNX+wGB4i3nQA==,iv:7ec2Ytixsc0szsgZJQu7pFttqkPWxzzw7zeeW8fCuTI=,tag:8C3lUguIO2zTsoL4KQK+fg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:kg0WJw==,iv:X3AXLwq6f0e/MxzpzCIwkkix9Vyx/MsnSnOZ1uyYXno=,tag:dFspvKjTLuhIbPfcV7IYsA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kdcc7wffaputy8qnagsrcwhlr4304qkunzgh39qw7jp9urdjr3sswwg85d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUnNGdTJSTmRkY2RmQjY1
            NFBaekNvRkNrYUZxaURoUCtnaHAxMVV5aEEwClBpMzhDd3J0dGU2c3crRlhnVEo2
            Yk91WWdjOEtpS1RNSWYvL2pYYjcydk0KLS0tIGg1M2ZaRmxZaklGSnpPb3JKNjY0
            WkUzdFJkU0RmQ281V0dlblU3THJKcUUKR+QhSwyc5WYA/Vnrz4CQTGg0fio8zsEA
            uPsIl9pfmNMMcIE+FfOnIpjCCrz+Vzka1rj5m2gbgTSu2VuGwRyqXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T18:56:37Z"
    mac: ENC[AES256_GCM,data:3cOyzGutvv7FpKo/N/GsSgp1b+ve0mBY0x9q1lLnKCBJYnKaBm6HwieC9RC/b2Cr3JvWr8H9bDF92cNrUp1PvYoFSU8Z6PTWcb8a3zJT53+8M3RlftIA3t3+CJN2FOybh2mvW/Aw/Ot0Iw3fbo5g/bNCd5HN4DRx73JZlrDujS0=,iv:ANT6K7u8uSPjjL/9uw5NwtCRSj0wIciNJzzI7TqMUHw=,tag:n+Q5QTBNA2aSxcXC7Q1Udw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
