apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:9Ww7/rSeJLh0v3AvTphvj70lC3FaFWaaClAfAzLW0rh1g8o4s7YpgImhL5rom0ppi3BSlgh2zki1zG5Y+gkXImo=,iv:5y6PcD0Jc4OogVjSoiOxJMKBGiFdhSEyk+PjhOsRMeM=,tag:R1nSn62NGS50wlRD+YQpSQ==,type:comment]
    #ENC[AES256_GCM,data:rWpDbRVplLgjgqA/hoyrAEHfO/uFeF1Rwar4FDAviMbpACs760LaX0tAsfg=,iv:My4VDNqzMKSYpsEeK3PPv+90fVeAwn5jEIs8GcYn+uM=,tag:CkHj+6QrdQwQCBwtam5h3Q==,type:comment]
    VIP: ENC[AES256_GCM,data:1OcK6vKV+b1VMvQ=,iv:YvZT/ccR/rsQ+odhEX87SfYnMZIahmzidgusSUdV7mM=,tag:KZE1RIJMcyNvfJZrxfal/A==,type:str]
    #ENC[AES256_GCM,data:x75gZxXrVmfuCvPNeGvAKhHjenemsOU3Jbw=,iv:13QXaHEPHcr70BMG9GQwm0L0VkwE0k3WK4PXfAXlYwQ=,tag:WG5T8JRjvAYY/GNDdNnE1Q==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:P++pxZjdfneZt+k=,iv:3kNjFDD3cqEZM/SgCnO0clsLSNQLGu3UL57DOYMq1iU=,tag:BPQ5RFO7YDQVut9H9orFvg==,type:str]
    #ENC[AES256_GCM,data:n0y4MZBxny17QxSp/sjZsW8uVcItjhCNvptY+FGNDkK0hw==,iv:H7GXdOYc/EwTDMwlAx79yrH2ZZFfM4QoQQlizrPmHkY=,tag:l1FplUsDPJnbCoOfw2Ujbw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:JKTKEE6ouvwInHw=,iv:Qs8pN+MAlHqftcw0iwurCyaSI98f+Q48TvdPZP3co0M=,tag:LYH3PpuhrgpEpI9owMe4Jg==,type:str]
    #ENC[AES256_GCM,data:JvIzzAVNNTiEsvwl5nUBy+adXeG6QuDxwsC1BUwv5VQ4Gba8zIEnRNCdtWuqG5Y=,iv:q/rACtFxQPHPOn09NWf16F4Fy3K5zvDREhG/VKjnUXY=,tag:dY+JMrEmCe1VHBnz059Fyw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:G30pO7YPgzgEpqGlAUVjOUtbUBcGiiMQ4w==,iv:slk7YWZxCDY7QI8qQNmiRTKFlikSJozwOaB6VPY2EnA=,tag:OM2zOjYHT3HHsKuz0ZJaOQ==,type:str]
    #ENC[AES256_GCM,data:SQuZoHD5ESNmn2Obvi/Ijr51OEJIcrxEyFEli+naAkPymRRlFUKiZBO3OwZRa8/ZeRXI7FdM71Z6uQkJ13xngQaRs2glafejPbbTa4LsG+g=,iv:FWDo/0kNYF/3Xx1onNvvgcU4/gsWP1WPN3ORd7cuugU=,tag:Y+y06DYmZkqPlcrvU1ygZQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:hJOx9fYf5B6CsgMZ,iv:Zq6LjHjVKepVBpIUoEC9uXGhtrIpja1nCLwdZFREid0=,tag:JaEV/JGeHdzOZgikiJgw6Q==,type:str]
    #ENC[AES256_GCM,data:aM5JTsB9tdvOmephhKFsU7pSMViCbyZK9TenbG3GyTqeh2aOUIA/Bui0W915bI3LC+ZOs5yL9w4=,iv:BQ1TLbAf4Y2WTflm7zBtVEbA/dXGkWYg/AlnnqhMBvE=,tag:72nBO91U5Ta/kptSuQZ1wA==,type:comment]
    #ENC[AES256_GCM,data:h/N/FIvgR5ztNv6KlaW4OfLft3Dkzqd5hw==,iv:tIJrp1ta1sxtFNYBsWHJaZ9cI+4s/maSaD+NEzH/4ic=,tag:9GM5bcUiL16huy4DzRHrMw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:lfCXMXH45NZV13zy7nMq1dUIzyk+b6H4FnaJNAYFvhzr+rPRuJd3/OyOTA==,iv:wwEvnBAhT0PE9EE8zMrh5awBKDA0w6Q5gfnvASjF2ho=,tag:/yjE0JK0iQXL4yZCKcWTQg==,type:str]
    #ENC[AES256_GCM,data:vrakWFcuafa1CqyMqj4RSw2/eyubxMYxCqtjDXmkUkKUnX24bwOW3GbG4cHg2XSdsW3Rtif3+RsAt7+HUq2p93hdgPsMKMc=,iv:RiDgSny25+FwC5pTCtBJvTaeicmh/1KJtDqCGVK6hQY=,tag:nD2hIV08GUo4a11NV+QNBg==,type:comment]
    #ENC[AES256_GCM,data:gM+Fp5LaGHnvRk3Go9619yJIOvnzjyWXVMJ9huI558pfJxc1bT0oCB08D6X2O3NgEwp1U7v/,iv:XDr8r8ywL+4WvRG3d2NWZzKkHlathByefBmCGrHVgC4=,tag:fMPVML1r07T+wIdlsMoF0Q==,type:comment]
    #ENC[AES256_GCM,data:4XtIVvF6Z5sjP6rRFwKBUMfio0MV24TRUUB9f1l9RoPFKMw=,iv:2CZE+Hu/RZC0ACVo9sgcJxsl9aDkW0eZDeUiEKouv6k=,tag:9McsIx0M5yN7Do3waS1Oew==,type:comment]
    #ENC[AES256_GCM,data:MMqB3hdz8tWSPXEgx96Fwk+CURNP2howQkNsMzMsX3UuIg/xUTE2,iv:06mxfDc9LOH2sc2MeUsEFirTEHXmn2V4nOqHfgtFhYY=,tag:tvB8ZIuERUzbT7GmktpY1A==,type:comment]
    #ENC[AES256_GCM,data:D2Yom2Uy2XEmrBqXw30=,iv:M5NdOaw+wblnkWjUCQtWAca3+1Zd7uq96ksVAFg0yK8=,tag:xFvNNATV0FUd3FleSOtmeg==,type:comment]
    PODNET: ENC[AES256_GCM,data:W5ehOtEGXArjJ+OfMg==,iv:JSZvM9qpliJ4fo7OrUu6eW7Ss8Xy3Um9JRK1w4fKzLc=,tag:ecdwkniVb+Kne8YZVsOwZQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:k2+XGEfWaAqTUz/oig==,iv:CKmyqLNVPbXGg2gCuQ2D9KpNSTa07QsG2SQB8vr7x/E=,tag:B36sGg1QSHzJNMnJ81nYNA==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:5gPv1aVNUfNbTmY6,iv:bsDp12VGpY930C9wOfX2EX7uj6gy/1eXUcITGDfcbJg=,tag:6XTnAzCbYqgJouy71GYevw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:EzqKu4y9fWAUYQYk,iv:vec78d7OJLokT3d00j2BSWSccwVPGdvsDVyqOndWS7c=,tag:zjOtEvVdQMdbeS7byWj1IA==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:WBFhVdPAgBSYI3lr8Mg=,iv:5KJhbfhqErcZyJGIRW5EWNsNv6XO4J7xdn+sbjSZEOI=,tag:PuWzUWS6Qf7wXyxThwBW0Q==,type:str]
    ADMIN: ENC[AES256_GCM,data:/DQUgj0=,iv:yn+IJSnwx8XBWakjYzqB1Jw9iv7Ne+dPUJ+MBlZ45Gk=,tag:WaK501UazDRZHTyfrK1+BQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:/JDgumhdX0w=,iv:cqF+owhZHZifKDOpuo8RQM6kw3AjGm+RPA3ccn9VqLA=,tag:2UzN33PBG+U5rD/wtOy5uQ==,type:str]
    EMAIL: ENC[AES256_GCM,data:NhP6aelPqjv7eIx1mwAacjXSVLg=,iv:yx620uV+saYE0nsaz1Uq8OvOi9JwyhkAjaSfLNbNWwA=,tag:DxD1LtFAhneh5AVHD4wylw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:roc608gOwDFpMA1XzaffXlVLUMk6dsB7bN7Dxo1BfeeOweTns+FQyA==,iv:9rqaoamb/HYNq0h2xNdhdOjg/u08Ob97LoIH0Seaxfo=,tag:d/tDFYNdAUXmFRljGYfj+Q==,type:str]
    VPN_USER: ENC[AES256_GCM,data:2/HRMjf0wLs=,iv:B1cesPPY1chSFSH7Vx9LG1pfCbtXVrkUhtdK6/ghhz4=,tag:bWgZRiXoyyXbaFRAJRhHIw==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:GYGN7djz0xRaQQ==,iv:y9qlvndpDWsTNFd5NsMHDT7d3oEZ3Yq90ZhpdyYVev4=,tag:DhXy8PrcPXAgS6TmEmdh3A==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:7T9dVg==,iv:JmrPSNs+6mAOjj6u4IrL24xnvY4e1MC3cP3eD4l+k9U=,tag:z7iisaTgqP7nXgb1RuwgAg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caandqrgue5nl44eylp4nvake7znrvxretz3uy3r0ccfa2av4aysejcgfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSmo1Rmk5dko0dVV1NlZl
            MjlPcFZWRTh5aEdkejlvSzNUQVYybEUxVzJFClZ4WWl4L0dTcUZiT2REcGYraTEr
            NHdTTGJ0YmNrL2k1dlZteWRvZ20xN0kKLS0tIFNLWFBYMUNVdFh1WEhvTzVsTWpw
            U25sa01kNEdtN2VxcnhhVVRkbUYxYlUK41Dpp4k/kUtB5r/Z9+1q+PwMU7m6ChMm
            OO8sfJkKZ3Z7eeryhY4+0pSkp8mOHVA2/zqFhKprzhdAql7C58idlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T16:19:46Z"
    mac: ENC[AES256_GCM,data:CYVV27mQJnaLjeOOiwnGsSOLlld4wRangCzByboQ78heBv+R4Be79BOGxV86gywBZ0m+02HGr72MbCkOSS9G/3lhMqmKbLC3WNnSh60n2atYaTupZejp9GgH/TYK91nM+BzgVbAV230kGtOdNoR3WQw9fn1Pbiy2fsB71XYIorM=,iv:0XnmD8jLGDSDEAoHq71+L2soMMbNRp5+hyvu57l33ZQ=,tag:7XJu1M2iA1rzDImhOX8ofQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
