apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:8swJpRvroyTKa8ICK3cixnYd2fg6n7FJEmA7J4tlnoeFOsVPlb8Ea9IKNskeoCUrmwLiDhe8EDJKPb9c8Y+Xv+M=,iv:tDFDR2RVfoKtF7sCA7Y9lVGZ2WHDyJHS8hcuvOLpP1A=,tag:xNw4MY2f40s6LjejRHefcw==,type:comment]
    #ENC[AES256_GCM,data:jaCEPmB0GSpG1yYWPa/zH/LLh1qS8bUXsqLrLZQRimWDro5qttJ1EV/eCHM=,iv:EXFmh6I/n4NDzBHVopPxbJmQMopUAEnkGqjUbIyV7nw=,tag:gqslCq4q+/9bIH6eGmyk8A==,type:comment]
    VIP: ENC[AES256_GCM,data:Eik0LE4WwJXsRsQ=,iv:sRwimrqruLKFOhju84bxmtq1uZKcac6owsWL8KIFmEc=,tag:PgBpwSzEPOsgxk3KHaUxYQ==,type:str]
    #ENC[AES256_GCM,data:kgxlLhxXMSNwY2n71xlXwvK5jlvjxX51QBg=,iv:R6xpkZRQCWQQUUJXzPnR1D2DLNifnXr0YPkmd3xFA5I=,tag:O2NbSIaoQD4J8RIq4aHXSw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:dGxC1liAzD2uK3Q=,iv:V9N+5kKtmH0NSGE3HzQCBRHZSs1pBww16SyFFVuOAFw=,tag:Lh9b4XVyQsdt2qk6qOZ6aA==,type:str]
    #ENC[AES256_GCM,data:dkAUqi9a2e60ezqchwSW30NFBUmxc2jJt1zfVfhZs7li/g==,iv:xNWP8a6KweIBPtm6Kecy8gDzzLWh0BDZLuvuE8rNcjw=,tag:DHhgwJLCEE2yrqHUnwLecw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:5GvHlSCvwV2TyiY=,iv:GCErG2+fZg6yeMIxg3pvd+fS4KloC0UO+8Fov90qqYY=,tag:7f3ZT6898goAKWQwqe71BQ==,type:str]
    #ENC[AES256_GCM,data:DdwSLmW98xGF31ns5kABnR26R2c7xB4GwamiJE6QNLyJsABMHH+lXr809QxDGt8=,iv:6y2o8ZrwpqAeQ5Bw/iE3cTrQJAD4kxcDHNjDo+ymTok=,tag:kSccytEwAQYtRHsemp295g==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:Gu9twuU+1y2/E61Ly5q2Jc5jmI872p4Hsw==,iv:cdKFCxnnj6XXrVM2oohw0H07cogPYoOvAbWw5vrcejM=,tag:kyqB50BJ0al0DCZHzGkIUA==,type:str]
    #ENC[AES256_GCM,data:wh64yO9L/i6KNlogtgo1xCbvqlAZjYGS327KTNzRTH97lCqveM4R1ZKiDMX3HIDWpuyWOKA/xSUabSrEal8/+B6W1A2lTlYSHX972lPO1QM=,iv:1Gum4PIb2x/a+KYCwaCyfCl7/lw9J1LtHl0xF5xMDwM=,tag:7e7l7BUF40aPiwCckKfbng==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:gcRhFe4ZyI0OY/+S,iv:JuFQ4WVbQI5fUI3CvTxGH40BBXseP6j+3nkw4BMl7pE=,tag:Mil/SFbWWnyKUX8vbDwCew==,type:str]
    #ENC[AES256_GCM,data:ERY7vT/hhNcUnCHEU4RL0lRa7Pf7Mf5Ys44moiyrhuCTKC/LuRgSJ7HpUKfabR13SQVpK/ClQcg=,iv:0xM49SWqxhG/cI1N/9ETd9+SJ/qcVLeeR0uuvllxi/c=,tag:y+LcKqI3g63DCK12coV2rw==,type:comment]
    #ENC[AES256_GCM,data:lJYKNovFlb0k3PSLNhHdy7uxCmtLl5+j9A==,iv:8C8CC2ok+eWm+eXGRC1/kawQT3wQ1/UlpFRO3cMX/8E=,tag:ecumpkCVishkfbIGHDHi2g==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:5t4sSEeB7IR7DLEpVZc3YOVTokAcJPNbtC/L7T8GV9h+9mMw7hGAxivkrw==,iv:LdtuS+n6+toe7lNV4+HYTsYbYyDZfiSB3K6iirgwORU=,tag:D5Vq4AxTnQgF199ahp7irg==,type:str]
    #ENC[AES256_GCM,data:OkZU7Flx+yRJ6ae7RA==,iv:satT/yceZsI4yT7Flijvnn9vW98sU1V2JH4PbugnDak=,tag:litMChoNDDGqNXjAuDschg==,type:comment]
    PODNET: ENC[AES256_GCM,data:Hs4r606xwsxZ4OWLIw==,iv:w3Pw5R/9w7mcrx7nsckfktrOclayMt2fuVKGlL1irLw=,tag:y8JSsGQE0ay3CoAtYxZmRA==,type:str]
    SVCNET: ENC[AES256_GCM,data:rqXbQ6Y4EctFWVT7cQ==,iv:crmxhPxlZzUjte9r8tWMug++hWJCbWqjV5JRasRl0Mg=,tag:51tF69p5YkKHUM54DvIj0A==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:sjTWAAkvd7fPYkDkIpw=,iv:b7dHVvNZwbQXYfhHgRrD5pJoXkINfBaKVi31a7FcYsw=,tag:H297rYTl5YPwr2oUxF/cRg==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:yaBBIGRxeKEvqoe6,iv:GaotSpPiABsRsOFlFoAJvFfKoD9j/78nsy6S/dCcc1o=,tag:bWSuau8S1PMac4tXIkNJdw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:drT/epSJk4IATNVW,iv:uEUi+aUeBOwOfYNV6KBFa4EfufapbsGkDcEbg8BWCrg=,tag:+oZP0w/+2MvgM4zFci2TaQ==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:EiHFGlLJKNCijYkZ,iv:fla8hJV83IK0DHx+okf4kNTYYdE390f/9h14DP8RcZ0=,tag:s53kfLwjeEmmmeNNpb9oUw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:JlQT0A==,iv:hKTIaB4SVc8lT3tV7M+XHH2Lj+4xoy4UhAxOY4ShqY0=,tag:BdsA/QkEfQepHkUYPbns6w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e6uh7dyyv52fhht5teyq333fslyxxm7ywzlmq362lvvr6h4yrv3qvq9n3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeWFDUjZnbS9LYlRkMzlx
            bDE1citjNW5lcTJqb3o0cE9OQk9Ya3d6NDFFCkY3UC9Fb2VqSFFzcmdyNlBKaktW
            emVYY00zellnbVpPeExzemNRalJ6OUEKLS0tIEFUTVBxWCthY1QwaTBGR2NIc1lj
            M1FDWkxFK3BaclFHK3lZbW1XUmxSQ3MKH26toizZ0Ad7VJ69nZs2jh+5prnZVd9r
            zqAU4zP653s/YvY7mca2fhwld1/31BDqzH68elN0pDqGIoMco7IrqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T20:53:35Z"
    mac: ENC[AES256_GCM,data:TNnH9c5X1rJjv51goS9L28GBxCiE5qg0oOFEW2lm/y6sg/QpcrvTMTZNB0W6rmxtEJN0YNjlXBBlobxXqId+8igu2fTcytmJy+IbbXKdAwuJFxRJopLo1SdO60yd6LWmlFrOY5eINhs1agDerk6cEt0hIbhcpm0EayejdubDxf0=,iv:yoSNipXWDP2qZ6wtVUJt1E4b1xXK8ua8EwcGlXNKg+4=,tag:vIFrABaQh4op8zsvpCq2Rg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
