apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:hdXQ5TD4iAIfcplYu+x0b/CA1ygVA+Xfg05JzF60RRE0GvA9zI7HhaD1f6Silu47p5dFO2XjU1NlvxuxEbNfeq4=,iv:hx/X/OKRKn9+60pOkLxk84kMbb30mnq7EUDaFifs4jY=,tag:RGIzb+QQDfA86Vg4Mox+Zw==,type:comment]
    #ENC[AES256_GCM,data:yWmeKZvHgBzuxPUeeAN40BWpGm1SdKJ+fLJz99FThITmMJnL782zeLfsutY=,iv:eGcbR3pZYhQIXRZMXwqCISd/VVD4Beo1zaatTlWej9s=,tag:db3ml2VW5YFDOjvWsWwgtg==,type:comment]
    VIP: ENC[AES256_GCM,data:mZ2FnPyvvLGlPPE=,iv:MJTCIr5lUAcFl+Nbg/R2mEsuDoiG1+H3TJEt9WzUds4=,tag:7eMI/YyA7BBbcxk5cc3N/Q==,type:str]
    #ENC[AES256_GCM,data:+bJlKvtdoffYScyI8IfKXryE+kJjvqzDiV0=,iv:IyOrhILE7u0rFV7Qh3RnYTWG2UDtPLrlc5XUMdEEtCI=,tag:Jyv+2wGr/MPqIABAtSGVVw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:dgG3IyIywW0iaO8=,iv:pl15k6HFtItGLlGdTwolYl1w72hlBPVcF6sn8F+EseI=,tag:5GafUQOeNSrGW4dCpnOL0g==,type:str]
    #ENC[AES256_GCM,data:CefSiuhBgW+AwvoGpTJMSdssvqtwypHcIxs4K8wglUyXbQ==,iv:Lx4u6bLjYoPUZBZp7bT6o42IA54NHhO1RJ0xZla1Lzs=,tag:N7aNZ4XbvoRKmUjlOlvoHA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:VWQouPKYCuh0BEw=,iv:gWVY26aVTkX9EUxB52ZneAhbJO+8mrpS1gzoEuA6qT8=,tag:72Kl6CCfe3eCHrcYekQpCg==,type:str]
    #ENC[AES256_GCM,data:EiC/aQwaJ/DJQNyUJhygdmdVj7As2DbhMF8TA1R9uiEWK3rHpvflPnnhhtGrzFw=,iv:+ch0GFYRfFphQXuordMWFZPitruDgcSpbEbWb8v178Q=,tag:v+5c9fZbMAdyzsAr/DRkjw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:YafGTNM2FKuKFdJPLFcdyZieol9PBDTCEA==,iv:rFL2YheAG58Hl5Elm2a6lDPLtZwSE2EiUNTleQSirxI=,tag:aWBRXTY1X9uRDcNRZzgLvA==,type:str]
    #ENC[AES256_GCM,data:Ay3MyH+oEieFb2SVeOMEUnjHphQwLhteQaaD+zPwiVIJak6gjoipXYfY5WdxvFyU46NoPlv2VZKVrloGwn5EMdhhAELs9j+qchwhIAGFDEY=,iv:Aj7CvIL0Wp9AhE0ZyvJ31oSXLkTrCWc8uMCO2fwyS54=,tag:8HisORTrCOFMWfCPVD5Kkw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:dZaStVcF62j34X5W,iv:yzKyNLtZEzQ/Q9R5Yhztz62VR18IFuM/sTc4crFfQQ4=,tag:6rvmB4M+YdP5NJi893SXGw==,type:str]
    #ENC[AES256_GCM,data:yXenyhn+7QidVSmvLJJFWAqhM8GgBdyuUcvCyX6tsuqn+wo6PewW8AfPqXWqzQn83QFk5H313I0=,iv:WJ7+SHGPRTLQ16qV8ATk8S0V8ViGqvktYujQW4q4MNE=,tag:eJ/gBnzJzGtq+tilXCjlfg==,type:comment]
    #ENC[AES256_GCM,data:vawq+GDSmgabQoctHZPWyK+1X8888dfWwQ==,iv:kEm67nGgwylHSZgfJPAZ5j8Ro99OQSO3zkwxmno2bJg=,tag:Q05zcz3883GJyyniFdOHrA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:2RHL2d8lcZzgvKvz3wTsWhWYERDdW9uq3+WAFOAQzYtHNxt5PVdr,iv:lx0hNdYEAS3USr+mdt3ecH3j3tVbJLLJICCDloG6uLQ=,tag:g2Vu+y/XY5PC+EMCUUbjOA==,type:str]
    #ENC[AES256_GCM,data:xRWskTf0dPxak9rD5A==,iv:BlciXSIJ+3oum1AgSrgJq8qQEYOIN2AzFIlxMymwzYc=,tag:sAqusBcz18hgIrB8+xEe8g==,type:comment]
    PODNET: ENC[AES256_GCM,data:LUDhjDadtObyhGlspw==,iv:2yvFYnCyfAVgO6oty3Fs6i8vp2GVl3sBZ37cU/QTe70=,tag:QjDUcnPoerFZzjI/tgmJhQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:eOMyC9zPLxhMNjtMyA==,iv:8oqb4eKXtRzGT60Nl4UrJwaDsXQ1pQjvFj8g6PD9LAw=,tag:Ky+bPRawBF0f++42dxIKeg==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:THm6fleWBmLmoNNW,iv:54QsB6KZtYsosSXyN6B0jHB8pOBdcAxbiI2DXm2C21A=,tag:WNUj9z88SiTNwhYGzuGyoQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:4TgFjGW/IqBGnq2cwv8=,iv:mkSIYtd741n1ymmkGkoM9gmXR2qCA5o+VC0IDJc/yoU=,tag:YTxkIsVAWEhK5Ir82qWDUQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:bOCGcA==,iv:4CphUcAfzRM3nineIXwo2yiwTr4WejXvHAM5Cso4e+Y=,tag:My+Im/pZqUpkxPjC7/wUlg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mckk7dum63y3m9l06dmtf9vzzrseet9fxuketlaln8zm8eatey7sh4kshd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSUtkVHhQc25yVytyaEdN
            bk4vUU40TThGNEJBcUhqWVZzdGkwK3dxejBvCncyMmxLNVkxMGcyeXN5RzlCSnNy
            VzRWU21wNXh6S3c5SnU0UWt1MENtM3MKLS0tIDVUSjFEZnYyRE5UdGxUSHk1OVNy
            QWZydy96WFAxZGp1S3F1UWpJaXc1bjgKUBe5rORGfdtm8C3H66gc080dF1ujFDL8
            vmOS30xoGH0dH0gRCTJ35vxMBDXT4OyZRDlSazXV9Kj0aSbSysloIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T00:35:59Z"
    mac: ENC[AES256_GCM,data:CVdqZDOJ4wzQZHb+FHM8pu8NkdQzNgOhRpINT/9uyQeX2UVKvHYO8TOZQQYzzZ5mevsCnB0loB+BuiSmmTo+EyLoV73BU7Sbp+C4sXapCTuvKh03yAV8YQJSzeSGw3NRqZ0JMvj19mBdpFskmpUrrTPTKARpbWMM+TUNdsnM8qI=,iv:a/HvTRDdXZn9zMzk6lr+AuFkzanIlVCm4l/i2GFJpQ8=,tag:uaMos5NosdcyDrUAJtNpKw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
