apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:YUqB5JkSWvFc22nqF9cGMMH+aKehIlg6XJb75d6dO3gy9F6F3Y/MXyG7DnXUkKXBmmVzDq17qoiuYNOf8+HoTsI=,iv:uAyoWh9MbH+5pd/KTpr4UFVlQVyDQq04QnD2YqHh6wo=,tag:MzYppw2vr6AoGSDPzwzxeQ==,type:comment]
    #ENC[AES256_GCM,data:IzmraNLPmWj/+Vdw3NIsRyxvdeg8Is6qeClOtvfhVLxIcw+Ov1H5UjpjO74=,iv:kan58wB+Ew8fZ6QIn2/loAUT0TxC4yHRY3hCZI752Lk=,tag:T5n8BLpCejsRnFGssBIKdQ==,type:comment]
    VIP: ENC[AES256_GCM,data:GfmEltPYAYwEhIg=,iv:yAJMSry5W63yF7rxs/4FBQHTfMZBIOaFOr5PmiEZE2k=,tag:2ZlzvWOGE+1//nR0YLS1mQ==,type:str]
    #ENC[AES256_GCM,data:nM1wzezBmD8b0yRa5NnMHL/v0H5+lMZhwAM=,iv:joCqqxxucQJdnK8u2vkEfnqN06FqtrNJQPUUZSu3MQk=,tag:VT0fpyrOIqCmdxXc70MviA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:gY9yAovHZYMsO0o=,iv:C/cfuJYSwJLvV/Fll49JpJ4EsIPXOXse64kCO5PsaOM=,tag:0LJqWFgvvl92EgodaMAwhw==,type:str]
    #ENC[AES256_GCM,data:Jz61JHuXOCDHPx+67b8s391pQ8E4KvSYNWr498VvPK8iwA==,iv:nQKOj4gBa19ynjU2XNNhisnYSqrktwO96PxUnj4LZZs=,tag:4w+j1/dsIagrzR0VUC4mTg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:TBmT3s1XvT3cZio=,iv:ZEK82pQlgVbnAKoN6CZodt3gV2AXiA2tYJS87O07fBY=,tag:GYkCpiZ0mRjbQ4PGH42/LQ==,type:str]
    #ENC[AES256_GCM,data:57x269jabhxLbQczrP5l5WfshSeJIHpllkbxFq43GJK9wu+aIPX7VezhWtQqFDk=,iv:FUTPTvKJKGEU9PofngI0jmqZkx/DVK0jWC+F+IvYcUY=,tag:zyqvHzGiJroYPWAawhT1NA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:/Z7JL9rWTPEngLzIv79bKSswdU2Mw0m4BQ==,iv:MRWmrbg4CGpAFhz5c7GaErW8HG72qnTSGC6JXMbluQ0=,tag:1tyOMBEwu0YcA0aaNOx7BA==,type:str]
    #ENC[AES256_GCM,data:klf1qvzM9dqK7aaz6ws22aVNyuGWunlwluejkMXzhnFTOZ1jFzaxs83azUZ6GXJXyMM2n0biFapwN8AJvmZb2tUcbkHZqAhQI2mT99nZm5E=,iv:qyv61GV+8M8wrLyez5w2SCHjoSd7BMjkdAXt+zsrq+M=,tag:fIYx5jOdwXXjBJU4D7azUA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:BRWKki+p7uesVTeO,iv:vuk02hn+naGL6poYTuQZKq7NiaZS9nnYWBfiPRB9sc0=,tag:BGwnV6YMsHd0xweQ/12CAw==,type:str]
    #ENC[AES256_GCM,data:s2rnbqwxcD/O0fLY//IEx+hM2mnopveawyRY0v960rkWuOxvzuJ5ee0xF03EYPLVzfcnb/xB6bI=,iv:2T/pIuLQo8vsCULzQilmx3D2igZXaf3AxmybJyChg2Y=,tag:va/o/vj+MU9HXGAJImaz/w==,type:comment]
    #ENC[AES256_GCM,data:BKjHEvlQb2jStYwnEyGVCHJEn6CSEueJsw==,iv:qdd87LjujiaRV5AO/DXW8ozJUWqtKB5xCoQDq2HAO0o=,tag:AdVCeHBNiPAm7HCfHXnB0A==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:Q4Dh7Gah9Lis4GQwsJLHrbVWCshtZeTI4x8ZI8U/S50BcNXDde+KO+2RWQ==,iv:JVhUPrTEpbOQLwL+jhvE0v7HwZQXdGw0bRaMtfYQbAw=,tag:LVz5CaiXUSGryiuCnkhmiw==,type:str]
    #ENC[AES256_GCM,data:WN4JL/7MmRhFltf6YLvE674CYXLY+Oyr+/jF2aY6qDW7PBpUxjwZ19tt5+ePqO71wEkUgO3/Y+0rcdcmnC3ChoOCqy85QYw=,iv:yGX1DZA3XkCsLYloOyU1koni/57VRmt1YdHp30PMoLo=,tag:Gsyg6FT2jLhD2BywxVFBAA==,type:comment]
    #ENC[AES256_GCM,data:bkTQfISSZdYYf4S7x1AbXLJWcF8asyseGepMFKDwq4jlctLtMdGqf3zKsrUKV9wdRq43YAyX,iv:nv5xLS8KkvFVLW7QuGLq8KuxoCQfvTsVabjdMzw2ibo=,tag:4mkL8AeXGKv7hxzsYl2FMQ==,type:comment]
    #ENC[AES256_GCM,data:3aBSMbfpSgQcB95MS26eSjMzLl/3YD2o4oZydBvC/HFRJhc=,iv:57kPHIdyoTbhlYCxkm2JrlxjzstgUnHQEvBmZbgx/5k=,tag:MTPKI4rLE6rpWU2SMwNxGw==,type:comment]
    #ENC[AES256_GCM,data:fr6201bAGJSWHLIbVR+4Chtr6G1w0j8Iok7PpI2MD79ZOPFMvWw6,iv:UdOK6EjDxsKTGTk6k6mcbVB3hhr2MyDHe3co08QkIl8=,tag:QL2faNoKdVXl3gL9bM5S/A==,type:comment]
    #ENC[AES256_GCM,data:+hXy/yMXwub67ddQQEk=,iv:SL1Fs6Psa+AtVOSa90uft8Xm06pTZQVO1fNphnz6KOM=,tag:fU7PrdMZ6CoZJW/c6UIQfg==,type:comment]
    PODNET: ENC[AES256_GCM,data:4pGsm0qrSEDUYJfxsg==,iv:yHmPXhsvMjlqXo0iYBk/ad6FOoKrqFd2y65oOrHO6Yk=,tag:i/lXc3g3mdioi4z3WDwF4Q==,type:str]
    SVCNET: ENC[AES256_GCM,data:opqwOPRG5fjblkoiXg==,iv:U04F83H4eZttQRZ8PNssV8wytCnlLf6p6c35ZOzSSlg=,tag:kCeKARJmyz27Bs3ihCsP1Q==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:alghieAe3r8NOh+/,iv:yeek211ZK/tMSctik/J06rqRv4sG8fvw15eo1dLbKIY=,tag:zHdU294LdMZylvE8hXi8vA==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:UG4ut1wS6fYo7zmi,iv:AeI5Qi0u3bKcdrVVh55OOSKFHMoHSSym5XjVMUXrfXw=,tag:CSe2IXgIaFhbBPsx/VnGQQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:NOsgcT4qFRhsei6CFnI=,iv:i0DmZZSYYWyvKKkc9qtVPPalmMTfw7TrCGTXRiVl6pE=,tag:HOutVSZ9zHRRLM9tDc9d9g==,type:str]
    ADMIN: ENC[AES256_GCM,data:e6sZG+I=,iv:ZA4NmP8Bm98Oow3BsX02MZ5JRLIHiQeEmJkzj81IatA=,tag:vTv/wPMmckJiHVeDjB8aEg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:MFPHGpOEnmI=,iv:h5sfWCA3U6KMPLZXYRSE5/wEKlmizQ1cR/mC8HKBlUY=,tag:UJgBuTXr63D6FdRDRwKacw==,type:str]
    EMAIL: ENC[AES256_GCM,data:slz6HITbTmHZnM4vZYKfZSZm1u0=,iv:DG9pQKQeLtFvPL3bN4bSllnFwGamJBZ4AMT4PC4RIV0=,tag:i9tla69Yqm8IXz4JyzeT+A==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:CeILXH4I+7Ho52i9t0yvZGghMZ7SzwznYk7KF/WQPxtuRGXAxmfLQw==,iv:J8McVJQNn/5H62FqiV0GB8A+SnEQLfcm4Ked5c44bXU=,tag:/mfweG7StMLe77nCKM+jMA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:A0R3TQ==,iv:XdZalzbtfI061HdrgJS2IVSb4JwH5nPhekX9YeCLGpI=,tag:oh/eKpNlDlfJUbicyusWwQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caandqrgue5nl44eylp4nvake7znrvxretz3uy3r0ccfa2av4aysejcgfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRjArcjlGMXNEdENYQVVX
            RWtwZUhHQjM3TUJIUnYwdUVpK3hCUTk3S0cwClQrdno1bWNRcjFRcVNPN2FJbHY1
            dzlhNlhYcURxUEl3bmdmR2x0OXVsSVEKLS0tIGZsbXViaXZaLy8vTS9JZlRDbUZB
            S3hGeW5yeTNHRGFhSXhtdjhYWDIzSm8KLYswMrAewkAbBFmcUc+dZ1nke6OaRwL3
            4G9d3ULa9D/2fpScH1TuIKScmlonz5/0roW/n7ccMInGswpa0j2F8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-29T13:55:35Z"
    mac: ENC[AES256_GCM,data:GF4PvQ+VHTOk8K1OtfbVQo2n10MTRB+76yTK9ELopaASiznWU6rZ8e6mH7HfvMvay3iMohwDp2OiUdnJ8kLK6j3iSdcgFZfIztveM4wLNc0y9j9j2ZukLBKp/d5RClpqR90gpOfM1No+KaMWKwSZkR+qbe1t0BdEf2Mh+WQlaUM=,iv:anNdL7hWdvrByi2xPDed20Jd80mo5B5X38dMNo7YuXo=,tag:gtvhMooRP63kwY8iXAkGHA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
