apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:7Ij4RQQo/U1/o/iXQuol0qsmDcmDDQixoOiXYpiw4Exd9dimVxkU4ALJX5nRUCbWWczsoIO+CbwoNpCFBh113hE=,iv:qGNxb9XtwT6jeFQLEhNRgg+z6jCz3zH6Ww1rno2jC4w=,tag:OS4221BaBlA8Kdfr7TD2dQ==,type:comment]
    #ENC[AES256_GCM,data:qvB0wFJSllJxDwyywHdD9wNeHp2yTHf9sm/vxTLJycEKifyi0Am69putQC0=,iv:FE2jmdT59jh7Vs1B1BF3vb2+8PkLrrE5+viVuZyrzYk=,tag:7EKCH7jmpcY13Ph3WdGVAA==,type:comment]
    VIP: ENC[AES256_GCM,data:OJ61xu9W5gJsZ/0=,iv:Y+g6xXce23nokWsyMQXA2HlQ8xmU9guK9CL7yKw+jH0=,tag:DF+7doKcwI1+dXwmOC8s7g==,type:str]
    #ENC[AES256_GCM,data:cj1DLq6OwyV/sQUA8d6INPa+JW9ixd0lC4A=,iv:kmEx3g7Yf/oxvPVcocBmpAYaYsH5vp2qWvCYER4Q50c=,tag:172vh9OTU24kTTlpqrFLjA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:mg1/tFBcWMqciDc=,iv:859da6BHpaBfVhhZrwMHuiqjMQk3+KI+YfVXMDMkSt4=,tag:hRY7gYWwwj6XYTnly/8G7A==,type:str]
    #ENC[AES256_GCM,data:aSptI5cdGoa5uqX2pSz27VXkJoPSyH8YSwsSFXBiuR6iVg==,iv:D+8xQ6Y9ojd7vsF51pLRTV6oz0omYCM+0hucGTgJrvk=,tag:aQcifKvNbkM+lnXJkqgp3w==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:/WJsAa8cOHdrtio=,iv:o/nhDyhFH5fr36QNekrDnV1/iHXSlaZBGTmZV1+V3xA=,tag:couD/YA48D75HaOZiHZWGw==,type:str]
    #ENC[AES256_GCM,data:to1TpArU046AyF4mtjsYbQW4Kt42yqsUhqJ8MlNVXCnRf3N740mYueVZ5tHN7aE=,iv:Dnimww1np/S9RbxdWcshJ0EmMpnfIOFRAvDZkCykE/o=,tag:qGRb/Mn6IdsWQO/u7I6lWQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:GYesmjbBbuoQZT35S1f/X7MuHecvp7hgVQ==,iv:y1ivIpjxWFW/F8CvNRdrhTvHD9t9xYQcn4EVdUDuwbE=,tag:clHpIUsQLIGEQW5qVZ9hJw==,type:str]
    #ENC[AES256_GCM,data:epyDyu8Rf2YXwabFSSOIBhU0xpI7+w6XWpL0HArjFm0Tl0drkau1S5dOR2ZZ2flW0M+28Cof2n3qjzrKd41CbEK38PZloiqJ4RhW+59OC68=,iv:scUoTmK3pu5HVncnkfmrtq9Pqq+mNVjTQYQC46TepQk=,tag:h+zQyA6JBKxdgp7Pl77oAg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:0Umjw9OqsNsJr+5X,iv:5WkRlHRMCfd9u3sikQa5fqJ1mNwC+SB8WF4j7soRSM4=,tag:rE8RCLW9oWCxA72RTfsNAw==,type:str]
    #ENC[AES256_GCM,data:GQo6CiOQ/NvCdHWzMOFtEy0Xw6svoDZSfsYvgcjIeOq/G+qHL0HvvsuEdEmaJRPD01pwh0Xnyo4=,iv:fwjhrqp7ljqZe9cUmkLjaDGAIz+Vgw8+NpjpaQd/dBw=,tag:/W1uHX8HMw6ZmFWAt/XmLA==,type:comment]
    #ENC[AES256_GCM,data:gMHcXi5ee952VIx1uSdW+R/kUYHPgUWeKg==,iv:o6VzgVrfxT7y2eqvSHxW7HDWNiDqCyEHBFXoiBnQAjA=,tag:0PXZfeyZUhCsjIsPjgibYw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:CQCEYpa5hnuOlWhK9NAD+KRyAQHrCGRJLvvV7/uGd23cJDbVJAg7RPVknQ==,iv:OXJlDLk+ua6vWwKtxaSZHhm8PY5WnKDppBDzYdAQIxA=,tag:aK2hC8D2AB7/NEklaoz4hw==,type:str]
    #ENC[AES256_GCM,data:eYsYuARbAL2wYcy7AEnOgcRW9ptJM/nLrHiRTG4pNm3tryLIn6foSu+XI06/rvCbKPEpzENZSyeC60ccHv39zHlOvcOgEsk=,iv:oxLex2Xo4fU+7CEz52yFXeboBFu+EmyovBut6sVnbWk=,tag:p/2bFmExLot9pfhrOU1SdQ==,type:comment]
    #ENC[AES256_GCM,data:JRoY21SlbXZpiZMqA2zrkfdaeO0QGYkBrk+JTUjp4KYKFiY+dQPZOtFl4hcYwSugY/kF1qFS,iv:J4JpLcwhZoUv2Iep4fexe1eO2SApTXvBePFi9WQeUqk=,tag:Hd8RzDA/5RowUTEjxuInXA==,type:comment]
    #ENC[AES256_GCM,data:jESFn6dSg8DT85/MathZt09+JhPiEjP1PYE7FspC++vVLqw=,iv:DBHpSdaz5yUNj3wjUspjySOfIBBAUFpM4MmCok3EMT8=,tag:HXnKqbeFSLFcYOaRA5TbbQ==,type:comment]
    #ENC[AES256_GCM,data:+OWdtqYk8qpc8F8ClEjAWkeZn5X6aHmWV5fNbxIaKj1QuuJVJgYm,iv:sCT1iU/IFPjOchv0Ee9sascOMob1GKE+515DUwISCfY=,tag:gXjUp1Gv1Mx36OlzKqvRZA==,type:comment]
    #ENC[AES256_GCM,data:bXOSYqiFDPvxVgCaTaA=,iv:EUbIwWzJMNgLCobTT10kVgf41xQPVzeHO9DooiiXESA=,tag:3fBQFxlLxVuD7WAVgteYkA==,type:comment]
    PODNET: ENC[AES256_GCM,data:c4t+S9uaFSGWGw4kmw==,iv:gx4hrypJ5wCNvg8CYs+Y7VUxu6zCgLCz3vB+A2arLeE=,tag:+LVFi/+/fIdkKmcUnTQJ+w==,type:str]
    SVCNET: ENC[AES256_GCM,data:FaXLY1UOeEkoLfpHOw==,iv:Z1VffgRTyCYBTllKCSJB+Oy2yDvOBa99ODVRT31mIR8=,tag:QZswrJ9SHcf5JbHuWxksow==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:C6v0ksEPMmjHuuZe,iv:sQ5Gye7ynnCfDVIAhUcvlLt/Zjeylnvg78X1Q0wH0AI=,tag:kjOP4ZpecH2ZbuBm9HD4IQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:qN46SpJ154U4/VhW,iv:YfjE65phWPYrPgclxeZMSBD1rnWC+9anGNYFyDi4vXM=,tag:l1AXT5vOTruvbxGEaMMB5Q==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:TtoozqoAeP7OJU/0kYo=,iv:ZaK1F5gX8AL2u8rzgY2xDl73kSyML9fOLJuj+Yc/36Q=,tag:L+8Qrc76MWGm/b0MthjGAg==,type:str]
    ADMIN: ENC[AES256_GCM,data:uOr25xs=,iv:aqSccw2yHEiGoMeWu6vdorJo9WXAqH0fP2F6/reBFWo=,tag:v3dFpk47oq0OVXywiWpzag==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:Aw0gUR5bgOU=,iv:I3w3cwwg53tbUjRTcuNuEL+HJMPt83GBRAs9wlQiHPY=,tag:ntG1T+fHPFbN2lQ4/A8sWg==,type:str]
    EMAIL: ENC[AES256_GCM,data:jjiJYDCm37LrtGUmsW+a7bM+Big=,iv:jgeBY0rV5glO9ho97AoAermQZGc77K8j6XnhCHHCL9I=,tag:nu+S7RkGJKLgN2E68Oob0A==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:qABsjmz3Emp7mx6A8E2Z+LjfATFd1E4vZ+yTvgkWximeUsbIMv2ppA==,iv:80QhjnsMODE4d5I4/ZW826g5m/tKOm5hrFjXO/Xp1Bg=,tag:2TS1p0OHedWt3Wb9sW7F2A==,type:str]
    VPN_USER: ENC[AES256_GCM,data://9nnyBxFdA=,iv:2ttnQ31aATYgKLgFrO6gps8vcrgUhmR1t0QzE1iUdHE=,tag:CbBzAjxgoFid4UQ5vZUCbg==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:hrsv4AEn3HGmPg==,iv:CstsTn2ma3mwCg7nP1IFYXCByrPv9rx93BD8KbMPUUg=,tag:8yxQ9+19nnhC0YtyvTsu8Q==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:QyP0+Q==,iv:hfzJJzf6HiRSlOB1uu3i+fwYwFCNPqmU7C3mHD4Yp+4=,tag:DLnMlB2WoH0RNjNDJ6trVw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caandqrgue5nl44eylp4nvake7znrvxretz3uy3r0ccfa2av4aysejcgfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSEFGTkRCTHhraWVHOGs2
            SXYvcmlGN3JXRDhsOEwxK0VReFhVdWFjdzFrCmlJV2dNQ0UvRTBsNUNTYWp1cFh0
            am15d3Zkd1RWL2FBcjM2SVBUb0RnbGcKLS0tIGthZnZ4blBtajVaV3l4S2pHMGZa
            RzAzdnhFQlY5Mjlyd2pRS1A2WmNrQ2MKV0iY6UzlE0FrZcHM5yiSHCX9FtPzMkXl
            mZJycjWYJwMJtwzpHRbxfW95DE5jVQRmsA5PiVahNLN3XdW13YXbcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T16:55:57Z"
    mac: ENC[AES256_GCM,data:uyG1m7Iz8/VMQ5SkqYRukokvQPbASM0gJz3LnDulSNibtw8ARDGZsaAbqOo72AMV3jSUHT0iNR/f+3yMeoK1it9m2ERBpgjV3I0cB2Evmk5GzBSMgX3WlJt9/xfoysb1UMPu6IKTJ+vQ2NQqkMrtT71k9vySVz18MWWbiM8oCKQ=,iv:dIpH7jE5CHWkf1GCjqs1/ERV0OehYrUZ6YAbTPUq9cc=,tag:rjez6L+dIgDaQ/x5mzpI6w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
