apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:Ic3xyw7d/bdMNVKMmdf8iOOVid78Beu/KiXlonFJguK7EfvrX3u6tp0n7Xl11UNN3gKsATOKs9B3xQgWDLMMpJY=,iv:3SSCWv4fp2RQQOH+pqIhzn1qn3+T4vUMYd4aTf+VQsw=,tag:eDiwnsXKt9m8fufEgdVbPA==,type:comment]
    #ENC[AES256_GCM,data:jjxHNK3du3KbHgoyHGVekVrDiappf4lmqcZokbJJqHgseueFde+X9M2w2z8=,iv:kBOTexsz/qY8vuYH2RGveWqTprgTCLQ7KL1rN4/s8Iw=,tag:wEh6p9j11zk1sAIWPzZf3Q==,type:comment]
    VIP: ENC[AES256_GCM,data:eNS7zhTnhzK2Zc8=,iv:Nxu4CSFhK0yyLy1hvu/6ctwac6qf/J9WQ8tqIChIhlo=,tag:850NU8cstD8jO9TgYCvDsw==,type:str]
    #ENC[AES256_GCM,data:95R+BWndHXfXmcMFANUBY11mmBK6D3V5Wv4=,iv:bxN0tkD8OI0C0YiMbVJWpBYQjj+Mxnvhu9raMxNGDhI=,tag:rIpaKuza44AcBn7atYISuw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:taH2DJGuTJXvGMk=,iv:BnqZMDFJKOwzKacDK6wkMUlvhbw+bih5v5hxrjDnCwc=,tag:mDR+Qy05yKRYMZNKFNCR9A==,type:str]
    #ENC[AES256_GCM,data:kll6txFq3ecYEEKMso9SXAqZrIBaZfdFz6OJWL158Ok3IA==,iv:32uAuuxRr4xx2ALGWUyL1VrEfzJKKh2yOI7HjSe6GBM=,tag:7krLR6aQQPqISjZDUq02cw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:u9BxmMaowU8GyLY=,iv:6uSM08WLQizMUrrI/tvTA7/cTTqHx5GInf2bi4pS0k8=,tag:h/DgD5AwixJMak/2djVj3Q==,type:str]
    #ENC[AES256_GCM,data:eBgmqOhTC7TTN8uSnYLuWKG7X+0QMML4VV5svkQUBm7p/0SsT2ctfcBFv5464Vw=,iv:OwrwlOAyyYCRdAj3Ditg0/NQwlIa19d2WAFviweN1q8=,tag:vVpEXl0dlrIvD0aFfsJ/0Q==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:xOMLS9/3k0nuZuSnvvPCXVl6wkTjtz+yGg==,iv:XYpnShrl9Oqn++nxDuesB+ND8S3AAjlSS0QFM++0A/w=,tag:NIP9SsgOoqfX9+HdkdluKQ==,type:str]
    #ENC[AES256_GCM,data:B1n/BbdkRXA0fE/AEkOYr/havOSsGEGRbGbJFSb+0SeTx8AwmyyqceSbMGpvOM+rjjJHVstIr0T9XgbGADzWwFlEbnEkZID5kYDK3cDIvNU=,iv:mx46r3FtEablt1IxyB0wW2gZKA4j99s2fdfSDWKuKLY=,tag:ERebiqs0kqHTotoQ5NNntg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:MC7KweSyFDaMvJww,iv:5HNyi6VKxHQG0WmB27/0JIVv480hdj2B0uV+43/6CC4=,tag:Q6OqyV3iV+Zd4yJ7upSczQ==,type:str]
    #ENC[AES256_GCM,data:yNYOjsMQ7hyMFhjpjj4uFy+aPe9Jj/HIrpz8i/z+xHVFm3EOBhopKkmbxDvVLJI0etWkILbjf/Q=,iv:SsuTSQZe0dXRa9c2a98KuAGjc5SZfpBDiorFHDpOJs0=,tag:ziwe+yh3w0rul2XgA3xpPw==,type:comment]
    #ENC[AES256_GCM,data:pCTwey6fjIHelkZZoa/7FoEHmETTLBMMLA==,iv:nIIoQSDj4CIcyG7w9XhSYKcrRJid5/Bc1duwlBpC/i4=,tag:zBI67Z9d8SuJ5UW3JO4Otw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:eBUQFAUC+XJ3evREvM0ORFVQzH+scD7KxSA9oJubFTHbHEPHgHWsUSkK7A==,iv:o9xiJqMHznO8oejI8dUIpk252eCJ40rT03d19WXYTCo=,tag:U+Hp4Q80LQUCRz31lSv2mg==,type:str]
    #ENC[AES256_GCM,data:JjIZg0YBFtZh2OaHNw==,iv:pPOjxXkgUa54esvtHEi5iLLibM1cjGw4rrILot2lS5s=,tag:5NCWWEiCDI5fDTYu7BXSRQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:FCXM3V8EYQTO4z0IWQ==,iv:fOx5rleNqiByC3nU+jiElJeC/tKFV0tq6IZFlocz4ic=,tag:WYT36P4woSMAWpCXQxWb+A==,type:str]
    SVCNET: ENC[AES256_GCM,data:OpSzGcWFPbTYbsAIwQ==,iv:iJ4djG/eihCQFTEggDu9JNodsA8MwgFZvZz00VQUlgA=,tag:JxstJXYVa3QOreSdFJUcGQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:HaZBEcsjCgj3T6KnHP0=,iv:vG/vVqcUWKIAdRdGzJwVFPdUDUQ97cGj8rK8JvK3eQw=,tag:jd9YgmOxQ8t/0JHDr6PJ2A==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:9V/R6gPo7gbjm74c,iv:tMr4q38HO2qWirH2YTw1zvrqHGF3hldUUZNyEzkkcjU=,tag:/VwClTiZ7myjr3ExC/kmwQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:bs5yrHC4ul/vuv6V,iv:foNMrr982TBHkpATQPiL40NXbUQOcbASkwpRIkCQJUw=,tag:97u+NTqLkjtOlYCUJ8L5SQ==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:bz1S31yGSlQRCY5T,iv:D7RuvQbOecEJmMaYhy0YBVSGVQBexJz5mO+p1gM/uCQ=,tag:6Vf2FyfXRhlswM8Y5dsBmw==,type:str]
    EMAIL: ENC[AES256_GCM,data:8EmCjGcS7ybIZJIj5kS5G1VQjiY=,iv:NqNhN4L1WX6UmNvLHPcisIMZVcKSW7LavpuGTjOQFVY=,tag:woJaOQRpoLsQrilJIWrcdg==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:SycUUXddqEmjAcB7jcrtKKny5F/awnIf+r7xI7Dx1GLchVax20Z4ig==,iv:XI8UYguiJHf0oPy7pQvr0ZQC6JJ5MCwTi6XiPC5Axkc=,tag:pnApllkbjfhnev6eVKlsmg==,type:str]
    ADMIN: ENC[AES256_GCM,data:RRusgXY=,iv:7IeD/CWEMVjKrJ/R53W3mhZBcQJgsePyrfhisY64IAo=,tag:CyFidFx3AztI8kAdX3Fp2A==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:TAk0/RaYmM4=,iv:tNS9/b9x5WP+s7H+b2UopRDn3Iw77ARMG+Pe+DMF5nA=,tag:J7tO5qfO7k5c3rN8SS0FXQ==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:VBRRm+FtRScVQj5lrQ==,iv:6G1TGzunmtAXDtSF+s3d0nfOBGEFj+4LxiYpjPxw9IY=,tag:q6j8nSGCYnioJj+ZDdgkhw==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:Fkierw==,iv:nWvntmbtWREyrJlHqNUyDrUPaG3X/Zu8zGFjD5M56us=,tag:0yNY9g3jcl8v1h/52ZfCFg==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:sRM4bbTe+YZvCbAhtfTk+sG3r/ra3ffODx7Ho85oqA+8RmWjQvJe6K3M4TM=,iv:G30tsFkRrTOtdJuuoGiZmrsFznfY6XvguKIAa/9iAE4=,tag:R9zATJ7L1t3Qo4Ft9fYk8Q==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:yItK+AV+eLPZk+U1RdubzmbQYhYPGMNRQHpXfEUy/1b8vLa5/xSxLmRs5Sc=,iv:9KH5mHNBgZNaRDM0XYtFds5CmSKORfzOfkCx9GpPGW0=,tag:C9L7+Td1Vndo2F+XXawJRg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:spQlOr1nAFNApN00Ew==,iv:HWnkSOLCaP4JgzT8pLi7I1igJz4BQBFLdqH/vTyH2X4=,tag:2odleq36lc7XuZDfdyGa6Q==,type:str]
    VPN_PORT_FORWARDING_USERNAME: ENC[AES256_GCM,data:Z4PUVb7b4yg=,iv:KFSvjEadVLwgvdf+P3ShxZ4ogfftCsRxSO9XVL2i8b8=,tag:mTcB7geeNogNf/Gwojap0g==,type:str]
    VPN_PORT_FORWARDING_PASSWORD: ENC[AES256_GCM,data:DrNi7TrBEqPD8Q==,iv:v/780TPHkUGWhsE+Rin/wK0xXmFancxNkxTMHj+5rE0=,tag:qBRAJfVg2lph0y9VzC9uTw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:PB7Ivw==,iv:+WkPUgMhjje4XJmpNGh1MOjI07EJegVJBjvIoJpjixw=,tag:TggxHKYGqo6a0VZYVNMF4w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUUUzTmErVndTY3d3VVFI
            V01vc2MvSXV0UnhUVVAzK2VqaWY2RkRIWTNVCjZBWjlkUFNGSVNwN3RxYnIyRi9S
            c3FkUDRXQXZMbzBMTnhOWmhIOGJucU0KLS0tIGg4dWxqc0kxUisrS2lkOG9kamEy
            c0pESk9vVFBqdkwrRVVkcnlYQmR4SGcKY+PEqGic0RpPVadaV7Ier3v85+eV6pBw
            VhMPZsSgjBrSg9FO4NfQCnMH6a/D0CxzXTSCda670qpoF5ixmn+2EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T22:52:42Z"
    mac: ENC[AES256_GCM,data:tDIUg0PMgCEtG+eVFg9Aaq211klUg7Vy4Qx+BnjsissZmD5DzrodEfwcuvgsp7W8rNeUmDBEQhIDxPfHCvbY1Ihd10NNaFgSUXJWjcsOLhoif2ugWqKPUtzZpLToAdGhUFf3T+Iyy41srmhb3FZn/y1yNo5qI7ZNDuaKsfNgOGg=,iv:kI4WkzFGSbmL03a0WoHQ8BfM4u6k6Rmt7VLZ6uSyhEw=,tag:JPoa4dS9dspEWD/b3SCjJg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
