apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:tzLfUyCArwdLa2yU0NiBE9xQJI42eDXOeaaVVJbyNvmy3xa5u8L+Krmo7qJ4L/+SJJp5hPM4X3EP/TKQrCGmeJA=,iv:NZlqUaeg0Trt3FrqisYRF3FAwtePHYDa82XMaqr+Ebc=,tag:wNcebJx/yNXQaWN9j4qPJQ==,type:comment]
    #ENC[AES256_GCM,data:sKwP9CVseK7aFTjrSBk1SgIxcfLdx2maV7JhRZjhqmfIOlYbw5LisB5gQhY=,iv:G3j7JAUrZMkRJX83ZEAcF006VXlcxm3A6G9dC8EVyYc=,tag:Tk64oNgGqLyMDdVQoNsAAw==,type:comment]
    VIP: ENC[AES256_GCM,data:s59KAkPWHaljPl0=,iv:8q+6+LtT3QXYBlbTz3bPl/WWYWQatsb32SUwUVMc+wA=,tag:chlhP96svowUBaIp+hxVlw==,type:str]
    #ENC[AES256_GCM,data:IX6GatLVsCnjbkG/3qSvUgsyTxFpZ5QjS3s=,iv:EIRAa8EVpoovk9vS+bulezYl5iMj4+4i9lw/ewHToBA=,tag:IHjwUCaIZTRZ0JxsufHVmQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:pynx/+bx5lP+wfg=,iv:fW7eSFr709eGNgBEE6Adwr85vdmkmlhrMNS8YVbolBQ=,tag:Ikk+JmOu6NXpbztm4imsAw==,type:str]
    #ENC[AES256_GCM,data:3JnsrbHLTI6Kb63JvwQTIHcgKm2nwtWT8xGfyAZ29L7gew==,iv:Hs57GicvbbnU0T3hxGtK+qiXklKkbLtKCotb169DPo8=,tag:vVhwKlhcRpnLVufg3C0jqw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:YwjVuU8AHXjy5iM=,iv:PKxfB9fPqyAXq+0mL0Eo/GRvlBYgL86g7Ru7rreURrs=,tag:6htPGY/z5GnGZC1Lfk5LaQ==,type:str]
    #ENC[AES256_GCM,data:EYOgVJ6qpOIRKWy/Qpc6x1nUdlmEdIKpvdH8bgaOgzw2CUyUyY+Gcv6jp8YQ7o0=,iv:trnX4QKxJsHGHyjRRU2/AI62LzMBjwZdciK9pfy8LSw=,tag:Dk0hcv+eBEuRNtbnpcro9A==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:/KWLxTXqADYUTbu/sZMSW1WGaV9nWqU5Gg==,iv:X9ezZlr/AlmWIubyyjKZS3i4yzQNNepILAKcoO7BRfE=,tag:3IBCLN8GsqfnMqUgESRU5g==,type:str]
    #ENC[AES256_GCM,data:q/jxzpW0pEBgu3ffnsti0DeFS7gUfQ4kSTOIsUppSM6pNRAhF0YuYbZXdS+MB3f2AfkwxywBxYSxILSrIwpPCZvWlVf/kgQKSI5BLcNiQok=,iv:C4WH5VDRuAjSLjU4ct3AEYZbL8i+6HVtDVcNLH5Gtbk=,tag:JWeDD/ugZmpV1MW8jLwwwg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:Q4coEVrAwbfUuoXy,iv:zm0EmtmKmPgPfmCz1DIShjryTxsCK5MHsXbHPF/i798=,tag:v/xz6YIJqz9Wp8XRd7gPpQ==,type:str]
    #ENC[AES256_GCM,data:NOy4XpmL+eP02EoKE9Dutk4Re7SfqtferVmOraS/Uxnivv81/TIqxobPtzBNOsienEeAhVkPoY0=,iv:6D5n5/LsSceqQBhyqHif+9qHx0htzuZveQMbUoVVW3Q=,tag:bvbp6z8vVj5pX6t170v8bQ==,type:comment]
    #ENC[AES256_GCM,data:T/cICRanN6Scacm3NdR2EYFeO9DBH5tr7w==,iv:aQhpyQG/rdKOU5enNPqqCIPzPYtah2H83JXDeH10oIs=,tag:pMG9skG59gbUDFU9UP7++A==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:IPAXlXrOs1nPhIys37WxRaloI2eQe5+6o/qlvm8KHNV8NsVpEcLo24D3UA==,iv:m6gsY3eehmCePWmgQs8oxAqrcVhgDky60DsvDmiYZIE=,tag:JJxr78TADkSWe3zX4hv8Aw==,type:str]
    #ENC[AES256_GCM,data:pe0h+vkGOzaz8q1vTA==,iv:c0prppIOETAbzobmSy5fCcPiptXsB4ANPSn4ItAijSA=,tag:1qzUKgxsKNbKtLtVKfGCBQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:I6qFIjZW7/W063V/3g==,iv:M205H8h2pdAcKNOq7WiH6N0hUf1+ORSBBALhXPRUGoU=,tag:eUsj43hXp15549986A558w==,type:str]
    SVCNET: ENC[AES256_GCM,data:mP0dsSQ1oEemFUcrdw==,iv:3B9ED01uQgPQydcpQppR2ukXwjFhdDnAZLqMOHV9fDQ=,tag:OHpoLD6dPf7gIZHOzXSKgw==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:cvFwMzmKpxXgYQDrJi4=,iv:D9fQdyWPW/SmvxbXIiW+NDzldSyry5mJihCgyItqUXI=,tag:7gH3AhgleB9uEa9nL2bagw==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:DXvITPxWzrHc8Wyl,iv:WpzAtFMpgo3Q1Vyut8cAsAff2jAPgP+rHpf9MjIaNw4=,tag:2AgxvBua2eVqY9axlD8sHg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:432Ol6jkIq9wa+bd,iv:VKIz+XqgPCWdjL9+nb/NkIVIxh2A0EM3hXuZmqwBjlM=,tag:Bx7aRRJAJOWfB7NaueXjlA==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:slSjjRn5ZhnG2z00,iv:SZZrL1lWcc8wQEn8YN8zCnpMdIcPFDJzqYau+ErLkAo=,tag:kFGYz55ildF7p0worvYpqQ==,type:str]
    EMAIL: ENC[AES256_GCM,data:xmW0INktohjsnL2KCYQL3prRD3k=,iv:H7FsZIlCZ2At+gP6JCplNW1gmIEZCqVGhffgSpdmavw=,tag:TSFPiUiohnmroH4VqeXM0g==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:7CLZfN1szPsXEI8zwDZwBlKDWOaxr6fgec6mDWQ73zfN0bZa3KCPUg==,iv:jQJsS5E1IESAVN1qQzAiKfdcSvY7qmiIDqTThQ6IUYU=,tag:Xiy2EBYNly5nXGKrXfUAQQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:1dYbsg==,iv:Y9nUGNfpJoEQOxHs2nwSLtIlsN1IWMvqTHC5v9d5No4=,tag:VUe/Kpi9d1PWZeEW90D6vQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Y3dZM2N0VHJaMFJyTDMr
            SktrK2ZWWENUN0phWmI1Vm0rcmY2QWl2aVR3CkRJZlo0di9yYkhXcit5Z1FMSXpD
            RTBuUm81L2hCNEpIcW5mck9TblBucDQKLS0tIFJ6YUhrWVNPVGRVbHkzakl1ZnFJ
            OGZhV3Nhajg1cGwrQzZLQTRaL2I3RGMKUu1GHZggYcPAFBXD1ttJf7FqVw66/Tj7
            NQkBQYaGEU15kAB8HvCGbIinnoQ1azMBxrVxerc9ifGwu7yFLBjMKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T03:26:53Z"
    mac: ENC[AES256_GCM,data:Qp/v8+WaVlKSnZKsMoEhyrBKOIqdHJW0R10XJEuRW9bm1SfOjZcgJom0vA/wixNib3EoP9iZfx/QDWLQ4WJtqzOylcSwpNll9NtVrO54GIlGhoiIMao98GR3ufvOZ1rHU++UhOQnvLV+hkeOdLLyS9orzxB/ufpXxPxlKsrpLmM=,iv:lg+BULo+iVbNvLGiRcMQHqmawkoJphwo19wh/Ycf21s=,tag:z0nuKyXn7++VJ9xfTRlOSA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
