apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:gymZ+Lsl5hdb8MYFNTiWXVN5fNRQhiDJbYF92UUt9sh9zMnOxh2yzkG/RX3Jv9SBFFkgGPWTDSUUYieVNtT2RKA=,iv:vBybYvVHld4SgMv5F9YqEuwHiGsprlg3M7nHKq1GGlQ=,tag:XKXuU4ilcaSSlDOJMU5haw==,type:comment]
    #ENC[AES256_GCM,data:/tkG75Fkrq+lOnwuXFsWBubhf1xBADxhaiuWPLJGUTeIcxsr67NCLHi2QfA=,iv:MUhha/7IpxHog7uVQb8CdsyAuOMfhrKGQY9fg9h/L5A=,tag:xEjJnbOc1XbVoLioicWalw==,type:comment]
    VIP: ENC[AES256_GCM,data:/HJVFUkrlpPaPw8=,iv:POiPxebMDyWkiR0VPuvYe37eR+n3qizwWxff68WiMPY=,tag:f4LIqNxUwYnnI3lmhUDo1w==,type:str]
    #ENC[AES256_GCM,data:LhY0uuxk/O0QJ/OzP+bpet22lSqd2aNsGD4=,iv:XSsKHeCNRHnIZiFBnjWWJlDtkytwUupKtFDz2ljLO+Y=,tag:aVDjCpYj5ccnQKYuHRHhgw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:J+eZY2BqT2OfRnI=,iv:W1SBL33DVI5TslU5tUir8WvxY/RlCC4k9JGmDUsBT4g=,tag:ZUcs1wCtmvv83Tp3T+Ujfw==,type:str]
    #ENC[AES256_GCM,data:GjKjRA1a04EoX2pu4bWIyIOr31VDOzW3Ktx3/nO4h7STHw==,iv:rRK5/+M3pmtN+4uIWvUecck5H4m4KIadZAK3no6o3zU=,tag:L/ACvO/N+wDsimKcpZ9LSA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:WmtD/Vx7Fv33TuA=,iv:ggItldivVkRrc4YYJfK4oSMwWdLD7f7SbTa6+11Z8WU=,tag:zK/qTorR6mQMCifgQR+5CQ==,type:str]
    #ENC[AES256_GCM,data:dO6/Rjv0VpofERrzhDxofBF03ZG133CH/3HSaV/9MbtEDncD0i1Dqg/xhmICm+E=,iv:HVOG3/R7g52x5zPyR6jRR+saoBFbX9J1NnaVDpHbrNQ=,tag:IMPujqrWEL0+U4D5VsTCeA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:6q4u2HMzqW++ILjsWD6/kwdqHbR1GKosfA==,iv:lNS+8VJL5ahcSi0dYTKk5lqi3Khbh/3ciqUDRlLIZC0=,tag:kn33XREmoLsslI8r1IV6uQ==,type:str]
    #ENC[AES256_GCM,data:tyDz/NDE1xB6XxfZyKeBurCMwWHcdyWilxfd7xoYugHg81z7SjF+6mHSP/IrX6MBeEhhNQe5eJVOFCD5on/+OQ6q50cea0dB+Mmb4GxP2CY=,iv:9fEZXQoX6XkpWfPCe52PFKvLIH62Ffx4PB556mfoFdg=,tag:+rLCZ3OdNW7MJ1KHP6Ou6g==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:5nqT+x1Abq7fynoG,iv:0wROY2wibZXN5xfDmnCDhApGx8LnCSt7+gcmmbjZhfg=,tag:MA5kdWFJkh7BF1pvy2j7KQ==,type:str]
    #ENC[AES256_GCM,data:3DZ6JJpUJ0N0MZ7Yyd5aRkDPytkVi2htsOxHuP6NArtDn12olWbd6EbuVi0BZ2QEf61Y2J4qe0M=,iv:/zb/2MT5x2pyVN/vPbUFCt37TSQtrD+16BcvhzAr1ts=,tag:XKHTmQYb5CFZUX8GD4OEuQ==,type:comment]
    #ENC[AES256_GCM,data:WoOAtfpYB2EQLHw2uQLR8l4QBtZpSKRrNg==,iv:PAQdCZy88cg2RRaIzOHtEZ2Rb3u6dxhLxi9eqrCnKWc=,tag:bAHoNJRW2o65sHFHFvGbxg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:IGQFIOSaFWjWn36LxX6qW4+Z9j6mQFGOWfY9OwH7LJ1Nt38KEDGpgJnEGA==,iv:IfwHD4mZHMg2M9KJQ+UHMoEWDlMeoe3ir2AM8WcChgk=,tag:YFDwtfcrfcyl1GQ9Fwt4qA==,type:str]
    #ENC[AES256_GCM,data:dBTzbAZUSFiTE2RHUg==,iv:OBSZYyyYgDo9/9ElgDdzk3+AqxNJVyykOtaajo3YWOk=,tag:UGczyM1xuLD6Zk9MEEgX2Q==,type:comment]
    PODNET: ENC[AES256_GCM,data:DS1miogeN6suq+kuzQ==,iv:zm9bfMIcboTx90Feuw+k3NKuI7zFrWzmKqFcBYem4B4=,tag:U8f+vjbv80mCdeOKavF+DA==,type:str]
    SVCNET: ENC[AES256_GCM,data:ereRrz0MafMUBAQdIw==,iv:G8DQfA5nxNoDaK+S297rJ6Q5pi1F0AZ19gUvHhx9wsI=,tag:SlojZ3DUsAo8wVJS9DFzaw==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:EnODs9dV3bvAKx92fJo=,iv:NciRgomIsQy3fUX9QcnIZaRSN15BvV9n03GIijWzeqk=,tag:5bEnsTXbpQK6lCTMxc63cA==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:K2EUZVyNDb1sFwVs,iv:svnaTXdaNsutNjyGcF/9mlzIDX/sh9WZXXH15iENIwg=,tag:eUYxT8P4o48rQUr6rkm2bA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:MVA3JQ==,iv:2up9Xr0niL+BchgDgBRBP6tmoRRvTzjbpVzQXFmRu4E=,tag:8OKhyDEefRkm+3zKZQn8Cw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c5g23qt38utyy253gvf729w4l2jnj7pqn5s00kkzsw6l9k9d5u8qmkvkwk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcEFFODk5MVdjSmRyU2Yy
            aHVqdjk0UEtRZjgwcWxsOU0vUVVzREllU0ZBClBuT1dzWFl0V1I3QVhEY3ZOZ0xj
            R2gzQzdhamxWVGpjU2gvYXYxK2xNSFEKLS0tIEhqVTFBbUhVSWZDVG9veEYwQ3dp
            eUwvV1V6NDhHWjYyM2JQb0F6elVFTkUKGPj48CzToMkYKl03BjC1lukxrxF2lv/C
            Ngr+rsVZeNRuNsfzVsuG2FDyzgnffgJKowlWKWnmtYVgW941kohyxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T18:11:43Z"
    mac: ENC[AES256_GCM,data:qEjza0CutRpMHr/B5DP6qE7S7qZa788JcCepp9I6kyAuDay5/ypF583o4j4o01K0WKhFtjkqa2QO2pelvj7cV7ps+NT8GI1LwNVi38fpsNjSvUNPnQdaS6gmpRKt6wfO7kXYOBlVUPLiDp3mu47t0+mxETwT3waGOMq6lYwGP7Q=,iv:RSuwltkR8C1pFlsWJNi9NqVPkzHCH1i94C48ghv/WuI=,tag:aixiNUgZGIZ1uhZRRbXyog==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
