apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:URjFl2Y0yCw4MOEbkPEUdG/yeE/tiSliSmyjlUn6g9/JkmltZpsP5ZCg689RpHVlqBVuXlc45sdr1T5dnHgIQp0=,iv:KKn90bKJwhbTRTZhYIGV9GEjOfAgHOQ8MbtBYKLyrmM=,tag:QukWJXohwKtc8FWRo4beqQ==,type:comment]
    #ENC[AES256_GCM,data:M5jzLBJUWokY8j+p4njb/5JcOnVt9X1+DptqtRwV0DiYN051TPx0D1NtlQY=,iv:MUXymcbwG4po4DypEelXMHOwOtv2/IhgENFf0CWC1io=,tag:0whb1O8CEwO4FuoJLvEVTA==,type:comment]
    VIP: ENC[AES256_GCM,data:8speMxIrj+QsGrA=,iv:DnoNasbOTT/SlLrO7ARgaHH+0/rqK1uOtLoOVUHyQyw=,tag:ksmMBr7cr8I4uQ12AVf5dg==,type:str]
    #ENC[AES256_GCM,data:Tarn9jTMfuiHHE89Pi+HI3KTjzWXHoDy0os=,iv:/HnstTxngq+0eIBC+IkMQiIsXtsQSTucmKLanX1TfA0=,tag:1Ok1V1R4hSyI5wBVFJK9Fw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:yuR/A86RvFm5tVQ=,iv:SXKVgIDHNIox6rKZVHoJ998+kzusjaFjAgBbPVDep8U=,tag:ZmzzyC3fL/VUyU1YL/f5yw==,type:str]
    #ENC[AES256_GCM,data:AibcMy6v5F6IUZhbVVCiWrGFSXhg86VI6YHS3JVYET3BDg==,iv:T0L1Wy493/D+MtjDsyuAnbEMSFtRjFwD5ZIZ9rt/Bks=,tag:ZvtJX8NLORw58nPG6AAcsg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:RHzFQ3L3IOKkSXg=,iv:mbCCAdCqq9HIZf22E5077yIQtHu7CCr2aHbRCljuAtk=,tag:mrURLecvT7zVeWXfuqiqeA==,type:str]
    #ENC[AES256_GCM,data:/8YHcwOdreSpmgQQIeud7bv0zEtzkYBg+tVHmEAR4hNXAa55ryLjOHYU4Y3yCZE=,iv:UqENLUcYBFAOw1j0Fy86hCXI5bzvIahMtgwGY179/yE=,tag:CQ6ULN7WDUuXfLS74eQhdA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:l/pjxxHA1nSSt/GOXGnmdZlTM4luJ3kg7Q==,iv:1pRycWFNYf3O4ZyFGDB6SvvqPbitNOxq385Up3s16HI=,tag:nId4kJplWZ5RVAnxIKMs0g==,type:str]
    #ENC[AES256_GCM,data:ayZgGDJ+dY5ywSQg/UrnRMBnRsNkmD2cHAEaq51mLQQID9smCnnRUAI3cNjyQd6Iq4672Buhh81CpzXXbuju7TaGJMOrMYRpMGyZ7u0sNLo=,iv:I3igqyNw+xAs7lrHtXRrmi9TpGl5/sL75ub3K4RNh/U=,tag:OoePQow02kY53aRCWaSbcQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:/OAgy/HZgxNHpJcN,iv:zFY++yOVla/is2JGd5WxeB65FK3+m+m8tcJWVjMfJic=,tag:FVuy3SI5qeQrf3NdOMdZQA==,type:str]
    #ENC[AES256_GCM,data:lqUZRQ6TwmwvDBJ/4FqBkiD/bBAiMCm+YN9hwdfTBmlTZ0KHJ1n6jcyG+rgpSa0e3DOjg4CqGKU=,iv:7+vUjwyOZK/vOLWuxhD0+r2vXY3fJHbF2iHs9BmjvBM=,tag:wt5qzqbHYYyenx8yq0WdMQ==,type:comment]
    #ENC[AES256_GCM,data:2LCoGXBCtfEIWeh6IqOgsHoHzPkX0thvLw==,iv:VdeSoyilzMoVXTlbmUwU0dQ2VvQ4Uq1avKSXZTqNKi4=,tag:vUx5p9OBOqcEDUPKKBKLnw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:ARRo8alX0zJcWHvRLZTgVh+kqwxNA46OKgvU+KnnkmBSk1kWDeP/Zx/9Qw==,iv:mDwWXCFvd3+s6jfHVWQFpkWZC7Uzlpd0HNZijFBWkxA=,tag:4ziDvD3w07CxfkjSKo0/Aw==,type:str]
    #ENC[AES256_GCM,data:jSF42+fq+qq9AsnvP3MXuFzsEyZmTtErfG+FZW+C5THOMgUWlZj/iuBd44QsvaE6TFT39gTWlWmaE+KEsCk2v/gQLU1SQoI=,iv:sKC5Of8UwAwldXk4kOFSBdlJfKg7N0tB4D8LjKrTLzA=,tag:XRkMfsoBWAlCwS+RiRQ3iw==,type:comment]
    #ENC[AES256_GCM,data:exZIeTYvZJ7PtbC3ZMLu435pvJKT3PwwhaRBDRpPKEs8tmvg29Fw8lqcT3rK3iEEfOIX4DUV,iv:+rbCoCWysLiP2qRP26Pmp2b5buuesd64L6CxClHtyd8=,tag:2ifwSxepjPh2RAg2826+hQ==,type:comment]
    #ENC[AES256_GCM,data:+bhKZl2wfbn2bXqMvaXDD6Q9l1jnL4cidhEbeB1Xe3jTcVg=,iv:Tqgi2ErnHN5a94QDz/Zy//WlV3k4g9LXUhCY4sRoasg=,tag:ft5mYEIAC/ZZb9mjmTZyaA==,type:comment]
    #ENC[AES256_GCM,data:5e1GlfnpWsXz3R/luvOJ0nSQoaomE1dpP5G02K6wlFxbH5R2lcsx,iv:EEDe6Ek2rd2bA71PeFYljHPONCvhojGyHvs9Mh0g2/U=,tag:TDjIZllZIUWuRprzYLcxFg==,type:comment]
    #ENC[AES256_GCM,data:zMZRQqVrQQGcWFjkvrs=,iv:M1jkLS+w9lZYRfwpuqmEeOULaHlQePmg0w08RA8LRaA=,tag:DMpZKS0L5fx0EeAQ0izvlg==,type:comment]
    PODNET: ENC[AES256_GCM,data:hd/uPCS0ql2gwKNZ2g==,iv:ODNdlOTVvi5KycTyiaasXsfuxtPCnrOjSnDWhLypfR0=,tag:RVJ1J3TtfajcrEFGK6uLpQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:7VouSnwODKSgKq3IVA==,iv:2OZEZTErT4nwRTOneHtDxkzg498SHx3ZtIfo1I+V2tk=,tag:IZNUWHpPU30pgPBN6Z2Hnw==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:8avlZegfB6nnSAGP,iv:d06i9GsmBC1UzBtWXiXklLREpPQrFNqF2CrpgewJzyo=,tag:HCBVHK5Qh9R7YKBoxDTZiQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:3EYNXVa4de+gYjcV,iv:C9PsX7bV1GIJRMTP9liDY/x3dENbEplKDi/b5Mymnh4=,tag:dkDWRPDFwDYfxjAT2vIYDQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:Itjl05QZPyS9xTdZLKk=,iv:4xrrBy249QFXEnlLR7NDyX5qqHpnlArOHQqYsYpgvpU=,tag:bq7Cvg7RzKV69fxEH4QSww==,type:str]
    ADMIN: ENC[AES256_GCM,data:ZJBMoho=,iv:xaHtJQq+qdPJP7IialrdrMLRsoAe8DRWWSLmaW2RCZM=,tag:AHgv7ye3pAomZnLAwu/IDg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:OvnpH254bqQ=,iv:xdcbb5AjcwxA/fwZ/jJznpaoOcl0zeTnpRPqL4xrkOg=,tag:8LkyoKKcFrhLvQ0v078yvg==,type:str]
    EMAIL: ENC[AES256_GCM,data:FKgZAhA3KhbQ3MSDyK6awSCXNZc=,iv:MX0k6n227yM+Zw7IgBZHHbgF+MwW/ifHh4ibeACUZoI=,tag:X9h/+BCDeEtF5+Wu4fkNwA==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:A/v9h/1S0/MUvi5jhKEO6A6/n3ohWmis+icKCHL7gjUHgB8CDrIjew==,iv:HTqOvRl9rHy0uPjo8tI17jYXGRwPNDIY7pYFMo9yOw8=,tag:7f7sXN0127HB2FdIxP1+mg==,type:str]
    VPN_USER: ENC[AES256_GCM,data:mhyOscYt+rk=,iv:IU6PP88MD+TD9j98P9HIXBMC9T03R+8sLt5pXWSx00o=,tag:cX0yfFUXXxvLUbt1lB6IHg==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:MNkgPk16SbNVlg==,iv:pu9Mc2wNKMnDAcHDLTOL3nbGlJGFC0lckDIPKV4Yz7Y=,tag:3a08xp7tTwOl1ZhHStY5Hw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:ITj4GA==,iv:cOGvgyU949BXa0tOLOhpu7tPIKVKspRMssgJ80ataH4=,tag:1AURKWIBRkqmGqTdq8Hieg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caandqrgue5nl44eylp4nvake7znrvxretz3uy3r0ccfa2av4aysejcgfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUajFibStKa21kZldqZnJK
            MDVRcEhlSXNFbHUvZjR1N1V5WmlublJWSVdzClMrb1duMHEzOFRSSTdlZ3RXOG01
            TzNOeDRKUUdQaCt2U3JZbjlXRUhtOUUKLS0tIExhT0t0YUZXYzIwbzRZZ0xnNVRU
            YUlhYjVRT01LWlN2QUNTY3IzbWNBN3cKRk0Fdr9VIzh7Rf8CU3Ltx2O2aEqWR5U7
            7yPazukV6zaozkF6uuD4ReOeVJGQRMJ0vVqg/lIHb5ADcu77KCTV+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T00:03:21Z"
    mac: ENC[AES256_GCM,data:zcDAC0Vs634iRXMlKuPQaH3VkkhSKTgvZxBJ9ATplXe3E3PTcPVD1dwCdWx4Carig1kYjbxudGbBDozSpfZbEX5bF3b05xguuuQbYffL3bd4VrpUlSIV7y/xAu33kVBduA+UmVBNx5OXlIBSvdyCG4Us/NC32rzvcNjpkgmpsps=,iv:X+BgIL5FuXdSSfEpxYRUKTdyGeMLCDuYII1t4cs0H74=,tag:9FY1sFZ1+CrIkbc3xfL6XA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
