apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:Rs5Sao0/EE0SdUSHsLhWQ2L1GXo19b5nLh9CtoF/83E0PvTJQ34j88sP0141d/S3NoiWyiJ4cSrPT0FRtFX8OEg=,iv:UPTY7Ui+hbnvLpAzVfZ/+uly8IoJYPygf8a07xOKeOk=,tag:7ZaVKCMZeKA0q8peutLnwQ==,type:comment]
    #ENC[AES256_GCM,data:5/H5JgFxAhYD6TlXZu/RuEu/86RNtzdD7Y3rn+oSMVjuFCwEOCSg9qXOtSA=,iv:3JbaEOQtq6bqh7bldBD7ikTGoZNzrXxvNCsWvuH2Rcg=,tag:zVoWkZ4g3OVOjjKwHstllw==,type:comment]
    VIP: ENC[AES256_GCM,data:ej7ZXnVErIVksY8=,iv:Pa7p1M4Yrr108UuZcXzdGPhox7cpaSrm0eWD/WhF6Uc=,tag:uAxBXvILjV1tjFGCSwuKZw==,type:str]
    #ENC[AES256_GCM,data:GDZJnXp3gTeQTvRDQvwbyhDOS5nAVALCxoY=,iv:TY3saEFTapvqE1Xx926+aGa4srDDOfQnNaG0sfdUDpU=,tag:08Snj/bWEIetly71cLwRhA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:5WC9lphhnVDTS44=,iv:dinduXL4ilIsZF9N8ItBPk3QIIl2n9NTqTeGMToUAQQ=,tag:3K5lQn9iycvfzr8oFi+8Qg==,type:str]
    #ENC[AES256_GCM,data:n2vvOPLX6aVi0Jvy0S/LMqpnRf6GN4jCpF6tq65v3ouuMQ==,iv:cJJJTpA4FJM2Ik7HcrshP4AMU7gTLJCBeI9X0pxbii8=,tag:EMzDt+fObcLji70lGbu94g==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:S+mdWci8GUct2BM=,iv:1a0Sg8HUZKeiiq8ERULG+Leat8C1wVXl8Rll5r3cAzg=,tag:4VJxf6TFdBzE/nS/F7/sPQ==,type:str]
    #ENC[AES256_GCM,data:HhMYQNEhICsDYKYM/uX2cFZSR9x8WEOMJef+cvsGLHpZU209Q6FYooFyIldM7Yw=,iv:rP88HZ1voD6zRx2rSuFIPTQWMaTKJ/HdgNZPCtl0MB0=,tag:xUls1g5gc0OVQJPhsOp+2g==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:8yjEQilKb6trzxJGjCUNreSf9sV3Gnadgg==,iv:R7kHHwPLysoSFDYLp5Nbg38BRF6Nz/M+aUPAILTeq8U=,tag:bEQeoSyvb/4Pz5yr61pcEw==,type:str]
    #ENC[AES256_GCM,data:48qgluNj4SiTBUYUeXvvjWDQVkbG9kOcNrCXIkeBoBEYYVq9fk426KzcObx74TKo21OjSoI9AVtfbgE0rOZ6Ce7vTbdXFrZ8zi5Gg4ZI7nY=,iv:3TA8XMuveSHRicN1bYF+eWrn3XjRhw/mEz37Fi+tGZY=,tag:dabTic1OKIDo32fUkSExAQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:eUpCh/gMZqdEtH3V,iv:OqlPMz2r8VE2A36oNet5zggVRyp8Lv8YppBRjZ5QyzY=,tag:2Jm9YiLoiZZIwIR7VyYtpw==,type:str]
    #ENC[AES256_GCM,data:Vy93EZz6L+fhh+k6hM66nBtmBHNQIi8gkSHQxq4p5CcmZngW16GGVU5Q1oROWKDkXUu8yg7OJ6E=,iv:mWkJf43GZ6s3t/+RwkRywtCvS9BbZaqUDTNngk1+vSs=,tag:zbAqn9hPzidoBwnzWYQL+w==,type:comment]
    #ENC[AES256_GCM,data:cLOqehxBcQm87BlVlfb9MYU2/+b1pEhjfQ==,iv:HgNy2mJs+dF11bsXasxiD3EpZFXaCIGicSz0l7wU39I=,tag:gi2Il0AddoHbNhXwXBG6mw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:pgZBuQejeWwuZ7yftubSynHm5PXAJ1Y9Q5bOd1JffWJ8Idnz/bNLQhpM6Q==,iv:MsoiNDchZ2BEAppS3+x9WS+/4KmPF5q40Udkcg6T5UA=,tag:irkuodUgzytrUsGQdjn6OQ==,type:str]
    #ENC[AES256_GCM,data:GxOUuD8rf/aEhvfOSQ==,iv:KYqgHD+WFQaNVqZn0aLKVXkegBc/4B37wsHLaTYetMA=,tag:RC0KOSkPoCWer4Dnvbr9CA==,type:comment]
    PODNET: ENC[AES256_GCM,data:my12d+fePC3c0+iwxA==,iv:De5zUPfw+/si5txRukPJSt/G6yvrDmubwSAl8Mpf4h8=,tag:2A9l2406N6Gm42BXYMnX4g==,type:str]
    SVCNET: ENC[AES256_GCM,data:8GCkKpjl46HW9RCEdw==,iv:o1VryE/aJ4b8EW+7izOV3xZ3+cBcqp6zZcxASpoeLCo=,tag:y87np2cmZw2qCgdBCCOS+g==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:C1GkuaHn1uCqMJ2+9eI=,iv:pQftLfnW8nZPPJziBrJoPwrAsNiB2mZ5D5qbltJ/Yw4=,tag:qyrv2KhPdbMVOY7PakZqpg==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:ohBHc6OVvISLVmyK,iv:xoelKkg6wtlFEfen+n6QSIolW5SrkGNZha7pZwk2fOY=,tag:oh/zI69t/ApffLHS8FAf8Q==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:7g0SsEZdpy1X9DRj,iv:iSLAZpMJ9Z8MGTMhpWFQMMEN7qcp0gpLwms6X0wJufo=,tag:BhnRbC3g5466iyvKJDo3EQ==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:E1U6l9oow3UriJRu,iv:VLhE7IpPo7llrO4pPksmyyqZY3Ymc9yaYCYT8TNWffQ=,tag:UHy/qgDWomJqQp8008UJSw==,type:str]
    EMAIL: ENC[AES256_GCM,data:BCSDZsr5gqQmIcnM8J7GjTWKCQo=,iv:xjZtY1/lmSLI89yfzeG6UlUo0QKrpxOI3yRQm/POLLs=,tag:M/VnT5VfRFV7IWPTBbGhXQ==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:9zG066WHj/SdzdkzcnvhZfiY/CQ8xI7/cieiwCs9MmBmmpc9yamqJQ==,iv:H3ZszWxZ7ppzAOnzHsNHmB3NZ2yvOL2wgO1H/79bPHA=,tag:mPskQ9Ogq2Gb3Xr2g5cP+Q==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:gOzbcg==,iv:R81NCWkvJ4PjIv/W6nlPKL72LQHyE0+xMQdq4TW50xc=,tag:NYrDhkpn+gEuhfnAr3cW1Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZDl6a0c2b2EyZDhBcC9j
            b2V0RHNka0pBRkNyYzc5cHBMUXQ1YWJ1SlRRCk11dFpoeHB5NFdEUHQzSUliL1I4
            RVZQT1lGeFNZYlUySXVaSmR2NWdnVjAKLS0tIHRnMEpuaGpBR2h1NjlmdEpGZ0d0
            OHFtUThWS2pHaXZ2cExzZitrQ1VuUFkKH1ET9vV78/VdFdRrMFwpMPm4UBjtUaMG
            0Ka1zY2ITZb6bE3YHAYes7li4B/IXw4XazYUnzqP2N44desDGBuS+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T02:31:04Z"
    mac: ENC[AES256_GCM,data:kDqzivtOO8i3IdGdfKYIbG1X2+J3fzzIWiSxLanjFJknKfk237n9NBOdA6EA3VNCsNhihCBYS0PuV5JktR/8Zt2B/d49gDtspEx00qhJWLulsJ/sQ+yuNs15bC00EunXN/tjqiFQdP+/VZSgupgpe5SXWnCN3DLi1rti99NU8CU=,iv:7LU5uBJdUHoXiC3hJNvIGI24JZEpVLlW2aqRLYBIX90=,tag:5qu57QoSY4h+rXiOXxs0bA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
