apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:hqNXE/WiOVoK7aH45Hyg0gJMSF+F0E/uJ6U+f9en6e6NLql8crFZuhn/qzC7jqx0n98uoc4SRN5XnNZ/SYVwWhY=,iv:OoeH+MXFj0oKYFV0cGkeMp3Fgi59sC3tI3XfcXBbvU4=,tag:dBw4sstZYRRUxMKZAuhLhQ==,type:comment]
    #ENC[AES256_GCM,data:UI9CjiqycdPqyuDM1EFhoTv1t7PmQuj8crwU3DcmSm/SfZQyWMAHVAEolN0=,iv:zZxDpz2JeFuuppWlrnePXP/bBgMRLNqGQJ9M2SrbVuY=,tag:gPVsspT/t6O/bK2KkqzhHg==,type:comment]
    VIP: ENC[AES256_GCM,data:3EOdxINl7jYMc3I=,iv:GLHSs9Y6DBDCOjKu+mtF+vgMYG6l4ldGN7J9aqMZ278=,tag:rCBCKdT81pRq3Yi6QPSNKw==,type:str]
    #ENC[AES256_GCM,data:6xJyxDMJFJ56LU0J3sMJJ2vlQmWZoel++zA=,iv:RdMVcVGnLHECbKFmmKQc7CVNky0rD8TVi9HR6bMYjMk=,tag:NXv6uBbmN4MGKcfAykm61w==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:SS1OeyZC6TIDDhI=,iv:Mpq4df10eyTMibDPDPir/9FKN0YaOfXTffbROdnxRvU=,tag:yxuyPFOYn8qAFZaLhtPt4A==,type:str]
    #ENC[AES256_GCM,data:64Tb8WMfyExQ2PXWgzGr8K/Uht/BxVs861tHpmw0/WuX5g==,iv:fzr6PoIB2t9QTZNUD3pkdDkA+AzXZ8wWtpiZ9dXwxsY=,tag:YVd8zVXHjy1loyoz9suGUA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:SUwWGmw9dLBy2KY=,iv:nQueu34ux6Fcy4bT1GgIq1q8zzIQr1Y39Q/CUYePEZY=,tag:04PenkmUWScrlqq0EqtXUg==,type:str]
    #ENC[AES256_GCM,data:/ccPLiyvqPqmAtdvTY+/GJjqZeI4ArSMT2y71YuBLBDa/hxonVNS25p/teS31MQ=,iv:HGIGNuiEJrnnPI9bRTmYqh8ISGFegeYg9t+vzjSJy4Q=,tag:DP38PDyp7sI6SachSBr+2g==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:lG6WI4bAAye73CU4GJKrMvUhpkV5xLFhQQ==,iv:AgQdhV0+nV+SdIVR2FBxPQZXMbM6G8Rxn1HIqA/mcVs=,tag:iHD5RwcEaQ7AyKs6CCHIgA==,type:str]
    #ENC[AES256_GCM,data:9Es8NlBqhv6mxe3fkdOQZoJb5uV0r4u7Vu02gGejlU5HqCrFkO6jBZIrfrF0V9qtB8ZxJE0vRx1lrWDIYs4/P3L9dkecYDdeoXo3bzrj9to=,iv:oePrvU/pJmugGoJ2Up3bwsYMbSbMXcTDC1k475BNYr4=,tag:X2zR6BNciFxwJqUi4a9k6g==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:V+M0Qdv9w1wRI/JZ,iv:jrghgKdK+v6PT+JYh+6cx0F4RjUFFDOYBfkpAFYytQA=,tag:JauQomdOusTlLzYoZnN7Pw==,type:str]
    #ENC[AES256_GCM,data:FeS3ULBjQb48gESJH1q4iJ/vQJ+KwY/h4t1+2PLz85Fu0ObdTSLNy+goETO2HUdAgf7lH2jqmyo=,iv:W8IihvxJDNrQ/6cXMZonDm0+1SsRZvkOrM/9Rsm2Szc=,tag:wxCgdt1lGX/LFshfIC2xWA==,type:comment]
    #ENC[AES256_GCM,data:4gUQDaeN9Z3wX9MoKLud6wmFiiKfN4U15A==,iv:oT3/QeDHk+kV87+rmitV9kRzl2OiCD6n1u+zVwB/8YM=,tag:KYHewJT1lLzjPp7N9rQZTg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:7gIpvyiuZDZknJAG5p+U9uaVi08cE5wNkZX0rs2AJasiSa4VR58pu/Vq9A==,iv:bozsdAe+7JlCc9+ohOprSJ5oiTvL7Jv7yDTg0tZZ1PA=,tag:U9nzJPL7ngX/fd/7s+FTWw==,type:str]
    #ENC[AES256_GCM,data:VOPOCEdhvJifDUq78g==,iv:vH3WPKVCCY+vQuvfIA9dFiF+Ib+W7mRAmbw2ouqkF54=,tag:/aOMqVFL3MeeR9MabIzx2g==,type:comment]
    PODNET: ENC[AES256_GCM,data:wXOORf6gItGaC2LV9A==,iv:t8fk1dpCQGPuIeZJNYW67042D644LJCM2eMLkruJRaU=,tag:Ilr+I+OgX7XSyOxXJ2aFQQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:aObsvDrKaY+CslMLnQ==,iv:Ilo/U6tf8+lXD2AWY+v17OLeTfrf42IPOf6r+jCmkDo=,tag:J6ZYSNB7ohsuCIPv2BuUzw==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:+jK0vmZZykYoRf7WwJo=,iv:9yeNvKSe4uunLNDoFEEEDJAAbsmNBN79vuiKmmRugpM=,tag:ydvuLTjBODzwWxHBR0Ntwg==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:RUDzzoJ7oDShjU28,iv:wnLR34rlVbW5ja6jV8OhNDUo8dTMV91roJ3p3Q4C3xE=,tag:7kHhM99DJT7axQz8MS7G6A==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:LGlFfovejQQ+3CiL,iv:gzXMHZryWAf4fmKRTGUrLTfeWKYpz8hDJSo3VisuZMQ=,tag:SHKBguT421mO3j5lRJ7f9Q==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:Qm4nATgDotkuPWQL,iv:XAk5xQUgKbzM3WLge91q60TTsNALwOV/DwinktD0vKA=,tag:jkYhsfF2RJ+ad4J9Pg8LIg==,type:str]
    EMAIL: ENC[AES256_GCM,data:YlHabS1HZ1BG/S+QfSjFy57mW1s=,iv:SldXsDStlKWFwhOHY958Hj3qkh1dpwTyuuqnRGkzLu4=,tag:ymbmub/UDTF72OyZUcYFhg==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:tpCt3ghTpAtQj0E7AJCNLBB8JSHjt8BWbKXRMCi9PTCccMX2Klv20g==,iv:NgjDeyQ1L3zHrtUg7sMUFo5tJsPYpMKlUvWxsCGZwDw=,tag:niXJYbWberLi5gEzWv4PVg==,type:str]
    ADMIN: ENC[AES256_GCM,data:TM7yDYo=,iv:I8DEVlt9iEgLMb5yP4eI78RHz1tJspuGZ6APcZGedo4=,tag:0Chtaqw+4AvPmzY5r4guSA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:2GA3bOiM5Ds=,iv:3eTdwfehK1YRx6DcvjDdi2VdQNpMBtQ7lY/GEyF5Ef4=,tag:Rh/6BgDDE67hDcfpljhUcg==,type:str]
    VPN_USER: ENC[AES256_GCM,data:grXj/Vw6WFY=,iv:3pigGpHP86nymuZCVmh8z+aaDtGCI5dL0Pm0afR+XXo=,tag:FHZdvzOSYj1uFUwWNG8y1g==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:Mz/A6ELbKVOvkA==,iv:MFhuyU71ZiRirFfIVH97sgA5Yx6PjYRfC1xn2qQnSas=,tag:wgHDddfZBE5MQ+QFYonvPQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:I/sl8A==,iv:mIvf4CkQ203zH8kjDvNepL61M9MIE5m8bZbZisfWDKU=,tag:7FULD5l3WFCr4pFrHJPzBg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTklYcnZ2ZEM1aDR5YjBO
            MzJnZDdna2U4QjV2ZlVQOTAwcDFGMUtDeEdRCnhtN0ZQNk1XamduRmtJZzFXamNM
            V0l5MFNEQU92MG4vQnEyN2gwMmIwS1kKLS0tIEY0WDBodGU2Q1UwL3FlRm5YRitL
            UDhzUTUvdEsvV0huV1l4WHl0ZFlON0UKPclQ9cM1Gcwc/yWPR/RKiT8FvCYMESsK
            wrhq6snQN8pcYaWfOEShWnCcZcWBzJ/PJGuvdSouusBCsBUgyUNt7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T15:01:01Z"
    mac: ENC[AES256_GCM,data:8QhF+vc3Gw1s8RY4QsNSDUWgyfEZCpZXlNKnt6rgzXVPsnxfLt6dbfJWc9Is/B/hGUtVK3/4WTt31btNLI9B396fpUdd8cV2aUzFU6WBniXGuG1SoBeOmYtFuUyCwockJSETVaPCMRm7KMUrRFs8UDCfl8xgPxkU8834mNjcVDk=,iv:K+jKvssXdQB7dOodqkMpsNiwDbRi+hmqquw8KY8+pT8=,tag:N+Rad7/hCPBzZJpXiGSZzA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
