apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:JIBvKj+I42e2udT3UMVhYTTR/oYITZHzRdSz6ULSGxiMRdg6mWNqkntnK7mIGZWActCAdC4+lRv7pQFCKyP6fJQ=,iv:Hh8lbstenGNvef0xB8cb2u3wYixxgIXTkJSW7wIh7KI=,tag:hI8h99xxxp+H3opl1ApTyw==,type:comment]
    #ENC[AES256_GCM,data:Sfb8gDU7wBBD+qMJ8faYfp0aiBAbXPw1Al9X3+3Nq5pFj+dshX9vUaQt55A=,iv:Avni/bXZ3wrJnvI8KCQFdf+8rDYc6JPG00zXOUU7Nrc=,tag:1qbdKNtF5sPcHvC6XrL62g==,type:comment]
    VIP: ENC[AES256_GCM,data:Q8V7lJ0frOgLTI8=,iv:L8jzW/lpoc+bWR18HE59/ovJ+aTwBHwuDNTU2wzfKlk=,tag:FRitLj1WyDRTrxMIUp1+FA==,type:str]
    #ENC[AES256_GCM,data:KTV33d60rS9EHUmjT5XD/HcUUnT86GI3fmw=,iv:O03wI/nwyK4JjV+GVr3V2y1E9191lJi3E0Miz9sKsIs=,tag:dLd/C4XR7VHl5fYWmR3AoA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:DU6AW+vFEYj6LFE=,iv:Y7c57hceiMGrIO4A6ZLHXa66i6t6JLMCfvCr/JPuk4s=,tag:7llSE74pcbUF+6ptMnSqgA==,type:str]
    #ENC[AES256_GCM,data:zFZHXkMJ9/F4aEUmu8ziXUuBrlQWQuYIfSi+FuTfFmVf0A==,iv:MNi3XZ605KmiBOd0Hlj9NB3fzUxQTX/zXUoiJUtcZsA=,tag:9mlv+Vd7qa+TSk8uuMlzDA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:6dceuo69cowhA70=,iv:L+3OviLmRmvWFgO/NoJR77jhzTKjeIxZFpujCHNA/To=,tag:6wHFaZnYPVN8CRBLtPgI6Q==,type:str]
    #ENC[AES256_GCM,data:F9VAHVrp7GVTQ3UCZ7djWoJyVEnreXYL0Y9Xm61mHqZLbXKDQky8U7z2nlDMxlA=,iv:IVnDQgvgNbt+g3GSWthhsQkS6/+TK/WGZP5DVsL6myI=,tag:MzKg2Ye1zmPNw/PiDfUThg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:/zWaZ3/nB2mx5sKEzbNENnXltRgqFp0F5w==,iv:SfolP8ump4eGjKNKRJigskymaBHcabYi3rP6O76gFXc=,tag:3v3Z5l7pnKlQTxqPQ8D8OQ==,type:str]
    #ENC[AES256_GCM,data:dmn56Tcpqe+jHcVyIgKOSVzs9gpZBKh547vX4k/5/ldWG5QbuBpNucb4Wt3iLPvkUG2ilZ0JVeDURNNMDp1ZtK1Dxn3WQXHye8f8kojGs/w=,iv:4VcOj5FqanZ1BTPoSn05vR/ChtiRlwuhhtOrleNiIks=,tag:sVDTeNt1jgh5uETWlojOHA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:D736Db39MyBglO0D,iv:pi/JpkBB+G7RqwkZzDR4swhP/ogiCJ7S7mpbq9fZpG4=,tag:crYPtbELmcqAxtCTaT9uww==,type:str]
    #ENC[AES256_GCM,data:PT+LF728Cf22eQVr5FBxv8NLlBCbyBvOpjz73jaCcQvG8DEmje5N0XNJODjPrvsD13krEUDH0L0=,iv:MdZE94iAdjddrFmtDthVX038sIPN1WQl1KUURg9Ydbo=,tag:XWeUAm166D6uPapXKfxhAA==,type:comment]
    #ENC[AES256_GCM,data:3bAyuAE3XF7FhTQuoACpiyzLHpt+4DL3sA==,iv:ZpIkHQTt/uVLNt/qjm745WZLxUPeP1pC3146kmvmpoI=,tag:yWEaLsmEUxHStl4DmieuBQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:BtI+8jriwfTLq5Pii/0fn1riKNXmaBr5W53emALkOt0IsXTRXQfNsA0Ojw==,iv:5HdgYLjODXFoxIDSxwWEeFGNhUgDe2w96xZgBCuHoaQ=,tag:kfCEVBXyEk1LdAZjR/OPqw==,type:str]
    #ENC[AES256_GCM,data:f0jBhQ9aUmgo3aMqFg==,iv:YM0NeU2sVHySDnuwX/QG83Je64ihhTLeXYYq00GgN2A=,tag:MX+n5LLkAuSAW9trivNJ9w==,type:comment]
    PODNET: ENC[AES256_GCM,data:gfGk72154reSDnjz5g==,iv:KQsbiIngFPePR9SgIdU7rSl3ix5pLddcolGZTZ3VILw=,tag:E/cqS7EKNL6SRE7bp0iswA==,type:str]
    SVCNET: ENC[AES256_GCM,data:HP/yFGExfwCquDvk2g==,iv:Pgwx+JSQ8ph986XBCGAsbLDEvWraOLCA08Qp6JCfxMQ=,tag:Z7Xpf6fqXhc93Do16z6ayw==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:nO78HalJc9Lt/lnYHOE=,iv:rojPRh523DbHzBn1z20nzxbEx/Gx17R2oAMlFM9+4Yc=,tag:G4sRk5rvaMZy5DjUhL3klw==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:L2naRVwFYkBci6QM,iv:ZnF7/CH3+lwe6UklijTbPC4EOd2qU0OPC2vR6dQWqVs=,tag:uZRDPAMEGnhJclQGbLuDPg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:tuNisY0yJ4LmIA9A,iv:Ps4cZuBmNbztQlryoPtsx1oFpy7dhqQYB1iOJiwb9bc=,tag:Rg1b04XlLG7hW33AXt06kQ==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:hl1ZihfARRoOD4Wn,iv:+RE3tIcAaeUl+kJlZTd+8Vxn7z1Bs+Tkua/vkoS9j8g=,tag:zvV3Q81yZt4c1uM0hIv/pA==,type:str]
    EMAIL: ENC[AES256_GCM,data:jbSAFUE+eiOkJo4WZLBUK0O20/4=,iv:QPRJjUOt8r2u7SwMJxTVjH5fGlfwq+Ncqfq8Bkv7WpI=,tag:J2ZFmZaauzDuFu+T78uBMw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:Mg78BKFj/CDHGhvA9KTEN6MZKL5H1yi9ky89OuZJNljbEyCD95M2Vw==,iv:XoYm9i+ItHxsNrSFgAMtPcHy5DFNKlEJ8VgdhYUJi+s=,tag:suaEUUL36YF+KewHQPNRDw==,type:str]
    ADMIN: ENC[AES256_GCM,data:82MlkPU=,iv:1UC1IQj1RIiY6yc0fEydEDepKn1ppakzV43JecCZ2qA=,tag:4w9PZix6JmlCmpVLlaG6aQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:E9Hh4oTAhw0=,iv:CfilPFh05Z+gY9R3PKZegigYFrXxSXd/XZnkr6APSuo=,tag:J3pESuNSuFRl0uQAsjGJyw==,type:str]
    VPN_USER: ENC[AES256_GCM,data:wNZ40R+6ilc=,iv:4t64U24BaepLt1XjbKb2IsIzg/98o4QSkrtMn59cbJA=,tag:ndrW/aGdkRzj19Ti4JCFDw==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:i8UFVimyjVBdsQ==,iv:WEYWkqSPs0d2KwBwP1+TCC8s8qWwrMEQQEL/DLWjrUI=,tag:O16qCo0JuvmRUHLZusUzIQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:oTAn9Q==,iv:L7RbOF0G5+3jRaEL8HsZJk6VFo3NoIXmwqf7uOrpt1g=,tag:YCLkSv8D5FiyzXROP5ytNA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdWV6eWRYM2pYWlNoMm8y
            aHVsTW5wM2MwTk1sVnZpZlJTM0J4S29VWDFNCnlkcEh0dnhMbzNDcmZ6TGJrREo0
            MnZZc0dwYy9CMTNTSE1ZK3VDanB4WjgKLS0tIEZXdHU3MFpUSDZ4cjN4bUN0SWY2
            M1IzdkxJcjhMdk93eTU5b21EcEF4V2cKaY9lbHkCcxPOE0jKmwgTj+sfPakUMuMx
            b+eqsnkk7JXEfVIi3ZHFKDcJs7U6D3bRzX2X8ol60VpUrPvY3qljfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T00:55:11Z"
    mac: ENC[AES256_GCM,data:ENz0HncvLIQBLEPZJCxTA8zJTmQUrAYQINYKYQZted90eSRl2Kw3gTs5s58w+4zFNHGatIEZCcdx07jEcjjaOEFkV2UvQ3DceBq8ztPHPzw17RBlJb9nFhmNekE+YTmDW5FXK/Q54hMuYp6Nn8Ixu5w9bMRePviM5Z57Xo0p0U4=,iv:IM+xiTeSJ9EGRk7N6+SM+uHVYHWg2TD8UX+vXn/hu5Y=,tag:BhnA03CWwqpgh7xXMLbKYg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
