apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:9JdwZQtgoWmrKTIb8HJ5p0LvRPUvQfDGpzPUE3uqXJ+/PjmDHQuSwzk9n+VxiDLI8/zh7VgYp8U+NS6SVYuLm3k=,iv:0C9JDS2EXtup7JnZl8R1x9AVM5DKW2TY7BbcvllebXE=,tag:QhfC3fXSNn/f+7StldDHMg==,type:comment]
    #ENC[AES256_GCM,data:GDJZ+6uQqQ39OHhQzBzf/869yKuSX9Yjd7TDJRSgN0Quu3KPDet+S4Ek2SU=,iv:Kh+Im90RUkJoxqWoKrPyAz9iOhzUimC4F14cvWaAMjg=,tag:tOEOQUisYBHdWsC5UT644w==,type:comment]
    VIP: ENC[AES256_GCM,data:+45XSf6sQIcx6V0=,iv:IviXdQM8+mt8R2zZsybw2/hjjTBMmDpFg7XlZ4coVeI=,tag:FjUzCG1GSlsNmu80/R4N6Q==,type:str]
    #ENC[AES256_GCM,data:Ocgsa9xbIronLnUp+8YjJZi5sR4fKnTdV00=,iv:wl1lUlcf69gnpuaEx0S0pE29Y6zJOpHML4t6/twpiW4=,tag:Caq+3Ce/ASXNy3AnnPbcig==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:HKMwzdxglVMkLqQ=,iv:TSS0xkuSLLMPpGjwM2P7fMKpLb6tlwFBy2RVL+qr2cs=,tag:YXRwWZlHpGTS50UhNClveg==,type:str]
    #ENC[AES256_GCM,data:oExMemTddBQjtbdDc4ZmT8E/0BIWeZh1BVIqH7giCiGDzQ==,iv:ribq0ZwTv4KrsX1wiARHzq83p3pEaawctAafJGDLN5w=,tag:pKASTmNJDs4SnlzJB5Zvzg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:i9352QiJLACvw2Y=,iv:U2DxWd4YxVu3rujn9DQbG0pApqWCBWg97bkgxf3Z9UM=,tag:TlsWYugk9XW3pCQ5Y+6YZQ==,type:str]
    #ENC[AES256_GCM,data:YrCVx1rbDWmdhN+X9DGKicm5GX0+JDRC8VVoJcCJXVyFqP0nQwGedrrmRvs/+j4=,iv:fJ/xKg5lJGT1fFAy5B2WbUJCa2Wv79IfOrg7MCrB0xU=,tag:wMiE0bY0c1hXmNgk2HTgog==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:E8apzLR22fgs5wcuqViLRVTcwr6znjsnrg==,iv:21+wfN5L9jxWTip51Gdyis2lDeh597UB/alH6quic2k=,tag:meMEr7boCh2zYFzpCqAIZA==,type:str]
    #ENC[AES256_GCM,data:eAxe7TS49QsvTMGvETVvL93YRm0lj/irgWaBuZ/SQoVColMlSfyePjIBlDlGwyDquDVQTwNaDKqanz2M3gHeaBy49s0llWHzOkBr+vJ9mRM=,iv:Ab0edous9yi6JXglNBHENAHns8gH/agNSB8SEo3fLNo=,tag:G47I+TnyT/bTQGnq/qovnQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:AzZZOPbUkwVduzI2,iv:597AS1OXDiTrtlviOweLhp6o58Dh/QC2C5KljcSaIsA=,tag:ZG0UZkH9G3fhF6HZ5uH8bA==,type:str]
    #ENC[AES256_GCM,data:H88oeY2YVvidgE7Eyf8aTfDIuuEq2F9/jR/5LwyNox50YMOhF/Ge2aRuJf9g2B4wA1aoQwjKhIg=,iv:d4v2Hx41ma87DiG47kmS/U1OHU3lMDz+wzXO4O6Pexo=,tag:qmfXON4JKGaCF27PEjeBNg==,type:comment]
    #ENC[AES256_GCM,data:RGtnxjTOzrsm2n9u9tdp/Ekto7oPa8l8jA==,iv:XuLi+zzpZjdw6VM/Dr+/7cNjpYWH16ina4Tzsvjefg4=,tag:pWfVrPDWGtgViRICGlHLgQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:KPTbTA3r0I0pP+PQx4WKK98Lvosw/Gb4Fn2PokRGQe0BGIMdOtsc+10vcQ==,iv:tJ0rQNBviiilKHFNiTvn2687xasbPKgInVbNC1Vxjs8=,tag:nn+APpvwMhn8hbfbsAV3Lg==,type:str]
    #ENC[AES256_GCM,data:31gm6CL+K9G1xJZvBg==,iv:r1pUgGiVhEZuU8gvuyzMn565EUIXzTqjH9/KPWtmN78=,tag:mekAy2TEg4jr9JRhTnIbfQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:npxCWMduEhM4oCKjiw==,iv:1/qGgq0Iz7pNQnJG+y2Xx/wzhwQ3abgxUEfpUNNgKpo=,tag:juRG70W5Kv72gcqRNiqRUQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:WtQXwWSYcxDXfgBcKA==,iv:P/TpFKvpl7iT9U/aJSBcPpv4jR7gzErkyqVNY8kKs7s=,tag:F/hWMpQNWC82W4vALx1W7g==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:QenmjNMkdjEKyo4yre4=,iv:6wthCtdONIIyoz7tgOae7PjPfU++QdQSy2tpQMk7JHE=,tag:EfHdApadMiQFcyGGnWawyQ==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:JApFYZfTzkHx9ADw,iv:1I4hLdSbo8TUlHgtUth+HT9eeE6M/AmzT9d7A89TGmk=,tag:xfESrDnSLR94IffPJ+OxMw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:EKOUAw==,iv:sQGGrEVkAslgYUtAsu7EJ5sSXRbGXRYHO3yjRLgCBt0=,tag:21v/hLu4z3O/un1EJ0jcuQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c5g23qt38utyy253gvf729w4l2jnj7pqn5s00kkzsw6l9k9d5u8qmkvkwk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWkhuQW9kaXZjMWxaZm9H
            b2ZCYm9CUnJRbHpWUGd0Ryt2d1pTOEZEODJRCmVhNnpPVmVWamVFenNaR2tTaWJY
            M2hqTnQzbmJyVTBYMzdKWlpHd0w0d0EKLS0tIDl6WUVFamVvdnVZV3k1STlJTzlN
            WUxjakhOMi9QS3o0alZRMldzdlA2L2cK5L9jSpOaeSiOKX7tIBXQ8mtb/HNbC6oQ
            GlJCkARMnSNXsxj+w7O3V87BEm9XH+uAoJT3sjvPkM9wkTV/tvc45g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T18:17:26Z"
    mac: ENC[AES256_GCM,data:VI34386+lX6AN12NdHHbIX1WWWAjyVWEQztc1FcGF/iRbUSRfJgaLFalbdajJ3kBAK4Nf5CFk5Cqr/byVhylZ2kolP1OvRHF5GDxBQZMGVJ/rlNWuAkMY+vtLrdLxWqxXdmzkCCcfLyBPBdvhWredRrKJyojBMGrsuQvzTVp7I4=,iv:QXa5olUd9FJyYQKcMXWX/Rz6WEODLApQrT3tksrztGs=,tag:jnBQcBliYRoMZqSTY2aW9A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
