apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:jpXilxZICYskOozyYjj4M25R7lMIzOvTZVw5zlgbeS80kqUpJCAU0hezEr9DemrREAFo2h2mIZuZ/L/5o4iMcxE=,iv:nWInOutWpQ0gpIeZ6LUBzj0RqGsL6Z+msRQvRl28I0k=,tag:L40XcPNme3D9WBI+Lq8qxw==,type:comment]
    #ENC[AES256_GCM,data:qzeJvNpAK0kbqBLMZkiFujCZ9koy9yAbx/Hup9KhMD5LY+tDDrKYJg3ataY=,iv:GBhIFh/2nQFHlNW7hUrkw9kRnNAf5XiqWEnuPbqTiUs=,tag:vnII63asdNO1nwpFISW+VA==,type:comment]
    VIP: ENC[AES256_GCM,data:wJWJsf9gM3i9JBs=,iv:QzgVFoKSoEdt/L91nnSEyUuJf+5xhvdGsCLcN03U6hI=,tag:78/4ZZdKMhR7s1sP26NuCQ==,type:str]
    #ENC[AES256_GCM,data:XuRMshOEjfV8cyDMUVLfWZ4MiVWeo8jGfA4=,iv:Psf6diMvl11KPsP+8l0b1fQixdd+3rwRtgSwVcHGhs0=,tag:a0mfDMVrmMqqNwZ2WpX+AQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:xb1lLZJslIkkR+0=,iv:Xaz424wyvIvDJeZ2lKKPJ08qYSUteAMetupgA5ZSlrE=,tag:dMGg2MNrrY5mUuFrvWIKcA==,type:str]
    #ENC[AES256_GCM,data:4Kb3FtkhFzs8J80EsCVMZRvkgOzEUKuCxyv8l/3Bs/5MGQ==,iv:en77LtU+cw5KxQ9eKCXzJZJUu9DUWs5Scu4h83vqQ1U=,tag:kEuV3xRp0IWDlX6SXFAC6A==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:L1tmMV7ZSpIO/SY=,iv:gtyti3mK869TWGE6/gp2s/ix2XT7zGNQybc9nUXATO8=,tag:HKwJW3VO/cWtLBa/JuZV8Q==,type:str]
    #ENC[AES256_GCM,data:LgQgcdNT6tT+9Z08SlJWo7yDQwsiEbg5X0PSvZ2tMEaN65e205+TSkOobFQY8Ro=,iv:pdq5CT+F3eDD+dGu6LxTnW/Oox/ZJTXVQ50EPGoecBI=,tag:W9XACkdcpBAvXOp6A+98FA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:jFdOCpnI31ZUgBHxUt3WS9vrZPueacNh1Q==,iv:92Nv0Fjndk7NysYfLs1jk5+3cUynHdddEhj7LNArbCY=,tag:UET3fR04U4qv5wr7C3UrGg==,type:str]
    #ENC[AES256_GCM,data:ARu94Q8b6jfKjgpCrL3WybqRKBUfoknBoNuzvR4Dr2x40c9t4QxYfKPNVuwBY4D808D3eoAJGQgd/fKW9/Lxm1TsZPDTbK6KyhLuZx+YZ1I=,iv:F13EUdQpt+rfj1/uZTgJnO0Ks4N42lDN6le6UJRiY8s=,tag:unwMbJkqnLDoWERjWlJAww==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:8QE+3i8fQ4Ou9Waz,iv:QPonvaodZJlguvvHGou0nIjR3yMVtn3uCranIdyhcxI=,tag:zPfE4PtjqzLMzYrXZc87jQ==,type:str]
    #ENC[AES256_GCM,data:IJ6pCV7DgRpkEv88yyjcljSA/q/9M2gYkIIM7cdzvLHNCcekhii1eVDy9CCxXU1+0HNr35WZ5ZY=,iv:ntyQ6gH2hyICCjYehWgL/L/Ah1QfOiZXM77+hmdqGXA=,tag:fj8AJDvJAnzj7uGMWDVAVw==,type:comment]
    #ENC[AES256_GCM,data:aBmcQsfiG66Na1cfMZ5R1hsMj+aebl7AMw==,iv:w+JhumLGMsuxaK0awgj2uq8MICDKaxoUnZYFV+2U3g8=,tag:YyuCRe3f6JXi6ire0rOmEA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:Z2M+RKKGRB5VnGLRBrpN0HsTRsgP2vDcZ1NE5qu67axxDsdCowofWOARXg==,iv:Ar/2/qLh5H5Y6s6aZMFJ8ObUz8TBzrZ1OvE6qA3+/u0=,tag:bE21Tf6Yte2dlt2XykXibg==,type:str]
    #ENC[AES256_GCM,data:qkcexlgRHyyh4TsOuTjCnUIcXGua1MQQC9P7kRa51qJhe50nmZPDg6Xza2jxCeSw8fOaUDcNCF1Z4nVX2d8cZuYfOZ6S+B0=,iv:Q6XvVuvhRXdN08VBVuoVkwjMkk5OvXaAReYQMCUOvu0=,tag:dFDblTZur53cKr/dllKh7Q==,type:comment]
    #ENC[AES256_GCM,data:26HCXG4tYIiPgZmOdi5G641+zya1l+uYoG772hyq+wanpmcJhMAFTORIT1CagQ1+TcoyYW3p,iv:AHRcPYvHoVAwlQ7wWk8mMkj2VT6JthMTXUddwh+E4Uo=,tag:30YSYX5t/Uz+liKqT6sLow==,type:comment]
    #ENC[AES256_GCM,data:yLa3U1jYMrcFAG97iu9wVPFmVRPN3kvpZIqbM5eYjDPvKy8=,iv:J4p4AmeQm7QuwkqblVLBnB0Ph56hnmf5+ICJ1pnD0vc=,tag:l8zFmvqyjia2VtSIsR2sqw==,type:comment]
    #ENC[AES256_GCM,data:iVVU1J8VfgxVhdvXJprGZnTVdR3rmLytG0QP3nil+eUBnq56hMqX,iv:w/hy2jOgL2lv/DDz0HXNDpDYWBGKFJ22P8EY7BxBhdk=,tag:sOEdkgIZpPIK7cXuzD5bow==,type:comment]
    #ENC[AES256_GCM,data:ekfzYvdS1qlbVoPCN2k=,iv:jIkJkz5xxDF3IZhDm1b8Emw2EdiUIdl2ShXDEPnLn/k=,tag:y8ier1S2EL8e+Ee9n7txGw==,type:comment]
    PODNET: ENC[AES256_GCM,data:4T5hqt5rl6mGxIgZkA==,iv:N6FZpO6EviOZiKpcAtOfY9KToWNGUR3cwU3hYn9059U=,tag:QSSclgnbCXCT1p6vLEoaew==,type:str]
    SVCNET: ENC[AES256_GCM,data:9AxX3oFShbmOvW6IaQ==,iv:vml7UsoexDyUsbb6esdKFzfiof98VpVhHqeU5iRQZsY=,tag:Uoe5frnK/11ugNFKrCN1qw==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:rGZmcxqZgXrYfeBE,iv:tHBjd0sY2461ZflKEclP4XCA/eqfnJXb5Kpq4Py3RRE=,tag:Ma8S4kz5sYzTDh/kLDAPXg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:larfDze9loNttb3M,iv:l/w5VathmE7wqG9yxm5ZZM/3W5iXOjSrgW9+bG4MJu4=,tag:mI+hhjtkguTk7gA4HQgUhQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:Zx/zdUbJ67J4lcxrduw=,iv:OSSb3uGgL5wWCsXI4dT51nIxFFCHmDtKjpHKqUd/Sl0=,tag:icHbgwqQmJNU1FluIOlj2w==,type:str]
    ADMIN: ENC[AES256_GCM,data:mqSvo5U=,iv:BeIVGPz3r/8vI5tW9b1dazdGEQkW7jRk4y5jpkMNT/o=,tag:RZEBzLTZ0uQv4ggicKHNAw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:5r6A5ciggdQ=,iv:LXaM9/yBLDXO3Q1qIg+VraIFYtZx000pAlGABnaj2Qg=,tag:/echvzLjRAV4Q6CBf09mDA==,type:str]
    EMAIL: ENC[AES256_GCM,data:8wsfGukLE9on+DyDTiwS88AdYCU=,iv:lB81bTJspSIfoQVsnwovIIJj1cekCQdkFgtpjGLY16w=,tag:8xQAf1lbSGM0pDleh5vkaA==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:ZA0FyyGaS+8pwY1DI2gnaolZgl5EiPqlX0aLd4IKT867ZzzRTCuxMA==,iv:GyeWe+aZEv+hPmgINnR6rdAD8CLwMR6S2a/DyLNi4D0=,tag:gMEp7J4JJQYMnJEAFNMLLQ==,type:str]
    VPN_USER: ENC[AES256_GCM,data:0IkFci6yy8w=,iv:HZNAtxzYuzTLxrx8LXR9j8CFXSC2W+K4XFZ5599Isfw=,tag:1dZ8oT3uuOXPRhPoMnuN/w==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:dyd2zlot8yigDQ==,iv:kDv/cZKLbc67ZiziCaboT5DLlFVYUAO9qCKWRyI9RpQ=,tag:WfwCISxchuS3DWl5YQTYdg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:5bo3nQ==,iv:U9fl/PWrPmzNm7PY4fYx+nY6BgOkYaqIN2yanna/iKM=,tag:7kg+EcfCxTcmpM21s9acVg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caandqrgue5nl44eylp4nvake7znrvxretz3uy3r0ccfa2av4aysejcgfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NVJiaUZzNTRsaC9MYTBR
            WUJ0MWNZaDVkbWszdTN1NlBTTU5ueW9DaVQ0CnB4bEgrVHFiaktXc09VaVZRUVRp
            SFM5R2s5NEhZVmZ3ZFNxNkhSeXQxVVkKLS0tIFpaYlB5VzErRDJ6M0pFOGVPNDkv
            azNpN3piL2lrR01OVzhLSWFmcDgza2cKnO51fqO0TtB2THsqeRjNxXDK6tKtjG62
            EsFjlKnhzPbGUnzgCZ0pETfHtWuM7a0L3Z+QYE4RujCgb3gzF3SMLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T15:17:51Z"
    mac: ENC[AES256_GCM,data:XOuls6rHRuP5BggnKu+IsIJa2OkujeuohDpyy6slYPRFo40F7SSJ1JFIMETFGZQIqbrSAibhpRIDZHkTX+rz0yYNdjQJT6tIb0NLoRh0iyezAZ2YkVdlEp1nHtbAWAi17R8cQeamudVrJd5IwTgrRpVa6OgFb3ClXTJaZk+ATMM=,iv:LXU7R10foyBno6E+ppxZXYZic7L+xywOL/KLz4DzPCo=,tag:bq8v+ipBu/UttAFM2xHnuw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
