apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:HaZoTxK9fWadqdTjuyc7P2wEAvOD51hsXPRBLlDLeQNHJId8vhXEqcH8GNsg0fRVDieo+wg3KupEnriwQCOn70s=,iv:6F8SSQGv/e9Gp4QvCdkKbE1UqMyPwvBfPsm1oWycSVc=,tag:QZD3k+EkkL63dZsejj/Lag==,type:comment]
    #ENC[AES256_GCM,data:rZpj8RhcQJNy9aIbcTMuXxywOpxoQCDyOmUbo1KLe3fyXXwb/UcJe3GZiIk=,iv:R/RV3hwuOt4iLQxywmXfLubeNusYlNH5oxVUnCdFjtY=,tag:A+IHYXgDhSw8YbqoQNBOMg==,type:comment]
    VIP: ENC[AES256_GCM,data:7F+mtjQsaoqKTDY=,iv:qVWsQw2kaD5zACr28Q1FyP4r2oAhUp+mWrnsIYijEYw=,tag:FkUFz6G0Mu6SzNpuhusM7w==,type:str]
    #ENC[AES256_GCM,data:r/KnWw18g6jUz6+oJMjFnZakZi39xNSl/W8=,iv:BWvMcHybzDBZQ8uyDhRKgclM9+epLiV7RdjcI8l7fek=,tag:B8L+zqAG6zYgcHlLukYB6w==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:+uMFqVo97cpdfHA=,iv:kKW2yre8JnLLlIXBrWNn3Q5Z/vDciTWtoDmYdKqwKJM=,tag:vkLj/HNLis1weHHZyS/E9A==,type:str]
    #ENC[AES256_GCM,data:RYHtDe0omiyA98w7PM97MIeUJQl74GydYP22nah8RCsxWA==,iv:KKIwLdfMsKOiwYyb+X104IWRnbxuj/CahP1u1KZ6IPg=,tag:CrLR0EMucu+LcKyk6cAPug==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:4cFVNKqlchM/K8M=,iv:w2Dag/fbZ+11JnlazORiS8GEMugG+IrAW+pFzwyXS40=,tag:toIF6FVNl8ATupARQ8FONA==,type:str]
    #ENC[AES256_GCM,data:6B6qGR+OIoKTYVPgJyGpviSdPSJt4VKE2XsaTsjot6ntAvXoIaLnZ2y1AzIHkVQ=,iv:uanb4sDAV7HP4OTJN14341zeImGaN1dHKaJ82T+brfU=,tag:lyS05azXkD8BAoJjPEDTsQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:RHSDMWjX61pJ7ospL4bMj/o2OiWVLcSZXQ==,iv:GUGjACedMpPuwWQftBgVQNV5yL8wR4yib73p0D9yNqM=,tag:dNL0xMSGKjThBMHA32196g==,type:str]
    #ENC[AES256_GCM,data:LIqDJSfNsjulzbF18idwbkdnwUsO8AS2RyN2Xc4uTkt1NnSXj02QzO18I/KVUm4BxFSDf9CS2fU9C/OWi2TzzQ54AfKBQVoZ03YvCfkc2YQ=,iv:lvgIc5Tt85Zq+ZxPZujoSsNmWvVf68LE8S0cK3WRXXY=,tag:JU1fS2/NjqUsGa5gONNxrg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:3oh4kXggImqkDbnv,iv:ogBZVKTCOOyqY4XfQNy6hEGEukbIR0rkqjQDNElfbbU=,tag:t6vXeEgLN6NivdXkXeILCw==,type:str]
    #ENC[AES256_GCM,data:UJda2FgvUTp47jvLSiigVKWDF31sKlbH+xzoy3Chkj+we105GAy1h4AXlb7OSZkrM8wqu94VFbk=,iv:bhrrJIN9CVZCN9kU2AqoOxk4YouCsNMUBZhGEK9PCyk=,tag:aOt7cDIGAy2WKe30lcERrQ==,type:comment]
    #ENC[AES256_GCM,data:LTWv2OeLeN/+kVoISkCTGawwMFhDo0YP8A==,iv:RVNuXHseUOexE5nmOTfs1GnYttMm07F50zXg/48pCeg=,tag:Q14MdXAJ1FwptglgNuIFpQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:eji0ueEtrUB6vOkP/bp1zZJlRfrKD6FysKzHLz9KFsnQ1l8kPHKTzEUOsA==,iv:M99p6VVFTWr/voeq0dkDlJIJb+Svinkoq/Bk9jGzANg=,tag:9ZsupzE+sI/iY3IgItuWqw==,type:str]
    #ENC[AES256_GCM,data:KeME7dFGC9T2O1iJfA==,iv:2c7LgRj2Ld6Ln80z8juazagDocqqeK4YCe5i8IVi85E=,tag:vgp15I9nRODGCjBoW8HZjQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:29ECa2zWNnMky1XN/Q==,iv:0RYZpusJe8tTBdeSWkkvRUFXTn7VVBLH3ew8XnKc4Cw=,tag:nk3gXYa0bHNP8RJjmmBm2g==,type:str]
    SVCNET: ENC[AES256_GCM,data:pND6XGa7hpwFahM4mw==,iv:7ymHv+eZk1usQ+wgUdgp6+2OpTaBYo6k1wAbpbmHETQ=,tag:n3xmOvMWAQliWoR9743Xzg==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:KtQ7Yf69morKjcObKYE=,iv:E84mHjuKLapwi/lVPzAvyIHIkWE4BA3EgJuvi5XY9B0=,tag:bY8N82PWoEnNxrG1KOEQFw==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:KJpfIjTZLgt6tFmp,iv:FZO7UPnN6fzhY2ywzC5F5pwUq5JsgZXP8/glsi6+QGg=,tag:7D1CrnPAYFcQRbdw72TJ+Q==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:LdxHSeUGjEkCNdlz,iv:z9FCfnoI1v8Ozy36+ZpedgQXwugZf+yLb7hLfgbE1Sg=,tag:mYYAKA92MC62y8i315lOGg==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:6f5XJZSe61a9j4TU,iv:a/0F1P0SCwB3HjV67TTtKCVBuJ2mMopXyomAq/kH/40=,tag:Or1/65dMP0TgkdXYX1oHmA==,type:str]
    EMAIL: ENC[AES256_GCM,data:hWl8UW1yNKi5BN+k8ZIurcvis8Q=,iv:jhPm46jn5ylcWp8447Igm05UvA2vKapWqiHnKsbUkv4=,tag:724qYCJWn/LuY8BMgwEFAw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:yFsZXB/80A9pFq6z1+U8JIBfpTkm9QVyk9b9irnrH0qCFfFaF86HLQ==,iv:pQJnECPFzM/PuNRqr3bVWXbOk1/9InhQU1+alSL1F10=,tag:hIkjviC1e9cRTBuUex6dZQ==,type:str]
    ADMIN: ENC[AES256_GCM,data:h5L+KEk=,iv:xuy+QozCbwxUerHMcBH7BopsD8oiyJvjpdbbguh2BqU=,tag:v+Uo0CHUPDet6bYfXSHrug==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:P7PSYF4rzbo=,iv:z6kC4gHYuc5OdGJL3Y/KD0QBL9uizjBbs4a8QIqIcc0=,tag:uZ8GGmqfykVD5Q0p5K2wFg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:0h4RIg==,iv:6EUNXD1VVdNVNnm87pSMPVsZGQqUJ/9a0bWuTfgbzek=,tag:7yR+Kflfd/6WOVKxw46hOw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMWFQOFQ2RkZGWW5wd2Fn
            Wk5UcWMzL3ZOWUc0NW1jNmJ4UHZWcHhWYUZ3Clk3ZHJJYlNuVlE1TWlpcm9TLzJT
            YTRFT2V0aGxvQ0VGanJiTXdPV3lwMlkKLS0tIDdtMzBzUEpRYWlmR04vUTl1ajBD
            K0hueE5va0QzakRBWWZ5d01naUJEN3cKjqOzSntraagQMRZtMwkN4Ugd0dbU0iYu
            oH4ElY4oH6ezKejsWeHwkUNZWIUMs6jrWPdoIpon+xrnmKDTYEpm2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T21:41:08Z"
    mac: ENC[AES256_GCM,data:RbTLFY/9NQ/+qAKY9nHZqOtSE1jSxNhE4CatUQnVXO6Ixa77uHJyUDgC7ds3I/zYYxaiW30VOYo8IkTPtmWGV3Qlrk9n2W2o3Wpejb9/gLnpEu8KHY52O0giqf1RDjcJ3klWMLyF5tyXPNss5fo9XI4Zc4E0E+JvzAa8Lllc4gk=,iv:s+NqKLgUDRp140RmLEiIv7B/NO6ZN0JNE6cQhd8gIIM=,tag:ZHzkKTAbUtHJgQAvyXPW5w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
