apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:UjXztXMvqDXqOch3CfAfmWEQpm2m8q79Spvn+14dabBd/RNEQycrj71gO5zewPmvNKs5QZPjBqo1/wqRDDExJwQ=,iv:mMTCiY/2vzlxVrEgX0UVYPrko87gVmAwYln1aJCgEro=,tag:WKfmQK5wrkqEJ+b1iTvd/g==,type:comment]
    #ENC[AES256_GCM,data:n9USV7jMuResF4Y2tlwT2vr5+8jvhfvodQoSgoJSlDljdvGvx8joqT5VKTQ=,iv:+5QQJLoHOizr2yWCAafN1Intzi+mh45ejFvad5hcOXQ=,tag:MubjkHEm2y06f4co65mClw==,type:comment]
    VIP: ENC[AES256_GCM,data:t1oTviE/za0vOj0=,iv:H7j8WbdkBqE+U/bUCi0MZT+kmsEOtDiSKfTOEQqqncs=,tag:5ktjJxo0GcUPljpnAqUU3w==,type:str]
    #ENC[AES256_GCM,data:UbVieKRLHEp/Ik3yQAxnAcrOKhq3UWKYG4A=,iv:UgzQYTYPVM2m/LIiLjdtPTnE5EPmEcV/p5pFsCk1GuA=,tag:8wiPdj/7jjU7buiiJxT0SQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:WfgdmOVspd5E1F0=,iv:n/MEVyF3Pag1IQ8TQeJ2Bowor9b+T08RXQz7TBurFOE=,tag:bR9LZitrPvwaeksy4EmpGg==,type:str]
    #ENC[AES256_GCM,data:4ewrmPUQ8HvYppIZcJJhd/uPwR/VVfGRDdHqrsnUgS8nuw==,iv:RF5GUyp9eCs+UIYMsimwQuq6g4rB5G8nOcIn8hpu+VA=,tag:k3opMddGxU/hD7twK79UbQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:wTfri+6fkf5xDLE=,iv:K51wKeHBOxRlcrct+m5kL8LuDMUqrJ10/MPBjrrF/sc=,tag:2Qz7glapfXsAAIIO1I3Kmw==,type:str]
    #ENC[AES256_GCM,data:EeYnASYZtyHBZIWKHqqexmU5q+r8qW8C/vh6BhbSI0q7SIha+PFaowLu0FK04ig=,iv:3P82RI78P/yKAkFBG1gf2FKdUhYukv2eoFxiDvlnOjY=,tag:gIThaxhUhJPQIMu0voIdDw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:1PU/xJT67BGHcDnbEJ7rXbfN/K8oiqplQg==,iv:lNhA9Gf1nP+/axBOXHdg3lp6nRDhYrum1497Db2ylF4=,tag:OY/gPPDVDJXcQd2vp5OFIw==,type:str]
    #ENC[AES256_GCM,data:0lXJYWkMEwt09fOUs98KKRVlEDAUM6vX4fsUYI8ZMDEvovaJtv/ns9JU/rUa1uA3zSgN4bmxkKi58H2Trv3qZ6aO+ramDze+TxG9BWweeq8=,iv:oKMOJiotVdDoVW3f36mkcApd8VlR0QZNVIYUYQkNkMc=,tag:VbESjM2/twnbhwJmqID0vQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:ZIRfWM2yUFC4z1ch,iv:NtxujxQ8qKBLx1RBpkH9mvyTi0wGLrG9rSif983ueG0=,tag:j4f5GNjW54c59MDXKcIjbA==,type:str]
    #ENC[AES256_GCM,data:jAxs6DQ8QGieF6egO0tOwI6gii9SfyVgfbCl2TXNECnCuzfD8eLWHDlUdUxWSJ39vZjHsJ4JaQI=,iv:oDkQpZaHbk/Y0qOo/M+XjGXlTalZfQrnevCQb29JGtU=,tag:SsBLXSF1jw2prSmiAbS2zw==,type:comment]
    #ENC[AES256_GCM,data:pjpjCryUkBOkDnNZcvJDPQ/hmC+Y7Tnb4Q==,iv:8a5/jtjnG80NUNGPSsn+DL2ZcFs+OQ17BXOQxHbxb4E=,tag:jG8hWCgj7XaQBwRRWrpAEA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:4sK0dgk0p8isgDdBLSC9UA7vlXECfsREdDfTJG+O2xMAKwVSH31c6vMvFQ==,iv:PNdXz6eaBpZsi5oLjBIQ79/X1X8/IDT5iqwgrsuCW8M=,tag:hZiBfP1AUxHj+VVpkCF+Jw==,type:str]
    #ENC[AES256_GCM,data:YH9CdmO+AtAxw+98bg==,iv:LJKnhQQDC39HVa3RRwvGE4C8KNwFf2281teaTPFHGeo=,tag:TO2agpZZE3Nt6DQ0qkXwZg==,type:comment]
    PODNET: ENC[AES256_GCM,data:r+sM8vNGZmx8unyPJA==,iv:Nrmf+fgPUfq6WGWIFZGti+cWhNhETSboc7lbftuMWWI=,tag:bOKCRFI3fpDWuZKaKqa2LA==,type:str]
    SVCNET: ENC[AES256_GCM,data:9nmww/TzhrEvaTr6RQ==,iv:lay9kB2LdHDrqnq5seWe77yJku3wPf3wwPrvaVB+gxg=,tag:0lbQ+bqPve9508jLZ1M8/g==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:6rJRDoruNzQ1zVWl,iv:1NRa/2L+p9CA8+EDN6tim6MNXovT3F26Exzko3woSj0=,tag:YfkPcAeIOIrcwZzly/zXjg==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:9rFxUtrXfb/pmqSC,iv:7AXbzcUQiQ9AzBFZRLdISNNlj9BVgV7fPwPRekB5JIY=,tag:PXWbGFQE/uaHyC+YI0Ch+w==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:O/hqY6GRM+t6O5XF,iv:VlG7XcWHL3vLTD5KooVlxQBjKQmvWTekMwcydwDWVr4=,tag:WnUL2uFPGIdBQw7uqIFmrA==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:V4SrpYoMYF47XfIjz6Q=,iv:bYNpVxXbO0EA5pYYxgwF98Qz23ObZk0Fd2XSKu2fmlk=,tag:fvg+JWIbuM6Zs0nz74Z14g==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:z54Iag==,iv:AIHyV5wMoO2Pb1fRoOPLgNHPdJztB3uI2XVlMxS8l8c=,tag:97hUP1wC47hpQBfwT0c/gQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sc7hlwrp6qa6h9afyg34fhmn8qgl2r3rme4pf3lant02y20xr4jsts080r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdDBSdWthdnFoQ0ltU21z
            UU1YdVFqS1ZzcWVMb29GK0dSSlFjZ2Y3eG1vCmNoZTN5NGVUWGhCNnc1c3o5ZGJk
            bzl3SXhUM2FObFVTdTRtV3RZbGxmSTgKLS0tIEgyV0dlbjFZREkzVEMxaldVdXA4
            RGlZZjg0ZjZDeGF5OFdvR0JjTm9ObkUKQNXiaFPzGcvFn9vZLEtZEjMWcT1xrRZc
            buo/bXM8986KJOgRn8lXV/iQ0o8EE8lTsnuZ7M1ZhKYUugJDc4o+Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T22:17:40Z"
    mac: ENC[AES256_GCM,data:gfjI3LVGMVO6dtNlHLwpG57N+kZBcQkhiZ81P2acNc2NQRw1uw/8NSwL6dybS9Pkw9N1CvblgBVDZncqjp/r03y9jp4HxbyGHav0ahbEGLE+KYCFMsWEIn48R9bLa7/gY+zg+zQi8wvvrNTIzjP9Cu8ISAZiRShTlIUXF91vSHA=,iv:7x9Qa9i7V+sDKO1+eo8euHZ0XglyPQMLzky+cioat2g=,tag:847I4v+08cQAfaiKNJzP+A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
