apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:P68XlhE1lITBkFYIVkQ4/HnhVSlKfLAWsD55mFpQufRzYD2dPiWSS5erPEiqUlvLv57o9LdG7mzpawYTFZXVCVI=,iv:nlBfvVtumeSmnQGkchNpuALlJkdOf8QmfIWva52vsQs=,tag:1LRNBj9rUl5W+6wIMvfVBQ==,type:comment]
    #ENC[AES256_GCM,data:WmI0q2bNRYmngP6+PDdfTR9fnGASfukk/U0ZCFu1iy4KUZQ21yDwA3IQpbA=,iv:93C+jLIGgIfkoyDIZ6tuVP5q1KKZB0ep07GpNYLzgow=,tag:S56xzV14tHo+dFbgSKMA+g==,type:comment]
    VIP: ENC[AES256_GCM,data:HuV+I7ECAqvzEdY=,iv:JwYUWbuQJU3Sbkl0+pu/a47CRvZRgfBDtPs+3HJDKFQ=,tag:oRTsGb1Bm5WVaXO9OjP0Xw==,type:str]
    #ENC[AES256_GCM,data:6IvZo356gHKtFR6utlqPDDwxbM/MLcwIcPQ=,iv:Eim3GKWgLzSms6Nj4T/nwR6y6EiU7N6oXgfZ7azFfvw=,tag:gd66Sy2YWieF9Nm/tWGkfA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:hXGpMKP+S3UV6bU=,iv:79gfyeUxlAIMmDzCa/d+h8MqMuMAeanjfwvcERZttXc=,tag:U4C6B5NoflEi3dURXOTGdA==,type:str]
    #ENC[AES256_GCM,data:bO89dkhwxCmchOGnq/gyQNambwfgVLW4D4RBql71cIDkLA==,iv:m6a4g1/4KeulcneRvt8npR7WUfD9sK4+De15SzPjOS0=,tag:BHXqwMx/Gbjq+7kVnQW+og==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:XiiZdLwMV+MupwE=,iv:3OhJ4kLr+tg1CtmVLiOCX2/T5IAo64H5U8H+z0aQajE=,tag:I5iDnUwl6Uogniumc/1PMA==,type:str]
    #ENC[AES256_GCM,data:qkiEhls3DgVM5o1/Etk7SIxPrIt+eEV72yymje08PZhEOWREjvg+toRZMOgIHe0=,iv:1rZ4pjHsBW7kVUIJfDo6LPGAQZA1BgRp4j8DV1GWU84=,tag:hhElbjiS02YFVGjNnuCWww==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:QKdY6IDhagn6VfciYfa5abRZzbkGyHg2Sw==,iv:cvDrowq5vPURDThAHN8c4AK1EOKBAY9DRSGlxgAPdFo=,tag:CH1XYTvu9uPnPTt1VxZVEw==,type:str]
    #ENC[AES256_GCM,data:7rdldR0dbmAD/QUmLRBo7YgLlSoLYAs65NO4qkifX6dC4lDxT5XGGk+8AZRnZNuJ0ysEq10ACnVTyFtNROLpz0VOlL6JJLlclOqypmoZZew=,iv:Tvr9kiHfVabqQEe5iSdLd1MvgGDS5NCeEC2xfRKRXvY=,tag:km1suOjbktGXUSgYIwgOOw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:SF9Det9kkDaw4mlR,iv:tQ61iaqc5aO4lFQwyu2CvXi5r1MTn2NV5Qtpc1lNL24=,tag:IgGhl9wIYywXg7gF2b++uw==,type:str]
    #ENC[AES256_GCM,data:TpueMCi2JFno/RYSmU1aLEdMNlDlfH6lVt29LXdPWWYtwsbQoyNXQaiZ0KcadTn0pBhzr+48KOY=,iv:VLBlRaYwIJxZF05sPXIUFHRjSJ6wC5b5TS0lGafCNsg=,tag:GUTJplVk4spGLbP9BdvHZw==,type:comment]
    #ENC[AES256_GCM,data:c1hEsUtAIbT1l6U68NuKvUS50bLyy5nODw==,iv:0/xOn0Saz7GX8oSrlR/0T+pZoi/3RFyAW22+kkEg6L8=,tag:7C0tA64DKfq5A5rhHhLgFQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:wqmhZva4ZLyrXrV1pLn6XnUrUj8B5p2y+dKFFbe6BsllYSS2GxwYhb0Ajg==,iv:KtET1O8rUoIv6FT6X7wARAaA+NP0/D5VL/Bm4XHDa/U=,tag:rkSnZ9tudnWPjvsIhpdJ+w==,type:str]
    #ENC[AES256_GCM,data:mFSNA1Acx5TlN0eUCw==,iv:C7WOdl2WYgDoGHcdswQsn67d+830XmopKJSu28kiTAQ=,tag:VyLnmpcexd9gYinSrjUdDw==,type:comment]
    PODNET: ENC[AES256_GCM,data:oJGp6t2UXC1N2zSt0A==,iv:SL6Zw87F8E9iy5CHCvWr+CgdQVkVa0+o8gDSas55f/w=,tag:PB/z8afeABQPQBW9UODBzA==,type:str]
    SVCNET: ENC[AES256_GCM,data:2t/pq97F0nLLMXEfbQ==,iv:lPJOkW4NPQUKvcqcVxfvNxYE2ZDuXMyqR2hPcIuM5uk=,tag:9AJ7nBYbZQELrRGZKLsJrw==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:F8ufDUeP7HtIq27pSYY=,iv:9nBNrIT5okAYYuiZMBsH66exxeALq2xtWP2l3aycMmI=,tag:gA9o5W8BZbTlY2/BK2823w==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:6dETFin3h028KkCP,iv:FprDajvC7VzEhSNAip4ngDKSrVL2Jyj8TuyhhJYEZbs=,tag:ik2nQLUkobqgc6950HceQw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:wLd7nA==,iv:W5kSFIHw9YQdg+lxm1dBmKM7jdyh0ByAPdTQEgdkECc=,tag:TlQCfDPCe17his8oJ+1UCg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c5g23qt38utyy253gvf729w4l2jnj7pqn5s00kkzsw6l9k9d5u8qmkvkwk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZalFmUWR2ektmeFJGSlp2
            T3ZLaTl1bVVwdElnWkVKd0dnaUlRU0tHNFhFClZ3NVY1cHExQnZQUngxVUxJNVQw
            OGNtMkcrZVhWWVJlZ3lwRWhYdmJQcFkKLS0tIEJvMGpEM3BBVlNZdVR5d1pkTVJ2
            dGpwOUs4a3FwalIxYW9mVzc0ajBnMUEKQrtYQBccqaFNI4hAnqcRyKN66jbdLggz
            eUbFfXojg4kVPA6Xsy+9/N8PBggWQcBh1nyWnxYNrTwCGVkvfi1l7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T17:42:43Z"
    mac: ENC[AES256_GCM,data:CVjTAZByhpbp1UbgNTEzHtq4X5d/I5Ilcl5iauuSTnNE/y6TQDBzCgNN9bZpkBcV9FDVZZck+UrlbrWtSktqb4sGXFM12ylH6XziRHkhQjYD0NPakS31ORoqWilwuHIYr4xtsm0coIZnF/ld9/h6y/6UzTPZ8ZEDnevXZ8eSWjM=,iv:YNe7gbQpZEU/5uJou/WXPF/Us7T9FB9+CrNAvG9elmg=,tag:2oO6BqCwc6jIl2S0UpPOvw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
