apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:pS7Vp6zIiJl6oxjOWfu+iqWGcPe4KUhOFxrycxUBAJnw9uuAmWgAM9yGynfePieNp8VDHk9pijRedx0g05QucpE=,iv:nneK3JMmYgHnUU2Z8oxV0xJBKJzBf+TlzWI7trHuLpo=,tag:hhJhRG4NTU81b8veVGpvZw==,type:comment]
    #ENC[AES256_GCM,data:quXexznk6U5LdHNtpQecBvasoBBc61TGfKKhs08auTMLof16vdNT2f/3NMY=,iv:jgwYtcCi6J6elQmnVlvf7jGx4YOsJXoEpaYzUZT4H6U=,tag:2lyDLr+aG592ge+ovm0Dug==,type:comment]
    VIP: ENC[AES256_GCM,data:+y2Ku5RfcsK5tBU=,iv:zuYuDr6Hn75ZbY3v2rRzJpYO11pdFyV2H7qkDMiOOks=,tag:Fv49Dw5aFod1tU3AkruUJw==,type:str]
    #ENC[AES256_GCM,data:VXJk3K5Ksan0788KUMqnLkU03q5i5g3a6pg=,iv:OB0nIbblL0wSvcJDIcaNmKSe4zSsFh7y/3mlokekCYo=,tag:l8deaQGatMoKcQjOffoYJA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:ssV4lD54xZjJx4w=,iv:N5Gu2vPr2fWgKmykj1pOYsgcDo5luF2+7wvgZoYAoyU=,tag:qCkq4UDQOnKOk90a2Gq4rA==,type:str]
    #ENC[AES256_GCM,data:nSu9uLQjobodutqixqIO1RHJuvEkiiRFb5RUysCn11hubQ==,iv:+prLYRJeyNOFCPpf8rQROBLm8mCPylrZzacvlIndalU=,tag:4b7vxWXCp2NWdEs2kphVCQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:OwkL/iZEUxDe9h0=,iv:HWKbuN6enswMTa3neFqbY36sRzB07HluFYf7Ylv2cwo=,tag:Gdczk7qdi2TrqQWw/X+HvQ==,type:str]
    #ENC[AES256_GCM,data:1u2IbHzFS3UwH0B7MXTTmDI3Lgwzkv06wMWVc/xYoqyM9Xrd/sE91cooG79Fl24=,iv:Nexx/pTdUNyBPW3vYHCBlHAQHAqfNRKOa1Jg9bOA3OI=,tag:QGGEbLhYSTMKE9NJiGMgXA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:POv4oZxUoKCAY+WmU1aM64Zs8TcngdJt6Q==,iv:VZmZXZFeAlIHuVpYIYZ2+ptGNUy37bHdQMPb96BGBcU=,tag:iaOYOOn2UfY/FN4ZVmg96w==,type:str]
    #ENC[AES256_GCM,data:3wFswD3p77BL/ps8JYvSQ0CCtoZ1V1LJBUQrQhE8ZW2IZdjLCiUeSTYa0NpT8XYFLwOdu7ZkonhibQ/fDNJCQLml/j8YI1MpN/Yj+Kfys4E=,iv:5LgLnVI08XA3rYnYl6MFQLpeulU9Qlb2+emFjg9xEAY=,tag:eFimI2DN3hJZDuI4eb36Pg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:+kMxIMXh+FNJ+vyy,iv:osHnc6V58O+xXj3xmG9OUcOEdfjDpas8b61rGodnC8U=,tag:pz4dBP8mapg+zaNLFYaFyg==,type:str]
    #ENC[AES256_GCM,data:YUB4wRtgxbuEf5VSw6cYvwR9nh9jheUNvy+bESODy8PgfrlzuHd3NqvlLrNXCMGeGw/SEV1dvEE=,iv:Iavu0EXgiXOSX788Y14XJuxqjJxYNCymvc6+fIVeVek=,tag:KnxAQm6jdRJisRd+d3FRqw==,type:comment]
    #ENC[AES256_GCM,data:45qEAyRH7bp75IiORD9gU+0xCY4gbosspQ==,iv:Nca5iIVUWwfqLwgw1cmhxHRbsvPoNx8/b5zh0MfD6Q8=,tag:phFWTYKbn54yHqMREX/YMw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:8TJYYD+6p02gVAKM8l2fUt4FzpcKiKccY6F9H6mn2yA3emFm1U/3ectuRA==,iv:2EwJNnufFkOynSPQXGL1n8i+6FyBelP7dGr2MqU0U4c=,tag:oPxTHfZYfhCQpJO7PeIyXg==,type:str]
    #ENC[AES256_GCM,data:zJxXZob47L3k5PB1dQ==,iv:l90EmV2VFX+OGB+/WKWay6GXUmakcBQB0Jqu09w6v4E=,tag:ciws2+KzolU2bqWhPewJ3g==,type:comment]
    PODNET: ENC[AES256_GCM,data:Fd+B4X6pLV/8X9rGrQ==,iv:aEW4q5HmthaK/WwTrGSUgNLHijwnx7ekSt68A/a5Q/w=,tag:4AQBEKCV3mZrSAYoOk/vcA==,type:str]
    SVCNET: ENC[AES256_GCM,data:pp/DoPk7ziTrpDX5Ug==,iv:iBaoXUPsjkqzDjv5ItPdw8mDM7rOLd69Z5T72cvAD0s=,tag:jftHGJ3znkgdXGKjO1WjwQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:QkY/h6XVm1J/yIFGLGs=,iv:Z2ueqVXZUK5ZR6mMLVj1q6pRwJh04sCMBuU59m2QNto=,tag:dpOTqtIujiBgRIOo+S3gIQ==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:Wfn4fLIv5cr8hPFS,iv:EIlbw6pi2/jYC0dH68uenpRmqGCEvwfOtohv8GhcxT0=,tag:E4pMD6rU5sWW9pPrIqZcTg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:VVXcRJjJofThN3Ny,iv:JQxfr2h15AXIsLZUSGAj8g8VsC909DVUzMKwns28NgQ=,tag:TiHWbpTBWsZH3I5HUiO0EQ==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:v42ASVcuQmsOogiX,iv:rqhW1mr+HNc1e2iv3ONJzVjFAn3XhEf5CE41Nda/zeU=,tag:7JLKrVgX0+ao/IcWNVCCXw==,type:str]
    EMAIL: ENC[AES256_GCM,data:QjrXHi/E1IW9v3SMk42DhFwUSBQ=,iv:zgzM2G9YqN+mQGZjyN/DhDZBM6y5c2a2ZKufitIr/9Q=,tag:8UZ5g5t9rlkyKj3eZyo5dg==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:4/xP+87/godbuIDMLry6ESoSSv9me7xQxO5+iAdW6EOgF+06M63ldQ==,iv:0OEkaHwyzwJ90fCITAPCmhXvWPv+NLKUzFZArnq0sWY=,tag:j6nEdlI1aFceka+dEu5Xzg==,type:str]
    ADMIN: ENC[AES256_GCM,data:v/k0jnA=,iv:mC0hfMpYRc9LjMnMvD3vRMTjOSVlu4wDe2gEzNBB/bU=,tag:dcgcqiwk5yOzUqEPEsgh5g==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:r7rC+T732xI=,iv:nQHsLea51zr3bY62kbGHH0ZNeFpEhj2D3Yji6BrwKRw=,tag:PQgh/EdPiMiFpImD0opDMg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:AkNhrw==,iv:tBRj2h8g6lAFSMgooCNrKG4IRBEtVRbdX2QY7vkFUDM=,tag:RGra1zhYnqWEgQB0lL2Hrg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UXgvYkc2TVpLOFdVRnN6
            QnpOV2h2SjNINGdtNzEzblp6blR6bzEvTkdnClF4NkdaSnBDejgwZ1hDSE53SW84
            UVhnYlFxMndYUFVraGx5cmlYVVFoVG8KLS0tIDFnNnBXSFk2VGdNNHVHWEVXYUs1
            OHRvSGxyWkV5V3lJRUZvK1FLamQ0bGMK5T98GeAD6asorwMWI0wBYUmAR3DW+wLZ
            sC6b1Cbif2jkiwF9U/DSyFR23gNqRTa8OR9j3TMMQkRJ91L28tuJSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T21:48:59Z"
    mac: ENC[AES256_GCM,data:KDEthz7+kKfJFEyTMayMGn3/5UXnAudt7jb21TP1sQm9VWFIfze37X75YyWnp0W2nlGRdlxM0kkbW//oBYh+KgTjm+yDdDRlEmMYrJ4yM6JfkDy6qHFLSoQ+a9GQtRuFyGiAMhC8IWJvQPYS6BKSK5qIW1uUNsWb36NeeZLXfKs=,iv:3h7fZOZb6TxJjFcsxR9rC2AHGCQhIwvUPw4H+S/NkKI=,tag:4rpCbe6bYbfwGLv4z2IhGA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
