apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:iQ3z4w9VAISul6Y3JaiwGdjR3XjgEpbDEpx9vYA9soajqf3ege3NuB8slxX4Ago4IIJ6Qdw/J1N92opPXta4Nms=,iv:wJZ/MCjYIqDbaSj2Py6I6YUdoH3Vm95G5OHVT3vmGc8=,tag:kWqdV0Cs3GyDaqKvlAsdeA==,type:comment]
    #ENC[AES256_GCM,data:w+9XEtro29NiXhkkh2OHTA/+sRBoqhEfgd65z1zCjiviB45nBMmD9U1oaDQ=,iv:YNwzp0hoMilVnCezuTbM2T+MtV4qF7nH81n7DbAWqc4=,tag:FlQqFEhMNyPOWJ3XwUsTsA==,type:comment]
    VIP: ENC[AES256_GCM,data:Xw+lQG+AbIn+6RE=,iv:jxn3WEf6IJFv4408Ln97yB74Im5+E6QI3/rS6t2voW8=,tag:GT/8R2VhFOGEihpTaBO/Ww==,type:str]
    #ENC[AES256_GCM,data:0zog8ZzeRIYeNE34DVAITZUq2XQp/Prp+RA=,iv:409RWrVq2HncNAbNkt/Dz7Sk0sjoozk2M185WWOJGzs=,tag:DgW3FFNoKX+vUutQjkQA/A==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:1s5d2bGPm3ZnwwA=,iv:cn6v713pJJOEKEMdRikPEN982zjeILtnqdJbE6Tp6I4=,tag:yEJo2AVn9hOcHxiMFlOq3Q==,type:str]
    #ENC[AES256_GCM,data:hZkgCHnxzJnTowYrqIJFoeTbqU+G1jSqQZx3Yobx7joiEA==,iv:ntWgEqYU6dbB/fDaKCQcnq5MxxBy0bwDPx4Q0jPVQsw=,tag:FNhC545SknMIREDwOGJUMA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:uJXVWPeT07mHyRw=,iv:nBA8DZCVs6EBpCT9p6v0KZiX6HDNOM0dvmefHquFiyg=,tag:qWvBN2ctMOj1C31l1ELAPQ==,type:str]
    #ENC[AES256_GCM,data:n1DOFJYlFUGNjqgT35+wUr32uTpeokPtRexvpg9jJrWI3tQt+AxJhDtvbyaC3X8=,iv:T0q1GCNmSN8aYHnnNeOYnUKG39w7GQqo8Wfkj1slRA8=,tag:V3gx2U87EwZOfArQQP+KQw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:Q87GnC65OoAMnXQYkFC6VlsIm8ylqB40lQ==,iv:Xrf9IIRFVlCzWsZrP7CNGkyqT7qg3iVMiZfWqGfQ2cg=,tag:NFxuaoyjwtcrqAb6QttrwA==,type:str]
    #ENC[AES256_GCM,data:Ck/FpYEL+d+2hzQYtrHDcvOvrZYE79BGH3ji0drt+jF/Y548YDCU8n/B9MqCdcWCNJ7JULkjNR56dm3D+0Ipmktx4GnnGdkkW9VHUzFV+tg=,iv:T/zoV30t5L98eavb6k2fpBdMbO0rX9NyE/o3ndqy4ic=,tag:6RnTEnCA/d6dD6Gfaz1M1A==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:YHcIQVi9y9tm3Yun,iv:at4qM4dK+99pUX0AEuGxF0pcZfZu69R+qDhrpQG6PT4=,tag:p4yFrzwDnG+bAneEFGitTg==,type:str]
    #ENC[AES256_GCM,data:lwy5xFBjmpHedK+zXKestsnWt1msbHI3nGImgPf7X4oadF5cchH4gSQrdVXH9QXDSeQgjb0zbA8=,iv:j3XBISmtUBhh/7scPGWWhTxTTAPVNbCQ03zVCGL3AfI=,tag:gib8GeIqMbusiNXkqzapFQ==,type:comment]
    #ENC[AES256_GCM,data:t43z2/avlUl6hi9VONxwu0R07uRV6VJsNQ==,iv:+yJ4pdUmaZVQ7xtxOowGxVq3JGDlHELYcrAp+KZMUbA=,tag:P1weGKv7C7R1S1jkYCVaaQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:QwqMNNRnhB9w2q7BM6NrSBt7SGNYP0gM2LX1Z3/726AA62ruroHfTBFRiA==,iv:JfY7f7OelnWLmFOlHB3bSe8YGix6T1Gr7aUxLE7Ykm4=,tag:k+P6I2NpDEDDys1VmDKfuA==,type:str]
    #ENC[AES256_GCM,data:LW/vfnR6yEFUq73krA==,iv:UxXJDBh5lti+r3RywatfvPb+V9V0Z2bpgcWF+GMTXW0=,tag:pR8ABPr2tkW/y/E6TUtyCg==,type:comment]
    PODNET: ENC[AES256_GCM,data:Ww42DIjdcBKGvsr3oA==,iv:ONWsf/KLfkmtYIs/aTHfVtHxhwsxdWZekjUZ30TKDS0=,tag:gfrdJ5iM33BkDoSOTy7bbw==,type:str]
    SVCNET: ENC[AES256_GCM,data:DRl2PuvfFesV1DM/CQ==,iv:A7Y71gnTUnjdEMS9j87YPSuvWIExPCeb/1YK/+AFYMU=,tag:1GPyDAv59MgWjmiUZyiHig==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:bC6B0cnbRnM4Q9celoE=,iv:YSxfmS6s5s/rB4kweZZ2X1PnxraB7vWk7R4IdvDb5IU=,tag:ont/VefnqnWq2uxveNwo5w==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:itrFkiDZhQcbaLCG,iv:e9KFQGJ6ay4y6tPHafQqW2G1U0yPcpy2gkQWKhGhKNY=,tag:VbGoR7b1l19q5gNRglKeig==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:QuBw0wWORY5LA4lL,iv:Tt2Av9SYVfrTXpMajwdRhvevEpCGvJn3DgIocbg2lMA=,tag:uFDm4fwXaVzKg70aqYNyrw==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:oLmytODAXTDKEkh8,iv:Ufk0jrRF4rgvEsqS2lgy6wVGIcnxhtn5Ctqq1ex+8gE=,tag:bl24+YDfiTV/7t20oQ1vRA==,type:str]
    EMAIL: ENC[AES256_GCM,data:92hDy3e9UiJkfYClXdAAXH2bGCQ=,iv:WGeIv6exf6BrSnSKAwHGKUQ1szjBfQSB1SoEZ+VuMno=,tag:ikk+FZYP6GcMDn44Y1LRBg==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:9A7vuduJ+hT1gyppq0UyOy5bGfpXYJWwKdO2D91mqCBZaQF8X59vZw==,iv:LNCGlPvKDjaRxln7a+hkxIxSKqzCM883zkTww6hNvgU=,tag:HmE8l3vE8hCwWi3X5ftSMw==,type:str]
    ADMIN: ENC[AES256_GCM,data:YQBM49c=,iv:Boz5ZM8zY13nRhpzaCEP5GIdtqlONdEFGg7CrzK7VlY=,tag:dBJDmTc2jll1GxQjLa2qCw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:kV37flUXXK8=,iv:PSoIDH4UF/e8E1uo6jL2ZEGEwfDJg2oadxNIZXiFPBc=,tag:9lscdpyYoCe8ABYplJgKBA==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:aQ/9tCLKPDbyemRbuLk=,iv:ya3unIK6WeonkkLWwDlJ/MiqDA+tvAYlT7K//RuUAto=,tag:+GmFxmBkzH5L7KGCo2d7OQ==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:Ti5zeg==,iv:liROOO4qOrHDdUHiW0MgyXLLk5CRNzJhkoao8hyNqo4=,tag:aMaQPnzkLB4tdBKVureKUQ==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:aZh2tHwQSX7djO/A8EQ7HkaVVDkc9zsX3s1sTh74xPbnkZ41UyseyCQulq4=,iv:qjW+aXVDvYkiexxOMlZOPnYiwYc8Ii3G+8q/WStrE6k=,tag:Is2ABHnhKrFx9NCQu7XO7A==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:D2WhB5Jx6a743SNk2xjk37SB4kUOnB0uNKW884X52hs+vMWlNPDoEvOBFvw=,iv:OJbNvMy3yIaYfBHrHYv69EqUCrPOM2MS1grLeT1jCAE=,tag:47a6KrM7GHmno/lq07/r1w==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:Tcb9p0PCPdIAyS62WPs=,iv:0DAtNH/VA4lgkySyeYXD5oLHnb72Q991K+6OYrqB18A=,tag:oA40sxreYJfshLmkyNj6Zg==,type:str]
    VPN_PORT_FORWARDING_USERNAME: ENC[AES256_GCM,data:NN6J6YZzu+8=,iv:oU1n4QPUWxGMJxF11wewTH7HIZhJjV5tZvkZ5oEVeoo=,tag:vH4mV9cUVPnT3urab1gbcA==,type:str]
    VPN_PORT_FORWARDING_PASSWORD: ENC[AES256_GCM,data:bHZXAjjLUFhsng==,iv:ZdbdMZ3AL/bSJKSqzavCivoy/mjmjkSkr0tfyECy22U=,tag:DSl4FIl9HbsV5sbVR6JKNw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:iUrJkQ==,iv:EQQVz7+ITdUI055vGcY831SIIAZ+DCB3xXos9OkcC7U=,tag:JGETl8glGOXct7XXDv79XQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cmNvTWM1K3ZHOXY0bmU2
            K21PTkhPN0NGTXhpZUMxRXNhQ0FPcHdDVGhvCmhlZnl2OVNpdHhSMlVoV1N3MUor
            R3VYTkZMWHRtZG5JM0JId3VabmxvRmMKLS0tIHhrZ2FGcy9jN3BqZDFnMUpCRWJN
            MGRoV0VISHppcUFUSjBIdlJYZ0RtMHMK8pkVKhQ6DzdagAJOtZwBwhD9rKGxYtVq
            /oXlMoHU3P1mnMo/msnJEuW+FqZxlHklV4omjP5FUDcKbtwh/Iq0Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T15:55:55Z"
    mac: ENC[AES256_GCM,data:+L/VpwOiJbZpAZKP6bFgssh/Y8RL14pLtg3IghAodiGKEtieSmqAKfn0T3D5kbHRPwfkuhVUxjdVamkZ5toMHzQKW8VEluDooC1b6s88WugMT/5igq6aJ6/swezzga9CvboxYOYy8cjBsZpw1lfapo9+zApSVrf8ohu42EXAa4k=,iv:cBa6+QWy1/qxp/szDZg39+Pch3S/bPkHPyVyoq5LaeU=,tag:OfDXeuyW7tq5/fqB0/BvPg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
