apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:65YcQOs56yyUYn+EVZYOdkSl6k3Bx1iNSeLjHt7Dp4aN2dYlXXKp5Hfsrlj9bzejJfxOXK1Bgno8zUkacJ2weDI=,iv:oa54yJj20E/J6DdU1WYnjpLsPDCXJ5FOzLmfvFyD2zA=,tag:i5PmmgZKtGRANyHw72nM3A==,type:comment]
    #ENC[AES256_GCM,data:YGUIWOBnwZ+HCYjFT1fHtUT9+hgJP6cRMaX6xe8r9pbDWIIjrEsVuw/0ZYU=,iv:eA0lRdl/7UDhWJjbz+RPaHLQfM74tU8nZflWEELj5FI=,tag:rXH0wLqF+2hozxlzHn3fKQ==,type:comment]
    VIP: ENC[AES256_GCM,data:opGIv8NhFJ4+aBg=,iv:UgfmPVPH2rX1OITTruoqg8ajg8rFvrI2zek/CoUPeiM=,tag:U4UT0zjBVaKovrHvdIwUjw==,type:str]
    #ENC[AES256_GCM,data:geGZF8dr8qECCS3APCWj3bR5CfGbDkywwjI=,iv:s4B0ePVAcG04tGBSyoHX3UebEyIrJImT6tlPnWp9tQ4=,tag:JrlLESRf8fxQTRsMEfOvlA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:7VrSjHQ1ZZsHG8k=,iv:7d+vxkKVN3bo7PFLYVFpic32crTx/G+87ytYFPcwGGw=,tag:Q0DcSYjJ6OhJhRiy2OCHJA==,type:str]
    #ENC[AES256_GCM,data:T7EnNoBMw3iFDs5bR9Gko3g6r9DhocMRpyeFgN7x4Mcf/w==,iv:RNpqt4sGUw334HnNlSqhHGbq3VD5WyBef658631U7g4=,tag:7lXquthbRpQRJsDo88MRwA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:ZYj0ciMigpDX62E=,iv:BIMPa05hJgFZtnNL9j8x8PgNVOZFu7uYFJQ7uvo4f04=,tag:5jIfp9u5X2Wjs8oriJlRLg==,type:str]
    #ENC[AES256_GCM,data:zqL3VQeKjFojA7j4LBvAbmdel07ZReUik5sIAMERxxI+FzMRGbTKx4lgZ6SSGm8=,iv:1iIrhV7mbUPj1UPRw7ib5m/jkUBvKvS9H8RWpSPdzzI=,tag:nRgase6CyRYx74EByXEELw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:GtotauYPuX7SZSybwFybL3GkWQdmXmOgnQ==,iv:diOuKBgP2mt+9+otRisu3zZka51Ac/+TKwgUGIwAfvQ=,tag:I2hEN9IQ1lQ+l2gWLQYczQ==,type:str]
    #ENC[AES256_GCM,data:/+VaqziOy6GWuvCFKa5GkZokdRSWCJzzKyJHt894/syKBBCH1czbepfjnKL+MHm7+NfJZAQ3OMrLyy/QUPR8x6nT/RWhxUgbnuZcB63lkjI=,iv:9WN0MnjmQhkK6WclrNupQoen8Mp0XTTC12jpqPtVKj8=,tag:0MbhMf258VSwnAQDpkOuwA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:11A/levi/ZBqtXZv,iv:Lj1aKuQQI1pG0/gCAOLgwlpXnbS+lbQtoBkRp8HX2k0=,tag:SpbP1sn8Y3/YVPZ4q5ja+Q==,type:str]
    #ENC[AES256_GCM,data:yGb7krnSTR3XWEtfBdLbWqOEq4LQmZr6EbOlLp1GiFTdrHoLm//8JYJbEpD+1ZYY9lgnNNOkzoU=,iv:sCqhD0j8RI1ToHc4NM4I2nDBXj3Eq/gclCovRU5vDZs=,tag:CFaVsVOk64ApVfrnBjGW8g==,type:comment]
    #ENC[AES256_GCM,data:CI2amUs78v+uHCKokzDhTMXD2CwQn1bLdA==,iv:zmscYMear6u6BJEQgZLFV32/jTmaQr4vTFlxt9ofK1w=,tag:j2UYPMOuo7VldLcFVZ7Reg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:Nop5zoS35HKxJ0J4P1wNwUTNWtDTD+O9Nm688oDlvn/ZGfJNV6NaMIZ2cQ==,iv:eniJklYQRYFs3kXZdaoTFlw5paR9W09lkrgsQPMxodI=,tag:IlGrt62eMSbh/dBxOh88zA==,type:str]
    #ENC[AES256_GCM,data:eAaw+2RXo6zB10+UFA==,iv:SbJ48frSCYxJy2O3zoIaYWCb6sfy5bhdtTHz5KfsLoE=,tag:IUf475CqloQ3q/C70Ym0+g==,type:comment]
    PODNET: ENC[AES256_GCM,data:yMUoA8yrQLE6/i8N2w==,iv:IdeM+qCm9AXoaLmXTfUR9sGwBc4PWTYxKbafrDS4jHo=,tag:k6+V1tazeofLMWR/i45oag==,type:str]
    SVCNET: ENC[AES256_GCM,data:R3e+5Q8ihCUBHjF25w==,iv:FiP8hH55jUbp0Jc89CmERLNM28LMJWXhcbFZWmBn118=,tag:tM5uHFqLlxTk/lr3md0vhQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:R/MZVnPXrdMCWZlgeuY=,iv:NDolGqv9p0/ZEl/48nt3efhCgPSeEovCA7qe7ATUdt8=,tag:BDgpj9G1GX0WWpV1KsG+OA==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:sfbLwMgV/Vxwigzp,iv:1qrtd4x/ibxS6ADcK+ugD06oFqnHCMqTDIfCJBhweac=,tag:64dnEknFng8k1MzCkGkQfQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:NYYp4D5HyMfFPrOu,iv:wMiAoXOPta1r2XdmrvGa5yEi5xHnRaaY95KuFyLz24Y=,tag:oVPAZBzcn0hJ/zeNNdE+sg==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:uBufN2xMlTiWWo7N,iv:MqNNNeBG2iHTsQr7AIRXT5ExfNr4m5nLCg5073YvLYQ=,tag:C969Z9Qs1Faen0kAnuF7RA==,type:str]
    EMAIL: ENC[AES256_GCM,data:OPZmWMsiYxTbf6urNG7Dvf7S4Sk=,iv:C7w4WlJ87EJsRFPBfgf6hwXCkHZHgtTRtVO3MSoGiDQ=,tag:f7/mkN5p93TVop1bjIGzKw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:YhhegQ9KmFt9QE8ws3I8gwoCorUsj42ud6+Beewsqby1rs9/i2omCw==,iv:jvxFQdfMQsPONvRySEVkubtdJfyc/eUXGIZ2kRw62HE=,tag:6FIT2laUA9R7m87vvx1Jjg==,type:str]
    ADMIN: ENC[AES256_GCM,data:mDtUy9E=,iv:2azgNh/q5CGV5Pd4afnO1V5zUUpERg9BzuzkHfl4404=,tag:Je6YfHfG1Qemdb8rV2j00A==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:C/qMuvCcNM4=,iv:KRoLGzecG6+qHJSEPmyLKyWtDsitiy61rRL+W6RtDNY=,tag:4NJcw3yw5sP0cpM9e4WN0g==,type:str]
    VPN_USER: ENC[AES256_GCM,data:wcWv/Rc6Ld0=,iv:dZtexZYsMErMz30c6BnCDnKRddqePKYRHi7vW8pM9K8=,tag:OBORW8oG6QqVW4wRvDj6vw==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:B70vfhCMk2/jIg==,iv:4jNH1a2C+3AHuB/GHSlbPrgLmibLkl/yo6oigvXKF1g=,tag:ukZOjcZPiNKyCHs0Ic5xwQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:ujfVUw==,iv:lZVAwk4EU8UqxdoefZsHPHgBg3Xl1aRKvBu0IyEBGBM=,tag:u8EUf6VpZtutM5oasxnCzw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAya1RJcThBZ3RKY3BpcG14
            c0FWZkdKSWt2SW0wOEtRd2VXT3lRWE9XUmxnClk2UStab0VOd0J0SUVNejgrb05M
            eVpPMnB2NXJhTUhpdTVYQWd3YllFd00KLS0tIHI4WGFqcHFuSlN3ZHViZUtuR1h4
            aTVhUVJqSVVuZ2FRR2laT25sbnd1cVkKlqTyLpdvibcPwoo6wrWOFsGP7IE5JApI
            /xroXbfzOx0UgHU4UGhs3eI7zTb+Wpc6vz/IitHMIrmB8I/ia/56ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T16:41:04Z"
    mac: ENC[AES256_GCM,data:DYdCwSgwM1FOCe42BEgaveE13m8ve9mk0uWOB8GL8uA5TM8kvKxklh4lVG1rXQsSKn8ECTVS4opTPz3D+jS4nobd4ZYImlpwnWumgbJKtQdK42QADLUPxPxZRg4dhiWufYeS9oRIMdaOEsIHnGLyXJthgK0VUUOl1KngVGWhSFE=,iv:RA7JqkBUtIx7L4WA7kN+b9sb4vpc0A7cEGZR6T3ZwIc=,tag:vnjXG+p/pdUmC0fzPjf5MA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
