apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:jgkD8P2rwwTjfkPw2PBFayfOSvpEQ/h07rSQpJ8H+imFJhjqPvY+7VYmma7Pm36kBZOozifZnPG5IWMebkDdbww=,iv:QlN71r4d4q2zwfZNFl4b6uOTpNUJ9VEjCty52fkuxaU=,tag:l8C4qthe6cM+ChbORq+jcQ==,type:comment]
    #ENC[AES256_GCM,data:MIRbEI5qRW2KVWfvZyRTneOEc8E/tH4j2/woeCyREJpsmABrrqBHTeq/z3g=,iv:IhBat9GmmscPmwIcovXuVeCjXRCEi+oS+NTUj1iCdWI=,tag:PbJVkh2SupuB8vvO8+CYXw==,type:comment]
    VIP: ENC[AES256_GCM,data:ykZGvN4r6Bzvi+E=,iv:Kk2eyEbLlseha6y5IdPkshuESLBxz+FuHGpg/PCt4Tw=,tag:3TyC6opNIamL2ZWth+Xk4g==,type:str]
    #ENC[AES256_GCM,data:8410t57ahmWLgXcFjtoL1zFmGj1dBErIzvw=,iv:LMMBAVIVWo3IHpt/M9NfwfgUcW7dV7yVBlAwuHVZk5o=,tag:bOKnjQoewzDVFmMbAYop7g==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:zFdIBGqfHz9Iz8A=,iv:6O1X6Fl9Nh7IPcdv2wxq7BPv9iEvZ1kYwzZHEo+rliY=,tag:+/lc1YCbq/CYs42xT7ySsQ==,type:str]
    #ENC[AES256_GCM,data:1ChmhLpUBff0iuOECFWg8EUfxa5oiUTK9Llek0MPBPseZg==,iv:BA3zSn+r/re3YdkGPB+ovzODsnajkXV4DVF8l2+1dhg=,tag:hNL47yOfyDX5VAB49m0mLw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:sSYp1TuB/X0a7Tg=,iv:ybo5s/C/BeD/sCfEhGZTE1wULAbSy442gg0pIkS+HrA=,tag:8cbHP9kH1ehBnrSXrUX3uQ==,type:str]
    #ENC[AES256_GCM,data:NNVENMUnql37s6/k55bG628RB2byuGSv+enPndG/0Lqf8LGHmssvxDVGHJgVnTo=,iv:+T5eaGRKWMnK6VZZL7qEkXX86zT2+z2I9njNUO79/9o=,tag:tuP6xKv4Vfixv8sVdgItjg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:l3F/pxehsvT6tpUuaS7xdULB8L6pUai0/A==,iv:fgug87viVQx2Ib/35hS9ldwo9B1nMxuddauUXsdia/M=,tag:N01JFABAv8Cu93zhTQedng==,type:str]
    #ENC[AES256_GCM,data:/jMyIfDEgo3Z2m+Kfd3mHnNK1JyblEaFgz/Dx63AVmEvWwi5Qd38OXdBH6FrehTH4e/7TvGmlWjaRm3M99qzNidDA92ue143qbwp32O/cs0=,iv:YMr5o/bRcvx+EGF++pbL1GcfNOetZNlEQpWoks8LYiw=,tag:FJjdcgBbwDTvaQFYo0ITOg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:uzihSzBOfGgbfIul,iv:jrX7NwH/9zuMLAXtGyp/YJxS89C1jN3PXdgzK3rugLI=,tag:B++Gw6y5BBWQzqg2CC9jnQ==,type:str]
    #ENC[AES256_GCM,data:gh07Mhka7FpJcZEEoWyPoT68e+i9J3sHyyvMJ6TYbomL6N1KxWOmQQQSq1/VLDqKTaoKrM+xni4=,iv:QXgUaEwq5471exHCL5Ds6mJPnXSG6DeXklNFFP2KRew=,tag:QwRmItlRyja5+COGXAmyeA==,type:comment]
    #ENC[AES256_GCM,data:38grD5KV3XX/YmRoU76ARdHMqcp5tFrkGw==,iv:4j5nH0spkp3YB4aEi5MfIb180AGrbMd77DJBVRbA5iE=,tag:z/SD+1Sf1bVxyjnqlT+Z6w==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:MXLIeQ09gEFvr0oihzxKTkgDJew5y3eVan1BnIO7FjVBs6CDWTRmBqTicg==,iv:0iXOF0ZBnpPIuBuTbl5vdgxlN260AQg8yXGQTfZRm+w=,tag:xIrik3QV6dP/MHBpZTaRjg==,type:str]
    #ENC[AES256_GCM,data:FptZsC2kgD3n3JTugw==,iv:STPX1AQsMs7FDKV6CGBYSesBM81mpzM0JZ/5FaBDTws=,tag:3yOUAvQUtpk/GT5QtZxZog==,type:comment]
    PODNET: ENC[AES256_GCM,data:2XDlCBxMFaOBSLERwA==,iv:Ypr8VUAZ/P0ZSq9O3hr/Y23Onm3rQpf/3/JblbQfyjc=,tag:96QFPlI7PMFy3Z89PmEYMA==,type:str]
    SVCNET: ENC[AES256_GCM,data:KvTzkA6YNFKDbr5qyg==,iv:hZIBAMdlBGVoHoZy7DPJUPHwvdPZGTrTd9uOYLoWQBA=,tag:YD3JbOYExiJWfuDbGtRWKA==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:TihPRPjSztfGG/e7o5Q=,iv:zO6ow/lyKvkAeF7QHN/L7DGHceRXlmflDgYjjbZvXtU=,tag:0MC0oy+n6pUWXMBejRYatQ==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:Jm311mSopHuCNxW1,iv:u17R7+9n1LiZOJy8dfB+uSC9xxrX6pguMARVhrtJH+8=,tag:G227WLNdGLmMq8bWaym6Vw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:S/I2nQ==,iv:Ibuj7oU6eetSr3hm3yqXsCNSROlSCgyakZW1UOMq3eo=,tag:f3J0uAj9ooFLj5aeSEFYIQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c5g23qt38utyy253gvf729w4l2jnj7pqn5s00kkzsw6l9k9d5u8qmkvkwk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ1pZQlQrZXNTczlqS1lj
            MkNCait5YUxQalBjY0VsRjk4ZUZaSC91aGlrCkg1cTlZa3l6eUh2bzJpREx6bnlQ
            Ym9qK1ppM1NHWEhEbVpkMEdBL2NvbHMKLS0tIHVRSHdxYVgyQ3hZS3MrRU9lV1h2
            bTlTazl4UTFDd0dhZXM0ZjRDdkhZMzQKsMls2a++/st3i0oiKN4k0mbx9NxiEqnQ
            5/FSR7jW0MKDNWJd6cZTrdV0fHR2k6fZ/InTfEiUQBJKloIZl0EJhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T18:20:33Z"
    mac: ENC[AES256_GCM,data:P+wvPY8Seyr2gEljQSp75JhgV4GiuBVfxUXrTNx3pNc+u36lMsy6eOKYsL2s8+gml/phib/HPb9eVTHlbD59dvnjCQnKPtwZ6a/8CA7YkeBTWyZzPmvGcBIs2YD2f5ipa8tCHP1Dflx4WMpV2cczyBhOA4QZXBDGyEjZYhQ9/fk=,iv:BqazOVlbQF+RDDeGi2bIFBrfMTP0GbZlxvc0wnhQOaA=,tag:qa7iX9WLL7wF8CPQpIskqg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
