apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:7Z2kUXcv5cn5I91ErNEEBBklMR590r4tDeiIixLgLd3CxhHVoGsVLfn8xfYAqrjRikxhBV9jwOzcNqoYqThLM5w=,iv:xLsvJc9b2PMW1XvMZFhSR/D0XnXS/Pl9IDSf5QSsQ1w=,tag:XQDdAUJuJqc3GtZ7EKHSlw==,type:comment]
    #ENC[AES256_GCM,data:0LwRUCHP4vuf+OJRSeyhK6KNZ++3uK5+SYfzCO3LHoGHQHIPGPeeVJFCpP0=,iv:YAO8tuc4FAxxEsvsqWFb6Q3Z8ADnaHA8wP7rpr0zSHU=,tag:JXBbUuOH6xd1Z5XX/OZVFQ==,type:comment]
    VIP: ENC[AES256_GCM,data:haXSyoctmtLlmxo=,iv:mez3ENux/xIUS2ru2jLxLXME68tSy3vFbHZo3yxGsHA=,tag:IIvVv+XwABhXDXTo7vipaA==,type:str]
    #ENC[AES256_GCM,data:UnhsGGl+oTG1XHXFc4wsQ0J8kyVOOrirWo4=,iv:5yIPVF8JmDIOm65crz3Nn602yvf1r3Cgy1FSqKwjetg=,tag:X0LwwpaBmPQlYpAivN9Ciw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:3tx1aVWqQ+GE0DQ=,iv:5pQA++YITKU+z9I8o0CCuTuV6avX2ID1Lb/nPrYNy3E=,tag:RQWt79/+XkyCWuxkp4E6HA==,type:str]
    #ENC[AES256_GCM,data:WyzwlgsclusuROMrefB+JuQgBnwqbwTLOuEqNT5oqO4pnQ==,iv:Yd8ybAhex+mvMt0hnAFttC8nV3DVR7CXLg2S6lXcWjg=,tag:4VN38TEc85oD0wCxOsAjhw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:JN79tc1rkJSVwCU=,iv:YwnaGDrFrFCy0D0JldT1UYquYuznw0Rc6fUPW72rNbE=,tag:J0AyfP+4s+WlThNLz0HXzw==,type:str]
    #ENC[AES256_GCM,data:4bAm3ZwGC8E+5PynmtVzU309jjI5pRZmydPfGrxSZ4gcypgsqyraQ9rpYzoeK7U=,iv:pjBn25chkRxxA02tn9IioVU9keA6FfYjxpIcSY4PrNI=,tag:Padrw85061jV/IB+1CYDDw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:4qImXA/mfaj4moQkWs1Y6z1tfF7skQjbCw==,iv:nmvn5LULA0AUUrk68D5UUxuYLhwqtTwH1PBJWyUSZcI=,tag:80H93zPKd7GZftzW63rqkQ==,type:str]
    #ENC[AES256_GCM,data:J7BXFqCW8/eYzLT1ZhAPQWLE2rrBN09iDCUlnNp573RBhstmXENumvZKiiY7EO4TOs4JZmwfzNT8k2g/fLpTp0AbGAlBiwh5CTXmdXIT9A0=,iv:Y1OK4mJtFlb57Ubkra8cc3srTBZKUUgCpa0BIzpXY7s=,tag:aRY/akzfrhoQbi7JgQ9Y4A==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:vswrO+LnySgzZ5AX,iv:G+g3diUQTufveaqaM6u4vhqFx1h+lDpnlmaX9Uuu7mM=,tag:IzKgrC3QlucBghw9341LuQ==,type:str]
    #ENC[AES256_GCM,data:53AwOHM1T1O7dbB/GD7k+zhNF/nbOuQUulGYBJpPeNGtcbpI3AzuIT0WA3XX1iZxf0UC5e4v90c=,iv:FFAmWcnP6LApi9U+217STeWSwj2dt6+ZVnr2KLnXGLM=,tag:QX0rDVWKvE3MNmUFqkCeEQ==,type:comment]
    #ENC[AES256_GCM,data:i/+ePf+NR3X1U1AOxFqtgUD/sYlP2yWgVQ==,iv:f3dqMjffRoBpVeF4Rf8WWW2ekr+QdBjW998zTQWiTVg=,tag:W3GOjbg9sZb561rslqfEfw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:6yLyed2Mjpqf2v1W0qNrm1LmwcQo2YEm0ZDLTWbUmYSqhBcVD3BpqznCUw==,iv:w5uCwomt7obchzNA2o3QhqQXD772m5RGkvDv9io2jSc=,tag:1/A0s2Om7WyS8Uj92JZhRA==,type:str]
    #ENC[AES256_GCM,data:YQ/rvX+B7gW0x8ZQIg==,iv:6v1dvex4vYfbU3GK0hL8Zb2JlHoxMGjnzE3v1+wwAFQ=,tag:6wp2vM79TAFpYyogM4TOwg==,type:comment]
    PODNET: ENC[AES256_GCM,data:BFyqDyEFuT+qav8M5w==,iv:jj6itidxK9eVicdBv3lNx7+QEoimeBjmSSdKjV6sZM0=,tag:fQr3hXpr4q3g6bPU5kqoqg==,type:str]
    SVCNET: ENC[AES256_GCM,data:NPs5qkh3FTimtUAhFw==,iv:1A5oVB3ktirRdj8OPYOEHse6OaAvRoJwsSBfGCKlW68=,tag:EovT7MK65kWxj/L0AdBufw==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:r23W3J/lPPFYOP3liDY=,iv:qhB880+NcCrcoawxJzgouQooFc33nLtwrmbpmIkMb0Y=,tag:J7/LWie3PoqtBEeCVcp17w==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:O4iv99nic0kuHHkn,iv:XI+OgoE0bdlDm8z/xS5OJhN6HmgTLUXLvP5zw4AEIIU=,tag:V8zeMRPFc8YlfEy8psiERw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:T7e9AKufHlxO+cjK,iv:vKe0qNvase6eLS1AHv1cu7ADRO01d3gDXfhAf6cw9mQ=,tag:vIjkOBSKJTcw00Km5n5GCA==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:8xw6kikKE7Q8iHQy,iv:yPTyNjA6JYecgSnqOv4NTk0TFiowTGfZcjSLDa8r7N8=,tag:eH5wWMtds7nKOF5hixk53w==,type:str]
    EMAIL: ENC[AES256_GCM,data:ROx51NAoIzYM6Nx2xSoH2Ojz/cI=,iv:K2MzlLi+H1PYl9d814QkOl5FNI32PIpjewm/fzdgz5Y=,tag:6EgWnel9qPyTcmnLHGMEHA==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:cCaT8sztQ3uigfh5xM8AH2w/pdeQ2p0SiEqOpfhlLJkj/pGtvnFaug==,iv:Z2BfAt4ZTHCXmm+nQvw3q+xDHOOOS+DHl/zVsmRqZU0=,tag:oPsgOyOd7Y/xk6xMrk2NLg==,type:str]
    ADMIN: ENC[AES256_GCM,data:3vvm3O8=,iv:1X6rpNgFTbMVJkZDi9A62xJ+5Orvtkdhj50E1Oi+M3k=,tag:ymTETxbY9OB0oGU57ICY/Q==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:jVWdOR2pp+g=,iv:yDMXelmXp8iqICAKGHVFtHN2P+OnMYtqRojBKx3QJVY=,tag:IR5WgLXtljdRPhlmZGfJ0Q==,type:str]
    VPN_USER: ENC[AES256_GCM,data:klkxeApoDuM=,iv:0Q5hi7s9wZi1Yf1JrgqBea1evGBGkq2Wl+KyeyKAW6Q=,tag:aioVx8yrRBkzY2H2U+SI/g==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:rzTKbVXqBv0eXg==,iv:S0Azj7HFFk1KM4Epj2VOMsMJ3W72kjslx+qe5COYZ3c=,tag:gOUU9IZIavTiPQsgAz4vww==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:8fpWjg==,iv:Xd9zpajS2+q9kip8uUW69CTO3NL0sqFQRjHHbI+pP9k=,tag:GiFQ2JLDzSV0h7XtzWvViw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPeHAxWnc0N20zYVlwTEhN
            eWxNbUtSZlNkeDBtNm5BdFdUQ2VtZjhDWUV3ClRZaGp1QjB4REY1YlJ1YyttSE1p
            RnZWTVFPSG8wMjZiZWJhSVdOYUZ3cE0KLS0tIEU0ODF6QlBUek1GdmJITEFEQXR1
            VEhxVzQ0NTlLR2ppemozMlBuakVjVDQK44JJBkXTa8b8raQxMAEFB+ScegFy/Qzh
            VkhGp75WHG7TirISGOx5iLQBr6BvYfZ84J7L6lFgAGTYjx9LjO1TcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T12:54:48Z"
    mac: ENC[AES256_GCM,data:B9Js3hyxoCf3chegJuz4TPrmwPGwW9SZM3MYT9acrpNmQjs3vGoQmB36U7WesXdW+85JjZlZrMp+Q27H8oaZrlwSfkbLfkrupFz7WiVVHHsM9lX+DL4TFTnShySjjGexaiDxoUHZBVSawbZnQkD1IzMykjKL6GwKztodH7cY0xI=,iv:NLkl6deEENIqAZFsFzoYETwH2vSk7QsVbzCvOW+1xRs=,tag:GC2b4tC+U/7XRYXmNwk9mg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
