apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:HXBnRPN3PzTgyuj7PiLkjk+3LQO0cfxoEFCt8c9DTj16UbTcfWofPsAhCjAWBSINu90D8IIAwJhISLOsANNSw3E=,iv:E9SREOmmOffeLiA+iYafhEGhbZ+j/Od66XMf6EF6j5c=,tag:5rqZaM4A36+ID1qxeuCogw==,type:comment]
    #ENC[AES256_GCM,data:fvtB2tFfmCKbYysbDH/wtoi02OXtSdcnTT8zeQxARaqUgLYp5dAVoFiDLVU=,iv:O7QIJk3HBaIz7Y7pAfI5XVZy87FEehAsAQ5IRE0gB1k=,tag:up8+KxVV2Kt8X0GUwJuR7w==,type:comment]
    VIP: ENC[AES256_GCM,data:U2uY//JW7XC6Z9XwjYk=,iv:4vezpA9pXXxTcS8S+OYoKpixwXJPwXpbi8Vg4O5v7nU=,tag:cefuO7xHkl7QvsW1CPFs2Q==,type:str]
    #ENC[AES256_GCM,data:g1lr3KXGXNv0IY6hGBezxyEypH/zBEfGqHw=,iv:8ZuA8UMe+v3IsQjeQlpFBdz4H4BmASBxJwzsLPVG2Yk=,tag:dquugmHvSESalAE318zHhA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:EhxKQkPElOHQX+oYNqw=,iv:KdkcKW6sU2cfelJ+sxReX0UWzG6eCFYXBC9y085Ser0=,tag:H0PYIqOOEscUOXELzmsNfQ==,type:str]
    #ENC[AES256_GCM,data:sgR21/E3ME8TybIoqIooR4rVr1eduWPMr0m1HeNI9GEs5Q==,iv:l79JsGRfNVorNXNUNiPXkl175XNLqackafyKdS++ReE=,tag:eeOjn9ltKHm2s4pchfgwSA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:odbh9+q3mYG+T3KX,iv:ilUbALH3ZaUrl+fb2Nvyruh5l3CB6QZPIvPQQ5J9wgk=,tag:hZxYY1ElMJafHm2zMT7pQg==,type:str]
    #ENC[AES256_GCM,data:uLSaQKcHeRyd7shJ41HnDJWfJ9XOd73TWGfNijzTOqDcmTrXeYIdrEiEg9UKSUM=,iv:CfFydnM1ITGGxGdPzORtTlhqkhmVWcCc+pltzYRyVPI=,tag:3UQ3W9fhehc9Syo4E6gLMw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:pBfVuGaBMd0z1GCgtIOtYeCavYn8G+x2z3BeyAo=,iv:l6yU6nln6Vj86e38ykX/UnubsnxvvarGppvSadcwA6U=,tag:oMIWKN3gfrXyKWAUTtubtQ==,type:str]
    #ENC[AES256_GCM,data:ss2G/+futn3lq9RzHSsofrEejDIxDe8KY7xUSQTeuka21XBUielTJW4nTfQTCH4PBEPtDjOKv9EofIHAneMMORnFqIAtF/pVXOLFNbg/s4k=,iv:hurht1dsGDt77H12E6goEaDtwHvxeXkZPXWrHjL5Ukg=,tag:Go788udNrJKWrtRYFzDb/Q==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:C2Z3jLi1HCvD75crgPM=,iv:XCPs9KLVDhTPwWIIkBChUy2QcBEztGV3EoxktPRE2YU=,tag:NDnZ3Pw3cVwve/c3w5iczg==,type:str]
    #ENC[AES256_GCM,data:CySz+d38Mt5FzXa91vnbQvkjZmofGx2wmtNQan9vmZDkrhQsed0owLFMs5FCnObtQ/Ho1A3Ic94=,iv:Ms/7ZNzIpOjLR/bNiagAl1xigKC+eCxC7NG0JuOying=,tag:1f5AdpWwZCfgOzKWVgF5pQ==,type:comment]
    #ENC[AES256_GCM,data:h1kr5gfEQ5pJszi3TREELaKSE3MExlr6xw==,iv:CPMBkoWwX9gN2pKNgO3/WljZzQJ/QUbA2LuvLFGy5fA=,tag:491URfPWGEcG6U+kFncCng==,type:comment]
    GITHUB_REPOSITORY: ""
    #ENC[AES256_GCM,data:9QyO5aHWjho+XNZZSA==,iv:VtRXBQa9akg5DkcMMoL+45MrDWMpmRLRR/drYcHBwSU=,tag:CrP1jqxeLxfTIuWFbmAkIA==,type:comment]
    PODNET: ENC[AES256_GCM,data:Cq/CAzZpHfjkpvg6RA==,iv:JxPKF8FZDJSybRNkuvazh2d8UHa71+EkMTkm+Ls9epk=,tag:ttsYOMoh8PNEG5hTPm8r/w==,type:str]
    SVCNET: ENC[AES256_GCM,data:gUAxjgDLG81epMC24A==,iv:ImXHxhhac8PWHIenWWM0o6pPVceq6DeYFoQObdmwYh4=,tag:qX8Vh4/UUB05GlTmDuE2NA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:L9nOrg==,iv:RuWEJBGavzq3fiRVc3QwJ4mhazs8qfUCh/PPnpO6QXM=,tag:PS4MWgzNQR1bi0LJckDNGw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c5g23qt38utyy253gvf729w4l2jnj7pqn5s00kkzsw6l9k9d5u8qmkvkwk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNL1FJQ2Yvamt4WVJWQy9j
            d3VCLzA5S1NrNmxvdFNqNGwxV0U0a0xQdjBnCjU5U0liam1sSmNmOUpTSjJOdUw4
            Zk84TVovMTI2OGk2aVJNWWNUTEFaaVkKLS0tIEJTZTZ2T2tIRGVERmxCemd3SFM1
            KzdwTGZHcEhudklxa2h3UENCaXdsUjQKelvz1X1W3uWe7RbqsPMl32znKozZ3J3B
            L4AUKZWgY9dLSwN60THYWXzBySOGki7Qr4qJcIdUUUVsDKQi8ZBApw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T14:07:05Z"
    mac: ENC[AES256_GCM,data:U2IHU5qTCvD3fmXHUA5reIokoSK5AHz396VajsFMuae4CRhD4TaYT0RtNynub1w+LnMt2zeU01q2BMUkNl0PlLBsuD+j8gXcn0Bdx6tEaDUwxc5EcyCoOp1sDatUSd9S0wN2wb3ueOvqb8JES08EREIf3WLPtpwJlQiOMGgx2qM=,iv:Ef9X8c7O+Wo3KdFUfHLTVrx0P0mvk2KG9qjrq6gLBhs=,tag:JmlCoKrxJhHH9zoOTBBTYg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
