apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:jXqfZmOy7wqBNt4lrVMnHy+SY1ARikAI2qxYl10P9AXnjYA53UbJylHrbUedpD/PeqImQEPiXjp3Q2DLF88CAAc=,iv:h3P6aTymkBH4ZP7RecbM2CysByd/iNARgE9pIbIWPEM=,tag:XTd+O6jv/ivwWNad4MpLlQ==,type:comment]
    #ENC[AES256_GCM,data:Xo68FI4jKokyHeWVodtmJ8SQSyzDfy2/2uYiKg3twqG0jkucbRppgMYMb1M=,iv:JxcN1V8TMpiEDB49dzwhSCKbigFS/8Rkhh2wsixlulc=,tag:h+ToFrKhTpov2VpsS3ZwIw==,type:comment]
    VIP: ENC[AES256_GCM,data:giXuv1BoDSYxnvs=,iv:CWs7XoXjCL9wOCbC6BBg4A9zdW9xRPy6J6EcpAYFI6k=,tag:eQD8sy2EHXa9eOE1p26eZQ==,type:str]
    #ENC[AES256_GCM,data:nk9rKmUYse93C8sH+B8zzGTOCsIw479yujQ=,iv:y9nskz7wvtcWQhNAB30MZftKyY9Nfrsd2ZzLxHmd1EU=,tag:C48QID42Xe4JZji3MoaI5Q==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:/xq1t65c51vY/6M=,iv:Yl64ei57/QXzXJzvqPaHsz2ac/2jL5casDYqLVlfE38=,tag:03y4WUB6ZvE9L03WPFxjnQ==,type:str]
    #ENC[AES256_GCM,data:4RtLUWwD/XdmfisCrE3RroEHARE6xIcfjqAHFaPXEq9qiA==,iv:BEB2pLMpiKCFPLDUDPOZ2X+mWTj6pcKaNw5zmwBdOoM=,tag:HC0o0coQ59cNqw8orsd4/w==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:HalRgwbssYNB8Z0=,iv:Er8l/uYup37uUt43AvO/cCE6e0C3gdUPgKL3v3xagGU=,tag:KTEqms1DxprDNTuPer+9Cw==,type:str]
    #ENC[AES256_GCM,data:j+J0CqZhVHpA2EYgFqoDd3gNTQa9mnlWKpjU5HGVBKATNY5YPd1Hthpl0MY53Wk=,iv:/2tCkGQIoApgaq0fpPVgupvMPDofDjwXrGQK1YRWcCA=,tag:X0rEi8WCsqu8JT3x+ffUww==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:uc7ohsQYILv2VBnkTrsbtV4gQUAsUr0skQ==,iv:ryjU9BtiYM21a1IyWj0sE8KKwLKDRlMcQ8Mgrkjh3U4=,tag:NX3WtGdkbo6qqN+dDwjVnw==,type:str]
    #ENC[AES256_GCM,data:ZKBECXcXGyP+c0f7oe6HVdor1lKN9G/5M5Ax/NEEx45p25XR22xAF/2YZdJIbF+hYZ8u5/xaOSRiTZgBqDbPpHoGsmxVt4gpW946NmcBp8w=,iv:V6MWynlvT5qA54N9pz7jaKDzXyLKt4gan5o32hI+xzw=,tag:5io5JcD57r+9oGUS6f4emg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:6xnMe/32qOjdYQe8,iv:Rj3qTSSxMewzHDG9KtlIKOGEVraL2beR0/FcRCdZFR4=,tag:khYEqXiuHfPnDW6ZKmiZbA==,type:str]
    #ENC[AES256_GCM,data:ExFCn/d4Uuw2TxyuwZSpDKNMFWheFxuhjHcNAbpj1IsKDDiyhYEEJnqXv7ZkJo6upYejTZFvJC4=,iv:bPPWg9DevcHlda2vFFiYbG17NOfMtXSVcMwzzLyY20U=,tag:2M576xuh+Iqbo4oeQNCU8Q==,type:comment]
    #ENC[AES256_GCM,data:KHyDzRUtQEcGfCBr+kEXhftNbtLf5DKkSg==,iv:EV8PraMK47XVxzmv8Ofir6lne0QmTZ8zrLIQ5lScN3g=,tag:qp92w6pdSgEKUCA9duyuVg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:QwXPMBssSiRFZIrunskGOVKpvy6VGztdMXc8QUhqWoyAH2MzmqY1RuPGDg==,iv:LDfEdDwutT/vIIADFddQyvAo4VtHNNixxVQXFvxUEPs=,tag:fNmIUofRCUUdvGus6lVYLw==,type:str]
    #ENC[AES256_GCM,data:or1p8Uxkiav7MWJvAvlCRrJ9jdhrGltsAwaIPmg4lOY7SXU92cuhG9mYoTcg3R5dgAAZw7lV5FNctaxlqk5QS/U4E7FXdek=,iv:stn8p2KMqI102kKDSCS1ESPSQCa4iQcwumq+i8/Scog=,tag:0WdFj7UO4kNOhPHcM645Vg==,type:comment]
    #ENC[AES256_GCM,data:tnhZGpU4WehCs45PiXtD9pheWWD3q5/weDhTBpnlsC4qsjW3rmG4W7MvHP4LYpHdqEZY9kz7,iv:k3OfSvr9gJRGQ7KdmCen6i1HoZ41EZaRNAiS00GEl2Q=,tag:cAuVGyC0p7lc7Y95VE2gbw==,type:comment]
    #ENC[AES256_GCM,data:vyZjpDxbN6r91lZTgFvR0KVFc6sx5AtpImgz+25NbLjEkh0=,iv:/duFL0A7Jiu2nc6susODU5mlwG8p/dls87owuQGQ2dM=,tag:S4tH7PlM7kr+EfAhZtghEg==,type:comment]
    #ENC[AES256_GCM,data:ADSRmkn3iqWfD4wOTL67Fn4MM2u9X6SpsxG1T4AVAZRWAdAd6ozX,iv:O0DWBxkvWd8E/vbtRcMa948JeB0H4+1dOOBgeYlZTrk=,tag:YVS7zkrJMyHDp2L34VUdug==,type:comment]
    #ENC[AES256_GCM,data:LXggSssOdelf+RMeWto=,iv:DT64+obAG8m9i6w01KGb5h18qzV51mcdP8L3qpHsup8=,tag:blrb2gvcRpwGUaQ2y9g+4w==,type:comment]
    PODNET: ENC[AES256_GCM,data:UQtUlZWCajbRZ43Jxw==,iv:1n8virfdf0iSbYHCznz1MlxeMWDCz4n5jjMr5XmRJT0=,tag:9L+a5nypLf8wplIs4jgmmQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:9qDFiTPc6Gumas/2Zg==,iv:XRsAq86LPk2VHpi7X2qhVxC/3HUYU8kQMlKdF+ySRfs=,tag:u4le9NgEug4OXfZY/UH7gw==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:diWgzZ2urglRVYtL,iv:xvcM7lxFZuiiml26jltRdsw3N8Tvw44n3mrUGd2nlrg=,tag:J324u0uu9194CavLNXCgNA==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:BJ/tMuXNM7CZtGgx,iv:qiO0FRV1fLHhvjA/IfVqbsRlwc93SKrqkYUZNon3T+o=,tag:hXmFcPRAiVF7WBBGF2Y0Lg==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:WrEmRbzhBpD7UzPIHEY=,iv:MFkBfKds/WiJyihW2Ko3155kXoY3wqVf44VMXgZTHZM=,tag:Rw2nNu3yEphNvSwUqT6AuA==,type:str]
    ADMIN: ENC[AES256_GCM,data:HYiiD/0=,iv:rh8dDwkCpSgTuO2dDGrHBQ92XMbVl5TeB6rImNhnH70=,tag:88NYhU7nMSbJdI6RBiQQkg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:qMMy8TLSY70=,iv:9b3+LRV54qstvkx0zd1Ycp1PRrVALhG3yt3uu33V2tA=,tag:hZ7Qmi1uSFHvOVE1MSTF8A==,type:str]
    EMAIL: ENC[AES256_GCM,data:DUt+3wnS5F5dqi2RrAQSM1QhzdI=,iv:iVnr3X5KAUaS+ABXGqKUMP+p7RcGeJq83A18fTv4vZ0=,tag:LAjMtOjnEBw84KuqgyWv+A==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:rJ8uCL6iDg7/Y00uX63T6DRKokscROlW7wjsWb+wDqB3aqzzMb8Gxg==,iv:CTniN/0AI0TSeP0QZlgP0ILT3GY69LwvNUf0+lI6wuk=,tag:RZx6briIF/QwllM5OLHQ9g==,type:str]
    VPN_USER: ENC[AES256_GCM,data:ezb5YgkllVQ=,iv:VpFOHaprplY+wQc6NZuiQRYQQI6X3T3tuAg2ndg07Bo=,tag:vg35YnjiXTqyx1E5cd93fQ==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:kC2FHRoFJmGn5w==,iv:3PJC4/tDYYc+kRUvMeFaPJYWOTGeHyrEYJAYeAPOTl0=,tag:GMSXF3BMDP17sXuOXrSGQg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:XqFliA==,iv:59ZDKPemjt7v8IFXOjmZbDDChCtecbFw12l0yjZcMZc=,tag:VZbDEoxr0Uw0TknyMzsqmg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caandqrgue5nl44eylp4nvake7znrvxretz3uy3r0ccfa2av4aysejcgfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOGEzVjA4N25nM0wzQjN1
            L2VuSTBLcDltTVcyamhGeE9UeGpYZXdlVUg4CldlNHRsT0ZLOWtFRm1RZTIvbGVv
            c1dVL2tYZlg1Tk5aUDgxTVVTZER6QzgKLS0tIG9pdjNaa1hQUXdXMnRQc05nYlg3
            NW9GbVIrem1TckRCbTlKZVhKQU10TGsKh29nd4er5Q4Ry2QMy+2jg26CwfGsivs3
            x+SpbXv8CZOXCxPqEJxfHsMwJDABGy0k1xGfJGemn3T1k2+BwJeKSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T16:28:58Z"
    mac: ENC[AES256_GCM,data:o+xhfUDzOVsTPvdnQwSZF5GXKc7tetjrZyWvRtTAh+vuoiq8lzGChET8diPUyR9niluaHHfmxA67hrEwsPU5uS+oYh2MH9IYSQiWUnp8LEUjficW4WwDoXJDFV8rJWqFswv3RiDMdAApAHLfYX5zQBfZ7UcZiyWcEXiE9vExRtc=,iv:Wo7irmb6wJqYVldewVisANTdJX2dLW1edgoHz5jjNRE=,tag:TBpLD746nu5vQwHPz2Kojw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
