apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:HsYxHbmyyrW7OxXWraeBd3CZsltAQgnoEuuFl06+NyUgtiDluNm/kwjz1A42xfGVatfw20fIokcqaUy8uh8Mgho=,iv:vmHtFH/pWr6p6shZ8suGVvDTgbaWcrrSxbBSZMcj6AQ=,tag:GcSFR3S6lh6iZbT7aJwJdQ==,type:comment]
    #ENC[AES256_GCM,data:ujpFdVxQuaaJZ1BcLQF682RcucsP3RZK4p9X6iVRWvAYvDi4rTqOCtw08A0=,iv:RY0L3nheOyqXXoclODtFfq8F7+lsCjGFoR7L6e0itVI=,tag:9gYti6RswXoTvHrXyPpJXg==,type:comment]
    VIP: ENC[AES256_GCM,data:Tagnuto1TRR6GWg=,iv:oh71f0ouAy4odpDsVp/Dv2IiXZhssWsyN93qFXWxcys=,tag:MVcr8PHFX/K4xrtKt0SK7Q==,type:str]
    #ENC[AES256_GCM,data:FKvDF0Z/kYGs7ZJhxAovgN/T/QKfTuZQkWQ=,iv:tCmYlfV+1KB+xDG99l60p+D5MiYz10SQ7gblZnT0jfA=,tag:4wj9QP358Pzl2uQuECm80Q==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:Q3qGVZhUIO4nSZ4=,iv:n5voJ+IBZRq2wjIefH4BaTAG9XSgSsVkAMcPLxvsKeA=,tag:m1SoaiTZevtvc4gK5c6+GA==,type:str]
    #ENC[AES256_GCM,data:VrkUJViAaeCcKUTNz6PTvSX5UnCnrFmhm+4bxg4DyCAyZg==,iv:+FX5wzc3UMwPPbyt00vfYADpvQ7Z6GmKabCICOH479g=,tag:mQrzlcmpfUAM7TXMx2ywZw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:cIdCbUlAUFoMHec=,iv:YirY76CkPYyVYZxJfhEzeeBFvGJaiLFujpM89oJ6ztU=,tag:1UB1pIwTfCNV6I7wq1V+UA==,type:str]
    #ENC[AES256_GCM,data:CzIKNMFhVQJ5PX3Mv/hL5Ps5PnZ847SP7urBXsEsKjQQbEn2IeNuBw1mt6eM8vo=,iv:7Qb8B1xEeEXcVJlv+HVkqpMFIJNfT4Pei7kAryldRB0=,tag:xcOjPghrt2RnvsvpBM0TPw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:YzCB6q21Sem/nEv1z7w6aR3jucmH7EbKmw==,iv:T66YzZbchCxpsbFtWCDbUwSyVg0gWVuxVSup8f+VEt0=,tag:1fB9xowVwxM112r8ixcSNg==,type:str]
    #ENC[AES256_GCM,data:soJ/sZHwGBNyaBKPP7JoidQ9SKYcXhrQ0XA7RfQ/ZRZ1zrIvL+4duW0TW3tidf3z5A3SgW+nUhhulKZrDliJlZv8pEQCf3G2g8W+1QRVrr0=,iv:eJaDa+ZsOKASftljZztfMKHz4ms+QyRD431xP/oE9hM=,tag:jKd7npRgrtDJm7UBHURO/g==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:qwDixihdgIOQoCPr,iv:LpxFrRZ+eq+fAxv0bCw2ERSYGWAYtw8cOfkeL6LL+iI=,tag:uVdL7AukAmnxbPjvQOThMA==,type:str]
    #ENC[AES256_GCM,data:ggqJjuuxmWeUI2ODw58/rm2iC42z0IcBf2RuZieTeygQT8lANb0OvGqh1IN0u6N4O2KCIIBfdgA=,iv:qmmggqY0UPE9JcPhecRH6is/jNs92WIexub8L8zzFT8=,tag:8j7POLkpjeE8hXcelyfz8g==,type:comment]
    #ENC[AES256_GCM,data:eGjcNT5F6rZkVtUNYs21BCqcZRs4sl2Cnw==,iv:QnwAQwrmGM2oTlwYpV3KmttO7eWoND9kFNq0pGIo+/k=,tag:Yuf1o8wYyun4+YQVSXoFKw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:jN7s9goX6vaztPq2knKbRBYi9NR+8bikP6Vp2GNSwXwiCNECD2Qcscedpw==,iv:TJVd3CqRXIXieJWIm5wSfUEV2UiYGwsDrjSa9IV24E8=,tag:Hjc805aPnD9zJ/6ukx1r3A==,type:str]
    #ENC[AES256_GCM,data:xqpBZtObKb7F5u/JLQ==,iv:wIbcS0n9iICorQsXv01g/DsKzG/h6UWjzFprg1XgIco=,tag:CxXYUrHedZ6MqXHIHj858g==,type:comment]
    PODNET: ENC[AES256_GCM,data:ZMu7pqQD1zx7gMJauw==,iv:sgt1C/kzI6dvbRPt2VIORJP7VV7CxMoaaQU6yv0HOJI=,tag:PiAiXbJQ8947wemcF4CdwQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:DfwaDiVKhz0gHSR9fA==,iv:eTwGhdFYvGOyt97BlTXnRKHkDpSZuyQVSAvx1imsjGA=,tag:EP2IR5p3DkXtvictwN2Geg==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:Jiy51Po0w0b+wBORXr8=,iv:8pmYpsosS3IXlrrcErATYHJU3VAeK/j6g5kFs3ntB9Q=,tag:J73ms3+cgMqqnUPYNC6g+g==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:Uwn8VcNAZbT86RQo,iv:bO2uwVjEc44CIdHS5qnB1yZuarFVxAo6o9Gi2iUogsI=,tag:mABfHS44edfbDHB+3G5MjQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:idysRQ==,iv:+2StE23o3zy26EEHQRzoB7GKaPCSSmwPl7ImlnK0l2g=,tag:bRts0YXy08+VM+5a0dyRYg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c5g23qt38utyy253gvf729w4l2jnj7pqn5s00kkzsw6l9k9d5u8qmkvkwk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OGU0dG5LM2djUGdBL2Zk
            MHNoWk9OSU94WndtbFljR0w4ME91S3U1MUY4CitOaWJsd3U5bk9PQzVWbzJYNUFT
            YWZQVXV4L3Qyb1YrdVlOakdhZGNvY1UKLS0tIEtxeDJSOEhqYzJmL2JmR1RlL3FD
            VE5zVG9Mc3VpcmNmMnExZkNUSXJ6M0kKMLxvKCM9T2JuRx+un3chRCJ6X0KhHuCF
            //lSwlZX01mybfN4gRKm9mOszM9exil7wH3PqQCPn3v4TrzSpDTQvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T18:02:39Z"
    mac: ENC[AES256_GCM,data:Q28/1bGsci6hlhOvmoP/r9hfk23u7nA23oyI5BAaaPurmiV/j32vNYsLByrr60fxxInNKs4tmfbVEGJg0ili5RR6NS/XYGUM1hrGRS82h9t3/Uro2SAk9nOyAxYd0GSYo5eWqgJLZ23LPsQyl95E6qpXTzdm5a8rvA8lxCH0xDY=,iv:WW2odqjuYOrVyxKQTcRyqi/O/lob9DWGUc3E+sltlrQ=,tag:2HpSorP61yZLs5o7BGk7Og==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
