apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:rX7pfPp0l8Y0Nuq7EEHJUhDQymiQoxd8GA+zZZDPQgkkKkaWr/8j2uU97DPQvs01Zidrg6DJI5UUWV2nAogsw1U=,iv:ir9MEqbs+n/G2iWBysK7bYeNQS2fZq7DF8PlDMq3GIM=,tag:HA+wgcnrWHwW5FLJkWzVVQ==,type:comment]
    #ENC[AES256_GCM,data:7RHEh0Gb6LTG7CpxhA8ifJn1yrIZSFPWqaHvkD+I6PKFDjnJ98fZCLNF+04=,iv:DNc8a/usp0iSB2OtmM1q7loWmQhk+pOGRHm1/86Cet8=,tag:b1JUZyltdULFojxNqLcgjA==,type:comment]
    VIP: ENC[AES256_GCM,data:pWn/D7E3QDNiR9g=,iv:8xlUYN3YNBRmWPOZr1AW+OokbtN/LzavwWc1Vwie4ZU=,tag:ZnSeAfIDm2BrmIlw+rXPcg==,type:str]
    #ENC[AES256_GCM,data:2PG71ffSuoAuRxNCcKeMx4McTrt8BEqkuqA=,iv:dI86uluWsAZ8GLcUqWYCGKNaRIBtKAm/7CUsxH1K+0E=,tag:lm00OULxXq53R8yYom62Og==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:dQ22gdXG/o6mPAQ=,iv:dxgKD1/3kCar55fsID1Se9GyS0lUmp9cSY0rcQtzGUA=,tag:WImXHifXGPnqPa73vdNrmg==,type:str]
    #ENC[AES256_GCM,data:VC7ddcbyr7PfX8nUzBqP1tzqW+YLyKbzO8ETFpP2uenVUA==,iv:ccD+dL9cfcvzd708FvJ0p8SE7dZjlaJndUFMHjoBJXc=,tag:q3DMD9sLlTB1gEqoPS4uVA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:j72BmEC2OoRevHs=,iv:vWHM6F0FQKE1d2kfCOZqF1xSIVB76xNeHc60ir00/8I=,tag:6aZa0gKr0gc98Uo2XOAe7w==,type:str]
    #ENC[AES256_GCM,data:RKkpujz/DSWgr4kTO1IjbNdHjcT7JNrPdis+zd+Ku9c6bgWe8HfTCzYE5PYTTK8=,iv:mVnf589oQwJqRa7uam4x+zEOpTMnImLE1xtBYe3oLlA=,tag:NvNiJ6VrrdKRavk37y0mHg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:KyG+TjgCWYm/GMQaOeIp27s16qHNzUFW+w==,iv:cSJFvv4FFYIarP8GrIMaonYaHxn6nUbX7FrlKziiaOE=,tag:NtKcX/+XbP9x+i7MBJ1HTg==,type:str]
    #ENC[AES256_GCM,data:xBaBKYPUUxJphZ0gqBIlRmuGxSsMUIaJyAu/Hg2e6EwQLIQikqrKv1a3Tgd0eEtUW1bSSOk5N5dMUlWxkeW2B8dfYJSdPHY1AbUNNFS8zX4=,iv:gJMgwLxzO2zB0NXdblrDCjKuRpaHAYwnZpI7W5WTZCo=,tag:fS4rO7ywRFoqC4R97r92dw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:KtyVhY7Q0netZGvZ,iv:V74+COaciNb/2yTETH0o7uAt/7upUirP+cdPpEmk+Lc=,tag:1cxLUp6uQFhYDWXrj8BB5Q==,type:str]
    #ENC[AES256_GCM,data:4kT5oh0DTpbxrqfb/+jh/F39r78HgGmenSY1HCi5X+RI0CVwc7Qk68FemztfC0QflVse1sYgiB4=,iv:b8JxsVhpZEXuU+WItarlIeqfL8HR7UTv8Knmz5wzjLE=,tag:wcyM/RUNnYxHFhKBUzYA3w==,type:comment]
    #ENC[AES256_GCM,data:lQLDM5PjI14q/d54vCH/MZ3pjc5YnLenHg==,iv:+okgCckKco4F+3grHCFeg0Ha8kd05aVYOwwNaMBMwUE=,tag:BiK1C3O3gcGcjd03bnD7qA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:nL7zZtKjKzSuI/CNn1iZKERkx7V8oUrsjte9Ht8EzGOPWsL4t+8RSHmgwg==,iv:vpZWcVVKyQNoxFSdzvcHtYC2ImBB5sLoi0uZPiE/hnY=,tag:dNBmYkyQkJ1FoK0A5dLbMQ==,type:str]
    #ENC[AES256_GCM,data:ss0EkYupW2vKYLwb4vf8Bjf0pZBZIGcyfI45t8mcxZJkEW17lprc+v6sHnYZlzPztYoilN38zVqC8L8sNIr4O0jHTI/3jS0=,iv:/TIZKdKJoq0ORCB3iK2gdlqNm6oHOWNJiIycQnsEy3c=,tag:L+ja1opGDbw2qwYDOWcjhg==,type:comment]
    #ENC[AES256_GCM,data:x3v+LBZP9m02wdQqMlgQYOFwQEiXIA0/D9QucBJJGDsKE6Y2IuLWg24x5d0M6MP1UVkCdHxP,iv:qYjTpBLEzQg5wY2o4rscpfUl5mAT1tPAtutznV05PvA=,tag:FOiIjVNqpN6EsaKCx0E8Zg==,type:comment]
    #ENC[AES256_GCM,data:94q0PaqaZDkQrbRbuOse67wivmz5m5B8ZZqruVmr6UkFwT4=,iv:TkZihL+sOAzYqvItaYpOWF58/QVEI1fqryam5+DwwDU=,tag:RIQtzItEGY5Z9NMq8G8w+w==,type:comment]
    #ENC[AES256_GCM,data:ItnpNxDrYoFeKooof3JVLtTAR2m/LpoU1YADgDsom821mNj92uys,iv:a9bf4/Um2/Dmp4ua+8xVTuEldQLSBXmw5chwHgA/W8Y=,tag:l//WjaOkxOnjIaSc18U/mg==,type:comment]
    #ENC[AES256_GCM,data:57DKb9jq3EEU9UDJwhs=,iv:3xvajx3g8OrY03ZteRDepHNIfps5iaW8qRlAXCs1ECY=,tag:uBJbOx31bwYO9F46rbRc+w==,type:comment]
    PODNET: ENC[AES256_GCM,data:W33nceIOBesiAC6vag==,iv:QWCpO/2tHEpaTBDBNN1KiQnK7X4bbtdEM4XoycocVLA=,tag:px3CkduTtQ/bPMnT0HJOdg==,type:str]
    SVCNET: ENC[AES256_GCM,data:Dy0ATgSqAuqFYJVRWQ==,iv:LytScO6DWjfZKH1lJQvdaROZfqY3ZyXOmNqFfIfIvE0=,tag:+iVnALnnI+9E+XX4BSA/Ag==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:oJwPkMmiFQJhmhfC,iv:ZFSvy0b9RnQIWGDECiyRiGbUnDort7TwIA6AHqXXPfo=,tag:19j03ezFQ6zWMM8ZSXnGVg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:h58WATkBqrWLyRWX,iv:fdLkF58G2G0Sj3lyOf15nuwBx8OfqjD+uGS42J4laQE=,tag:pWMbGopW3Q0W79LLI1lXBQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:PU91eDh+LjVfkrVE6Do=,iv:MaG2VT/1SOjwEWDneDSXVhucI1woP5E68J7WRJxpYkQ=,tag:KUzKbvw3oAJKAltd8pyyPg==,type:str]
    ADMIN: ENC[AES256_GCM,data:4ApIBDM=,iv:Jk3s8wQd5EfXL1/n2gf2leZe8ZD1PxCXnBS4A7n0U3k=,tag:/vm5ucLzGB1oydjgpBqVLA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:nf93CP20KFA=,iv:Ias4LubkhoeLYGptgJSE+hY50wdTSlL+iwib1GcJmAw=,tag:lmfPX5ojrZ12xrMnAUlIxA==,type:str]
    EMAIL: ENC[AES256_GCM,data:amc/vJfCdoLvrbnk2qlJc47RQ2k=,iv:sbMf8yUUy8OLwRIyjO0OIzuwB7PVnnPvy9uv/m0X0aI=,tag:NUIvXakPivUqYfPILHivhw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:qE12O3621ajagBPwZdqLQ1N3PUg6JftnuXtasWjJM5UYUpkH0/qjQw==,iv:HFZTHyrywa4+sXtFqZyTBoQLP+a0wDdQ341iglHam+4=,tag:Tz84AMTHPPs4eXKC4IkrZQ==,type:str]
    VPN_USER: ENC[AES256_GCM,data:2wC6O9AGH9A=,iv:Hyn5nAsjn6HNWYNq9n1/dmt8FO7mFckg+jB/+XqBX3Y=,tag:V/3K8uXpXXLmR7HbgusJ4g==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:ZdItXkK8T3kIhw==,iv:68Isyi/+gNmFz2wA3saEef7NrKfHt5YtDuo7vESG+kY=,tag:RbWOQWqbpljF4R3h59dyDQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:wcFExA==,iv:A2Rg/LVTt1bJtQ0qN85iI6MjO6ZlIel+FuGTxluD+Q8=,tag:mNq23jYRKHBQRGWOKthYbg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caandqrgue5nl44eylp4nvake7znrvxretz3uy3r0ccfa2av4aysejcgfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3K0w3aUtLcVB2QXJPRnB5
            Tm1Qd3p5dFdaNXFrVkptYWxTanBEajR3L3pJCmlnNlNUK29wT244QUk1Qmd2TzY4
            dC96RHB6TGV3bm9YOXBSWXpndFNlYVkKLS0tIE9hL2Q3YVZGNE0rR29YcUtLMjhH
            NERUUTFrdnkwTjAvZ2ZBbTR0c1NtQTgKOvSRpJkEylQ6+kplfYK9eCqY+teD/oUZ
            hE3/MRmj5HT2rjDOEMceImjgRcldn6EfZdHyrV5aQwkWgLtRAALgOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T16:37:10Z"
    mac: ENC[AES256_GCM,data:cXRRX36UrPsvJtHY2pVVGrFWbvlm8b9t9PUKh85XcyBBBDdkom5eEF3+ut11C4AsZE2I4MIuJIrF00FKaefByUsxMpZ+EyWJXU1mAjs4Lc9hkzpdhlVWcvUuHtFaH9/t22XhkG8jsMwhc5bTONtlsO5nv0YsSTAdGPK7Qtw3+ag=,iv:yvZp8q7mfT9FTpLAGDETeey2VJVhC1jDNO0JDaGTfrk=,tag:VLw8ARBPYR8NBQTBRId5Fg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
