apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:ve7BW2xHbgu248v6iqwhrPu2lgDP3/vKZL5OrFK2cEiu0zxuAUM4KldBQijYFUWS5PfEr7kzFV202sSzOpdkevA=,iv:0Ck+b4vb3Jf0sEBceSIC5SB192d//F2D/Kjexinmrqs=,tag:X//5aDd7sKorQgwAnqgYdQ==,type:comment]
    #ENC[AES256_GCM,data:z2NJXJZH8rP8x6n4H7IGDtyzWpohpnrny05o8v6YMahuGSa8xjdzB7FIcJE=,iv:L8RoG850n4XduvgVMDInFlKVkPA5ltUEZ3mbf/GpeD8=,tag:tJxvN/9F/UxfX7K5pivxMQ==,type:comment]
    VIP: ENC[AES256_GCM,data:RmSMBVOXxl0fND4=,iv:LkQzuwryke8I0327+WzmBr7BgEPt0sGOdupIB5T3tfQ=,tag:dvY32ZX5z9dunAsbO9AQWA==,type:str]
    #ENC[AES256_GCM,data:AIwiWOEqxh5v0UncKoeD3KP2sYflVvx6VHQ=,iv:JfwwcS0skDL8Q5FShCUzj3Cf2aGts5b2/6IpcyxCkQw=,tag:U82WZFeQVEp1QdY3K2KDvg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:GWyXQpZK808/PY0=,iv:xRIUrbEj+0ELIF/EdIX6Sd6uh5r0/BHSWRX2oyD/aHY=,tag:EY1gLjvtb3i/4TUpnzsqnw==,type:str]
    #ENC[AES256_GCM,data:bNteCrq+kQMw+9pLe0USM/YBEC5NMU9GkIEOH0WlpSaPog==,iv:9YYGCKx8R0ARIK/AZ1ftbe4UcIk+YfhJH+WEG5JjSmk=,tag:uarPfv+AHZgCWvDGnVYu9A==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:VaXJ3YZ7NKaEq/E=,iv:g3A5cPFPbv6RXqqr6yes/Neg5ivBA6y46R4+B3fOSRk=,tag:Ud+VfQJy3J6zuujaY9IHRQ==,type:str]
    #ENC[AES256_GCM,data:rvqZpRJolK1L/V/RAnr18HnEFArD6xWQjS/0zfqXo2bItvXtVGaBfFXst2R6PGE=,iv:dB/SXQoEMuAi55aXPmFfkILaFhs6mb5Ov02a2uMIFvM=,tag:VdNK2geMHUaE9iYpgTl/zQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:OV4DOrbRS/idutZJDc1gLVjqqMB2ru1zjg==,iv:Rl5mNP3HS22nvhYX2FGa1g1iWMDVcx5IWGslCjLD8Ug=,tag:wLDilt1VVTPaVnR+i/4yog==,type:str]
    #ENC[AES256_GCM,data:27KXX53ymr5/4NCHbXoHYA/oqG8dhFyjAZPg7do/Qq/srFgCAl9tRccaA5XgsDLCVXab6/5+wL8MU3mY0BhvMYA8IaRPhRlZb/q+/wVv8c0=,iv:ldYHHPh1UgKE70TOzP7ZDmmEmIGuWLvVfpNojBtfPwY=,tag:z6Eeq6I2mdHrrnOgWN4F5w==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:1D4C9t6qgA7G/ZNl,iv:RliDILHysJidwPXw5+gT2q5Lc41VkJXQo7+0JVd++oA=,tag:hm6ij7eU2HY7DxI62hCkIw==,type:str]
    #ENC[AES256_GCM,data:JrR6fyG0FjB0qItpd6wCfttdpRQZNx/Vozj1dLf41TTWUVKHYsMtwf8ta3BkkdLSOfYtWKe/AqU=,iv:bBpElcYp55ohrIFoclUjTbj0MqJSG5tnEEOSygfACwI=,tag:ggzqpZnE08rPE9+8z848EA==,type:comment]
    #ENC[AES256_GCM,data:NP/SAP6VZUWLr7AXzeVIRcsiCtNQHxIVWQ==,iv:3w4s3icd10/lISUUYELFxxkykGNRogRShjfEMySR/9M=,tag:Z0nWQqhbNBy0j4u5uSqa/w==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:3eqX4rufh/8Pvkau2pkDsNDfCu6NmJdNXkDVlVmNAbojFCf4gNmT86Lkig==,iv:KjMwsspjDdv2kQ0AKyyZE9kmApWBLxazCkes3tVKfSk=,tag:C6y0gAsrC9U9OO6254Pqkw==,type:str]
    #ENC[AES256_GCM,data:cx2jjs48Rov2TGIDwQ==,iv:qp4wfEk4hHBefK4k5/8mWr93Sh+jL/UQN2jR2cctdaA=,tag:aS4a/+/yIM+N8OzdyTJAhw==,type:comment]
    PODNET: ENC[AES256_GCM,data:QMgba7NHKrzrhdfJMg==,iv:dtK4khQOjmXnGxMCK460D6/Mc6rx1J8fVbVcVUlrJwM=,tag:g7qf3fYgdZPYBdQpedrl1w==,type:str]
    SVCNET: ENC[AES256_GCM,data:F4n/9i+4GwESgcz6iA==,iv:EziJ5anRmaVG456kBShWck4CSaqq8q1mEm+Nsl0T+qo=,tag:G7q9yL/GsOMcLSDY0aAHGg==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:ep11mi0jdajvqBnCr9Y=,iv:JqGo7RMetQoyotoJOyWu1VPtXbWySOnhgGhHc6xpwvQ=,tag:mQTivOU06zeBSSnGKNvD2g==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:fS8Z3wVmMABf+C7O,iv:Mv6Xx2Zn2pjKznRODXBTKreiqR03kLQKblUvXQnzmGg=,tag:yY6XZmnmUfqcvhpA57DtWA==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:TO9WMQ3ZWhJakfzE,iv:3UhLkKa/VR7U5LoxfBPzoeX8u2oaYVWLOET4nuPZVuo=,tag:fTP2EDpexheIRbFGeNi+Yw==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:Vw6f8Cv9hk9glflV,iv:UNPHdi20+8xhboPsiBnnre8eil0HtLyi/BfMqU7inLA=,tag:Ws/eQ4xVnRt27UtwSm4Dpw==,type:str]
    EMAIL: ENC[AES256_GCM,data:Un1tLVSl0VU2s3kJimeWxXgMqvw=,iv:3URqqaFE+ukZ7fXVhD9o0lxkQwrksuzm5UKX3wU3ii8=,tag:+wW2h00vZ5VbjHsUHeP3Bw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:Ba+iUaLhWT+dRYK1SDemkB7uNtgnJE8mtO8Gfi3cLyF2AGE2OZLI8Q==,iv:RprbgoQMi8G4v2X/R7y/iTc3/N/qmb6cHkrYKcZlgww=,tag:KztChJAwPGQZ4gjfgJ76Eg==,type:str]
    ADMIN: ENC[AES256_GCM,data:FWJZ+Zo=,iv:0pT2NCtnUcbv7J78I0Jw2s8XRDeHWTMBMSPSt8rwrps=,tag:tBfITNXIsHMKHxu2fQsvQQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:lyaEZONz8cA=,iv:eQ91aoteWMJg8rTbPPzvFAsjZdi7ps/WQgfp3T6UFHs=,tag:1K4rGDAhQd8Tubm9dnc/qQ==,type:str]
    VPN_USER: ENC[AES256_GCM,data:nEDOesIRIrc=,iv:/Q0ekiCq4rRV8/Ha6iLZF0jdqRtcjs/HjlYdAn/ClJU=,tag:4CHfkGHuT6mqMUzF4z+E3g==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:jhCfapN1mrksnw==,iv:YHuoPFUkCjZuYyaREiHAYFDqyd4FSjqfGr21Blyf3FQ=,tag:WqR4jIHFCpgos99AykYVpA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:o75eLQ==,iv:YeYn0dJOn+JMNB/heCz0+dfZnDhHjsXKvduFTZUesqc=,tag:H/w6vfkUsedC156mYDn5rw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdWpMTXdqQnMxeWd3d2s1
            M29NVm1CT2hWNE5DbmQrL2ZFZUFjcTVTUmtzCmZKd0FMdTVuWVNEY1ZHcWduR0Jj
            Q2F1RHVCTG9aZVJzeTFvMVdFeE8xTWMKLS0tIGFHeUpjM3NITUxLbHBWKzNyODB5
            Z0VMdU0wVURvZUJWN1FhTzZVUlB2NU0KWAczZVzxFf3/Njndrr+lD8imnym8qXoJ
            yhJSfet9jP+xj3a2jvoPsVwVDBTuDtjQHcqMpRkGv2Le0W2YVlzcXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T04:57:42Z"
    mac: ENC[AES256_GCM,data:J+oX0c1jC6Nee5X436quz0YLOc38pZaxHCAnDJbYNqLOSuyh38cjRuz2buuX9+WipcxjwcAUdJMlTunVRrxlp5dU8K/5IURewLBKjMBLw305SKbcizRwXzpIW/XjIRMmFq8UlXQ49NJwvKHD9z2SBgR6ygilSBzVmTgrSH1VoPo=,iv:Lg3lndkhpqYApz++h1jRSIE4AF1l1MwsqlTRZNSEhA4=,tag:vVJs115+5SJeBWSWdwaC3A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
