apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:+DI35nbvev2r6JVKdxNEwLaKsskOU3TvZ68Y63zYsvPRit6l4/IO/Fj3gGv1OGNlL+uCwW/lumkY89J7Fo/ZHZw=,iv:WDjlXeC6O49SnMN8fwTl2iC1W85tELWpSZq2sW7SClc=,tag:ILCjimpU4pN3+1CxXkFtjg==,type:comment]
    #ENC[AES256_GCM,data:yfHPWRAeJ+T9uJ15Amx8QHTqZWvT1A07VEMIz3lJ2/gFHZyKK4/8ZcZvS9w=,iv:425izc01gfLVfYIfyE8y9HLtY9mJwxwR7OkVtC0M9K8=,tag:iCKqa7tHC6ugin1jYX3Frw==,type:comment]
    VIP: ENC[AES256_GCM,data:1slVvk/JfOhcBxU=,iv:UrF0e2lPPLhfnJGAhN6kLKPrxgP5lPfpryHLWHNYXW0=,tag:ednNy7yes6ocsnHjx8ZR6Q==,type:str]
    #ENC[AES256_GCM,data:LzSooMpL2NUfwtE0AdJHfQmPlJO1i3cWszHK,iv:xaHOU69BqzhxUZe4XQodfIEzVPIem9ed09OM2/AZZaQ=,tag:glPIDF/Na6orQD9YzffOnQ==,type:comment]
    #ENC[AES256_GCM,data:WMpu7KQ5d5vsnPgdD2wM77+GLyY3w4srljzYDAY/Vd5YRQK//ycvEPx5MZlgr9tFITb3bUDPFYHMywM0ln/bh+9m+rcfwfZgQMEhnwqaTcQOGilVO594d5c=,iv:uh7nToV7Tl0Y1B0ybYUZImxOwVpfvu+OtucdR0/Gq3U=,tag:mfdTBui75gvLSzgZe4/BlA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:HtyZMRnuZ0rB6sc=,iv:TmatidEDKicMVMHuDo+lt+HPpiZdxkGFNEIHwJlV8hY=,tag:zyKwyCjQNA6afixb71isKg==,type:str]
    #ENC[AES256_GCM,data:u6LUWias80nxykzno+CYUx9faUhLNtedw/0IaKJ6cJUTag==,iv:WuzHt9Yp3/tPX7tPySeconhhh+dSTNgK3p2ka8AoWAo=,tag:FBz+rZMQYug59AE5tIa6jA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:IY84KuLV9M4TUr4=,iv:n8GvXEiqbtSFi/S3NSEtKRa+dpckD4WmIiRUtUwcCDI=,tag:YqfvgkmyraYIJXaKK2eaNw==,type:str]
    #ENC[AES256_GCM,data:qkvrW+IjY/9nATZqblsArhO+cjS5vCvXkiryQtFFLYsCWYrFRRf8djwMkphVHK0=,iv:pz7AMZxxS+IIbQEGw498XRjqAbJ7iXVNMuW72krfBOc=,tag:yPUU8ifQIRQTlSylGO8fIw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:bNCwW3LmjhiIY8FDCMkpg9e6/vWfdaAz/A==,iv:C6YutndW6zUdm4wmBUJsGC7CmIYWGSCDOSKIUtltufQ=,tag:gA3Vv0jNv//as8oWP3DY6g==,type:str]
    #ENC[AES256_GCM,data:2vs3fqyZRwKJsr4OsKYRtiSdJ0q3YQfIDQnWV/rfo2ZTnR5W8tDlScddCgv8MhSAVM6dl07oiqBY/7EDWS2t1Yhodp+nw9QWMjWAkEsIVh71gA==,iv:pfXd7B9o9x3KpvHQS4Jr1y7IEgs+8ABw0b3QPu/jcmM=,tag:4dI+wbTcbgPTHIGa4q0auA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:cijWOqWkpNBAaVWh,iv:X/9NpLr3yJ7PZ631MmSwx8mv5cgrboBjZIgF9amMoGc=,tag:RP+jOwRCoFcX2ThQJHtkvw==,type:str]
    #ENC[AES256_GCM,data:lGsi24Gz/gimw8b4KEzi0AU8uZLFOQLT03b3XQObsyit,iv:o0Pig3ouNMw0Ppy/7+pJEW1SbNr4YdR0OR2X7R6rqhA=,tag:+M7oJkYuPBgjvp9BRr9t9g==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:B1S69EUNMcvZyQEj,iv:Chrpw+U/f7GmqoRWriKanp25d6HcIcmfhHhBnEoaEm4=,tag:VsSwoR2ScC7+TLA2c136zg==,type:str]
    #ENC[AES256_GCM,data:fZR5GqUVSRmGS8Bz1TgnuBe9MnsEFA5JuVro6wkfzkzwTHvINw2OYNE5umCCx+buJQy64xJoe/DdV3FUX6uC05SQ64qnzm6OK6jwc1RHopk=,iv:afVlMMsw7RaLBkyKkrIpa7gIth1OKzbYJIb+VQOlu8o=,tag:havBh8ZiRNb1FCHMnE96xw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:QwVaFETYdXL0W7ky,iv:XG8xLozJ+5JR6LBlKxKNPB2cY2wfGGwTBSEKiOeEvj0=,tag:L73kS0uvNTPyW8mMtsalWg==,type:str]
    #ENC[AES256_GCM,data:FhqqVw1ocHHMAXHFl3McOo1UivtV2xFwu0HVb+25COeQFTimTgLG3S9Qj7NAURTjNrft8YBkh7cyeTezUSmJr7L46UY/yHc9NN8BNC9YqnJKdE5g2p/R,iv:YHM6+Jnb7T+Zz9SCgzPWeRLiHGjct+TmLd0ZxPmK7Ws=,tag:gRlNmHJEyIC9S1WSbEDQSQ==,type:comment]
    #ENC[AES256_GCM,data:AB+rqZzZ9NR2RVmn/90BBZ+EMkHT7PP8kPirFkTx5Pw8jtVMSl78bOTUXzAV5yEXsE2kfvV5XlQAbnbHaWYiRWCHIHM7DMTamYINXUJA2zGmuzyCCShc+IAN4pZWin0rRpxA/xfaRE3oWrAxQY7CIc91qNw5AEdG6YKoEQ==,iv:iDUcIT4u2VEp89OwXKTzHlhsbcpMmWLQ/KdimMSmGTg=,tag:QLWZzjx5sXc3cWiVHDS/YA==,type:comment]
    #ENC[AES256_GCM,data:B7lsas8KP73n2UFmpIK3CrysWcodsP4EC8ulElq2SkfxEWNGniSpGJD0/+0eedIM/hD3Bq5BV60I90bYZmft1+POu+xwsi0cnJGvTSiuQtI=,iv:H44xluS9Z6L48X7Eurae1EGsNqIzHoVBOrqkYYIwFdE=,tag:+yeCn7f6PspC6NriQCPWYQ==,type:comment]
    #ENC[AES256_GCM,data:XINy2a3u4MyhBsYHeP70kDeqMmgUbFXPti5u5MPDv9XspmPhrUznq84BEunamBbRNaEuLt71,iv:7LUP1KHqdHf6wNQ9FzsNun2jZB5flgtt0V+vmrVlVTU=,tag:5YxvLvNKGr6UAGQUfBsVGw==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:26wYqi6qaqCQY0a+ShM=,iv:YXzbzSs7BNIppRCY+r2n5lG5OKHXni/IKrAA7iv7Dp0=,tag:3xvhS0bedBnaI/GTlRrWgA==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:d0GvdEn3a6rKz31MToPKvvdGG6o=,iv:dwJlSXK93ULbGDDA46NAgQuQ4J6f13PZ0r6kUNBkleM=,tag:jnFn6oIbgHqX/KteQfZh5A==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:N/J+XG8ViSCbBt7ZMWXCIiPhJy89uUgYzWGaPzVxQJX1z/f4fSCdDw==,iv:yWEOMmr8r04lS+GChpJ2YsckRcaooTiDVYeQcQPJ8ms=,tag:UoPWqSOEVL+2q1MxYksssA==,type:str]
    #ENC[AES256_GCM,data:1QDvOaf1Epy59WnREjgi1Na5I4YJIQYtUF5+3UsO445huhNIZNMovtvi9V+6WkigI3orw76b/HE=,iv:m5hfzF6GPT/GiIp//Hq64xkL4Eybkg5q19Je92Za2xw=,tag:mrRF6/1yguLq8UVjjSsa+g==,type:comment]
    #ENC[AES256_GCM,data:2Thv98jExVo7wP1a8v1PYY8fzSDIbiXWaQ==,iv:61hAMaz+AjC1AhBqN2jv0n/hlxVH9k7adKAenp/A6QI=,tag:uK9SNmjPLwLemOl0uB/YAw==,type:comment]
    #ENC[AES256_GCM,data:4CJdTtThXbOZotwgChjGDGFG/dOO21D08Ec5Mi8kRMhrIJoZoe8jI9O8TauKnT93ifc6e3YMJksnulirwZPV3Q4KbyouBq2Spa41mlQ=,iv:YECQX8+bqS11n98pclsWM3uB++slLSUcw/g5SOhy2S8=,tag:Jg4jC3UjMVUuOE3lGrD3Mw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:RV5H3Ze8CBFOSpjiFnUCekVVqdUOnxW9/LBhU3bpB3gZg/XXO/w2oK0rNw==,iv:J3Er+z/UH3IAW3dGU3G1B0gZgY5fyaPjomVgE/U/t/o=,tag:TF6aD3AEzDHjHJ5MA/sd8Q==,type:str]
    #ENC[AES256_GCM,data:iE7a5541W7hu1tiUTayl/hHNHkXVuFQKNBNxFLsz6XTcUx9JFU9WEjqOOuXH6uRJdt+oFMNI6/Wzro1y1iuIl10qw7NMxBM=,iv:KHpyl105lzPT3P8rcCTP3GeG5wswPThriQenOUyEFHQ=,tag:ATtDlwrFr3NVXVyCenMEHg==,type:comment]
    #ENC[AES256_GCM,data:0GkrxGoAOHdHtiNg64AcXgBfePNd+YRs5mUxNguy+go99gCjJO1jwRiEHS+rkv1DVaOTbQ4t,iv:+HEfWx09sWhGDoea+4IJyc5V5c5XO37TlYxM/ozxI5c=,tag:+nm23vhegfhtg3C7c7lDAQ==,type:comment]
    #ENC[AES256_GCM,data:bwfMSP0oPaCYt11EkptqsQaklCXY7g7iwcNrr7i1DBmLLv8=,iv:K9c7YlyKLCPWdk/a8s0g3XiL2Xwz6rBs5D/Qcq9Y2QI=,tag:CzYBxuhZLsyKCbw6HDmdaQ==,type:comment]
    #ENC[AES256_GCM,data:oc6UGPV6xux8VJDKaIwuqQCmusWVaLI4sNf94am3bxqzwlvoF1Ew,iv:V78plh3VcFkrYAFmK0l1Y4NZzkGUlkCfjO7cCRwWbb8=,tag:ZyW2n2J9TwLGnUfGpqGHYg==,type:comment]
    #ENC[AES256_GCM,data:alsN4fE8XvcY0hjfsQ4=,iv:WHREW/++4IBkz0qxA7+pTWx2kv0C7Ch1B9uRtOgevLI=,tag:9XUoURL9g8NyQRgaP2AEPA==,type:comment]
    PODNET: ENC[AES256_GCM,data:4okTVv/QPCRb97g5WQ==,iv:BzNs/P+ECXB077KEUZ1wMX6E/xEMcc9OSDqL/99/KQ8=,tag:0lXHGHdtFSL8aGq0js9txg==,type:str]
    SVCNET: ENC[AES256_GCM,data:9UioY6HIgH6Oac8J8g==,iv:rqCpczC2RmyAVUtpEQqy1nFgW4sg9lxdasrvrSZ9Gnw=,tag:FvFELWagQMel5leafK2R/g==,type:str]
    ADMIN: ENC[AES256_GCM,data:5GkjKJ0=,iv:VF3zJwQZbyLhAy7AJ4zEsgr/9HEb567D37TC9tsgtDQ=,tag:apFgIm8hzsy5YdldfyUHlg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:4TGs4P8YXA0=,iv:mhLeRFb7xzjQxFhouzhv1cVONQIYi8+ftjClMP0eKDg=,tag:/dQZXFi61Vw8nfPQj0C9IQ==,type:str]
    VPN_USER: ENC[AES256_GCM,data:Ki+vMY3495E=,iv:gX4mTsi0nFDLTDXXmOrQHQW6ThEkcYb5d2aC+HWiEMs=,tag:/nG+lBb3dwuFrKWqiS+TiQ==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:zjnwrTC2NN29CA==,iv:AGkjzmkQm3UC2O6vCVx4L/0bgSpDwhnPU4FXYcmxzBA=,tag:N67ZHypHWWRFks3fhNvNvQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:tzQg7w==,iv:CzZa1ponPHa1hzpP1BG0jqrS0dBPX1d5xvpI+w1bDiE=,tag:qevgzdi8+aZmv9mXehJmaA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kt6a6y84qj0y5ndxtn6n77ru00musyv88q5tu7vm80095wv9s3pqzxcxxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNzNzVTE5Sit3N1Y5ZEZM
            Tll3SnNsVm4wcGdUbDA4YjZNYjF6cmc4bDNjCkRoclZHMVdHWG5yZGxVZStuMm5q
            bFYzL0FMTi9KaDYvK1d2NU5TWVlMZTQKLS0tIC9NY1Y3WTJZQVpRcWg2MlM4bCt1
            LzNidlBOUUhtaEpINEpuNjlUcWNVYW8KhcWfh9/Pv6DdLypxSEQa1raIvlgF54UA
            mYCHEVzGZDx0Ec/165i73yzS0LgkkA51VTCNG1bCmdcsnE13bu0lkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T02:00:33Z"
    mac: ENC[AES256_GCM,data:XB1Ypa4bE1BFQG14sXCGul95ab2tsmivTz0NMhB+NPP0SDVnNGgq1uiPBb3qGsmi0BOxncuxSNq+2/idImszNK6bsBqmbtJLAK3Ao7wqZ8SVNU07lvEc0N4viD0O135aHmSaCt5E8DPi+j4gxgqMHWbN8vcFIL5ZF4RKXEsdGkY=,iv:GJ//oAJDDBrb6XgBxxcMdTKXaM/pXLupPIwG5mKocmg=,tag:9xSVhpZzIiEWLZHsXgoLPQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
