apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:pbuY10DU8jc9rxbE0UvvWG/HGxDxofngiZ6fK9eedimkOTWtl6J1YWUW6GP6a7jtez9820a+3lTEgGS16kqGu40=,iv:X9TkU1bDVRDBKYgf+Wbp6oo57li8x3VdvnBz98oTkik=,tag:2vVR5EpwVJtgmvYNzi2hmQ==,type:comment]
    #ENC[AES256_GCM,data:+yp8/YVsEnvkopMi6XuiJ1ORm9iX8JX4rKrHri2XmBtx1lO+wzZkz/j00NU=,iv:TGvxU3trvWS/NyUNcWp2ljs3GDCtXnulYl8FFLw1Rq8=,tag:xPjzwp2vMlwU8v/3Ug2fDg==,type:comment]
    VIP: ENC[AES256_GCM,data:CmcI+CikHwFX6e4=,iv:cy9QnnP3fWu0QotVMRQwWlB8RaA9lvZYItLsx425I7o=,tag:rFNG99mS7iKKCyLHHirgdQ==,type:str]
    #ENC[AES256_GCM,data:ya9rOQRYBtJj25vv13nRzl1U6OxbEOMT3Us=,iv:CrS+d38n/JbOyYLRhtwqy3qUmmp7X0zSq9SPodrWK9c=,tag:F7SVHr3hfTWpuY1vJ2pl2Q==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:qvZftvxJoTWrKKE=,iv:Rl+vIazkouTf2lvVuquNNapUALzTmsnIHPdy5eQ0LkQ=,tag:sTFOIELNCxFmUK3rmqbKuw==,type:str]
    #ENC[AES256_GCM,data:ZyZs4PZAOLW0FJvwOL1FuC1cAr3yWCaP++EQjo7fGy1K9A==,iv:XSNR8yJqOi9bSRcuwxDIPd9M/74qDd185B/zzcGMGHk=,tag:ccxZ6Xl3Vyd5uAs0MR37tg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:n0pcvn7VMJ97CnQ=,iv:TgmZjxFN+ML8hOZX3fYO3fWzvSDlzqvWoG2np7qzSW4=,tag:9Wo99ywThoQQcUvYGrt0cg==,type:str]
    #ENC[AES256_GCM,data:fCupIWSZB6gky6ZHrkDOtK8m4utBal3K8CHdxj9Sk3zPiLP9Rf1fAkQvEhOpls0=,iv:JJHSl4TgMQP4h45tcS3lPO29A2ZgSFNhTqJBkijhhw4=,tag:pvc6ZYkbtyClEPUhGUKimA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:aIzbMI3mKQvO6XCeQ2xZiawVxtYK0LcNNw==,iv:1mpN6b3XdGT9sL00dUkLAxZrBV/JLCYlOuMN0LfCGQ0=,tag:OOIdLLyrhKBdDzgFRI2DCQ==,type:str]
    #ENC[AES256_GCM,data:EPGRVVGjumiRNrUPbRFTAr36JiqS+DVmkOpypQxJWgqvQ4TaKGC5w3givS/0TdXYezNhz3K1xrScGSjuliCQrpub1nL95tWcam5d5QfCtF8=,iv:AERXU6OV3lPakSHesOxGovPh4MCwY4Pe2X/ClLjUVIc=,tag:mBWUToMAiDptg6BxYlMjjg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:u2FOGsJ9/8hUSg5o,iv:Fy2yyzxNgYGHlhxpD26gDlhmzuw5D4XuUTep7fB+Xw8=,tag:ORqnOqOHTosczaB+7txJ6Q==,type:str]
    #ENC[AES256_GCM,data:AGp89WfeaeJGfOv2pihsLKaPF+u2tS/ZSlFXhuhO31abNXPaOK3qOaNO7x0WIAXa1nGBKcNSA08=,iv:ZssI3PserelLkQ6S5guU9UVhzWH9lZsFmzrC3YcRl9o=,tag:BeO8s6L2ovx0eRA1GFr7sg==,type:comment]
    #ENC[AES256_GCM,data:2sT4eIY9XPSiiB0fdnSOE0sRnoG8BrK0iA==,iv:Uk4eW3IE2T9yVPgdINrZ8MOl9agy3QT5TM445hHtPL0=,tag:YXAEmzl+LNR27p4JKo9+8Q==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:+zDbB14W3RynLigE6f9/aifTyHA+I8dH25/E9iG8V6kJoAUMvrs7bBLcqA==,iv:P7jcyUS8Cf+/S1KcAnVPLgOaK/fKRxs5IKqVCteeVSA=,tag:CWOMp3snYGQocTwasEprlw==,type:str]
    #ENC[AES256_GCM,data:o4SrGO7svTgbcXUAGQ==,iv:MThyhv6CP0Ao1nt0XdQwWfYnWRVrJKIEUspk87fsUz8=,tag:Dq0XkMzFE6bNkz5dZmHh+A==,type:comment]
    PODNET: ENC[AES256_GCM,data:iIsjDRaGho59LiNz2Q==,iv:e6MbEwmKjIrCghgsZiUTK4qA4fNzCIV3kDe52Wq35fo=,tag:HJ4R/p/HgueAZZf6vNtcFw==,type:str]
    SVCNET: ENC[AES256_GCM,data:tanPhuPW752A7PlJ0Q==,iv:fva8M/NHbb/qIs2+pz8v7/mE5jhxC3bFjfrVUhM+ZOI=,tag:OdwT/u78JBkRcTYiGWC/2g==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:37sOqh0irs8tJR6OnhI=,iv:b9CwO7pPVzuw7ZjTeGpd+NXYb6xrisWSMTyHR9nSpfY=,tag:HY4Etm89liF2/eWGLaO/Jw==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:6NDs0A1x45cFiBth,iv:i0K5jEwj5HvhMJ3v5xMHZ9nyh0L4La1mY2ZrsrRpkpA=,tag:75ayOQArPeBayVtfrFe40A==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:S0cKTyegmtc9ucBM,iv:aCJHS4NMUddg35MlA/mEX4oSWezmDruN8ynciOVHdy0=,tag:pzlRRq7Sbc+Kplh6K8s2Xg==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:jUj8F5LU623djy8+,iv:dEqF/pH0XzIQJEYBbfbdWJgvErGbAS4yqa9aUJICIRA=,tag:SWYql9GI2ml+KmHwYmrLJw==,type:str]
    EMAIL: ENC[AES256_GCM,data:daHOvTuersfrl98rSrFSa+jylLE=,iv:Qx6HEmcRW3rrBSmZrVhIOqZ8cd2WWoCchTfL4IX0neM=,tag:mHMNafRAiw82sRbEUgQ1Tw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:hcYeGR0WU/bK5vJ6S0y4/Hf407rImnb7YbNZqVSMsBdOAxQWm7lQag==,iv:2+6TWz92vYpJbKsetT1r19ehu2+9k2V+lyv9X1uQbE0=,tag:3Csy3CPxMNghqa23oDxFOg==,type:str]
    ADMIN: ENC[AES256_GCM,data:nbylTrM=,iv:MpNjljmaxp9d6QnZjXrIC4VmKOKSneJQBYm1bOFlBdw=,tag:auQNXoBu1csWgmq2fOzvag==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:b4EMJeryLJc=,iv:l70IPqd+rsAzVCKYQWktOCKMeFYjSc8T0KShMuF+2+0=,tag:Lg3hvfF0CTsf1ubUwii0Uw==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:uD8qcxg/mI8FVio6lA==,iv:JCV0MyU0ghfLsKFpLiSWCwrzMY5g5hgrbwbizLBo9D4=,tag:EmAuJ/g68pd8BmU4VEJOVA==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:E+JAlw==,iv:7VB6+ODXzruAjpNry1fi5DiudcUblwHuIYvuc2ZazEk=,tag:8kK/Qg4RhRCizdMCQWir5g==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:KJSULuMj3uM77CiExL//dqitl5y5o/CuYn7ar2Y9hUyd+Foot+3BRoiyHGM=,iv:caOM3bmhtzxL4srYycHnjHlFq0YPiAO3C2TdO4yFbYY=,tag:89x7qQtVm955JXreveRbaA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:BjRv6T6UhEpLgGM652yxraaQvIJoYy2A8XX3dDcljN9gcJuEjglEFMk4cGE=,iv:ML96UGP4+6da7wAq78h0EBDKD90eU6SJdyA1gjgDD7U=,tag:qoCfPoKtayv10KHIf8apUg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:/+GkaAFbmJzf29QpEA==,iv:j+scWwmxA9BfXidmaZlkLdbEV2zFBmsOebffh9LEVTM=,tag:It1zcz/Lhx3vUEvGFBWLJw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:wi/Nrg==,iv:I8W1V+9KIBYoSW+oEXb8jjEDKXF+n9t6rYazzslbXuk=,tag:nk+l/ODA1rWU+0TuqcwyHQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZEVBK2VNUVVvKzVtYnRX
            NGNGaXUxRUJ6SkQ4K25XZlFBSElFVjRoZTA0ClNhZHp2ZSs0SHJLNFhCcHIvMC9a
            RUdLa1M1SUhncEZTMHBqYnJKb3lIL2MKLS0tIHFSeit0WjRyVDBHd3h4akU2RC9t
            SFRoRG0xZ2JLOHhZK1g2VjdTUDhFdDQKLyhNIbXu5NXEMZiIOTTlVIyVG6QPPNk3
            63FqqIF3RctJwPNsl/hECj1ETDK+X2k/3GFG/1G0jQUSuD5vs/LHDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T22:37:09Z"
    mac: ENC[AES256_GCM,data:NdT4cfhFJMWsg4kWvc/PhZx9NU5t0eNXlLJrf51NIb7+y6qcHE1aPLvINY6KQCTPVZutwYmqXuHWybKTEc4h0Hz27Y0dZp3uTtryE/cP634s+9n4iZEb/GcX4jkJsIbvXNnJo09NjN92KMsnvJZFWOTkSH7B/xCSYFkyT4113dQ=,iv:TgeBTL4QkgXUKBHw5gCRnAjSIrRvzbeunamqePDwg9g=,tag:XIsc4LBliZXEqcAm9RYHaA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
