apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:62OckmsckaJkigaTGlP3frHelWfnhVV0aYsllust57xQD1TSgjS4TT81ELl++1wZqpElqJE2R7VNgzPYpj7GbBs=,iv:j514x97OjS/u9UTza3+NnOtub/jhsBLgMCCs0lIDAxg=,tag:SvC5luLQ7Q5STl5PQRehPA==,type:comment]
    #ENC[AES256_GCM,data:L+hUhXQtt3cmHGwl8M9J18VT5yxsvQgvB+IY6jin6SjlwKu8pxQFZ3o4meU=,iv:43tQvOEOG0MSbhg8aQk6sBeSySkc1tOunCaMnK0WiKE=,tag:HllcYG/OlwONnlJuiq4tGw==,type:comment]
    VIP: ENC[AES256_GCM,data:oSX9ugxBQI2j0KU=,iv:60Fe8UtRpjs69dT6GEqHQrIL3GfQNH08oUAeb1LVdJI=,tag:G8UJqQeCaaDuZw26WxLRbQ==,type:str]
    #ENC[AES256_GCM,data:W0v1E3psA2nUdQBwUN5LwkpUj9nPSGpNUCk=,iv:PdtsRicWtF8+cy3NyWnsF2izOef14952sZZAz7azCF8=,tag:Iv9ZYs+k6zqAHlWOkKP8fQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:TdyCdWsOIaT6IvE=,iv:K66zKixTGTgPenMtIHqXaaO6Pdk3o5Jr7Qv8MX/VqTM=,tag:RZMZo9pyvTN9Af8GlGNWQA==,type:str]
    #ENC[AES256_GCM,data:PCc8nrKxbVraTrZ+0kyMfsAlSuQVAP+N4JYFbEnFzz87BA==,iv:uUkChV39xunXuHj7f8iYrAZxMPfFu/sF/3fVtrxcvQo=,tag:VrLR1f/0H1rdcUze556Fkg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:i3PnAgMyJ892ZxY=,iv:2rUTbA3HTQCUohRm2Jm/PQx/utvzfhVL81FyVwEonKE=,tag:P2tbA/cioiJ7svdAkHgv6Q==,type:str]
    #ENC[AES256_GCM,data:e/jbBUfMR2wImC1TVinAK5OMvG784uDtcwsnEM/45ZWvn5COfCg8Se38lRVG5gg=,iv:7tk5o/icE9NqaO7etThWXTO2TD1P7cCmA4OfZ2qbE5U=,tag:QqY8zcF95cj83qnlSpk2BQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:bzOriN3mbPkhbIY0B8itBkRmubthDPgtEQ==,iv:xDMsaXd81JjCNWlZ8i9rxk4ncJrZeBoDC6hIYwzes10=,tag:dWMk0lS1eSnrrVEDWPw3bA==,type:str]
    #ENC[AES256_GCM,data:9TEqbhml9bgv53zH+8T+PEDk6KNE8DL/D6ns604sHF36Q/d8qE9EzCP4+aDfAyiDw0li3sxgBwMLwv+C0EZ5MbR34/1pYfRbjw0liEH9wlc=,iv:mRWG0l7a48LWtGKFU0BMCAS4+CNzU6f4jqJUTN6Q30A=,tag:kPluYLDF5a0EccxvJ9yY/Q==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:/OiPfCbmb85eb7dJ,iv:23vR2Iw98GCOrzd3go4kGUvPQB9TvFi3wYv+Er6J2do=,tag:w/bC92zb19BlvWH0huFd+A==,type:str]
    #ENC[AES256_GCM,data:DikJkQ5GjFLQiKYo61hI2YzBqDhQWO07nPtLTzZz0/erpQLMOYjqsWNbNWoBWIfOxSj0M9+8Apk=,iv:ArhblX+ZWdvpo5dbn0D7uIMqN28pGwtRhdL0Xs9Dg0I=,tag:sGeUXU3zePXGX2+UuOs9rQ==,type:comment]
    #ENC[AES256_GCM,data:TlseAM9xZamJUZsPWUrEclm29XL8FiNVXg==,iv:rPBy1WX9TTQaDQuJzZCtVna7JzzZN4gVaPpwkNtdfSQ=,tag:sixSlTbU/x6rXIECKUWlHg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:5tT0vFTWLIwTEMf2IXd4aqzkvPe0XPtPPva5DzMkexZSIosPe2Ck4mb0UQ==,iv:6Ah8KEz/tjEEji9RzeofXzlswN6AXzl1MOZgkjofPFs=,tag:6k/HOzjLaqK5AoBoy9c6Lw==,type:str]
    #ENC[AES256_GCM,data:UdXuHxt/bv5vS0VL7A==,iv:lZKyjJluRSA/5ROQqYeP8aJp+ItfEmY23D9hzUboSgs=,tag:u5uXsEJsFL6cFYTwOU0/Yw==,type:comment]
    PODNET: ENC[AES256_GCM,data:cXBlpgWbdm7d50NSyw==,iv:RDZiA8Zqt1hTjRE7PHw+MRcTopAO0z+vLYHd5HAuu5A=,tag:C4maBbjDU7w/uE7EBSDtiA==,type:str]
    SVCNET: ENC[AES256_GCM,data:lT5Q9AZaFOUs/4L4zA==,iv:rT05+QN0UymsSydOtG8phmmyrfN/fz8cpQ0FbZEOOwQ=,tag:QkfLtBlAAfMJQvi9K7fqYQ==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:30PDkDFd5T1ZGMBf,iv:jAXWc+iul8pw4sx71zgXQfswK6MafFbNgqR9GF87k58=,tag:M/PuFf5qbhLv19B238UbnA==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:RKQ1ztWs8VbfS1Zd,iv:N5XdUJ4S08LtWIITPVzlbXLdEDaGhScFtpkRucmAggA=,tag:vaHM3E+QwRqaKQrVn1LY1A==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:G04sW/vu6unnzLSV,iv:zQVbWl8DFguydeSCqcVzL+DWYURaY4+7a/VPqc8rz84=,tag:DNms2K+fkM5KSTBzwrmszA==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:WunBVUB4HJ2yrV50gDY=,iv:s9VDJvu2+QvW4Ju88KMH7olhNEH6wjtJ+WhsbdgdDGg=,tag:hGdLDF7v5R9dMVYNJYudNQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:XGWFZQ==,iv:45eaLu41c3mgK1lqaaD+bDPVcUoYB08CBtHdekqtpUc=,tag:VQPn4HU5clBdjA28hJ803g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xy7ptkwqqqwd9hc0vqfflga9ep38jhujtjz4pyrnjzh3duljneyssrl8dy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRGJsTHllNG41TCtQWWtD
            TEtZS0JlRm53WVRzWjJybGFwbnJxNi8vSkRZCnVQcUlpeDd0OThSZ2F1UGM2UFI3
            Tk83VHFCWjFLQTdZSHBiTC82czhDR1UKLS0tIEhwUURlaTlaOUtjN0pYRXlVdytv
            QmRCWDVTSW5PZkVhdUs2c0xlSmVMVlEK5jDNpJK5Lx5E9MxZJuCYGyh3y0KqWDA2
            qfbZzZzxr6ZxJnHTORqGQaJ4hQWYoFZgL+lRnI2c+xaLtCskFlydlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T19:31:27Z"
    mac: ENC[AES256_GCM,data:X8dsmcmGTl0bMff8N4SzW1FFVdgBf+06mBQniW5pvVNeKdbfSqTohOuJY4vIMk3wmwN/WZM2FPPB9LvJbVCzAxntVrQBHTFSuNkmjM3Ljk2ooVpOeEVb6/FssKCeP6/iJpQ3hfHErF/C/bSBrPYe6+53ycwLqRUXDqqvHn//TIQ=,iv:WWVsUoWqZMk/QbWi7GzjRU6OJ2/87BxP1IOXqCq17yo=,tag:puA8RNjNyKkf4a9nwzo2xw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
