apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:tLv7zrghuINJ2f1jNBKy6FiWx9fpMZ6+wJwBe10l3d+YjeV2ZomQmOtFg+hwyQNgHMBXwPSVlwerpHURRSVvNt8=,iv:MUPDtXEsuQMO06MqOpT5B5ZG4UC/hR+V3OjO+QIFr1Y=,tag:r5OJIIOsMoZIjDySPz0y4g==,type:comment]
    #ENC[AES256_GCM,data:Qk7IF+MaxinLA8/3VQiC2/x1UjAfi5IPLfdE2x8mpULtF7+E6+wbF6Y8UP4=,iv:yVRr6cVG7fBiNRM6x19oQsLXK10Jpc+Gi6HkVIMx588=,tag:r158U0Xw1gUkPjCLbr9mFg==,type:comment]
    VIP: ENC[AES256_GCM,data:ll/nuoIPuoSdtb8=,iv:3daqnKu46+KRCQYnWCcsbK1xXxLSR3aKbx7VhAz7Mgg=,tag:O3HaXTRh+lk3rsLTVhCTAQ==,type:str]
    #ENC[AES256_GCM,data:XtTVhwBVTNmPNWntoHqYWOKQK0CD5b0YIZs=,iv:8lzMpg62/HnyDezREb4gIF95wOzNWDAztUzMtcwTh2U=,tag:I2+M4nI5u9GDWiL59s39VQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:CYCbeXQ+7dAq+Gk=,iv:oJt/+N9gBIJT0gS3jUKclFTKmMRNG2lQHwEopC+0m4I=,tag:OaCCR+qhgMMcME+R1PLELw==,type:str]
    #ENC[AES256_GCM,data:qv9DPibx35P519//tmULUBi9xBbkK7rkSTvvod1aQnZAmQ==,iv:cnN5XdZu3kvK9+JRuk5UlCVPwdgwKvmtNc+4kOUobus=,tag:yg9DLdhIIRRaPWfafM5nsA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:6nHz+ECnAoMwxao=,iv:5hESuCynGpZbvG8xKhTnGVm1Eo9oxBoRkaPqrwZp9l4=,tag:knPzG4RbLEp5QmVmJV2LVA==,type:str]
    #ENC[AES256_GCM,data:bLIaMQ4Op4UyDsnNp2umNtHrgHuU5Wmi1L6h6/sGiDTKeVwH5KU5kEkLGMOYyoI=,iv:M0ZmVkWr8ApUIzNUammT/0d4oaJuEgU7nXWMHTNnxnc=,tag:xSAoNpeZullPkvglSwvncg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:h97dfVWs4xEdFrkBPV4C4chShKdQ1AdmTQ==,iv:uGwRa+S7Q4yVgewiC1an7VhM7v146ts2VCDShm5nNX8=,tag:4X8vbHj2s4kKC3ecNG31pQ==,type:str]
    #ENC[AES256_GCM,data:s7zFarGKsLAsod1H3+xsL4OIcXyxdM6RYIsl2RPH1bANyiweRN/ArWpQi8RWBpbePf0NhuSpHfx78wa3ckeJaP+sBX7oe0PCW4tA0qkkg1w=,iv:d0Cli1gyMe82Mha28ZIn8MVeYM9fx0aasLfdml1queY=,tag:OqT6iF0ZMN6QJtLv8Wn/Hg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:U88kvTDcl+ReKnxd,iv:SsadetTmYL/FZNlSN+uAw7ZmGyO7yz4EfqAIN7T+O44=,tag:bHZtVMxf1FiBtYKONC37wA==,type:str]
    #ENC[AES256_GCM,data:/6ZwouGvEdUh4L9BYCMNAszXZQd+bPLOCT7zCYb8as85kLLMePy8UsY8b8aJcTOZpyJkloBT6s8=,iv:k0Zijd9t64onzoEmKoAHFAcG/rBz8f+3RWpo5wpKEJo=,tag:srl8BJQbKvU9OOGe0KbMzw==,type:comment]
    #ENC[AES256_GCM,data:WDP62YCS+4gpGmTvCQx31wldp3yklEi8kg==,iv:p+AD2VD4x6Yqm20KxRd041YeqsT9iYQYcO25wuo/XzA=,tag:bbGe1p3uxCPl+Y48V4ze7Q==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:VegmjaBlUdZ0Lt6gwULXVHamhaP3lAgRhfMhTPZBx+VkNqRIQmkeZlxDww==,iv:LRygViZI1EFdLjQ7S+LhCUMgxISiuHo9/2/9/DnW/As=,tag:EsQkLwD+tbniKidvWJDoRg==,type:str]
    #ENC[AES256_GCM,data:unmdvNTepZ8GSoFYjwp3MY5YmE/1+KkAlmvy+E+GEzNa0023+FzR/Y8cyjL876ubCjT23BbnyUzqm56v03Ha8bakz+59bds=,iv:Rc+4O+qU0NdNfjP4LE+wvAeTp9JIlNCM8g/392ek7vc=,tag:kIcIdSH5I8aQNLD4DMHsCg==,type:comment]
    #ENC[AES256_GCM,data:cwBqyLPlULb/raPnqq5w7kVwDt7T0G+nVF6v+RxvuD5C3zlKNCQ3WMy5JBBDGO5hEDWVWHPB,iv:Scoz3DmV/v6qGFNTJBtsDVbQ6lFVV7+PFYzXsfHKYwE=,tag:3m9smEotnAOSlq9ZLljBKg==,type:comment]
    #ENC[AES256_GCM,data:H7olM01TMcMewdS+lvngwrodtwyOVPQ/bSs/1XZrb/+g0zQ=,iv:9R8KFEdi12PpnINYOW8pRPtM4obi1z5b0MjLOY83av8=,tag:FSQUd+BaiXZn7a11A3hjNA==,type:comment]
    #ENC[AES256_GCM,data:4qcA6SnalnOv/bzoTTcI4vGKuQaxkcBBOgTVi++BYuDyspj2I7h5,iv:NifgdwhoUpO1kLo1Wxq5wkJzCU4Z/AewMnpq/QFVTYM=,tag:7x5gR1Th0j7tYMePAwP1Dw==,type:comment]
    #ENC[AES256_GCM,data:x+FamJcTi5sTWs0zWSA=,iv:dJQSwbexcR+10NBxbjxJ2dbxACUQt69f4pllvy+k2IY=,tag:rBbzU1xzgdvlBeyfalytEg==,type:comment]
    PODNET: ENC[AES256_GCM,data:W56So/AZ+xM35qzwTQ==,iv:2kzXhBQxnTjCBiJmKLNmhKDCcw8SC5DBEDNoHeSEJXU=,tag:ySJJ8zQ0ALRnHTPf152Q5Q==,type:str]
    SVCNET: ENC[AES256_GCM,data:cTkuTzvX335znb0Jsw==,iv:gbVkdHuL27YnzSTOtkXon3YAq/nIGi8cGnVrythgBuU=,tag:oUj4SF0iPFf6UCd3lsyjRA==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:ZW585kWqO5g5pDR1,iv:e3/sTyFn4Q4hlCbwhnYs37z1Pe2kx9FW7iPwMI9WBzM=,tag:PZgKRRjJQaSlC2efTGxDAQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:Zn/xEwty0031encB,iv:747gUAYLfn/gZYZmFdnPznD0K3VgDCIDVvOwUVHIqKU=,tag:WON5BDYM+70+Ld0tOxZWLw==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:0b+HRbaTikfzm6aX/YQ=,iv:AzetElYKF1BVyA3yLrHbgnnjCOK0fpqpaPtaLVqbFnc=,tag:UxcA+xBjG34gz+DLrP8N1Q==,type:str]
    ADMIN: ENC[AES256_GCM,data:90rW/2g=,iv:5OM3D9F3WPBLl4poqLZSj8OnPsrXOTnqy0uf58RrpWw=,tag:x5R6ALX7oDRd1OLy7evXRQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:QtEGzRfOA4g=,iv:ZyaGWYauuJ7Az8vw1/1klsTVggJ/x8TuTbGJzNnRUps=,tag:PuRyqFqclsnJqlI2WW439w==,type:str]
    EMAIL: ENC[AES256_GCM,data:CdAF14qWBllTl98p86996N6OXTA=,iv:S6utJOrPsvYUBALOuq3mSeAIBzawgHMyBrZR2GQ0fhI=,tag:fiYdU/4vKEVAsJfHbt+g4Q==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:Qpu/10OfZCRDe/UWbKWac3FcaoiYRpwNUcIpJL3OXBJk6uZVbCIj1A==,iv:toN8ysL1pUJhni8SraEyx69xptqOIkxPcjNt1lXMxjs=,tag:vEMLpzM/myOjZHZgtRezJQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:2tat6w==,iv:36R+roaNUV8zEKRDHCfxLcf9o1OzT5wwJrSdrYj3LP4=,tag:sIXfU80IoDKlRZg97kwTsw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10w2tnhjhgx7cntj7kuf4s20f7uufq7xaanflccx77k8flcdm2fxsxuvjgh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bmwvN3A1NUZEeGd1NFBZ
            QzRQUkp3NllPbjF5TXpMRFVIdlB1Ry9xbTBJCnhKQU9qZnF1RVNUMTRxREhlSm1y
            QTg2dFhDU2o3YTRzd2k3bWs3N0o3M3MKLS0tIDNhNElSenVaU0hFaG1wRUM2WU5h
            MHA3cEw1TGdJcEVjME5weDFGbXh5Z0UKoYLXoxK2DmwiLNb/5XUGjS2DoXYExewz
            6BS/iamBBB7C5C21C7DdXlzoz27NolagZhgp81gFhkKFMwqMw/zQKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T19:36:44Z"
    mac: ENC[AES256_GCM,data:pI432w813M+/aFNCPwPnSkj4mvh5QleyLJYbs+CT9kSR9dFVgx6uryxF47ehC2ztqQTjgn/qOuwv9yMOUVl5tjgthBIa9/BwrY2n2JuddubSi5rmSozHpoetlx7A3iMYlK8ANyLvmz8gfEdeTdi+T9AxHeetc2R4ZMLPAYqrH/I=,iv:t/Gs/+T8wTANDv7fBSF87zT0KsnoJvfKdtaj2V2epZs=,tag:MehBqMqEsMfHZw7h1Fl/Hw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
