apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WKi51WxpdZuWMLazwQoKcuAxilt9SKruSN2324FXhI9wl1IYeUClpTzURqvtF7/45c8RTTJYEfrKMShX+fy5R13UxqatVnMtyXBnSbuVpkWWc/phPUaol1CNbK5YA+0ZnxlrD3MKv+1bR5C4ACW6ffNjtkW1bSrK/Rl3LzgwEpczWWI8FA6hTKKHBA2D1E/2rsq7/ESVXEHPM+F9OhT+9HxDjgf10F2kmFMAUVYHZ8+ahr+LQzJMnNrlq2wx1/gldcz3FdS0B+ZJ2OEk7BOzd1SZ8cWMCvI/zZBgvXz/iZ9OWXtQDaqvSaIDfAo+Ej+qT7eOlGqbnpyah3h+sg5Nsrk+eM4iB92zX9rhmAhkArku7w7qZNvh78SR/iAZYsvo,iv:/LHIeVcFqtPJJ+tQgDvSE79lXsYRrS5xQafX9JNRCug=,tag:x9nPyGegPIhotEv9zaWW3w==,type:str]
    identity.pub: ENC[AES256_GCM,data:F+wWtdiZTmBnY3/1QbgNoQW3Y7hWAjE+U/MZ91Ie3njjT70APDJXHHGwirT+5rtK6HE9rY+bXW8/6wHbkg7n3w88fnmlsSc6rB3B5OAtMx9Oh77ijtTuBop7BE+O0OLvVJuiAx1YeYwHLRfw38K3zfQTnyr3pP5JFXChN22e2tQNkNpheRHDyF4Ydup7mFZBen5030ZTifEzDQ43AGvynvPsk671Tzl9BsJ6UownDI26G+vUlgdJ97ebylv2k14WjuuJV+BKkTCfTn+2ew==,iv:9QdEKzLvKbU+PXfgVLQli3Qlduy6FNgR4xv43GMixE4=,tag:j/giu+295bh1J20rJmfPDw==,type:str]
    known_hosts: ENC[AES256_GCM,data:laKpcTwz02kPJ1+9/yyT26E6sSgWxcayAD8ezD51x0dNyn1q9P5DwxhMNl7mPv6ydChqBjYfi2P745zFH2AOV/udl/+M6TUYhCp/vhAg2SbWmUjEH1+7nel2TE8kZUfZ+Bx5xlaNQ92prLIXWJ/FUbl458dOpNGtxKoodH1XaG1xZFcdYFgkdXLtEBdlUGW9YrS2P1qd/cKcSKL0f2UdlIeRC3QlyEQJkQU3,iv:srkZ3QXHo1k0kcJBw28jjGPJvu6cTEIImiawDDGpYbQ=,tag:GdhqH4sR/k4+SkCUwg7mUg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kt6a6y84qj0y5ndxtn6n77ru00musyv88q5tu7vm80095wv9s3pqzxcxxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodVphL3hTalpMSzd6L055
            YndUZHBoY0NObGVoQ253WHBwN0lnRUFsWVZBCjFQMnpvZ2VlMk5ZYzJrazJ1WmdK
            SktPZFRESzlDdkN2bnNTQXlZMUtrMjQKLS0tIHRHZjczOUpXandVcmdFREw5dFd5
            TmptMXNZUXdOQ0Q3VnFYQ2ZmWDlnTm8Ksttso8tBkivlShPtBUQWpUkgbIiNBhF0
            itZ07E2uzkMpOdodvBgBUqengnFwazMpn5VZO/3mfbUJGv5ux/y7Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T19:34:57Z"
    mac: ENC[AES256_GCM,data:aViQkCm92vG5kDeQHY6kKNeZUEAD1dOKk9buEVwGJCDGroa4RXr9TYCeG0vRG9BShSxb72GorpKqbP3YomlVLogL95mGsZ/fGp451Q85G9F0/XXGkzi/0TN9Snl5Qeon8CL9jePMLh3llKsOtDuYlyGOgln98yHmc2iKX293Itc=,iv:0g76HFq/+buG5oktbMxTVKu6wXXOouxLMfozLApXPaQ=,tag:rEQK28LP6YGVZb8i2TxjkA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
