apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6ZBGGl7A6/C1VfuAR48blPVE20+yGjqyfIEhcoTOId68sA9AWsboV/rV9LPRGk4ddHPp6aJK+Ff01oEjIMz5cPxgLklKRRsMQ9G5alrBUT+GJ7pcvVTafRVJ+zdiPQ8QlRIPeJWZjfNMpsKKiZXdo1Ka7BjYDQc1+vFglrufp4nPLjlpRYCKNHss98M7+2w1uLlaUhOw2A4QsinyXb/j+yIopfgZeslDPvifap1G+JXWOtBeEZ9Dd5XTQIjn1sbTY+pW4BxIY9JB/cTPPbxW3fsE9jOADn1K48dxdAd8ZsH18G5RYBV8e+UAvGTdTt+IuqNlQgLB6+Is+YSZiKdGjpNsrcUcGdv1B2NEMG7muvtE/PeVIl93l5lm1GulKvTu,iv:h1gkNrBwQqTuseLDHhLnIWXrCVroGv5LgnY3xWq6boU=,tag:LrlhT0/q+YwfnMYxi7Jxag==,type:str]
    identity.pub: ENC[AES256_GCM,data:XDOAHbnHt0RPCmvXykLn7FDNsq++j23gpmyDoLgokSLC+zAVY4rvHhQGt8UWWPWkaraucix+1Dr9TmGM91zoENjZqWg3tOW9NLAtRRW0G0sYDfd6x0LlFQOW8iMgz40yV8rLWT51JW4pwnpvXiUjYFqbgJt9E41/Bm7jgDtuvtdlWPYkFUt3qbdruQmBvz9QinF3CdKBKH6qgQ25t88Mv8X3QFT+0xLua6ys2lD4lBxBTY6pU1s2pcFiosaXTQlFO6shvZBqzlTXwiRJyg==,iv:cUT4NjLKYQbMdMaaMJ7dC7itakbBDkujGzEIFWBmZso=,tag:HQmqG5zlFzDFqmgktvi26A==,type:str]
    known_hosts: ENC[AES256_GCM,data:4Fz4TzkRz8MI4c39h+vEnHAZlXdT8do2i032Rngy8iZS9WqQBhYej2Ywb1Dx9z9uWRUbstybSsZ7aE6mkVPzRPWFZsnHyoypQiyJ2GqMOSF8wIhhMyLLrrMBZK2cy+0tCkGFTV4IBe8ddZLI+Q4rLPIWz4BHttYOL93V4Qf/Ss1l9UDkhk/fMSUemVz96wLUHhpGOqYnCAv7Ln/RyZ4nME5R4IQiE1cSHpps,iv:Otbw2Zf6p80nSKch4afteGQ65AHJCh9MnsfA11+4PRo=,tag:aO4LIHoxi51k4qFO1Q3d4Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveGJ0QUVGZzg0TVg2MFZW
            THlzMm9GeU5keThOSUVmUjBjSWFlWEtFNjBjCkltekl6bEJ3c1lxT1Y1NXprcTR2
            aTNXemY2Q3RwZ2JvQ1o5dFpoNDAvUkEKLS0tIHovcVZnWVJYQUM5ZlE4a3pHa0dD
            QmFPZmtVT0VNd29QL3lyaVZaVzh1TXcKrnKEkYU8oWo/cqXLzsi+4j+eRpzgW4ea
            7XJ3fquFaiqAGcG4DBdUIMx6FaioFgJMFkbrt65bQdjsmD+HbQ2WQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T16:43:22Z"
    mac: ENC[AES256_GCM,data:WPDYAHJ6HU5iUMOLPog5LLt7YYk8rCoSQ15NcSR53i8IEzGi6mgMq5dZmw9J91JMIVF7nhux8Dhiy8XCKnbHbg5CvjNXaEFyxq4FNEaTTweamoJZzSgzweRmzdzbbnrG3eTSHz96dAVLzPWKSLBddeC3NJbOArtQ7Y+kP66Zmnc=,iv:sRASMQ46fMBMQf2OjSQd5bJyK4oHUUAAwvMdMQgYgDM=,tag:YJV3kbWJBFdqwS7+DHon4g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
