apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:r0zl4nZ70BUFK6ROpjziJhs8oe0HrYwIr8lmNfFavuRYJHN7VvUoCBXQNXenRluw+j8fQ9R/6lW4uC+STANxsXACVPoFKMFTbaGc2hjYzHY6vBf9kLialff2tqt43yX+LdMtFuIcF5CQbPGun6A75yHuTvBBQOKQ0V6aqr7HzS/MnnlN9cCxWa58DIvs768N4n9nICl2yp56350A85LvTj4mBrFBiDEM5ty4TNkh6kCw8EKIDnfd07rYpD5rzBxvhtRL/xNOO4eI199FttenCPG6m+U3JzcI9O4fMdM/XqSZdJs3JdSU0achrBvrfoF5j7p6iRzVxQoGxaFIHsMoyRiL2Bbqd+A7VgX0oSKWr/fUdTser4T0ZRQVZfRsLPmr,iv:H/GEm97WIwCh5hK6a2spSmS+/EL28ysYsDeW2tvEqcI=,tag:O4Wn5lB2i8E+hCC6lAymOQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:tPCIxXwmfqfwj5tY8totw+38Ku/NTvXAgOGIucmt6+/7zLS0XjqEoVcZ4ZiBEY/5CavdZBBpZbKVlLIqdT8uu+1qVvDttAQCTgHPyAzdDpYJWjwj5YkSiCqiNexQvzcPY7NcAkjbo7GmntHjF3clivziwT7K6c5e1Ha+yJKYg3vfz/Hb/rTnSASPuwOYpZksAcnvdIfCchZWUiiyflBF/QYYsTZo6Oa8Txw7VoMkLJwzEqsL4vgNnSkjeMekJnrMgC+4yyUv8/5sW1kg/w==,iv:rj6kI0bj1Szh+3oWnjSTc+6tmNcNLru7bKx4K3QvIgk=,tag:HbLtKoFWHRNqEyGdqM5jBQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:SK8Lcj5O5YKmzbLuKKT2FMzBajnm8hDGeMZW40pUR96uiutMAW5417cJrBk47GP5nNfVRgEcGJuBJJPWUjGGTqvo3d1P5avYx/5XLqp0tZhXL9JVg4/l/zvgy1S7fvCSS4Z0uxxQ3Gwm9ok46feFrKLKZqe3mTfYEz7JkGywySvjuxo1momsONFcHMfZt2+7HK1gnd8liKmk/kWeDJKkka4PshQtLUreyyq+,iv:8IkDse1236oWXZW7nSbMYdhsAHglWTZrzoKG9zTsm1A=,tag:tXpveuwSX9wJW83OKqPCMQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caandqrgue5nl44eylp4nvake7znrvxretz3uy3r0ccfa2av4aysejcgfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOEk0MVluOW9hbkxsRkI2
            cFU3ZGk0VjcyYjExZEZYeTNoa1BxcmJ2UXlRCmxSRXdjUXdaVFlYOEF4RlBmaCty
            T1JTWFp4UFptTW5aL0xYMnJvMUZ2WHMKLS0tIFYwZ083Z05HSW95MXhoM25UdWZy
            WGpkclN0dERwaGJwcEdQN1VaUTBwK2sK6VE4F58HCf8acQXe3JSnOvjGG1prknit
            W0gbBFA6a5tA2SINCwH98He1GJnrmShAq8jHN2+3NGSBT5aTtc6cyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T15:29:46Z"
    mac: ENC[AES256_GCM,data:m66lAggotTBV+yHPP97zUfFFRdnqGhwNA3sfQxK/1s9fSuAgSQqxBXhAGfsObx6wo1LeqmvLotCAHSQJd7vmHGCQ0DEezDM3xPt/V+z2Vdw84lYVxB/hWdF2fJiA3KRb2DmZtiuW+lYUKyQmPb8QKgwoIaGNy8ANw04wuuAcLRQ=,iv:w2Eihrby412wp8ORCbwQ644KFEolGWOa7p7PV0V43VQ=,tag:4cYlApNnKqpYS8Z3YS98dw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
