apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MaUR6iYWyNJS7gtTfoUXV4j090Wj7s6TpxFMumyM1+rSYGm2dMobjlKVStj8zYADKDCHgVnXGJ1LvBxCmFqYk/5SlX9q0M736USHFZua2bu8b6JxPfvzD2kV5OvmEIXyfvRpktHXcTuUd3K9f2kV2dIx7zluBoVg1H1stwRfjbek5RsdAhDD9nwU0MmCjXJSIiN5d7U+b7hghPNh5HgPSE6FVs8ETYosilFS/a0MpAHUX3BmK1pVpJ0ZIFwXxwRL0KpB08OmvKKorbqtDH2XghBHWqlV7LgpIxPPy4fC5kYbL8+duiMiMd0/ZpdaNV8hJQ6ZgWStt6Td/yw9VN8rlWZHl5wPFPPwO42Nb2DgjzWGuM6acdczKAtnzqhgOgwX,iv:ZiRenIFmj1Ret/fgYDwUxIQv5SUAdSpmGK4zyAWVNM4=,tag:3wZTbx18DTw+gzEHFTkymw==,type:str]
    identity.pub: ENC[AES256_GCM,data:AsKaSGrlxXQ1D49sQiqOBoQ4S67gahQKTBISj6lej+wcR7W+L/2rI+8d4ijhRjsKgbTlGrsxPqmumFyA9kqE51MnG1JBNvw6412gw+dZuVHcVlNPP1RVX0gy0CLY217T8k8IiVEe9x4jpTTqxbDj7J8kN1HtZDxZHnjWRK6skMdM3I555HZeFSGw21JPx+tcY3UPR4lvBfdHUyxi9gNyVDrp6qY/NbTvIEU+yRggeQwGJ61QAWuYyZnOPdxT8/gtA0FoXM+Ho7HzDSVftw==,iv:NPgIFLgbVK/yEpLysSY4yRnYSSwaiwhdBLmgGi1th1E=,tag:f35sxUY+oSXWszMEcuFm3Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:OgwVcUHXmoLu4SOWkkkt1Gg0+pIO46mwRIhJ//d6n/kIXUNi4viINEA2i8HOkbPfJJXnJdWKfbkI8mk5erjWqrn/pTSTlh0jNNy0lP0+VECEr16pJtlYZZFcbvAb7YVmqjN7s14WrwMTCu8Kb+Fsno0PJIbgKaydmmXACsmWotd8kFF54k0hmc1SdK+TtZyqYlOIfeFctXM3VnlP3HtKRhZyzgdK+yh1ejDt,iv:Jz0T5mYIr5zMexi3Ni0IhVtNsOSlunsZXmFrZVUHo4w=,tag:ZnOh0LedEKkb9Vf7hSzwEg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOXY3a3hWMEt0YlJ1M0Mr
            MWNiVkJMdTg0SDZPMFdXa1hQQjBUcENvUlJ3ClBSQVhuM3FSeHFpcjhzODdhMm1D
            aE9pZHlYRDRyMjlRTTFGOHU3aURlT3cKLS0tIHZKTWhsUkhHcGRCdWxJZlhUZjN4
            KzVad0g0TXFaNUpSWlVveEF3MDJCVzgKCIJFKIf/BEn4pVLl+AOiHxIXV8jUA5Ha
            CkLaF0CCpyN9+nIsqvdXxCbSfej6QJfpxYeH4VVtnnpA7m2uMeK3+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T14:52:14Z"
    mac: ENC[AES256_GCM,data:hEz0hWFGsh3NuylZvdejnRhpBO8yVVC/GBJmqVVUvmIGRxhe4DkVSa1OLQZaTEyGGCesVFs3ZdM1HK58qK1vfQTDwXSCtGluHE4GzfhFFyiBBnH770kNf2ZonTuk+GeMTzgWMPj7lK/JKwLU3npwewq5vmLqhb7NqB+K6stntZU=,iv:MgDT/sRzqPooVmuJn4WsQHRuFK0HxkeGRXIwo11OEFM=,tag:mz+tNZDTcOpiwBiPjofmGw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
