apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:bRtLeZsD/fW3t5uDq1xjWQu0XqKDRlCcI44PIVy1DwPGQqIEMjeATFd5nh0JQftLAYLtdypWuG151aSo6L3yg0OFCsenn/vdIfn8YsOvzzvoNLqNZJusW6tdrm+LpgRkhokvDbF9eHl4N5qfdkdH/o1gZ9HAgUpieYboT+63Zr1PKJat4Zq+OXcNe3Qy+B/syLtme/VK/P1qXCNaeyCNnLYzicv4AE0ItovTYXAFbNmReTea0xKHIzpXq8CNz8+8rV2kYvbMBu5CSHU0/UhGhXEPsPtGifaAzJrX1hlryr6gitbHt7bRRoKURzgBQlLpr0B4s4aN9kGGwuVHHDSP1IgIzSwy/YGUCiqhOWJS/gGkQG+g7vLhQ1tUgcwliD7D,iv:wHKc0hIBSPbo3xdT7E7NQvh0GASp4BZ07ugInCdeiFM=,tag:8VAq6j9UCVGBObPGPjVkyw==,type:str]
    identity.pub: ENC[AES256_GCM,data:i3p7mp6GyKXU5F+7kfSAVTQvvSsLr2hBvjEsmd4eEj1OdhdL/Sf1/xQbREGHfEcIZr1sL5mig+Jzey8BDA6Zy+UgfDjuP6x95KvP15qQCdc5bsUJ9KhBjuVk1G811lpgpL7tc/zx1u+ruRHN9zH2QfCdycjBJ6IDbQhFrjHhlYVDeXrWn/UueqRlZuIDl5EDDdN3tV//FRnr7Frw1CR8vpCmvcwEovOKG8Wgmk3E6vJ+1mu50mAckgSJ2AnpgBj2oF5MJyHTqTwQ6ViWPw==,iv:lArIOg93L3/uyI+j6XMrQUm4Y0h7xqgctcIFYTB45lw=,tag:l2cAzpZtqZepfDMlKUroNw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Nbf6af/c5CufBqFDIx7LAlmq0eZzL6+gEB3RPtKUiwVEhMPpBei72uC5spmDcB7wOr26emBzFvgJsyZlteOJREZ+GrmOGqFrtLaaKup5oucoP3F3MTk+mJ6aWgNzFr3yiDKGSm2BMl3Ig07q8nfqGEZUG8hE5vRMfWmXxknauXKc6ZOBC1XDrfaLxENEgVqeNPR4wIm7dg89KCxlvolYR7iajDjyXJ7AJrpc,iv:7+Qs5Qt4bXW7GmQe2bI4XaPmTHiikiXOEismSHxptS8=,tag:/Rxru8tBUsPOytGBBCuWgA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caandqrgue5nl44eylp4nvake7znrvxretz3uy3r0ccfa2av4aysejcgfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOEFkZFBEdXBIbndjSFJp
            MjFVT2ZzcksyakhIZko2dzVua3VtUjJ3UG5rClpXYmIveDFhaThCdVZENmdkUThS
            cnp3a0VEajRmQXRpNHV3TFdTN0FRNDgKLS0tIENMamZLRkFlUjlGUUNjWXo4a0ln
            anpjYkpCRmZlT0hsL05OZ3hTdDFqWlEKhc3zwoRvqbxT5RO74ILzAbLroHDJVi3C
            iJq8s9WrrzKTQhFl6e4NkPPwTr7tWQoAbkhT5kPSCl5xw6/5L5aaoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-29T13:55:35Z"
    mac: ENC[AES256_GCM,data:5mGddX7JukIVB6NyY8hSO5EoyuBxFWjIwkTQT55dyXXw35tDI3zV7An01YLDOjrzX3YCeKY2TQJ+wnyhX5cATxg4+KPyj2XYPc4K/bLdmK05hBh+Nl6RMd9JUTquRWKCy2nNe7mKdAM+zuPNxoEojy9qJZMckbhHY4zIeEuZCrE=,iv:J5scLB+UWNs+r7jljJpaGGeNAp/ZHHVXdJCwAKqfHeo=,tag:jsfhucRAiQOWVdCf1ONJjg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
