apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FYLv9drQVZl8slTVZmIVRp5wsUvnRlM7THfFu1ivVEU9V5Q4m6F06Her+OKlwOhrFDJeik4iKRM7VjJvqJRCRUn4q6FG1LLVmKwT8TAVJ1RyxKYHIH712QNWvItQKxtK7d4bW7vOI39Fi27+YhbOjSYtkaGcBpO03MOe6LAANsuDACU+2QGJ9PZcXIP4eKpnoQqhwKFTiJcvyuVBDVCdxXBxkaxfyoJfuumxi/q5r0/B8RraWLI+5d1WdmmS8Xmw2jhuprJyyZwzV85SHN1y0IBB0pmeo6NWGzkeMWh0W9YXHZsd4Y4BjmN4sPXuDxcbgAzSHLx5D2i2DC622MqcDB+uhsE/bWyX1/YQKULsj08jR54A6yNZ+BnTFQSzXrRQ,iv:EEDQT9a4bGglrzqUgp9pa19q9xIzktDo6t/q6HMOIxI=,tag:0Ztrk7e3JELRXxxW2B1jgQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:IQdxIcbYiGFi+TNxHBqME98UyQ4DdnTZzIMX2W6x2MBBlTaxLI1J+jE7n44WkNnGrE7gypHTuZL9j+5hQvZ7VrKdKfPywCo0NfbCyk5jEuy+flpZ5NAH0ig6N3xoMaaPtBEJwtIsVAOnicSE83gm6lBqNH1zduZ04/qBLpRLXCihkd4FD2qmh2/XVGrBkaILJ+uaf04vcATQFFhhILGrTiQDg/gIabJdX0Ihs/rGoHZvKTX1eIgjLpkVnYKPkdDB6sT2PsP6SoKA8BRxcg==,iv:pGW8VZCcSHcdxT4m4IIX7Ag96s4QZEkwqtOz5NODIt8=,tag:gS4mj53nTVDWZYofvrSo0Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:/Ur73IJHHB6CEVdnLOcIGJcoT8rH92wtLXcyjDvbMxmDoEWoUOVpj7Uou/aQiLhzqi2rAAX3qbEf9RY3fpIkiyhZ4Y9EYMS0y+2ZFTktU+ao/+nOcIC2z8SbTNCndIJcNXC6GyKiH2a5XIVT+XcUqsyYUMhaarxngF3bazPrwUwJz1vvxKjbXMkHFIkvr/kmneym9dbBO3w+4I1KGecf8P3Zy1d+lGn5KW08,iv:Bb6DMCPraKao3X3o6lPX0yDXSMHt7/7VDqXTFpWnszs=,tag:IuTzsdvqb4NAEVSa0E77Sw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caandqrgue5nl44eylp4nvake7znrvxretz3uy3r0ccfa2av4aysejcgfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYVJpWktTR0xteFJLTStK
            TWthSWVFWi8xb2diZlMvdWZrZDQvb0RHWjNVCnRBeEsvMytLall5YmxxTEhvZHlv
            UGJRVlorR2RiaVFLVkpDaFFVVkxMN28KLS0tIDd5dWZIZkMzMDQ3R25IcDcySjdy
            THNRMUZ6S0ZOOGowOTRPVkZoSzFRdVkKnI5TXzxJPRy90ark+Q0YmiEUxxeLxPx1
            mj/f7u0WO2GCW7S3KqUkGgzcIrBd9jMnZ+yeJtP02458l7HpKJsRnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T00:17:26Z"
    mac: ENC[AES256_GCM,data:oDs9dHc2k1wl6Se6Dni6uSfhPzFJ8Z3FBZRk+SoSHhGgmZo+Vkp7Yom3AX/PmACiqM0IxqGm/dcHkKuuQW1OtDnwxKfvz2/9qmcblAq24Jt2ZiizQssd6RvbC6eGUhmHFAHaN9nl3nMnbalmF5mzLIr1i2zVB5ZXQJPoI8C1CFg=,iv:3Nk0j2nu7/+3ig0nsOn44XrDoWu137Gy0vvHn6gZAJA=,tag:dSgvU+wxMANgbX8/peuhLw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
