apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:NfpJp0xggC0Tl+ij51u6Oy7vZLdnBOZnnhivzV1o7dmS53KHeNdxgeIwanBWc2tTjCc6a6KCH6x3nqEELL6emQG8kLfZWY5TvVxA1f1/FqMZFV5QZ78ZuhFpTJ1YqbVcteIQlpVUSnBsiTl+P0cwmSlMm4sXSvK+Y3qHSh8EYDF5MJPpuKip2C0Md8TWzeZzX8ZUhWZbcrIjahH1+FTsmM/V3ESdOFphC5ar1sMLAOaaZKNyIr8EHkg0UvDS7oQiXMO+SBVt6VaA5kBpFrfptcNMWJki56XlcR/Rquco5ApJx173K0ll+9IqE1ItDHOIr6ecqpxl1l/n16SmULa2qiEjuwTebO6/sFR68tKWAU8LekkRgjm7oEqtaBetSpjU,iv:1Q7yPWC+8SRwYJgtMtYaYFm2DsrKhuXNwES0v9lSerQ=,tag:H0JzzGr7j28hGHKgxKJ43g==,type:str]
    identity.pub: ENC[AES256_GCM,data:5hbaUsjEDfLMG8DQrU2NXNDdf5UKEcsU8B2XZLypBVfHy7BEviDjiYtz+m6wGYFqYkOS6rMEKAoL27x9y52MBQpkOZYnoJZX+pv0TDSM+DKfqzRU0pNVMsXBw9cv1t0EvUlzLbS3KZ31E9chAOwWeMeASA+8p1kssACztOgOvmDsC/sZbcPQBE6uFwqLarlmQkMIaIdzZ6lWrJLHUZJsXN151pqj3mxU0GNv5UBUqeEhe2WqDyWjW+L296Wsoypfwmbh5hwRKtJ/AkRqdw==,iv:sPvTXxWgFq7846YM1+pDljb8mBylX7EcMNKSwTXEQfs=,tag:NDwIluCWs37x8U7c+scuSg==,type:str]
    known_hosts: ENC[AES256_GCM,data:GLxB1yOzl2xiLRPhsrIqDucjK+Y91hQhyUMi3V3I2ZXrfmFajKqDQHynuoh2PUGpN2K85bD23AidQGeX0fU08MophsyucBBlHFmraUXPz8w69N7lO5o7NLMp8myenTmyqTHD4p2+bqUcywBOvAmadGGEHcOWK6QSYRaaFBRhJ0c4PqujoJSmsgPscfWmzyAAQEbHh58PzcsZrYoqJQKs+Xj7xI0WphQEU9GW,iv:LPHv/Y/4h1+FnxmGMZtkGDq6OCajDpMSu0mSAYz9NK8=,tag:a16ernVoBNOVRBkku29nYw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1S2l6d2t3K3paZEVBZkNp
            UVRMMmU2M3VkOFRIYkE0ZUdSbkc2cDZ5ZFV3Ckl6TUNYOFM3eVorZ0gxMFBvdG1l
            cjFOcm5WOEhmdzNqQjBhbUlySVk1aTgKLS0tIFlNSjF1QnlGMmJ2ZXVHTVdGSm1r
            UEpjaFlJUFQyWXNETGUxU2p2ZHkrZlkK999zGHJLcbfv6HD4oM4b0h6ovQdkYIzA
            8RkV0X4r/u8MYWz8s/+1pic5FZy8eQY4g+m8eRXN3xo37ieAMngsig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T14:32:49Z"
    mac: ENC[AES256_GCM,data:4McVM1NCtQ0uD2FX33+IMlhe4ZDOO7gWSks5oLBwNZVXa1I02+XGTXDd7kgg0bPSaEscRPzb3izmqyhXB7MdJghI0g5n56tMkytBB/k00q3kl5qOd4HbgjabH38s9zGMOi6dz2oHCGdxTT7D676hGAvBujwwY2epB56DxXB4QFU=,iv:oPuJEz0Xouk5irlfTJlHJvIcKHc72C+QrdioC9+Me+c=,tag:ekX2qn4INQhA3cPfqS0zYg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
