apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MgZMA9JAhC2TfK2S6z+Ek2fcwAOycVcJ5ZgqiZuh+LRAgh/Y/3wsa+3grN4JVitTYD5qgQbTm+EGbu6AXhPpxwkR8857XwsN5/N+vqZWGLIx6YmJHu2hIsd140msfMJP5w+Pgqa9cpWPdwsSrFrlM31VkNa8brVZdy3DohsG0jT1S2r6PKax9Fu9URE13GI74o/doc/N1NGWEnFXWS68SKlozEwAyfHE+otlNI5TvQCig2HCLJlBvxNouUsgHZKyCxYlhVTJXQNXhfIZAu3w7gHZsc+5SnHoa/5fHgKfFGX1882SmEPDC4fmPfjGIMfpt9cmb9kyP7/mpbyL+DB9cLw2pPztOUg3ZHKw/+Df94jnlu2lLErvcRp5lXgazvWk,iv:221IGl2DitbxSB+6LyIDQflOh0o2N0NJyDElLIyTbjg=,tag:hQ28RT2bAxu2AroB3jZnXA==,type:str]
    identity.pub: ENC[AES256_GCM,data:VLGSe1/VaFmY6HMcI+iqNqh8qa6hIuQFP3m3q3cXI+8zAu2aa8dNwlj35dFD3/CR/EoIQOHy6PH69rlcNqNhpMSi0BRHYH5PuGhfrpEeMDlGn6Kz3jBBFCkqphW7JWoUwdlfMo0a481nlV+2EVjAR2yH1lrccGX1CZGdQhDn3KbdbeXrPgOQyMQadSnDuWcD/CHXXuprOsXH2HTBkcGWx6g6mXAIYLVRFuPoLNFoBSBTQG9fxo5lG2tHcX4ROhs52t5A5LP6jCgl0Eyr4w==,iv:3/vy3WOiOR8xpmNUPcCUk81hxUDIoOxv6o7LCp4S0NA=,tag:OpE2D5eeqes+hhkDnLK0Gg==,type:str]
    known_hosts: ENC[AES256_GCM,data:CGhs3Tzr2dv3JKP3YTyX5xKMzG0nPIKTwaYHLrclLlOuyI1KPBC5QzS+XSBrppaewUqY2Xv431IXvIDgJv9zZxqem6sTCmjlHCpgRm0WYVdZWHYLG/1uCLBt57dbEskkBdKUlNhe3DbkCTOrX7wXw3ljxRxhMs0XJmJJGIjqXLfkpDy0ScwL4XeB6AfUa9msl0uSTQXInyKPPdDUvVMi8YjL/BQ5EUPqCPMY,iv:KZrBnvJbxCQiOzOtMGbywL0BGYvOhX4l5VO/eQuBpzI=,tag:Rk3bfq7k3WeI7S6WlrVavQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age178zf7et8frevcraphhp89ewxa0l3cw7wlert8c64dh4lwk9krsmq9d8gg3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbTFlZFptTXlVOEwxMnky
            d20xUjl5N0psaWVkY2ZtWC9rUmVpZTgxalMwCjd6QUZrd1oyZWRVQ2dnQy9YMGFl
            MktPMUcwU2d3N1NNSndDUXRzbG5ZbDAKLS0tIDNHcGpLQS9lanliUk0zd0tmYTBT
            SDhjMDc3RytkZ2RHT1lhaTNUWThRbFkKV0uO9nvl6h5y1yB6iiN4fUIS0hVrm6ma
            NKWpKfM4mRnrMfDH7sdiR6mz8nbD7YtjWvfKLbXQF+oFkWo2BXO43Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T20:13:27Z"
    mac: ENC[AES256_GCM,data:za80wnEBhI/Ec6TsevfNIvaYk6ZAeVa0W8aw+mRWVC/zBP82AVFZpDju9PXexrHm8CSbJVwWoR6H3v6k1D4bi42xq73qjXO/lWkjA7dyv3UNp9QUujF0yGmCLSQUjHRvsLodDaFPuDWde0f0fDSgvggTJ5HjX/0HkuJT8edAyVk=,iv:+u4GkcNI2eMFA9e1lxLAp1idiV4er8Fy1kcoKHMvGIE=,tag:66wS9JkLlwIB+zogV48G/Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
