apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:DUJsAVN33cr5Bh2EbVlmGkvnKT6UCGHElbB67aKBsp2Rz45rFdBYWU/3ELv0XyfsqebEOYI90quUT3e2n+5jJLTC9pYrL673UQ6NsUMo4VikQobed298swLWQZT5PulTSRIi4ewmLPKjesY05a3KvMVXgPTt1NujdZ7nM1vSSfEynjBCMrqhgYf95OeHac0anbEO3QeNMsIy1sXkQTydg1G++SP2J29LTFHPhXDAMScQdiVPkBUzdROg9znXW5dcQzwQESm7dagCBY1ff5Ij8y9b4LzTt6Rn26OYX20dTZav2NAyhIycRSck5NK3I508Jsv7Rz9KeLjYlWFweGk0HK+UdHAkpjcKxmxHtVw82V5E9VUKpvyJiE4L7KvKobzd,iv:uYWfVDr76TqjlZPA92Pc9EIE4RpNA+Gu8HuZmxfKTv8=,tag:NIG8ezyX84qDkNAetoqfpQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:FCeLe0XsDkOGzRa5nFB9z9MgC+COS04/HsYfDt8UN0Rq0nr4OYdODw0q/gX9nFtGWgwBe0e0kj7pFVTNlPIJKLXlTylYh1wdv91rP/dbZ9C23v1YVTn6p0f/TUek0gFg8AqsJbzb2RfNDv09+eTBysY0Mkggq9AnO+2cefAvdBKGhUYZvhXX0FWIeBD2Db34q86mAgvQyFx3V8kKAtsgWgsjg34YOt5tqhQsXXHAMGP3p449a0Npq9Y1EOhMHOfZiMJaCXeSlYhTqU/+JQ==,iv:p3MshP76uT0CoFzHN4L1YUrlU20n7Z9tkvXYf/p67tc=,tag:DZG0Lbyhohmgz8DJyqErYg==,type:str]
    known_hosts: ENC[AES256_GCM,data:g84+EdymOx/FwVt1LUQV0zmxSh+s/KpzMX+AhzCPW1NqLpkx9JiahmvZycbVTmx5R+oSbLIwgQcybJHOciBrIo751TBJzTX4YnV/vV4BlTiXqg9RpQ4BAzIqOgYl4ydHn8B1L5jAGAlp2mM3v52x2zbfZotIn+NZ5dYckABmbjTUXzbfMOOKXx/5gQaqjq1lxpZtwrCrSawhZyfl6ZEH/zkRBYINoKIoedXT,iv:CuJeq/o2s0Ly4nsKpyhsdSQHRiomKvzVeqwmMF7mjLY=,tag:hSDchyLN4734ciUKZ6gAFg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mqyd78lmyf63gcvntkmgqyyg8s78lxtserc735jl78fz36dr3s4q8me3p6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeHNhT282YjNuNVFsdzZr
            V0dzNnBDYms5YXdRRndHMDRiQUZDQmNqSHlVCjlSaEpIOEZwZGxNY0NlanJyY3ZQ
            ZVFrNEQwQ0xCc3RnQURsaytuTEVqZlUKLS0tIFNUOEI3MGZCcmZZMG8xQVdZU0h6
            MUY3Qm1SVzR0VEFNQmJXa1NpcWFITFkKxhTDScjjJ72Fp8GBIolTPJAeQCaUYTfo
            V7LeIieuXGQMi4udPOpKI3uu5uTLf80iouXQE4yxJ+rXpyQ5MFhsLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-10T14:32:59Z"
    mac: ENC[AES256_GCM,data:o81NCLbtzkP5usi7CEIIjBHlNqevLij/izOtHuOn2EQd+CqDM7+kz3zfYvzMa3TZvs9yzsOspgnki5K8tlDxJd7SHtHyuZj2XR1cXY0L6kDgTCjnii7gO8UQOoHE6sHAkx2xlfJgh+2oWhiBd8IziwWBsAzXZkY20bZ5aYz6i2A=,iv:3EuoNRsfFQRLBUVTFmQsYjTCenvcEbyl8Y302fXBLxo=,tag:r/Dl/VaKuuoGDhFRtds4aQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
