apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:580v/sUDEuPcfYjQzNmbq5Iv73bWtLzi92/Hz8rPPnRVqfWRT+QlEavTL3LevXeC15e56UChBOL2w8JPl+C63zsZ1D437Dt8wuS2+kLnSJzRE+cSAk8LjWS/GukaJukjFEvajuCivW9DfmiYSZAEZvCZopr9zdW2mrI87dpKYNOYzfbDmdCnLzADyJrMA/n+D8RH2HZQdkhrU6gOO2ynKopk0N9k9qXmzlJ3kbDCd6oww25V07HMsHkbioCL7wIwbruz4wAPejFEy81CGPTU/Y7D8Nv86X80UM6EVx23HmBQu/rWvlEg2Q5Afq+Vp+D/1r4rF03YWBOC7dqPdKTqyr6TyZssJda5NU5g8qeubLKlxsN92zCrSBeg5NOtLQ+f,iv:l9GpqtCIAQgbK0OHTbz2PXg/3/gNZONbTjW13Vlnj4k=,tag:3ljaU5j9/bn9g/msdPz9jA==,type:str]
    identity.pub: ENC[AES256_GCM,data:o8m2kVCCQ7LKkieSZRly2wQQ8yd6Es9dfgcWs12ciTyKcUFWmP6hnVQcpMMJPOyfFq6yaWZiwXTji05qmLKDVAbpzP1zNRt/mZAwHwmZRYTSxdXx+lOEuXxht/XrT4S5Dd0km5ulljfe7F0Kv+g16DoyaXOinmwqkuYSx42jkzXARCF6AYchpoPktft0clPNXLcEWuaB8PyEZbsbuM6mN5Ze1JMmy+Ub0ffRBgSH6cIhB2rvx4nq64XVChzuI4ISvgafj0cwirxXJ634kQ==,iv:sqFC41RH6IGUbVk2PVdIiMjxFFIse1NU9WbkAfYGNfw=,tag:N8jjFYrUMIi6bO9Nlaz5qg==,type:str]
    known_hosts: ENC[AES256_GCM,data:+2e4T6KW8zR4mYoMAp03Cdh4unOB9goZ/0hd8b79ZV9eTLrxK4Z9HrG5O8Sl6q6EIy9CMWzRI05zGuHeqvj3KfJCww0X+ils1i1zXg6yIk30hWtOqK5ov8ItQacjGKsglvbVhBxwWCVLVLJNKMkLmX7h7GUF45a//Fktgh3QEHUfzZcVTb7xgJ5YtO+k6ughgvuM3PG585hNl4l/l5668dC3ONELnzDdv57X,iv:e1mkGJwi7WeVuNUXNvA9elTSu954TVDW6HIIA0frDIc=,tag:UPaaiN2l0Km9pzzX4AmZOQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSXBsOCtXWFFFUUVmSXJs
            aXRJWm52VVhleUt0c2xJYWVrelNnRVJFOXdRCmlBbFp5WEZCM0hGTlNDYzR0OUhu
            U2Ivblp0Z1V1ZDRuMUN2Qkt4djdTS00KLS0tIEM5NnJtZVViME5Wa2hTb2hiMWE2
            RWs4S0V6dDZPZ2ZOSU5HSkdSWnQ4ZmcK4F0jIG+BUJFLXXQ9j8pEXDRqY/BGpwbD
            VBgkKgeHhWT43X2z9UO6uelP98CR8ZTMgJNH4zz4xLnuQxkXiZuMWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T21:48:08Z"
    mac: ENC[AES256_GCM,data:sjPHip5hqevSLjVZYa4TqaDs4+O77Ngt1Q2ZiESvDWd42BtPykgj5OK+Y64hYbxmEuuvIFfNZ+LjBOS4Kv+em8sP23TBdGMEj3Y/KxcyGqRmTx52UbzVxbu94D2KOfD26ISBq2H2o9Ej49ovwChB56dtcgbCgbVjNixVfayFr1s=,iv:+S9RtqlEBeTIN7Jn9edgcEBLRs7umq28Gfcp3K2Ps4o=,tag:6R2REOPKiyFa9cpppPvkCg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
