apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/dtO6R6f0IM96iKN4HIuNFGQ8QjvkHVwIVGAZoGwhuXsKP9lawXz2/jI4w9PZ1p5xCJzH7/T7RvxbW84XUgkGLU4JuuVssR3Tem1bfwYhnYHnTrmQcdr6pDtfrbCV+42irxnR/83O1wrfyE2NHt75FVTXScBcxMEm4AeH9dm5A/3Irwv5i9B5u3ty2zojPR9gbmY8iELK/WF9eWCzJit0poJyI+ydEZBOqrnohqUx5J5FzanoKTLmfliR2XQ0tGml/XgqA4opkTLvjxHaOxYXoSk7FkO1Xe8nUfLNTNgY3NlWflrk5lCMUeKwL9fB7uOKK9JDHmLI044ck1zGaPPeBIB4UxW6PAUi74dMUSFy24H0NEaiz56V8UKxlVTez/w,iv:XCaPw74dQ1pp6Vk4ZQkurYevbB1KxxuSGD5xZu9qOp4=,tag:m+LWznsIZjOA81X2n3OJ5g==,type:str]
    identity.pub: ENC[AES256_GCM,data:4/qQl5lLAwGIHODrb+llM8I0ZirIkBDUc0L4cuk6Hsh+VSrF0ZZCoKBchtosQvXmkCMVBLQCH2p+HBF8XaGoZ5Auh9O3sQ1fujOz7cOwKr6rsjPADnvHK57ssJ2VFMhKXJxlVdtHdYcozMZmhlJ44Uf/dyD8lekd8iktbRGy52x9qLi2hPiGPPul2x8FnVhDMaPYql3Xx0cnOokNYKANvqIzLCNdPYOYrz+gaf6KUh9EtqakRJTWGOqaSb/WtVanXbFZd4qcQMtgjx7eZg==,iv:v0Q99Phs2xxF+P0ks6CLvGwIYXtVQQZ5PmQ0ur4uhek=,tag:PG/PDnZjYV8rcx52s+5OIg==,type:str]
    known_hosts: ENC[AES256_GCM,data:Oc1n7TIH+qiMB1S74fQkADwWHladXGJTVJGELJNFt6Yxl7D84hBuIVn3kzr2C/S6VcfzI0N41s3xY4N/rTKVusCMLRZDqdncRe4yUNpjL9QJy6Fn1YlnbcwI9bFRLJ/7JOnGNIkiY47aN2wm89prR+lBmmSoS4nSQFXrZIhLpout6L7nBRdR6LV5kqJR/5vcomJeWTu/OHhgzwtExs9WQWAi9obc7d92Z9D3,iv:I5JzAKIUyTJuNyiEQctfUrVE1Z9CL4isffjhTdgx2EQ=,tag:IafSaBsRYGGyE/40NmLmEA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caandqrgue5nl44eylp4nvake7znrvxretz3uy3r0ccfa2av4aysejcgfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YXpCbkE3MFVCRmtlYXJ4
            KzljUU92RkoybHhGMEphbk5lTFhJMk5nM1dBClp5NzFZVVo1YWpvUXovWGttRyts
            MDRNcXBoNkIzSjRBOGtNTVpCekNVYkUKLS0tIDlSYXI5YlVkQTFML3VGUGhjY3Q2
            MThwR3IwUmtSb3o3aTRsMXJ4ck1GUWMKVie1WgSH134BtKe45O+FjUpjRMy/zyuy
            HuNEwfhq2DVuSWiXOwHUCmJwkiH7+/Pt3YTAMa/3TUpMWAxSpGBCjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T00:35:29Z"
    mac: ENC[AES256_GCM,data:X7xUI+C4ZAL/xlChW3DSi7Q9unjZhIj7RwTSoQ9TzLU4utYx/jHAUdhwrTc3W84sVVt2qSz3dijoG37la3CQD3OlwNytCk54wyyMr52VhxkN6oUI8HGOS9rLvhj0VXcq7OCbFRz5g0UEcK86Ucgu8L8FnN3j5zrlKujw9iGAUGk=,iv:+sW9IAPQdKiKgRnAHKphTY0+98nKXn05XHO0sSKKd4Q=,tag:WDlnEPQNBTdvKdqxp1QZJA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
