apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SbLXq+uOEH4v2QzWVN9ISBGmInSl7VhK+dmKrisikXF7VUYJWPteb5tHNQ9T8EnaWFQnhblnWSGZS6ggIAMO0N03N1uiEmvlEAQJ88BNroQr5UIggiHUtREetzMCNMJWn9bYWd0WrPcUjtM7ydWWktQloLv2k9ahFEkWjIBDN1/GUqOVDnBFj22pdOFeyi58oxvywZERzy/KLigDbSiGCspCSBGoPg1LJwLOqgRxnTQNFgvKu2Wj8yQVRV74qOFjbTo/p0Bs+7/O1DIEbsdmSWcMJW73AEEtwqrZMEDvnzJ7Bx0AQtMJ4kNjrNnXI8fzOCBvhSU4HNu4TxnGSusFFwBtGejYIYxLB+mSPY1zOtw7C0TWoRCgxk7FG6BQ+N3d,iv:Bn0NiJj2LJX3QsQDK21lkpuxk8kJv8+IF5QcpNhU4NU=,tag:dLrCTDf0x7xglAYcmkW5aw==,type:str]
    identity.pub: ENC[AES256_GCM,data:usDIrwZroJMqvQ4MRvJG37jHc3bWMrNkuVEefmn8jpVJQlvHXBBwdTuVcnIbKOIREXX/Z4crtAkINUVd8hU5FOYei76N2peOd/nElWhEtszmuKn5v1b6UKFHxD9o0tAFxDpNQIHF93d0KsLmJ867FHBUTFSbD/Z7K6niGFOs4sdvy12DkTQ5F8nHTk0O8YOK5aTU+Jyw6XIxT0vgoQ8m4Mr6OwUKyZn10SVkm1WiwTjaol8uAzMOfg3ZDuxJfpZg1OjIjxTlx8acBhcMxw==,iv:vsKLFiHELwr3rwVxnf7bq4NPJceZmURAtqFVDDU0peQ=,tag:sReUnMSicIyVJ+PKVoADJg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZkfZBcfDkjBclDz48akKOo1TaHtnkIhlUtkJXAp72TK1cjzDsUazAh1BeMmXnvHLy56zReADxhYJK7q3yNQcIjs6adXP5QIwKKs7J4oMvbREJv6i9rI3U3u21yWGr6iWecHFMd5LIz58scG4uOmzUDc2uQjjlFazNjuSoJ7Kghj1MYEmIidFyIL/mSWvJbee/H8Qyy5VzBEhKx0JzKivC1429z7S16+Ainc6,iv:Coajnat+c7lGJZW7yTBsvVRdk3ZIZ4NnFjzpL1b9weM=,tag:v/zJeFmaI1qpwXZsOyx1EQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kt6a6y84qj0y5ndxtn6n77ru00musyv88q5tu7vm80095wv9s3pqzxcxxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGM21KZnJTM1ZFeXdJK1Zk
            TGs4dGpNUzFBU3pBSnhXMTAyZHB5c255R3prCmU4a1FnVlpNcVRDZ1RBd0c1aXM1
            UVlxU3dUUWlrdUE1eHUyd1E1K1I1a1kKLS0tIG9lTHRxQk1SMlBzV1NYaFUvb1Vy
            NklIMVlKMVI4YWRlN2hUSFZXZkJ1TVkKtH1snm6Ou5iMZJoSGO/9fVRchby9PVxi
            dxY6wpoR/f6jtbVWP33DLx7FNhaB99aOb8EMTOa8/ogyUDu6Czfhrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T19:47:41Z"
    mac: ENC[AES256_GCM,data:n2olSx2Bem4Lhw5+QA0DDqVlzAPNmdIbVcmA5CQCchHi7FnjaHXZrSCuXIU+vyxWsBVvIdWAQHcK2ViClnU5lhBY1zTtVl1auRsJmZANU9PeH31gYcCRgTrHeVCFUPO1Z7YUywdhuI15AedS35beNYPau0KSWYl8ou9jVRMUQMM=,iv:w1wTlouWhGf2JWjuAxPwPmuwTdhXFefViRooNzKYvSc=,tag:ZN5VXGqoAT2XqrhM0IVPcg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
