apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:iBjg9G/gSaQSzofH6Oy00cR2vPem23AY5YpJ3osTnTlG4ySX4Aj8IzmdncNcfYMLomi6MYlHoLj/RP/QoNwFbof7//k7uaoa4utwvNh+p0y62+hHRj/h/ICUHEcF5dmtd5fEFNWj8n3i+ikALcJ6bh5ISFEcx5KwvDcdffPDNr+mwEDBTTOrUVFisQelqXzjsoZAoFItlCu9ScJxPHynSdVGgQkJZRMEAmM2ddN0CnbYYAnBzaK0lpAuncA9Br7l1eeMHG4U2n8l5wKT+VNbQN1YJFDb1vQrEeevji/EbRe8X6ioDOtryUNz9kmA7Rf5V7hDSAqGJLcAq1meodYhXv2EL7Y2/Z25LQY1fOBys7YqjxMcHM7ubqSSyh5wQNAC,iv:YK2ji9fxMeGVGbKHsC/bkWRO/lY+G9kzizNClJDL3R8=,tag:IyusiWys2slDN5WDboXcWg==,type:str]
    identity.pub: ENC[AES256_GCM,data:MpCDSOL08aO1u4WRbGhzDpr5QNgb5rrXlK/1yQgVQ6a3SRwRqkSsYiETI07mWJ+7ROTJveETd4YczPp6QYHWfxsDPwACAbbCaHUqptZ2meneBImIw14TuJNTcqm4BTFdM4rxKhTJMpTiZKsRBOaY3MjFa5s1EsDnGaBuKIDc6w3FD57HOklR9WvmiXPNthH3PQCrelGgT9JHTs0K5bSmyMkPxwWybsUsk4KQ3zGhNHtY7ergRwqWRDlUmcCxfsE+Oe59ReU1RT9R2C+JDw==,iv:3vLe7AOAmUMHBrnwv0eAAGOpMxTZ0miVDcRct0VM3Fo=,tag:KpHgOA727NR4s2SF/aGOHg==,type:str]
    known_hosts: ENC[AES256_GCM,data:g+m7KPAxF5eib4CxXLdFHeBLcdzae/lP3O9I67w0ZxJh3l/AJPr2GZwEsRvBRjay5jPxqclB8qZmVCcVCy4jTp3+8Z3cJdS9E+uFJ6qsaExsHlf9PP1rjXTTnmA31W/aPYtGXgJlRmOfGn+0HbYUsQ14KkRgGOAh+yKcqghTmQKD0x+VJelgG+XFUtNiiHjn1ZgPmZMeohgmTSoTvqXoRYxcC19MaD/qErwW,iv:D+44tnlvELUIhjVmc/dCvodZm4eF88Oc/OehdLc1/NQ=,tag:JgDj4yos4gSlBCUWEZ4lVQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RGxkUTJWOUd6aVRQQjBq
            RDRSaXVncUEvckZaU1F3NnJxV0xsdzlIalJjCk9zakpNQXF6OWNvL0JobGdoUzVa
            TE9kTmRsT3MxNy9qNU8zZklqKzkreFUKLS0tIE0rdXEvS3JIWk5mQUpsa2J0OFBm
            NzhDTzRrdjJrQUNSQk10YVlNYmFJR00Kv0WObTFySW/UqgBwjGWu1rHwMGBLkU6g
            JVenvQM1gHlaMEOpxjAoVS+EZnVrVBCOeMzCVBHx4QPwT5/Si31Mfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T12:25:51Z"
    mac: ENC[AES256_GCM,data:oBL7Jma2xU8Bn+DggBQ89QZ1pi/tlecaCBEerhCtRR6CmeoDNVRbXOY38aTuwpKMt/6qfOueIwSZfSVCg4GcqGSzip0CH3r09fYj9e1dFabkBageKHKwIUOs3lH6YyyleX1b3eTN9mC4YSlpcdxMqZdfCzOKoECFi5BnGDOFdd4=,iv:aT0Xew7Qlq0xrWXeEffpZN8eO+Mmgfix/vbr+E/+4EU=,tag:592/tQd+hMlc25UFeFCcMw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
