apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LN/4LkTJiRt364Bpx1dJFZHE/L10CCgFHMeJPF3GgMktf0TejKkFfNl3pZJynGb1LShXJFvwiojUVAMdEo7Soa2cpX/5nl8a+rNZnLq+jrIc6BcOt/fwMC1KZRUgtIUw6Xc07CYQJm2ZLDWPDTJvgYBDMCPziOo9iXGmkNVisH8G00fK74L1iBj3Z5+VBH82Qe/Btr4tK0VuF6elSttDrkYgbs4pkhz0BxjgHWfGbk1N2loz58a8pVee1SDg5/y6XYVmsMB8YJjmVSITc8KOcU6Ac+Ndwz8ldtvvO98OY1vzJzRwhFvZHcz70jbjxdJoUtjtnsm2bGILzv3Kd9mJIXwBFbei7yALHOOlIfJKjZZOvOGF2Fymxnp4zcexyLdO,iv:Hb7QQ6UestcLe/GqViGg1WetKHsXVVMHfmkyMSnPifY=,tag:8ssCIHR4tEDQipLJWiX8AA==,type:str]
    identity.pub: ENC[AES256_GCM,data:tmpx5Mo9MG9Fd/OV9R3YntqqaYCxSzO2W/RetGx7PcFFGVkBb45A/kUWcTYpJ5fkchFtPVEJA2TqQA6nIntml7YzVDz9wU1Hrf9NONDGQ5h6I5C+GQxmbyJfei74dj6Wujg2TYwvR5fp3vnD3MLVxfv94FYtrkVB9w6ZoL8Em0uBMwNsDQhx52J6UivE9D3jEf2y7ToK+VLDuDtXjYyYfkMN2q+b59AZRfvU6ycLa3zjuZ5Ecmm+bhueg1kG/AboIaPKU707bcHKenEiPg==,iv:JLfE8NKH/mGIyBKS2jWZqRXSBwexlv3DeENnoyg1mFw=,tag:Fk6tQTLF2MXwa6Qcn2PD7w==,type:str]
    known_hosts: ENC[AES256_GCM,data:k7ecLMtkwL4MxS+SoQAo/nZ/kdaf+KJpdBDm49WPPI4wU6+ZTkVVsqhj1W0caRp7mJxTpb//fxKOiAz/FyL1LqJxCg3ZAIEBXSA+/DGAh5DUZZ+5uvfG3v8qbmcM8fxP2OuxIYI8nT4ruF7Q6+BU8m5+j8AO0gjSkR8RfZB+fUUDc7QQfTJWn1GuD4Fbf0hwLCJSPhfxXzXksaB0InNIhrayX5cEKryr3zqT,iv:gt737S/tDEhFSYGcJPvJfh8vvIReCM9gPxTZagnt3W8=,tag:9pxvE2d1PXyCg5yHyECSIA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c5g23qt38utyy253gvf729w4l2jnj7pqn5s00kkzsw6l9k9d5u8qmkvkwk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSb0JOYVRaTm5hK2N6d1ZJ
            a3h1S2owZVc3Z2ZxYy94K0FVWi9aM1J0MnhFClMvV2pUcDZXdFR4YjJPL3huRzVC
            dkNIVlk1dzJ3MUtJWVh6dXVxMXllTGMKLS0tIDd6VjdiUHVaVnZVV2hWUFFsZlNW
            TXN5R1VCa0NxOFAvQmt4YWw2QWNJUkkK67ad1sA14Oq4G6JzOD526Q/qJGNRikbN
            /oPfzBqVmcgB3PoqKKfnp/Z71SCUiAm/EanesYbAcxSSjkmQ4Ca+9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T15:47:34Z"
    mac: ENC[AES256_GCM,data:T7k3mO2+Zn/I6NFW+utKWnOcKiSqp8+ILbmTpbdH07dahTj7f+dnUF682gqqid2BZ3jnXiXbLH52CMTF3v9m4gwmPFmQeDXjZx871+C4tvZOsscwf8NsFru4Wp64sP5z6CslHXhEBVQVWnDjrjxeKWX15B5b+hmjnkS9KAC71gw=,iv:Ebgm7OgO6zg684FNsfP0rIh27NvOm0MDEwWpJ9xrEXM=,tag:Bxqlf6SNwQoIbU1SZ5/t6w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
