apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0d0+IwRNzdKBzYxgzc1YpeD0Fv2dAX5rO/MUSPFHTZaarn+p/3hpOtziozH+4JwoAoa2l6JXdyE1OlHx4Eef6WNARwU4wzK0a8S0jZuuLh3G28CNTXLaS7Ur+ZphXD0Kacdm/XFPd6zl2w4ENTiGsniIrvCtC5cHJ2X7vgj6CrdQA+vrpRT25pHpJLpIXlMAU0UXbkWUplVWh638bdERRjusn+m/RZoY23wuuZsqTQPOhv6AFngyVHRNOYFAhuQ2ZTlBGPldIQjFavAh3YbwbgSNSLJUO1VOjWW/nfmIEPtcu+d7FEfDRRwAUFMRGLjuSBJ/k0X3mn6C1cYoZ7PgmQs0IckZPNXzPnTOSI3dZnIJ574DCcAMaEeOQH8xPjvS,iv:C8G3QBI7zz/g5nsAbLgs+FInz3Fb0IGASWAz6EmeR0g=,tag:7zdR3HRzHVpxmpIm78zYiA==,type:str]
    identity.pub: ENC[AES256_GCM,data:rccVAuylErosjxGErhF2vZQmGdjT2ZIDveXXOYVArYho1jAbdO+ZhFbpmVSsk+2z/4H/A60E/tiDNg6YBO7Q5JR/jaJcEQUqVY5aTQRtF09m+DELsJHc5Xg0dHYXOw3HHO58jGyP+W/6vrZ437pXLiPAoZbyZgwmoHutxO5z7dIIJEVPW/0IxK3Z2Ux3wLQxR2uWhE8Q4DTCcFQqVTJfy1NQxxf8MZ9vdNLIGdqYGuXqiEDLq8ZXbC3HO62Z5A7oEDPe37TwolMc6+3Bdg==,iv:zdyWyUvpUSiNO8x8PfxApJQVQ0gmi6eolSS9SUrM9Qo=,tag:+vMqXscA7ssxVsyTBOVveg==,type:str]
    known_hosts: ENC[AES256_GCM,data:AM/jpxWNayHEIfoouPBj4fb0itwr2DRxUGz7URNGvo8gwQt9qtPVFqUSFVMLEWwST5ixYpjy8AMYrZ3yIw5coG1AKgiYZdd3xLNbocL0Nrm32v/S5OtLLzaWrVgiGF254MFm2lPfYbUCzuCYQoigIMXDcefikmfIaLTYSYrAJBJfAvakSwyZgT7av+uTAZDL6M/YIPeKYQfaIBmIIPDpJnAGbKLDD+7PGYnZ,iv:DkWUBbSkrzgj/SJqofcAWkXjZqrp4/Bz/uUGmouaM6A=,tag:2spNMI+Z+tezTlGH88UvvA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kt6a6y84qj0y5ndxtn6n77ru00musyv88q5tu7vm80095wv9s3pqzxcxxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTT1FkblFOVnFjb0kyMVBo
            aWx0MlI5WjBTYUd4NlhMdW9VU1NEZFB2eGp3CjdWaGIwUGdNV2E2c0RpSEl2L09T
            T1RqdDI1WC8wVFlEc0RyZ0JhbjhNZW8KLS0tIG1iQWlEcnhKWk5CSlRzb1VnU1c2
            OHBGR0l0RTlTUUJmc1lxbnNWV2lTUWsKGR6g25joJyoVg50Bjy36QFTViI1Rgn3m
            ZBDKPaFbaYrD+f+4kjOhzUERlepp7p+L+TugpQJIgjYDPszEskRdCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T22:12:20Z"
    mac: ENC[AES256_GCM,data:pqdFgr7L4w/oxMnUGq0G8XP2VdRVDoM9qFuNMORAl2eRIiMElgSqbNsdgJmU+p026p6MPgq+NC6mYxZQjgZi2iHYlMA4Q0/MSHBYiJ7VLLSBZizZ3vVMLEJ6JvD+mV2rW/mwmfOYfMGzLCklqSvsHb5mPYbRChtzeoyJ4OUsNEY=,iv:rBo20r3txeWHO5tXUp2xNa7S0fHlFym/9Zlrp56CE5w=,tag:HnxWgQ62GFX31U79YAsueQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
