apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dPBcxg3PPZORuk382MW67lta8G7p/7aJp9EGvfliFyDIgVrS8BY+UA7ONNWPlzqh/epvVZ1P+9MMUfsbLOrlLKqvbOFfzZ6+sy1ymLH0IFTVClvhvgU69DL2y2FN24RpgWIEbyGJSVcG4aOn4K41FwESliBAoBS/T3SLFnJEjM2osalU/iJnoAuGXQvwpLcbd/pRrU7w797X16T5MkLAzOatdMZuiQfud5RK8l5gMwGPYJnhqDVW/oBIkbwjh1k9o5hLAJrFj0SgrR1NxpmI90z6pR97VRXIrwY2m+6YLqrTyHe+/LhBjoOICZW6NAQxf0IORfcPXT0Rq6qtpkMfZtSeSw1qQfGYMTdcVS2/H9XslM7Cb2qo12jPF5pMSJlB,iv:AuNzB6zvUZZxTymkgupTXSCQ0ztW18DJvgBteVlfaHU=,tag:MNFDQlD/UUdoGS6JMs4+Tw==,type:str]
    identity.pub: ENC[AES256_GCM,data:5OAWZWa+L3SFTdC6DaT6TvzgDQobiQs2vsEhgdx1ggdxvcRrDwDX+LcwSBB92YTsWN8IZKNLuQynXnLn5BXrmt0bOOf4ViM7wY4Q/QOmWr+78T/wpEdcR6m8H7/S+67DerR/Otf56JjrnwBvc93S+XBVZlBQi+sfbjnuRGNopFRf+Q4nRXYXyVUX8RM+R49QCkdftroDySZXEdwd357cdYvXTAzcaUyoZbqL7LPgEf95Zm+fscH1Ea+oQrTmQkVN6NYlfVsQO9hj0y73Kg==,iv:nG5BSKDJHNsBwVfLckH0pJQ5Z7MSQdJVMkWqievx+t8=,tag:v0MGeOiXNqY3XQxwI+iZ/g==,type:str]
    known_hosts: ENC[AES256_GCM,data:zH7rgh8KhM6SqZQVseHHx7Cc38zI0xBNngHisc+zXQXNmYHHqGWzcr7nPFGrKEOy88/Z1nSuSin7vUYQTWl1TCqCJ3C50zCe+N3ZyF5fRNxDbPx3LWh6KEeuZh4IIY81VNjPa4nXhDr5u8yJFRh12YyEqmV1dzWGygJoXXI0ME+yxaGVbCSPW6ADxKiup69rEJPK59TXIOBTzEnzw5kuo3c5CdTo1P2EKwXy,iv:RqyR5HCqh6XBoIuAO7+JI4a3kKrX6bx/90Pwr4i+WpA=,tag:ns3Ew+KaGR3WD8EdJ9Dp9w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kt6a6y84qj0y5ndxtn6n77ru00musyv88q5tu7vm80095wv9s3pqzxcxxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdTFZb2pKZEIwbmJFaUtk
            d0N5dENjb29CWWt0R3dzb0ZvYjNnQlVVNVZzCkF0RHRoZVB5RlZ4ck81MmZacmN3
            dWZWVEJxWFVKNGNmM0Frdi9RcVBoV1UKLS0tIG13dXNUdkhSOWo1Y2VnekUwb3Bl
            K28zTFhqZlh5SE50QVNTZHQxTG9tMW8Kp4GZAdOpdN/O8csB25Bs2uB+c+4l65Rm
            Ba4obLkR0CeqFozwzMHlt83YC2+myk6n3v82vs3pY17P/h7cicyRag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T02:10:45Z"
    mac: ENC[AES256_GCM,data:o68s/IHViObueCw6FYHZ6uOqSgGmxQKBCBu9ubQJ12SRB6yRjKuA6ebbiVLfzTfMdlnpaUrM61o5YtrN4X7ui59FzI4Tv+xx7QlN7TTgB8aHMvGD1DmAoMr57ldfyFOdiElJ6zsRt2OMxA5S0zFG6Lr8CARGK+HeI42dpdb7YVA=,iv:9tCZdfiV8mIFk02gMEduiV6IZ9tDd175AaWbb7MiUwo=,tag:Wzy6D9XcF8TSDqeDXLCuDw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
