apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:eUz+EzZd9DA6TIUxbBXrwbc+XfgToPQGxh0/XdL3UATsoPDOKWwYB28Jw7WMKpUVwT9w1o2cKZjNnGTYyDo7DnYu1Vks/cHjQV1ukyMpHnrGxbFxjHYrSehN/dGr1SE8z32/u2f2L9iV0Gepx/wM/8uPXodge7VGinDr+JZh0jMfqzodL9zRj8iYaals1YxBv+GOLeGoNWiVnRUaixqyeqL0E4rRvlSjPH4AP0ly90mbCezp6IAhXlf6uEvyk/iVd/M8Pmew7tC+OWPgyssyfaD3H1n/zONaF1ckfFFaU7H9gD+q/iV7TVnsK0E2QEUSwjanTnSEi8bE6YOfWeiEDblETs7BGvGL5A5Sc/7CmdL+hBB19GyRNfPYIlkpZ0By,iv:/P9C5DVfrjiV2+pu1hG5729B3GtORPKfrq7T92gdNMg=,tag:UJyZpMplJCr42L3s4GKsXg==,type:str]
    identity.pub: ENC[AES256_GCM,data:B3QH5BhWpfVI5H8oisRyOnFRvpa4eBuxuppezIH8+9Pqojl5oWn9N3zkoWXJBTbEbBfNaYLrEZ8qXZZDrWNeVVhQDQojwnZO2TMiSTUU9cQ/cqTEnofnyotDVabqqsVVmeZJCf2T26O2MVhsqq/9mfeOeGxoqEyt4EiKZR9ouokMFHj3cGS6997iIJOdVRzh7IMgCjTA0CpusT2E611m2J53zNrNVF5lY/XDx5taI8ncrZlqwqp+VrXAm4xQdgm3yV2KzsK3SSYuj+W70A==,iv:BJNmLr9vEb4bH/ALvvv5gzdU+fdjxwo5xC65KNjE5Ys=,tag:0QhniuHf8JZqnc2Fmfe41A==,type:str]
    known_hosts: ENC[AES256_GCM,data:tyYLWZfP472/BIef2dPKWllWPICMOXlR3udakli++5PcV5vjfVTpqEGXvZNs+4v+FwveS+sHygmiZlpRkoVtgUbF9Og1OjzHg9LjSQPS7LZhbgXf0gyASDs9WanjA8eUaT6HA0cB/oscQ8FRo6FI9ikq5HgPmKSX9shRhHy6TRXsXqvmqrx0R4C958GW9SqCRlIxzrt/2a1j7NiCz9nFW83UwVIadUn9EuFb,iv:g53Lnl6QkbL/XyxAYFn4pDa0+1oYCPgxPF0k0dvW5WU=,tag:CFlqSQ0pSsWEHZUrwjebVg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caandqrgue5nl44eylp4nvake7znrvxretz3uy3r0ccfa2av4aysejcgfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TUlKS0hleWFuWHVnN3I2
            R3g2OUhPNmtFZFdUdG0vR0pvVzZoSWFEVFNjCmhnWGdxTTg0Y2Mya1E4ZmN4QkZW
            Mm9SUktxU2ZGZUtrVGxKSldUaERwVVkKLS0tIGd3ZzBPYURxOEU2aTFyaHI1Z0RL
            OTlOOXBZT2Q2ejd2MXZqSDJVSHpqdkUKZTPjVw2Kll5hMI3cRonZxXq6PkH0DX8a
            ycXDB+0eMjSkpewtzp0CqHOB1GrmQrcuN/9W01IfjI5YTJwranWTNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T16:19:46Z"
    mac: ENC[AES256_GCM,data:3Hh7YmGIjCZXohJmZtFEFo6rLYRcdBxOUP9iCgLzjeI/XijZsQzIrSMf/sMrAhrF/LTK1Nk7QePBlu41W4AF0DgCmIOC/H99huXQaHNaELS11NQ1Qvp+SZSqJPzWC90dAhEo0IhSjQePR7gkw3T89xo2/qWTOHlVYgCChByux/8=,iv:N5Bfy4Arjkkg8k41K9N3qUguqDptfjPj9OGXY1v6UAk=,tag:QekXm6qI0EWKV3AkX5JCbA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
