apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:BSr1PvbmJwIEYIK+u9QDRNUDACOumXKcnLZAB6hwvcvQ6rG0k/+CreZ4PNAf+hsjbtXJLhAvjwGv4RNqkX4OZUMR5vS+k9z2FUR8nzk+mKtrK+k8jnm6ZaHVOTDgWrimlHE6kcrTZz5XhnuhRHnVaPoagp/eEhMfTTKiyY1jF7tiprd+RGYaAAWDtdJKw03TcnQTN7VzTwHMX76fjvbNp2Ol/4ZlzR23lyWHXYJHy+B5wW9eGLtSFXnXfAvpNyOveA3F/eZC8nL0+2I05+aG8b95y7nIpF7vOdBUzioGAxsCS28GqDYgVrkAPfj0ppbU/2ZGHmNcFm2CiK7V+ocgnciJMtTIOD0dEldAPUVHDVRRnmXEcYft1B/IChD2UJFM,iv:Ctii38rSdQjVaOZtQDuSrAsYMT1EOnO2Y6zw6Z3zgzo=,tag:of0W0uNimiHNYBD6LhiP5w==,type:str]
    identity.pub: ENC[AES256_GCM,data:kSlR3ssPEDMihsKhp7ojcctRqj7uTUm/2hy8fgqD3LgqXbWSDT7SGaUSHf6vr/WLYjye+KOz3/GYhLWWVOGxASGJPup4goIr5xYN1+gjco54o4PiHq1xH5fxyZvxH7Y+hHXXV3OHKx4jhjotabNDoP8aLccE7pZmIrukggXyOIAoShQEf20NNYEcU9Tfn+A1Hbv8QsMLbyLeBYKzr5Xr1nXdC3V5CUvGFMXHS63IzYJuDv4C9zLm+kkLFEZi7dn3XPNy+AcBIcUeq0EzHA==,iv:ZZD92/HXzo9PT9uxuaScAxkPfuwXNMZ+1dsFgW3fEzw=,tag:CJWVv/V9fJDpYgwiT3apyg==,type:str]
    known_hosts: ENC[AES256_GCM,data:mmsbQ8303rvl/+R2OtWwiGzrgR8IERhqAeHqz7rBTnoe9sMLppPdmMKp/CzIv6L7yuKK0KIFJ0oGsYnalS2ZNUvL2vyJ119WPW/hANnZMCdVd9spIKX/8CtTuQ5JE82hloDtypQe21pwduxR7loCE47+u73Y4hK9vEWJ0MkCXhOl8pd+gfMqzfn3oo4UGoA+y4m6CenHM5hECDDTnet1tbafmghoVSTijA6R,iv:TeQG50MFnbWwTqQPKZqQ3ExOjiJ6Zl5EVYbwZNkHWLs=,tag:jM6ppu70fC7LaMyRGwgjSg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kt6a6y84qj0y5ndxtn6n77ru00musyv88q5tu7vm80095wv9s3pqzxcxxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbjRKK2ZmaDdCNWNrWk5h
            N0NTY1luYWJ0b3FjUEJyM21XS0ZjVzRtVmlNCktUQis3byt3dThMM1hCU1RqbThU
            ZUtLYTZYMVJqREM4K25peWtrU0JnT0kKLS0tIEVvdkpHTVBsZ0dWbmxqUHU1SEQ0
            cWV0bWlhSzFGN1VkMjd5TDRlMnRwdmsK52UrIUYNaBOd08qA2c/6n4ZkFVjV2hzk
            Q+U/vIttu/6WynHraY68cTUdxrS00ebzylqbUbNCVYmplpKxy+TDww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T02:03:54Z"
    mac: ENC[AES256_GCM,data:CFnVyU6dwGSkuEWgmLNFIJBlmmPRSs/ep7w5o1TwMdbRxtev6XjenZxsRBY6w6uyFZsTk4ZgN9AljVBV0k8rSlwmq06nyGJiDmNVM2Y2RXuth6wVqumPobDsUqU3Q1+xMqVReaqqqfkzUspygHbkMHHMukgia2SllxGx3NX7icM=,iv:lsI3SnQwpoFcTSj5Z49h7n2ku/ZusP4aQ6pe1M5VeFU=,tag:cvar/L01avtO9oFwkMHWdg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
