apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:lJ8Rlkd9BgPcxd25GvjLltJpvH/SM/qksWwzgnBrivDtjtvZFYJJSHMvT2nWYiOfTOrsDL90hp6FOcdhWso5sTMeaJADCdEgkx3o7i1OjaGGht3GkVRR4XA+WNKLxi6AOtQtPoveajHTq1PE+hkv9V3/yAti6uXtCzpUZYCToLyftHgK+NhmB9MgWW78az1JcgYiE8MMV8ajzPuXk3F9h0irgIyTzK0riVx8kiYagnr9lbIRzlv4Er3B+AAKlaPZEKwTkTik8TEiv/ZSnW+WHEiXSugvkn08zwgVj8CDSzZuT7qkBChN6rQDNga2lVbDIMS6QAIxHwAV2i5epvCvcrszWS0mmxSLeRQLa9i+Nk36fR8AMafU/KWyFkuQ+Vyv,iv:QDbTtjrB64nTZPSLAJAkHDlBfEiKD3MP8/YZBq9VCP4=,tag:+uWr4omf+smm1EI5/hEVCA==,type:str]
    identity.pub: ENC[AES256_GCM,data:D10X6yFNq3sW5+ag0C2A5o+hYq1ATmQ/nw7yyZd9rW2lRy8Vqvh9795AotkF3looDDm36vdgWlSMlPplL8AdY8tuyxwvHBWaJX6S8ngQyl4oMh3XjikYpOZ81UZizNoxl1QfVgB5bKyHOCM3mjqKkMwutBqyscvQZQqrrU8YSdZCIzvWVZD4KovCpPQhTufjjhINr8I8CkPej3DPaWPHJtbekF0BOQuyQ9zZYMzancdtdbFKuQmUboP8XbbMKFcJUM9HbKaiZM2nDsGgjQ==,iv:1jy558GV+tjlxcfgCGfNYCi0K5l45H4izKKrf+9I2fs=,tag:Xobgxz+uho3CBUpHRR+gTg==,type:str]
    known_hosts: ENC[AES256_GCM,data:aXuzB5LnK0bbsQAfLDNMz6d7GQknE/3R5ZlB9AKZhPUrMxuO3u9ceHNRjV5P9UemU2Frbs9aEciudqY+juUK9LjjvcGM9gISzpvNELs5JFewg6ghLUDwN9r0p+p/i9E8+xEEHUFVqriuuifFRZN9IpUpW6ofaxCwC6jk0T70wcyyO5cXVTn4/vwLnSIWFt4hMX6OlrpomH7BBOKe5ur8D5QE6507S96HISG9,iv:tvZBclJAx/ZOK19G/aunqf1ah+QroyU8q1NPnBBC3xU=,tag:Zqd1ZEqJgn8puHUWMUKLWg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kt6a6y84qj0y5ndxtn6n77ru00musyv88q5tu7vm80095wv9s3pqzxcxxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndFFjQTRObE8rb0U0UFlz
            R1VzckF1bkFMNnZOR3Jadlp4TWNzTHlibWg0Ck9NZitad2hwemZTU3p4c0ZWMmhP
            Mm1aSWh1dmVmQ0dvV3lJekNlcU5oYTQKLS0tIEFSSElnWFFnUzRTd3ZNcE1BcHZm
            U0NlQ3pVYkRhY0VmeEpUdk9mY1lTdm8KDHhmq3yO0XYstGU8NrMjVF+ZHhWdq+Dy
            clakPsP0Mass2dqSx/tkNYU0jwBAvEuvYq/IkSX9zRtLGtBtqXvGwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T23:49:02Z"
    mac: ENC[AES256_GCM,data:9WghkJbta3Ccz2H7ma36eULcqfOCuVDB40NrvLW8NSKOgaWWJuF3hkJH9jxgAm+FyMZVnvtny4kYrT1sOo6PbM6UqCZ/em/L64heWi7RJmkpGinkXjYGvgS5kiAEhDZj54+tGqHW831N4DbGNlnnioK/k7GuJfftp/510Ivjjww=,iv:57cY5h6msTRBAkgN/qdu+KloifRvFz9l4ZUVy1mkE0w=,tag:2Wt8dhnGF4baaVIGrYJGsg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
