apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:pNdYBwGahQXPmNPX2015yCHPV0o1dV4E12Ql6kvatBi+/8nUKiKRlxOH2swWq3EVb3qqnfiAGsL0dhWaPEg64PR2fNBNYSvJ44ElworjedzlOs5tyBLI4f3eRkTUtQpSKCNV61a3BuA9PB3jB7o5RXJBH0n+hTqJwOebdfM9qsQ6hWNRjsLk8ZzidxtEAAY23iSAVhw/LsR2vW2H2ux8ZIO70zSaNuvU0lkKcifkry68tJOA+CHw3KdcVTvTPA47kdWaou5cwF3jO22IUE24sPtIZMXcytEBc6W0RicmXcQwH8L8JIIWdN4J4ILQcQh+xBJzZ+4L7S49e0DMRUmGOPklBHYs9+pkek5syP4r6G8Hb5k3t1JxG9XBoH8iAXAW,iv:o0jps84jUX2HIAoUW1KRzM62+ZmynF5hh7wHuXM3/0U=,tag:DxAf+t97bBaug3AFM6WOaQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:lYCdQma02QkuYzY3hB8e4COWQdMFfMCdX2E/mnu1tWqFBDu2fotV9W5vNwN4ciAZWKk9fjvdV6upzh6zuvNU6njcL+yHLV8TDTO0ObI0l5wo/odP9X+927EU7N6DTwDURcVKosSmdI8mszVHJPj9DIfUhsJRzOe7Fg5VigZyj5J5qtSu/Nvlm/NSND3TRzslXWyFqIZ56e/7/jgxXlYz/LKwVjaFn8bYBQ2nCMUUqHqdmI7YyUIAfkZkTilTBac91n3YFNmxB3vsCtKwVw==,iv:rQBQWwftILz1oSWHRZi+sqI2orv5hjfQpy8zfW8SFZY=,tag:s3mKyzuYN0Ad0cwGHjCtig==,type:str]
    known_hosts: ENC[AES256_GCM,data:7S6OUDEEf04iSb5h+iXZ1s/WXu5uby/QLzjox94qPQ+sCN1efBhdVvuH+EPAB0iwoq3BJhIdt+RsSExmR7Z5wbfnnAvlwOwyUrVjlrIaOFjYZS8OcL5rTb0TQ2vU/p5R53p1FV5vxKO95+FakSEb0ntej3UPsi2duqcIqXTrIuQ8JXwIhMD7+Q5bfy6PYSeQ2ukQwV0p/+h8xANUTQlVbG1fl+NQmyHg2WNB,iv:8rGLtqLW0LBfJ5D46jBuRAY05XLuglYptLWswCauY00=,tag:wE6VyjH+2Zh8K49yya6qnA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVWFWRjYrNElCRHV5QUh1
            ZUNRditkaUtHZUxlY3hIM1ViTkcwY2dhSURjCnlQMWg5U0hWc09VZkpLbC8wQWF4
            cFBwN1JEQ3ZvRVpVNSsvcEh1SW5QcUUKLS0tIHJXQkx4MlhleGFjZ2J1dGgrbjVt
            TVZNd01meVNkL05BMlVZQVUrSEg5dDAKjqVDFzDpCq3CVQdg1H+PddT3I3okreHf
            SDERDEKnF6I5UraHQ/x7hHGkGAsW8dnIFnx/8Q9D+8qGwy56vbcwJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T21:03:45Z"
    mac: ENC[AES256_GCM,data:ktd2iFIgxxPOgVE135USx2kdEA/kkhvC51BYayc3L2Fg1+sneiyBlRSngZ72JdxaSU7zgYlkAK+eMP+shiTiFQe15VXEfuNw7qEXq+rtXXi/gLFX5j3u31r45JjLTOYwIljn66HwiRoe8oq+BqvWp8ecdZp76rmmn6YgXgROxAc=,iv:1QYUINtjHAWXeHTNcQekfjJRh0pAEOrilf4iyo8pPbU=,tag:VVAdzPKmOC9n/RZiXPIYqw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
