apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:sGfCFXfwVi06PGBaX9pNT8Tx+chAjCr1Z/ekc2E1uoHTdXsAwmGGTjIlWD1kOOUfq+tnQHAYkxLQ4nA63q5FUWzApKWhIOIJ/4+J/m9JQzh9/xLbFCNBQZuzezvGeNHEZMTPV0IsocF2aIRweiZtUTvC8Z53XXkp4CrBZTFPf8jGokjvDMFKIHGlWLzLuYhYde3KFY01bqToSuA7skT2mz6YTEcV6VwA0IigoKVIO32PGLMjcCe78UcA2AezLuTI63dT8TfLf1GepAndcwnX3rHE5x5F/TAf2Ua5Y5heKiS7pedV9TKS8fMv2oJsGs0xtyTOgCBswFdKrdJxKThHHQEdjjE4kFzA7W5o8v+mHIqJmuvwB8EF2TSnNJOPqVPH,iv:29z+ASvPHH3Q0d5I6vY13QEhec/f8qpbFZRpxHD1z9w=,tag://kLiKkxxeLvIxg+7Y6CiA==,type:str]
    identity.pub: ENC[AES256_GCM,data:SodgfEgr62neEQUODINEH7ekzGSThS63gArVaGm/ojGbsWbu7uhaPd6te0QsjLNh0n37Mvu7ob42GgR9ylnhpprgzc7MuEYPAUauZkcllnKlop9KSsdtLEIhNYb07a1OU0vY8HftvtFrJJZIawmZGxG9Ahzsyyq/4+ZhdFJXwW1qHKCSI9hW0HiBkthK+O+iEM8nSONp+lypSvdvBip0tr9PT/5kBOLUbVkeYWVqhCAGyj742035dkj2M0E9562RM/o7iQpuauMRYNAMgw==,iv:0Hdzl6HXKmt7y4brsk/FbKXB++/aMs86eoUVJif5P8o=,tag:Mt43VQqfJmxMvBVt2ZrDzw==,type:str]
    known_hosts: ENC[AES256_GCM,data:/XhjeuD5vr/1eKrkTz5tRzni8K1c+jrlt2UD3VEcVnk1g8u3LQ14GK96VAB35uuFT4rwOBdcMO8CMGmgHABWhim3Yn6aiUzWG9nWAbbbbfCG6Rr+TKRGcpRRqN8JF/Iog6Hs9sZ1cRQX32SSQyvGA71F58SGr90Ppy30x9S6TvpJfJBympsR0esJEfRuLwlBWbU7xssBh+owBGCaQXSLOpOMyL2OtFEyUV2E,iv:scL1RUCMvYgS8r9D5jr0zR8d4FYu5Yvh386Je33eWKQ=,tag:1z/1eSTicaQXuJL3Sdp2EQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10w2tnhjhgx7cntj7kuf4s20f7uufq7xaanflccx77k8flcdm2fxsxuvjgh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5b2dVUzcxMVlJMnZZYm04
            cTFWWmU5TW9SbUZtVVQ4aC81dkdjcFlrTUI0Cnd1TFg2K2VvMXZ0RlZCYXJTUGMz
            dWtiOWR3TGRiNVdkMmpxNHVSeXFMREEKLS0tIEVvaWlhNW1lMmEyaTVRdmRsekxn
            aHdJSnVRVUNXdE9VRmZMbUZlUmdadTAK4d6EH3zQIL4let+cisgH7lJTd5rFoSXs
            YB4S40YJQ9D8J9AyGgJpSD4Ysv2qCh0jxH2/pCTnOL6pppnZ+h3ZWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T19:39:53Z"
    mac: ENC[AES256_GCM,data:gSHR21uF5AgDVnxh+3mQd4tJFXHdUY2sSPSLccb1kiUPGDuprMobLHvJI28bRTBbf8PlwCziAJyKwqNFKnAcNoafvUcVg2OwzwPaRE+IHwhymXk9KR258lFq1AhnoIuTOZOH6fXx1NJSBl4MfKJkEyoLT/g2//1RgOLnC0BtneQ=,iv:6BgURrCt6IqUY9lTwBq6xjqsPl39znIkwgIcOQ5Omjc=,tag:VvT/7lwm/ACR7LP/k0xtAA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
