apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:odEW3e+Fj21u2M5s2MoaPSMZ2OHELzj4DnpScCCvPHZ1x3+XK6UXUHPzXTgsn+1SdMoV1ggMHCwRQap98bdz+JPrGw8gGIQhOWY9Y/obR/JliyoCq4g+8CrIRo/qMOpa67jGODrwdEoNSCUrl9B0RPvN7ng8/iT0imGxDW2OIfWeE2vxjky0XxXLisz5KAPAZZtr+WbF12h+0eov1n9Syl73Q1lltcjGjeT7rB/moYzvtIyKnQu38/V+OgBpohPq0xH8uv5RbzyDRMVdg7wMAgqFPjGyjq7exdzNgTjn6QVr2UxP76MBBaQ04RWDj5D/WH4D4Z4Qm88qkhYzrq0SlMMLcS0pUgSQWpN60K7JKMQyWaREnOIqkx8qfdumVqfY,iv:F9Jpi75y02Ceu3fUe/RKEk7A4pq4y2agWuZi4+FWsW0=,tag:CSPHMnJ+7kFm4Jf2/3/CYg==,type:str]
    identity.pub: ENC[AES256_GCM,data:q3/pAF/Opefc/CV6z9iPMERh5P278rA/WhHsgTe3qdQBeifbSQfR7kwZlxLZnrbavfrAs9A5JiQGWl44N6pgOdGkwHcWki+cnjVDP9pbg4ziUJDZd4/1xLcAayO2CfFFAqTRab9vPiCkGL11/1d0uiejboerlMW4LUNLtVaFYPQSyjHmUPb+9+X1J2fgyedBEAOvURH5yvW6odgxCEpF5Es+VOIjRnbm6KJw10gE1zu9DdoVEgzNi+AmASzRzkljq1zLO4rNu1Bx4L3/Kw==,iv:Qw0nPUZM8UnePYzrMiawEVkU5MyWl9Vsddvwb8VrJgg=,tag:03h4xQWL4YGqAorE4CwDwQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:NCeleofiS/4poacoOZCnvLjAHg9J7XyROrbF2mB3Ono1e129Oxu9xnlfzmn24sad3dyftg1GQzwarCl7wZGzihTzazArW7CcPupMuf+jAFHIuieSkhAuM3LH5WoSE2XRN9eWBEd2AwLQf5DrZMXgTYxxAoZ+295zt5bm8Ecxa9ypxMRkS9Np1bhNxWDeoa/FVC+2wBhatrywudu6gr1oXzbXr8NXylxLu5S3,iv:9LNagPmil0w0Vm9Oo4w1KhnydILBzN/aLq3ZIsesuNc=,tag:0fUTWQVswxKTrux41r5EMA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMzhObzlMU2hRZW51NFBz
            N0pvdXJ2VkJtdDFDWmVjM1VERWwrV3ZuNFFJCm13SUZVb0tqYlpUOVJsa1loMnYz
            UmVSUnpFbyt3VThLT0ZVa2RIbkp4ZFEKLS0tIEtJMExwdFFxTjhoOUREczBJdWlL
            TmdIbm4vSEp4Ui9OeGZIRWpNTHJkejgKcSxxMPu/UW4YTp+aF6u/wJdx9Zb3IfXu
            GbK3Sxw6cFRCoZMWEWbgnCKGhN/1eEu1Q0c5I4LZojZR+zqMOa8FmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T02:23:50Z"
    mac: ENC[AES256_GCM,data:HApksm2ZTt7nPLEdadaEBqkcPcvfKgB1fUFXLpMO92SQjtB+q8is+b7+WlvuT1W2Sg4tvt5yylFTJprYs1MhDRnWAIr6+/NL6/0vHNfTQY1fBr5X2GPH/Trhv9HPtH4SRiCykEJhYTmJDQhNkR5EwL1p4HmsMWfpZBjq6xj8BhY=,iv:+ET836/dCGvh9oisyi2sN/evnUISIHHgMzc+o3OwiBs=,tag:IvCb+E6Nufq29rEYtFnOfQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
