apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:36R2wy+s8e5F4uSdoSP8NTW184hMv6ihw41jdp+CAHe0d1j7kooWXEpoMzwK5G0rE1ypKs/JyJFtqvVAoKH7ty2b+kArSm/Ve4+iT9ZLp4fnVdpzulhj7y4ztjoti8do1Mj6Gi+Ql6qB+utPQXnJFdHBKSkMihgRYo04YjJQfJ0vkfXSig4EPgYwm/eMnsN2ChglkL2agTa1hiND5kc/KAM7tVRzD8o+uTptXUD858D80idgMw3fCAdExveZsxmnBPtDisiL8G/80wSovG7z78Cz3hPDNEjhL6LG9nBEVPA+Mp/WNhHMSeZ/s71vUUKdQL4iBzlwcTEu9cGU+m0cu6+n+sg+BABmuR8e0dx6xCwuKzrU93GUZjfElABbsiin,iv:A99P/Jh5nw2wfzq7TEQUco5LD+kwTSXIpQtjY7rBD5U=,tag:unnlsgaepeLiwuBxzByhyA==,type:str]
    identity.pub: ENC[AES256_GCM,data:4IWroaVSPbQUdl7h+q9Yy8rMCHpJ/R5ZzpVSBhmrI81s5RMxWjB8CzMqzqzkuRswLL74sQD/e1PZW5604HiTF3u1moONe+u7UYVyznrKeMi7MQTYcqYUmTDumkTJr5DFfQnzMGJnI0hBiFnLWxNa2YqhaMHmbBXpvxxcRKlEbfLlYJ7kFgh4UKkl1tgFG8vn2tVVoCbpQmZSdhAe9uObpYQGNBJ1THsyDTJnbhf8MTANqmIbTxVdJFcLJ8g8IhXPAzdree0jP3T6Su3ckQ==,iv:nblHz87TzdnBNm6c1SjCvMpaaELDTQL77+jgzC3lm6o=,tag:iozU0WGXG01RzLr2nnCXew==,type:str]
    known_hosts: ENC[AES256_GCM,data:OdZ67sIYrTZV7ViT6IfhqiLsbOsMP9jc0lY+67HSZ2FBtd4dNpKpH575Pj2AmzNKORdXvD6knYv8xghYlZ8p5ziwTS4qTwR5q0bH5exOYDtFkW2EUiz2mAgvZFtFdS9kNiycUA+TGerdt1xNV1EX2rLH63wfhxrQlKSqycVV3T7Y9E91p02N+xMR+O1qHAU4HNxdII3O9JvUacI+/q612otoxfHcdY0t3u5e,iv:iWrodtvBx7+PRlYtl/jTd4RywlYO/Ng5u3PEPrxC5PM=,tag:pal2pzqCTHSO88Pn8eordQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UmwxWVlMYVhYeGgxeGVv
            Y0diUGdaZGxjWVY4Q1BFZ1l6SEo4YTdpMGpNCnZocDIxT0JzY0ovMFh6bGI4OFdP
            UWlDYnlyaDY3MllzdGJLQXI1WHFyb2cKLS0tIG5CTm5YUllIVG5ZN044ZTNBV1BK
            OVAzVWxCR3Y3aVdmNWZ4VHd4cGRPRUkKCdmIP6N5P66dzqKaRxyrs4JzU0tuKm/U
            ZfrkIMmVvAhQ1w4b+8b/Dbrr/JA9TFOMcnqp1rsCyel34TbIWtzGaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T00:55:11Z"
    mac: ENC[AES256_GCM,data:j1/VerWYPLpXPfRUthD7+4ZzakdLhFNJjPTV9U51zn0OaGPVw3wz5r4nieRjiethaIy9scXjCMH14hwz+6ZGPW1kjtZvR9cuu19IE5vpMRwhgyVXe3HWkeBIRNOIG2KWiXSKiIB6exRnAsnp/R4aQwI+v79scIK3QrKFPHqMJOQ=,iv:aiC42vNprR8YB86UtnbwT8P87nwZr4EgzJjmzE3X+Ys=,tag:ZQVstQq8Y7QKkVtOd1OmLg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
