apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:GtXTqGGQIoKuN63PSyFU3mHl1fBpJ2w0UwOXQRIn89NqXmiO3Kyk398MgGrx5b2esvhqPgRz3XgX53bBaCZrMVCeSm41/fGkgUYuHzXtZZIsbF9IQsN/cPOSo9mogXxpe0no8oF+24FB34cALpD7QKezG7R43XN1+I8K2NGErvDRuZKROoOhugLc4s3GHV4t/+Lo4Mm0iAK7yBV36b6feLrco73+ugVsTJEOEtdrelWT7fOa2iq4qKnpPNvaimkrFfHiqW0AUNnmJ/M8LctXIlefHx7rmpbLJKfhBuBZtkqjY26V1bM75MpMyxbyhDa5IkA66uQ9G+ZEyl8UOjE9TwPlVJEVK1wmV6yVN7j3vZ89icidSwlUJ5q0TrnZnJqn,iv:TfEcSN8kDE65vOzokPGp/4ZAw5umXVlEYKaiJnRh0GM=,tag:AG68GLE2PCINulDx0x71UA==,type:str]
    identity.pub: ENC[AES256_GCM,data:fbUGclB4nL7oLubsdWS6nsunX4JLjzVhKddXdEt99pvxelHg1e3WhkqLD3GK9Mpi2OFoC/mOnUaMQXFIOqfBq7UTrFc74SPM7Hp2LlQl6VgSeVyTPcVY1ppZpd/7RWZKKqEacCWlpBKeTZYGjS0kint+D3h7cIBVNMsDdpBBES50BZ0ZxPGrqJr3rnJ4q7d8qSP9Kap8BC3XQzQPDsxhm1kkw0s4mpFpGCwWF4wJUFq7rkyk/TNRuRwjTHtCfYRrHZi/YuY8ysQb1zbsmQ==,iv:Y9m/cuwoyRNlxXIqF+RjAXrTY9OBp6v2QIROZ0BE8gY=,tag:LboGmeq7SNBG2YIaY1UDXw==,type:str]
    known_hosts: ENC[AES256_GCM,data:UjiOqNsoPGj1Kvul0nY2rMo/LaBK+NwyJyrcCrTkA1VSt2pQXSJD1YBatzi3TcUQyYi4Emg64ZgFGG5efbEIx8b5ksE5BC0UNrYMiHnQDN1PGhM6nzbNNCMja4R4ir+xtbVEaQkK0Wa1yH6B+c7h6JrbReOVbMB4TWSCA/czl7+uowBu40cq2mZ/ei+9H+cczZzUmI1nVPHe2FgEH/V/CoHQfQ65AV77X4pg,iv:cCcn9e6ArPlosEm1Hxf5+eZz1ynbDkq5dKlJ+zjYs3g=,tag:oYwMVAbZas+OQ5gzJafyuQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kt6a6y84qj0y5ndxtn6n77ru00musyv88q5tu7vm80095wv9s3pqzxcxxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSW9KQUhwbXo5MzVQSWg4
            Q2srU0U5QWNpMDhuQjBleG5JVnlvSkJma3lrCnZ6Zyszaktpd2VhdHhpMzRuMjdV
            MXd5TUt1SnVaTUVFc2xibVJFczd5TDQKLS0tIGJCZnFVYVk4bGhXOW9xbVRKcXZn
            WHYvQkZLVzdRUFVTV2VnZGxhZ2Y5dkkKz9LX+WMK66C3WBsibmYNjfyJApxcx3MN
            qxhC2UVU9MlZCUmL6bBTPT/X/LPS+A0JniRpxYy0zHdtuzYs3wNQew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-13T19:16:28Z"
    mac: ENC[AES256_GCM,data:HILY6B+tKrqAQkKhz8ieQjpbH70QpHzR4YaQkLpdgRZQIahD9OGp1HmNwpcr4QDOCfzEYfAq8Z45PcEgw5Po0u9e+fm9vf4tSwdKlOz0KrDgI0lexOUS0+TtSKOie+6vK1VLfJ82PiINhSNGvcqLvKp9sPExyLIvWuM6ZjhkDHQ=,iv:c8j0lAw7JhiqVP1dkOhNufNvSXJT4B90Yg8rN7CdAik=,tag:iokjoR9Jc/J2mMjcJc/8+A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
