apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:EJmJe6l/oZC0VWrFjbP+Y2mpf8YDDs33xcstabtG/y9W2Qfx+QQ+3Mm1mmMBGN0m5K7LyRyJD0m/aqiSkyP0QKjkJHTrUNOmYzGn0Yaems39KyTGHUROPbo14Jh4x5/jbgxl6pQKVGr2A+z0Bgjh3WXpZ49evQFBHws2SMl1is6qjKUATpkvxpytmP5YWJunpFxX0xyQDN0UWMQVBF3/tfTVFB3I7n3UthEL8bIoiQ5TbzYIm0t4DzD2z43s5lCOtvb+UCFn5wuFOrtZrYXul8A9kdEYKJEKM1plNRL4+3G+KUFMxUlCPkf6gFzYmmSOSBu0IHlK8iD9iuiKMntN6d15RhKtf/b14LzNWSZNLq6WLoV7D74RrQllsTrMX4Va,iv:NleMR4HJD5Ld2B6+DD/ZO7lJ9smcNMepgjCJIBWjyfw=,tag:xRXo0J50M0knpyAiKr1BGw==,type:str]
    identity.pub: ENC[AES256_GCM,data:mmYSIiXQ0J+W3pKjaJwlSukIrS7EUNZ4sVIuUm+v0cAtdiMlBv2SvSh8emM1aKjLS7Sbok7j3q4tKwCOrroGWdB1hZiR8zVVAaTOo+OoxB4tQZJMKoKnlG/NFEhzLvPXlpQAz2N7OQP/o2+ncDNgepz8AYjqAK3j/xQYvB8A4YUw0A//ChIK/CWQObr9UJBSdxqk4KyJsxmUOZQBqHB/X06H2phm9jBlTRDVUepfMPh0fSOTJ/Xvg8nGWLDzsWvd3xe+WzFKcfRbsltkNg==,iv:Avb/2Gq7Olx7Mf+WakGQd2Y9ut+jD2uQZeb5e+hit4I=,tag:K6xJxt0DBJs4uZQJnw8euQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:N5Kf4n7OKMEsjwohpmP0f84wE0gPNGdUZQOr8qApG9MPvIfiOPPgbaivLjaVfnvV3ug++TQ6pSE8EUex3MVapmfFwqwCZcwmOY9vS1IDQ+WgSTVjn0jh1SFY9xsBSUl+p/7iHpcZFhR6dkh+mX1nnPi8Q6DJn83NX6WtfhpQ3kYHXKndGowZupi3Jt53JHCoh9OrSNTDLlfDK4hlaF/rUYoyCFY18eU7SYuW,iv:5ObmrNAmqJqyqJRvY8bbU9i44I6947xeXDlf2ZLk5NA=,tag:Vh1wMWxY8kWgMQjGqLMczw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1caandqrgue5nl44eylp4nvake7znrvxretz3uy3r0ccfa2av4aysejcgfc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArS1A4L3pOc0NyQmczUW10
            Um5oblJTMllzdit3cU9vK2NURkRlajRvdTNVCkYvcnFRWHE0VC84dEpCcUtXMVVv
            UExudmx0d2t1RWJYR2JLYkkvVGZIVGcKLS0tIGo1SlhnendZMEI0UVlpcnlHb2FJ
            WGNzY0YzdE9SdUR0SlJITnQ4WHMzMXMKPm2rz5uHjOVVzb342QG8/2zMGwO0ITcd
            hozWmBW7/6k6PUTqSRHl1mDS9JTQoDqn9AFw6ciOfj+6zzmblUU2Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T23:59:24Z"
    mac: ENC[AES256_GCM,data:JUVxno9I8FUHGrEbwaiyP/Uxfym2MdulWCXLKzzyDCo5+CR2zC6MQ5G6bftkdrsaTam5qW0/oDiROPKcSn7tyd7adPQfsymZpLOKOaJiKrJF1wnHnWFOjTGSN1PkK8iIvrr4evNhO/vcqEuNfi0PcrTXelRqxbBA/eZ5onJXWZU=,iv:3Afa/CAMPQdnRJzWfg3YhH5GYy68d9Z8irXHCVotAh4=,tag:UllfNK/Q3I0cgz+RrcnlXw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
