apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HfS+e17pQB9lXN/iJvqv//6C3oPb498vkTya9UwgWI4PQdMxb9bDcLPrS8EKIh2aOtcVSLlmdK2m4CM/g7EEF+pWT6GLN0UqtUnXdKMATw7ZGgyK1caAc/ZE26ydtu0zAr9loNtONkGhgScHv4LU1BdzRxLEVTeKESXs/E8mRH46JHu4pztPbefMgYC23MUaOP0UJHPYs/02WucjOqtDoHQNNUVrYOgBQVMedz9wsjSWCmhk94C+xoajLO2pUWb7thTTTj73q5QLpBEZCqB5oBudI0fAN9eQXsdWvWQJW5Zqu8omo1kFh+D48769OwzoLbpVZGJ1nqjBTsLJreRT4C350fCwOMknGWgU9tMqiUe3yD3WHIvJcXuWTltsh4S3,iv:kt8SPwwgEzXyerptr8jo7jtMs776PwYP1TcAPO1BQl0=,tag:5p5Ps/w/jYlRjGOYFzWA/w==,type:str]
    identity.pub: ENC[AES256_GCM,data:SK8scYxHfmarR2i3WmXr2tpOiWNRDIGjHz8iXlrxMbJmG3qEY2mnv/ErZogNUdLVw5fBmks8sTiPtUEa+iGZGJGBZjL1C5g702qqlSndPlduuq5674AFK7SOPA89/ntiAUZgn83y+ndwV4kLNYzN+joBS9O/iNnqEvzhT006x6LEik4qKeBYs9P7zToenU1q7jJTMUx+CuX2jzIY88GklyEpYr6cT4EMCXbCwYJ4c4tRVu5HuRnp5f/CtPGm3fsIsa4friP0xqQUk8k5ww==,iv:gobsadrckC6junaw0MOlD2y+5zfZ6P8/JcaQABbXtjU=,tag:5bm1ZbgdyZDJWJgiJ5Xq8A==,type:str]
    known_hosts: ENC[AES256_GCM,data:PxJpHWCptR2qSX6+HaZ0TolMQpYmOyl62pje+q5dKImmtU8PFgH42WI+oaownYSzrWFMkWlh4SEfapGoPwwgW+Y6qomvIhCcar9f4Sry/gbC5NiiY+Luk/eGbnUHWNOtJxbKiKZto8ZGJ7qTK6Ow6l97sIBRBivBJLnjfFvFd+ogFntx+KHhI+hnUE1CnMZLYEC9/u2HrhEAJhzmsjiylSjUXzXByuADDcKP,iv:baCLgwRBe1iDOpnya6Z3mvsdEChFFjQktnF7cPMc0DY=,tag:Zh2n6Oz/72Zfg3rKiLLc8g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kt6a6y84qj0y5ndxtn6n77ru00musyv88q5tu7vm80095wv9s3pqzxcxxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4a1RlTkRLZk9zNFJxRmxX
            SWVhY09zcTlMQU52OWdTcjBoOTBhR2RON1dVCkNSUGUvaGFOZTNPQStiZ0MwcTdP
            b0JVNnhDdHhlbC9Dc0pBK3ZiQ29GY3cKLS0tIGFLelZqTWFGVzYxYmNRaS9lQ0lB
            akNWN2d0MjMvT0kvcU1Vbm0xUUJFUnMKFX857UimmBhwWoTIAxtNPhlPI9xrzR/6
            PkhWWT1P6/P1ZGp4kku/n0sHkpF1xHOiX6sc+6JhXMhtFIflNoyprg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T21:58:51Z"
    mac: ENC[AES256_GCM,data:fFGrkM7qLl7Vsgn/gfMqzNOmjYiz6xqYdV6yGR1aIYl26JkwgYflZTLg9k3Ag0b30bpYqb25JA4jWdnqbDBwHyLvxkuVAK4Bo9g84I1VGD5cWwBGdTZO4ciQw2EU6HCaQPYFB2TuBwV/7UI6Hq4wIeZ5M2tpUtighjIJERaBXP0=,iv:9d335nha1Qwlh5/lzGIP+ZXz2YBdz4K6b/mksAv3Ufg=,tag:pUHF445JpNvfZAqEJ5LsrA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
