apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:X+GqwVvxp2DBlO4hOlyNe+9rC7FtMon+A6zjigDwHkM74VDMAlo+rkJfn66zITHWR24LSVom2bxPT9TkZfnEIE63s/zNRHG7tbg7kJ2LizX66xbSWqzcU+i2Csf0unv08UYOwOdXaHnstBEjA7+I/sk11S2smNXhIxY2wIAN5mPhSwgpJUaI1pYX1Zj6Pp9dNVhu+OAZ4dPyhELyC8vfbYQM8hAd8s6h9uMv/TxRpMs6hoDFSuGBZx62oJvwQu2c1c3G+1vcDrBkXnIkXh1M7aSkQs4GZ96njQsvUGxDw/kX83WhZ8UmAAmv0S8TEYR9yb0Gk3BlYKf6aOeTpYHuCFujrAdlWEM682VjoBi/UOCgEOBfFJJVQ1wyAypfiOky,iv:pRDqrmH0Ey0CWaC/b9q3UP0SplzfYa1LHAXo5u3qWKs=,tag:NH17oCPhMxwTB462wOcvZg==,type:str]
    identity.pub: ENC[AES256_GCM,data:jfIfcV2NlCWI8xiKnArX0CBHbeXNhKK7l+W8P/PNcYHNRvfdcr1vj0kEmig+c5YKGU4haVB6FiaCsAZWu4Ph0i1M4zfSb0klROYk3JeER4aPWa3OlStoX9QsxjQccS5npGVX68Kf2XsWiAXhW7+PmZWNQUsui3BD0+b3MGXo1XzwWo6C50WzpnkwAbls1mybTBCFsORnZnkoy18joj1L4RROjrvHE4OIkKBsWVgxoOjNOd4Vq6nKqWWiX5eAL7Yyhc2DQ5Frgs1AGMsMrA==,iv:aZjeIdMBeAuWrIUIuEYvql3IhZAQ3wYJFwOqQIJ2+cU=,tag:p17QOLxQeZCSK9+8YsX7Lw==,type:str]
    known_hosts: ENC[AES256_GCM,data:IQN46cW8juSoZldBtCsFg4c64M9ZWT/L91bJdsQoBpJA0Ysayoy2qXcPGHWZIGdwXFEqfoRXqQrzatNtJHPRiiLOZysiZpCQ1AQyS/E0Pis+sqiiEQInEbgOZ0BOZDjOOgTEziQIkW+DJq28KTNePWqthsbNd6VfkWPlBZ4eVaSMsHq79xq5jSAYqTWiMjVJWn+e3GbZIe+vtQsDQ12b57hKa49Q8yE52Z33,iv:lEhTBBZDQsEL73XmQmFSM1PnK2gZd9VK2EYVlax3cS8=,tag:6rHMLqFTlZKnuI1hhKKytw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuS3gzRTVKRzVDSjZ4L05J
            bnVZRnVJdGc5OGQrejNhWC9tMCtWMUhaUGtrClBycmdoeFN4aFZOTFdVMjNTbnRx
            a1FYM0w4czdCWjFVZkVpT2FtMCtMdncKLS0tIDlEbjNUZlB3NDV3c3ZDTURQSTVL
            QUpHQTZYenV3OVFvbGk0clpwK3gzQmcKccG/Utc+k7l6SjBZq5I4keEDk0fCiPLE
            4YmkPd7ztTs0VEHClWma9ODwPf8NXu9USDoGzTame2KTOr/9su4w6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T20:40:24Z"
    mac: ENC[AES256_GCM,data:UL0Bc2YurjgzowKzfHuBDlXNFH5ynFMwWjbvO2PagmxX4+KQOY9Ws4NFD6R45GTGdcQNh3bEJdkOZyKdErlZfSalPbQdYNJdEKk+nzhKm2RzGt/ej9E4VXROoAwrHg5O8Ir7vPgAopAUBe0vwUsNoMLUfH5tmHIqNyUiVfi56n4=,iv:zJJh9glRybrPQ5UX623LuSmT9yPuxpA407wUsS8mmzk=,tag:dQaq9xO8jd3/USsecpXIZg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
