apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mjxvcDtSaxUvHeRCPPD+2P7Pc+a9g8u4hMApmHU/XzdOFCZtfWxFOftpD1SDQ26k50cCXGevSoOng7qmP4XdZCkiCkZGABUcXW5SjXfNfRTX8s9M5s9L0I0a1v7DP7wHG3T+fnmlZjrKJ1cJ7ExMgB0OnZLXf01QI9kbBQL0oCP/79wEDueSC1wZRwL9JcWhkf20n9InvMOFalMJ631gNhUapC+d1Dow6yZjw3BqPp+OVBjwAbrwZZvAzNNWinM9aL94FTETDS49IpaelcGPOPhyPhTsooIxFLxsC+33MtdWe4In1PaQtlXRvVQ2hZwFiBgZmwfs5eF2bwbNp4rAeqlXNQjTF2bpOhMObF92ucd/ah5NW8j7pRBH42OsWB/l,iv:/GsicfcaZA1DmukZElkYb1+6kTN8pLSuBBPiXl1WWWo=,tag:Np6mfz+DYPtyPPPY1r9JuQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:3QibqQUKFSz970m1sR9cpMt3bfh68teGJiIozu9B+hKntVA3WVDPrXrxTu8lZnz1/8kBxjm8HjgXSd6IcXA+x1I0mROfpPzxFjD4GhcNo0aGixqbmiWXiwWJyWurmeCOe6AYQtSrQbrPBebotTAgi8vnjSD1Qvno+3Gw5XM9WXkGCZzMARJqgNIbAxbTcluazjyntHoH+zxpKPDWvi3+10YXOBSKQ2uFQNGiFzydaYv5jlOheYsSrCIJ0f2wWT7W5guW0wcEKZQxxMr+Jw==,iv:GFcD8nI4gnbx4pB/uiBttIwdDt9azyR2cU0ckXxFiQY=,tag:pP3XJzo5F+LcTIW/yrC7bQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:KI8WNyoYJkFSPlESIgyt2lqb8h6atdWFbT3IdxOyGMVldBW2oiW2xv61JnpJIfVwscDZZYNbeabaFejI6rUeNnl1ULhP/BkbQSqZwpXDgO5+jnetvEIav/6N7NZP+db8VL42rZEg+HuuNRnPG3Wkx60oMY0KMvyalvGA+/h5yU6l2Sd5Pl2nZ1v7hsi/pdu+tTERrRXvme9Ru0km85ol4c0K+okIMjGiM2fW,iv:VF+CQKJDEyyQuHoBXpu0uHxA/y+U6k8es89f3zz5J9Q=,tag:p/bJIUZ8Mfn7+Em9BKjovw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpb2U0dVE4SjJtaEpORjdK
            UU01aUJ4c2V6UVFwdE9JeTg4OHJNNEtLa2s0CjdubkIwSERJeWJ1OWxtaXcybXk3
            NExlWG11aUtVZEsrZ3J3Z2hHaWhBU3cKLS0tIGpsR3VKYWQ5cGMyMkpDL3ZWdHg1
            b2pwMmIrREhhYjdQQk5WZWR4WHFaVm8KdnDi+Nj29QeWLLYgVofPP94qTwH27XEk
            6cRed1VxBcq1eAwJTkAzVhWjdXjK6joTLsYIrNS+lvQupDYaGLgrXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T14:21:03Z"
    mac: ENC[AES256_GCM,data:Mh8dfDO7DebGwaUdEjB8LADwTWrk1NfYOrThRYE7opesogZQqoMdUm/RHzxz2qmC7Ynoc5DsRKKqKBZTbHHOkndoj8861cskZPhFLcOdQJHhfVsS6m8dcFT+DE50X2tXIxRPe1cBzkHPc1jkGhWSBgs3vhr9tEOQ5PY0q4d6Ues=,iv:rwgiUdqjc+Gj/8l2p/br5Mnai4A1f6hOjyNClHXs24o=,tag:peCKrmzvmSdJqP48n+ywcQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
