apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jbkojH+e0v7OmphwoSEV6y0dvHIgTGkJvzt8ZyieZRw/h1OVVKwu8OZOSX5N+JV7A5bOUF0q3xXls9oqnYKt3n9aaX7x/tEfvVEh0J0edXuh7MpaVJBcJWjgORdgbTUNWoVx8qC6M+GhOqpkcafZopCmeYW7yp+lloMfn0T4TbHdT8tUf3tiEE5EphdljYu6Anq2egoF7RB71P5c7H6TCzg8Io1vRISFgwdeugLug0w/mSrn+jbtR03P9qaiVH+lUNE9XemKNSF01LA/EfCP2FHUXqbhvB0z0doEcaaGzKtEYs24eC2PozNBn5+QrgPp0U52HtmJHGPSGOKKzzt+z3P9RgQP7NjrHgGK5u9xoR1MXiBd1NXJUHrtKLqcVEj5,iv:QUA+XIArZ54ADtt8NKVoIwWuBlTUsETU8p2L7bvK0Qk=,tag:/8VqIBHhai8nD0ztDZuW2A==,type:str]
    identity.pub: ENC[AES256_GCM,data:3cAO9rHgyAGCvu2rW5pwrAtuLVvDyBfk9PYgW1iK6Vpmx28lH4nfk3zzY7RK+zM5sLY1XwLto7TiWlGuNHPEDdpae7o6cWOJbjee+pIeU+rzEl9rk/R+lduiw8MYUeDHBYtm1hf7ACafJbpAXREYZ5XnZKWKNRhMd0gIf3uPYa5n4Na8bbpVk7PTfkbhwXosyuuE3IKajIDIFgXld57Qml+ziWDp4bq2TX97WGqOpEqGoEaGMmlLaFdo9IQLFqJqwaayeW3amrkbnGYlLA==,iv:C9uxnlfgWtLpWnoOxhtVgvMYzMGHh127K8GntjcA5uU=,tag:pC3qLnSKECfsEsvoLdvo/g==,type:str]
    known_hosts: ENC[AES256_GCM,data:Fy57m+FqTYz3KfchApcH2YUh/0nAVsBrHEC8sL1wsVEzOGx5ZH9k67JFAhJTIDQA69/gAKQyAU7JEgl65m8ukXEhiR2Tbn4SdmDV9vioFW0YqWE3DCW/Sy07Q8Oy16N7DXBsa0etUJBeJnoUQKvfEJhCRjjhun988kGykrYT8LkG6vtEC61vkQaXpo+mMBIiTI3l5ASkA+QGFTkArQyiJIJi77LoYk+JSczS,iv:SeBI3UZe3jKgvo3bCe+X2A8LfDBfkZ2whu5KDdDEjXY=,tag:voM/lkfslgJJDudDZ50EvA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TVJhajZWRVhNRG4yQWNa
            ZkJQd0xDMXZ5MDNJUTQrdDcvVGhQU3FLV2drClZpQWwrR05scXhTK3FWaXk1NXI0
            bldnaExyZWRzT0h5UXkxK2FIUDFQZ28KLS0tIFduZlRrVDZiazdRU2lNTmNPVnBp
            UWlWS25oRVBWdldpWk9OK05wbXExRDQKDrW13qpCoGHgARPnUzgWuPiFYpI+E0WW
            HgmrXkr3mfU7+ec2jgvwpYtcFLGDogqTGy81bhUdo9LJNSTrOYKWXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T22:08:17Z"
    mac: ENC[AES256_GCM,data:dpEmYGZrlOy3yFFr1nY1NyExrxQGs2dEAr4LUPSmechhmoFirGwceR1T6wxf+U9A9PTZNHA29Ox3uuWUlNctZG1t05XWynXUscXMnrYgbqRSCaza7vVpRnYjFapMXCHtsZBKkHYUT00K8PjJ9lBcI+qOG22wpo6iww1xQSW52fo=,iv:qXfMKsqDGHj62p8RcQ1HrM/MsWUENpnVJr/sRPXX9CI=,tag:GP3RXNSYOBux3MJrCdRuyw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
