apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:YzFEzUs1/G4vqxE3YOu5gyc5i76Wx1VMJUDettjvwBZAjYsALxO3m+67MxNQmbW9RKhCqMMLynqQjNAVagaUBwknxp+fw+8GrKu5rYbZ4hiroRAPj+UNQVWu9LK/6fq9FNheAWn430yiYnh8fs3+KR+lEVfmhLD2G2IeLARVBogcCMX3Lxs0Ku+XJ6LoOn0Ndfdxlw2OvuCsHZgVb3Yps6mZu8Oe9gMOPNSGxpN7zFfxrx6pd4/pREeMm6AtEna86eUGcwFWvaFOxlS34uDFAM1qmoFFwb3+juATAkIbqu2LtMZnN07uAzX0vxdc8kxTAgTBDQ2P6l7D5F5MD7V4vPttM9Zmob+l0Wu/ODowUEXDp7N2O464FBisS4k5IQ46,iv:sdHiZnPNt55OC5DjNnqzVSaagw1xdsheo/E9v+t/edc=,tag:EFgZKdFEFf8kpc9jKoQldg==,type:str]
    identity.pub: ENC[AES256_GCM,data:JjfWICDawYTST6PuyTKwvDJY5oENACZCqUUIYVegqIx6UbfMh4CkiwR5B6TUkIWeNsK6e/N6Q2aXqGUzBw7spOEJQ8PO2dyK2j5p2yMY21e6toKjG8mrYFFmpvoaix0zfel4ScvzJdpmFLhcYAWmzb5vuHOEg1czDL0tPWTLAfliMub3yjVVj6zvlzr3ss7oRp7JijKd0zJ5ZVETzdYrFVKljnA1ol4tmEJ2XdNsoz7/5djSegmHW/wvYlLNj5M1vtO3Wr0pTuCWZ0Myig==,iv:KtOnn1Rfy9cIiuJ9ey7eCkIGQNOmMuSy5XLX5SwJJL4=,tag:9DBkYz4Bbkif/9mjEVos/w==,type:str]
    known_hosts: ENC[AES256_GCM,data:9R5HMLnoFig/71AHr1k9i7pHFdN15M5tCRbzHnsktHWaIgBb44SrRYc59iyf7NY+c6mmBoVzD4sTGoGCko9HYLxJUY6LT90VWEW/onNj9/OOUxm/jGVvOATndvD+4ERx8I2qBceb7Dx44oowDGTMcTdrK4gl+VWe9NGcaRU//dfKYAzc9l+Sn4aVqD8snJgj4xWAKvtxpVH9QKwjqO1M/wMD0XugntCLaRgi,iv:JmckQrE2adQredrw6xgybX7HCmccxlLKyVUD/bHjtbo=,tag:B3wojKyJVEy723UUrsKP9w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mckk7dum63y3m9l06dmtf9vzzrseet9fxuketlaln8zm8eatey7sh4kshd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd25xV3Z2bEFoSWptbHhX
            MHNsSEFSaGpYQjNrL0toYnM5eVBJTDZ4ZENRCk5STEEwV3ltUnlkS1JETXhZMmVU
            aTR4YTFRb05uL1NYVC9lWG51c0tHdzQKLS0tIC9ZMTdxVGxMbUxTSkV4alFuWENT
            VEt6WG9rL0FjcFBZYTI0cC9aOCtMQXcKbaP2YRnPcHlYXQrTK8j8n6LG4A9/1ZK9
            Ai9WWHtoxA6jYVClcJQ+9uqnMe3j+MpTyFHwyk0Z+DRl26af2KyfxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T00:35:59Z"
    mac: ENC[AES256_GCM,data:Z38tejAomlklw5R+i4NtMMCz2ddU79UV/WlWCbgVTcK3ubhRjSRxyHFEgLIKcmm6zAfTnF9ldu+4aMYPNHdazISKlWKbPGzWA2z4CYXlYcvPHbYY/QyLqS4BbSAVrQpNip9CymGc9JlHL+edgybTAaPWWzVQod8LWl4JyXxxDIM=,iv:UKsrwHJQpr58j2dFAD2E/LLJoP0zup6UACJ4Ka0LW2w=,tag:9K2oLh3zQluObkdV2n6kYA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
