apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:fe45iKtQKOJSUHsp0m/t/7eOXBQ28c7AemTFRkIwzbX1x5k5jyF+gjYxVS5wSzEGfeQhglFa4gevBdnZ1oo+o+ROWTz1AZfmnT7qwYc2Tp2vJqzYXTTNPAD/DAhCbclayamILoI4hcTDRoOn/dmd9rwLen1kFUnuAK7/MGB73qUJ5RqctATXU1AMIQkChRAfU4+abgHSeY4Iz5XE6m6fx8Im01QXe3VIloAffz3sKTALWo74Qx0SGr+tUZf24alOEHxdc7wVeHEC4DETGTNvUde78sTuAexsSWMTTnLnUUzXaUZQrJP3lW1T9lkmp94DCdbUzFzk45wndcE+T1f6/0HRZOP9beRbOnM1wIpWuLytTdfm0v3AE/pOidP4vWXX,iv:R2LuMbUbwT1F0sztXjzx/raRLsjq+zT2Q3ZnvwkBP1A=,tag:toopAKOZwnq1BkstjQ2Tvw==,type:str]
    identity.pub: ENC[AES256_GCM,data:o2u5a3eqGuVSPn+ouI7w120sAVLSZuFlBz8E84oid3qXmexFSx6VepJ/OOS7nOs3dwqFzWt3WIeVYizwz3Rl0KbWhL9yDRZpcVexio+CdG/+Y2mtCi3fHeRslVGayVZsSj6f0JezhUmNqoyqC2hFEOjoJdZHRJYyn9O/hizK6JqfF9vJRc6HCQPTmTSwR5m95Bp9nZrJN+pISAbWA+PrCmzeVBXklRay5HGanFsHXqWLLwZq87FtQPjKuqZROuHszxYZvcdVOQmME6pAlw==,iv:aVmhphj16feb2qceh2FBdms1E9IDlAJ814QSI3lMKlE=,tag:IyUdQNNakNC5cbWIFWq//Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:+IULJPJ2GuwZznFqavNt4IfwVAMzAfSRoc69y53h5mWO9xnnGbxgkI3qCC9RQxKrkHmiYAsaZyEPNixPoej5vHB5GjYwt/t4oZJSJuYwkIxDD2p2KTamDuskAq5Ak+wVR77rNskHP2HwVwrOc0rk5H73ezZcvV7KjyKCR/cb2oPADDkS6p0GTVXq9704VfVTO3QBFdnWtmB9PtC+xbi5NN2z9nTf1DZywA/E,iv:jZFzWafkURWSqnkYw5YhsSyOjOEuK3bnwastBqErRXY=,tag:KHm2uk73vULQ0ZL+62E9YA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDT2UvcENDbTZwdS9uZ3lC
            Vnp0U3dPY29PeU1hdkxMenhmeWZ4QVg5R1hjCjZtbFc3WFdnOGhlWXpMdk4wd2V4
            M2w4elc2bzdzUmVLQXBUdHFxSy96VWsKLS0tIDBlOG50bUVLU0JuY3ZpamVSYXVS
            WEN2Q1R0WUNBVGxXb1NCZFhBd0pmQlkKhC/CGaMKTbjmffXLCNa2w/PQbrWqO2WP
            6/Vfu0neF7qYXLPrIsnGrnI1EwtuIqK4fiwrof3CM0+yTReWzxdHxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T03:26:53Z"
    mac: ENC[AES256_GCM,data:JTmwunzgEKd+F356AjcyjD2Qp7nKjQZnhTwthfIgZfm6UinrJVN4JCEHQDRbVjcnmCJWSAY8bOBBie+EvLMRcIHustiHy4HGamljNjAeDm5U77xN6Kj0IO9pl6zzUFQVKVLAtttIxs0/jSDIjJ0sJrVVMsDeMdEJH6EoKmqP1nw=,iv:3MfbjG22ETnFuJyjhNB/Xb5VwrV7i/ZhA/GG6mRxUtU=,tag:JVwjVF6FvaipJLLqXlG/Mw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
