apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nFsZF/yF8R+AYunMzUN82XOxqeiGI6ZKSAlCiXa9xThrckmT18bspe7RDLxzvDukKfjJ7qBWleHp95DtQI6x02lzmAUcckIJQYsrsvz3GXQzOUoaesUb3x/GEzHOoHxdYxGCxao+hxXRqhu8H3B+m45Fwg3GK+6qzQEcJqQnbpzUS4VFPfDbA+0qE8Ogp/wNy45K9XW+Wm8t4/jjq2/Er0uTEfsiCzyGiraKqcKtc7lp1vAM/9UCACyqlkjKrQlxj6VEklyCp5XKadLFjVF6AlcXuNB8QnZTxomKr04LfC8yd+VO1zjhRjuZiV65PRab0SC2zBw1VmUWSm70DEdTaVIgs1OHcC91nbDkhmrs20I4loVgLWSy3nfwbUDWboSk,iv:v9ky41rixEaDKjeAYzCm4NpyHZVBw5KoY84yUWEZlVg=,tag:JUPcHfGQaKHCMRNsjg7wvg==,type:str]
    identity.pub: ENC[AES256_GCM,data:ggHQ8slvqzsUX3U5ZXeWHsLW9QTaCGs340npznLrVVEST6KCs3IY9jTx/JGe7wls1BoVdb6Q7JISMlmeuZiGW58i7ciDVWQSN7eFjs68G96S2IpGPiq/c9+w7KE0qK17TZqK3veyfWTGeIxO7e+fPc2YUWSGDxSg/OC1tQdf4M608goDyGOdb+KY4EynUFwb8JJ7kHJfUl+2OmJgZh1fT7RI5J80umUzRDZwO/cx7snVRFtF/Syv8vFWAitT+Su51zwrbQHO3i44eRdq9A==,iv:OQZsjRGfueq1/GjLSAKza7oOnznYL3A0QvWDPL5+65c=,tag:9lCQOKaZG5z7j1ovr7vPtQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:o5r3h6fPymvTw/9qvLqNy1y/wqBBnrPgbWMTa7SoJ6uDBe8q1H6oPVp25xkvUtXss5sWaLR3w15q6y5039Z1Biv74vQ4q2G1a8K3yy+Rl6+fHqxzeH92lj8azDHjeMt+jWYOTnC8erXgiC6RVAlWmGvQVZt6RVN8srJIltKw9thk0ZOfu1nLJWM6BD+/gqyZSsSbRyDiPlnmyxofH72oybm5xEZj6wsqsvB2,iv:5xCW1jl3nTnRSVQzVuxUCt3Ug7Ixr/bBWk9QziEjOX4=,tag:ZTWWrSS07wcvmskVSmTWzA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFd3loY2FYbU1zTVhqSHA5
            QlB2SHZJS3VqeWVTS0N6ZlhZb3A3WFBKSDJ3Ci9FMVdTMGlDeVJMYm1ZT0tScEsr
            N3FUbVJVN2tLaEpXZm1pYzhaNEtOVzgKLS0tIFZYcVcvZnUwaGFPajRqVkthNE9V
            amMxU3ZsMFIvNGhXZEtQRFdzdXBNVTQKlmUsSzk/ck+KVVx0bDtJAiXVt3jKua12
            zT/OxFkVF58pUW0cMgwSKAv1yNovYz5lBCmeUyoiZ4Vd8plGHfuD7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T16:40:13Z"
    mac: ENC[AES256_GCM,data:amMEkyIYOoWIs04ox5oUQvMHM3gKUWps4G649gpMtZZ5N9w8hNN4hF0j6KFc/qlO7UFFxljlrN14jKd1KkytBrePA9Jg/I07a+Yu/t/xe+xh4geJGQu5ETuoBWsNfyqSAemZJdgFWO01cb1+fOvTxwopIyma3GO4dYOWO2T7G/U=,iv:bxMOi5ncYox1UOBvxdcR57Dw4yIzJEnphT+TD4LS/tI=,tag:fm72lkSNMJj3tGZ74RFZ0w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
