apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Vtsr09+/uBDbe6+lJal9zeKn+KztIZtiy7wyKxE7VdLyRKbrIKDbuKZMayiva7rzWAjYMWj2wjQcCO8q7ROxpQk6PlVPEjsQTDBD7GNoRfUkZOREsMRSl1BQKYuIRzf0/TTHXWq9U5+cAS67jyelD1EmddYJduIywhTM6kBXo4alZ3UtjgKa/o/s/Pua8wJSJcIXLNrg0t/6mNjI0eOHk2Cr+oSaCLa9xAaACE2/mM5dYYvx/UUn9nx5VDcb9ttWw3K6kUxLmJdIgdzstSiqlMg4kMmm/JLgWDRmtXjaGOrt23pnFSgBq3tQzIKglNL+kZaj/5NrA7ylq1OsnUC9gc5ODyGXFFxV2G+h501UwQe3pbzhp0vGLhaOdSxGWFOG,iv:nBN+qK6wa/11kt9uBkAfeONAO5MkwVmQFjhn4vzM0y8=,tag:u6XfZlwO2rBmOc8u9c1pgw==,type:str]
    identity.pub: ENC[AES256_GCM,data:VOwZVIPQ+4tDdPen6sQtw6m/bTg9OQCMQJqvRvJ/F/ShQ3VsG73uLH9trkmweZ13JHpHEeYO7IkXIi2rNiVIozmygQo1t0Zda2VkgqKihVgUe/LAPW1FWgPCADud4C7R5SIYV8kwxufWD6qO4PxJvWxDV8uATsYBjWFB7S0n/AZ4XbsWloUxNyMM13/RiicY3fnLfSmc73UKa2D10hAEkz8v85MRSWsQg8Q9TqXxGCLKur5wNj2YuxpKaXj87WEwbCqzT1i6InvpoOHF9w==,iv:7iJ99Jp1l0fYLUc7jCCHwbLMlnN72IJyLRghvnZiSuM=,tag:lKQfQBNKhxjwKAGNSHnNOg==,type:str]
    known_hosts: ENC[AES256_GCM,data:wViPx5MWGJGWVqjhIAUivlD2zSgf3ouLlVb39y2a6lermnenxuQCcTnXQ4TpylZiBXx74OPzb65IU4bs7BDIm67gIHJ/d4WOhxfSo1xq4z2UM1emhyWn5IN+KCDYmIhJWnRu66XzhjKWrH2W5ZBvcafS2yXg5bw3rkSDK1f7qMr5gHd79ygdGWLYSJbZf8vCq4Xx+8SfsQlHPcnW4+md2opamv0Rk4xTh04r,iv:2ljOMoZZNO/jALwSvvIr+MRLdqkdtbOAuGINL7lZLVg=,tag:F8o6V4lLZHbILugcsR1yHg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gg2ypgw9nq3an7rrwuwyf6rsu0sxr2edxyzy0nnv75rws22l334qw0ru2n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSzFMSkFzblJ3RzhVQWEx
            anZNTTJjcnI2OTlodnNwUk51eHpveXdGMngwClNqYW1zb2VoY2gxK3lRa2p1Y3Vh
            TldWdkMxSUw3bnprbVRCL2JQUDRDSTAKLS0tIEE4YkwyV1ZjcFI1QWdvNCtBRWFn
            TG1BQ3I4ZUtiUWxOOWFXQTB3RXNpVDgKeoaotZlHXt5khx801tQRqFeIdaLNfvqD
            p7y8KNDeyP6NQ5Dt1h2ZKAE01P/11TrgmaWm7rHIBMj/3yqWWvSqRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T22:43:19Z"
    mac: ENC[AES256_GCM,data:6bvJaM4srN+77hcaibNtloVsbqG2lstILsylpzJg+lG3UG6flfgAFmMCgojYtUOKc+Ah2WtqSnZyS93nlvmVKTbJ/z+VRlDm4esObKUbsZTBxpN3tq7W5tDfOot+VV85drob7AkWERExGoDLbTxdK7VabBYlKo58JkSp55IfFWw=,iv:bPTBBQ4TSt1a4c7J5qFCrd9rFAR8cHze0GL9pkmVC3o=,tag:uzgbmXjbDnDvePdvkgEvpw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
