apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nFIzey5G6JDj7DxSHm5Zzw3TqNeOexdBF91AStcPOp18aHwb/XaROdvedmwXYkIQV1l5m49XSjpanCj/7BpxEXhe7NftjcGn6dnalGUqkbPAYdQOqpkYWV0Ioi7upmPsWNITCXJNjLZ7C412CA4MqhcWyIknA1wNY/QLfzQV/m0Ri6O3EAUOx50cznmwcaQanerkwognMv/xZAC16kBui/e1WHpqCzthqz0l/rQnT9jqJq7V9Ykp0voP+uqwI0dtoq7UtFb4elR+13uRSsdX+inwS4wUnfgELsBBMlJExC1+3ui197JDDwBAkJmWaOiS1EwzGAVkjSkSihQV8F/3ZDmpw7vrrR1iHoUtoOhunGjN26UeSdYwkbfDJtdXpi2A,iv:B5ZCf6fKilqwzMMEeS7Dny2Rb2oa4bBVLBQhwHXY3og=,tag:R6XUhNydGwc+k4cMuv7GXg==,type:str]
    identity.pub: ENC[AES256_GCM,data:MxTbELcgVwbpPqrnYs895XoYzcTJPMu1Rmb6Wi/OK2KAzYk+HGyAT3TD8MnOkzR280Wv2b70W1f6jKnPKsiFz89DTn529wk9iOs/c/PcplTM67LUOje9o4WRF4iXbxkdfamOqwKebIuOWwNzptg6s6zMS0FHNM7LloPP1yRnOsV5RUIYR8tzijn3NF0ioukyfHqWeC3DA0ocfaHhiTBPCTE475+YCDDsoKAaWzVpJIIO0TkjFJHsuYh9Fq5/7pzWHIdXrvki4trAE1H50Q==,iv:qvBs3YKFNF6YB1xWcrbzGPG0MOSl+zp4f5qymWFGd/k=,tag:ri81zKJiQmIXrnFN6bM0gg==,type:str]
    known_hosts: ENC[AES256_GCM,data:v+qUCPc7cZDHb3m2XwrfSpMGM76GMgsBj/+p60jWbZmiGKTF34ijDmy9Q7JKMHKhMlGmi1Fo27zuZxnxmZhQHHE16RrimOpdsuOQHd1hCWD/vmbKv9nBtDEzoDpdBSCvXZNh13dfaQc1okpHoy1yf8ugToa8m7QnYmv3pRbuW/ysEPzt424FMmzF90szJj1w801s0MzMMXgz7qLHP/s2DjT2JXBiFeWVe1X4,iv:/+/nM0+9zuCwUX/sCBEFVJeqQC1guEfmvxfg8UVLGY8=,tag:z/aNx/e9aYYMbfOGoDbnVg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kt6a6y84qj0y5ndxtn6n77ru00musyv88q5tu7vm80095wv9s3pqzxcxxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL3Q5L2VPWmg0N0svWDI5
            NHFLUHA3dmU1SStJRjJYM2hzSmZmRWtSYjBzCkFRN3FOeUZXK1EyU1QwakRkZFhv
            T1dEb3M4VlhvSlVCd1k3Ull3U2JFN2MKLS0tIDF0TWR5Vy9Ec0lmVDBZaExRdWxC
            N2tYSWxSR3BYTkhLQmFzKzBhaDlJckkKqMIEBdL0JzSSuNacIibWvRpN9xuABMs5
            LBLv/sFv0ZeR9QSwSupHA+z+FJNWOD0efpVyTjUWJcMhfFLJ4g+dVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-14T00:00:44Z"
    mac: ENC[AES256_GCM,data:l5uzEDIjxjeiOQsp1X5GTDJWDeuY4zC5r5v+THDeN7WRkLgNYvSs1BP5k/Tsg4TCRLwEieAwMkJMXPoGvzsYn9PRScZdQjR60zR+tRW7GxV/Y9cYFnSw1F/mSdKdYbNJS+LxCWtXXlOoSRJaDBL9GHVH+YgGjjk7JxGAlPWLDrY=,iv:WInV9HUv5IHO3Sx4Md+xNO0DAiFUzFeTyWpTWHZp1XM=,tag:xwS7LYXWBf5bPGe4hGZqjw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
