apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9LE/CdPWzmYPz1++nJ4/CHs0EY0fT00rlTUGY9fnS4vf4iYWMDfqVsZajEUDUbrfvxcSYyHtm8krCPTOldCGENG/EnCjcuwfm7Q0wm8//jiUTDPjZ6G1hvHk2l2vuiztY84YC5R2a2afcMH/WZt9gethbd/HJ6yESYpjNmjxdCQxQMUueMaBKrgCxSpfelMvb64BnBvF5i745HBFsoDFDEWznp3Qe91HS4UpBCnDE3u2VcA/Pr6JZ7s5Qf/I2iH3+Hs9ShnskV+Ee5pSXAhIgtsrcICEV6VUhNKUiaR8I/oSh9dpjYoSudcNPoyCohCdwvQlyTEU2Cc8GaljkKyajgNjcq8XwrNsxwg8cXAzL/RrfvlYTNqXXb1j5vVc1Pr4,iv:xH8hKo5EpinaE2SY6qLwDQFyxdMZ/5174U0eLTe8IBA=,tag:lb4Dhejgd00Eg4uaxNKmdQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:PJfiMZA1DKFdblabYf7MSUiJaq9WbRftPzUAMvf5+jNW6S+xC6yoeKGUlbEnXWJN9g8hoNc2IElLiiO8sG3cqBcKDJs+qM/1ge4y8suMkA9wNu7gJvkUXUsn5ydhCW0DR71YYXeySiK6Yh8xWeCzSOCPAxdbj3lmswm3ZvIbUEbIf9qCGFpXVQs835lpF5TxCpzQI14KSwd6bqsAxfgfAywetaGVnLmvuO2SmGox6Ebn/JPUq9cEvVYM97P71AclFTq8hq3xUsgWRuy6MA==,iv:GQkrLbRLQd/jcnfirXOKyS9lu00jZ1CqZxAHiptu4AM=,tag:evlKf/udtohP1/9p3nZz0A==,type:str]
    known_hosts: ENC[AES256_GCM,data:DNMDLV+eJDUv5q1S6z4yoPZd+WbbuzzLWlrZiBUnu9/wstC4o5TZrh+55f16Za3p6+6PNE+Rt9tik6iyJcmVtkaXGm7hDFZh7S7n6fywUWSBT7r2b7zs31SLI6WS/OS+wRzaB/+7SmK6Ln69mMpL+tSazx1GdLOD/79lWHzMlXWOwXn3mFjKMbyHPKSRe16Vnqz1L2NRedZfsAFkZ0AzkO95a5Fe2+g4A0aH,iv:1VD7ctfx6XOScoLDhOyl5amR4QeSpAZ5ZsA8Upi4hhY=,tag:CeqJXIZDh5WNw5y4pF7Cww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swsgarauukj54dzyvls6t9q0nehy7tc492as9d5f03rztgtksvlsn7aryf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeHdqVlZLUlVjSW1IUVUw
            N2N0T0NYRjZUbWJKUjk1c1dvZjQwTExEZmlVClBIellXMXFldXVoNG1lbElyQ2hQ
            OVkwdThlMVRKVkZXeHlBL093TmF0SlUKLS0tIEVwSFlSUWtyRW82VXM5MXBtaDhO
            TCtwa1VDdk9WNy9Rd0NPVVo5TmRGUXcKavodiQqZi6kP4l3aKNktdzzTyLDOY6yI
            5hoACHm5N+GS3GEYbIHZ1rO1xl1/GQgC6AIEvLDvKyO4/9ab0+XFgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T20:27:26Z"
    mac: ENC[AES256_GCM,data:KyrGaiA9clN5V/g7336Y8bZCZ9KmGtClDJ+QuYBEM+MPTXfr0nwdBhKh+LlPly3D8nZXDcGiloUHn7y4Ry2WBseBf07MslZIK7FsIkjubITurhRQv32FCoPxB/K3JLmTADAIzspVjSiZEA/XXjvYJmTRckqNhOzSgGbXQoUkUZk=,iv:TTXYpK5n2/RjUHwJzNuc7oWdA5A5+9icpQe+gOvD8ao=,tag:/KIDrjIlheyinS7kkPwHTg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
