---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ispy-agent-dvr
  namespace: ispy-agent-dvr
spec:
  interval: 15m
  chart:
    spec:
      chart: ispy-agent-dvr
      version: 11.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # global:
      # stopAll: true
    service:
      main:
        type: LoadBalancer
        ports:
          main:
            port: 10184
            targetPort: 8090
      turn:
        enabled: true
        ports:
          turn:
            enabled: true
            protocol: udp
            port: 3478
            targetPort: 3478
      webrtc:
        enabled: true
        ports:
          webrtc0:
            enabled: true
            protocol: udp
            port: 50000
            targetPort: 50000
          webrtc1:
            enabled: true
            protocol: udp
            port: 50001
            targetPort: 50001
          webrtc2:
            enabled: true
            protocol: udp
            port: 50002
            targetPort: 50002
          webrtc3:
            enabled: true
            protocol: udp
            port: 50003
            targetPort: 50003
          webrtc4:
            enabled: true
            protocol: udp
            port: 50004
            targetPort: 50004
          webrtc5:
            enabled: true
            protocol: udp
            port: 50005
            targetPort: 50005
          webrtc6:
            enabled: true
            protocol: udp
            port: 50006
            targetPort: 60005
          webrtc7:
            enabled: true
            protocol: udp
            port: 50007
            targetPort: 50007
          webrtc8:
            enabled: true
            protocol: udp
            port: 50008
            targetPort: 50008
          webrtc9:
            enabled: true
            protocol: udp
            port: 50009
            targetPort: 50009
          webrtc10:
            enabled: true
            protocol: udp
            port: 50010
            targetPort: 50010
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        tls:
          - hosts:
              - ispy.${BASE_DOMAIN}
            clusterIssuer: cluster-cert
        hosts:
          - host: ispy.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
