---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 22.1.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        hosts:
          - host: qbittorrent.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - qbittorrent.${BASE_DOMAIN}
            clusterIssuer: cluster-cert
    addons:
      vpn:
        type: gluetun
        killswitch: true
        excludeNetworks_IPv4:
          - "192.168.0.0/24"
        env:
          VPN_SERVICE_PROVIDER: "custom"
          VPN_TYPE: "wireguard"
          WIREGUARD_ENDPOINT_IP: ${WIREGUARD_ENDPOINT_IP}
          WIREGUARD_ENDPOINT_PORT: ${WIREGUARD_ENDPOINT_PORT}
          WIREGUARD_PUBLIC_KEY: ${WIREGUARD_PUBLIC_KEY}
          WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
          WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES}
          VPN_PORT_FORWARDING: on
          VPN_PORT_FORWARDING_PROVIDER: "private internet access"
          VPN_PORT_FORWARDING_USERNAME: ${VPN_PORT_FORWARDING_USERNAME}
          VPN_PORT_FORWARDING_PASSWORD: ${VPN_PORT_FORWARDING_PASSWORD}
          SERVER_NAMES: vancouver431