---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.2.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: binhex/arch-qbittorrentvpn
      pullPolicy: IfNotPresent
      tag: 5.0.0-1-01@sha256:d274ca2e9fa2c57339b61676ab571d2c2e6a35226ddb7ab9d08107a59a816748
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                VPN_USER: ${VPN_USER}
                VPN_PASS: ${VPN_PASS}
                VPN_PROV: pia
                VPN_CLIENT: wireguard
                VPN_ENABLED: yes
                STRICT_PORT_FORWARD: no
                ENABLE_PRIVOXY: no
                LAN_NETWORK: 172.16.0.0/16,192.168.0.0/24
                NAME_SERVERS: 8.8.8.8,8.8.4.4,1.1.1.1,1.0.0.1
                VPN_INPUT_PORTS: 1234
                VPN_OUTPUT_PORTS: 5678
                DEBUG: false
                WEBUI_PORT: 10095
    service:
      main:
        type: ClusterIP
        ports: 
          main:
            port: 10095
            targetPort: 10095
            protocol: http
    persistence:
      config: 
        enabled: true
        mountPath: /config
      localtime:
        enabled: true
        readOnly: true
        type: hostPath
        mountPath: /etc/localtime
        hostPath: /etc/localtime
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        hosts:
          - host: qbittorrent.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - qbittorrent.${BASE_DOMAIN}
            clusterIssuer: cluster-cert
    securityContext:
      container:
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        runAsUser: 0
        runAsGroup: 568
        allowPrivilegeEscalation: true
        privileged: true
        PUID: 0
        UMASK: "002"
        capabilities:
          add:
            - NET_ADMIN
            - SYS_MODULE
    addons:
      codeserver:
        enabled: false
        service:
          type: ClusterIP
        ingress:
          enabled: true
          integrations:
            traefik:
              enabled: true
          hosts:
            - host: qbittorrent-cs.${BASE_DOMAIN}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - qbittorrent-cs.${BASE_DOMAIN}
              clusterIssuer: cluster-cert